export const hailey_good_3 = [
    {
        sceneId: "",
        lengthNum: 41,
		endingSceneType: '',
        story: {
			"1": {
				bgMusic: {
					name: 'Vacation_sunset',
					command: 'START'
				},
                background: "backgrounds/BG_beach_sunset",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "As the sun began to set, like so many others, we wrapped up our day on the beach and headed back to our room.",
				choiceNext: false,
            },
 			"2": {
                background: "backgrounds/BG_beach_sunset",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "After soaking in the salty sea all day, the first thing on our list was a nice, refreshing shower. Hailey always takes a bit longer than me, but she told me not to wait around and just do my thing.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_vacation_house_inside",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "After such an active day, I collapse onto the bed in the bedroom, scrolling through my phone to catch up on the news from back home.",
				choiceNext: false,
			},
			"4": {
                otherSoundEffect: "wet-steps",
                background: "backgrounds/BG_vacation_house_inside",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Quite a bit of time passes before I hear Hailey finish up in the bathroom. I can hear her footsteps padding around outside, but the bedroom door doesn't open. After a while, even the footsteps stop.",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_vacation_house_inside",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I decide to check on her.",
				choiceNext: false,
			},
			"6": {
                background: "backgrounds/BG_vacation_house_inside",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I look through the bathroom, the kitchen, and the living room—but no Hailey. Where could she have gone?",
				choiceNext: false,
			},
			"7": {
                background: "backgrounds/BG_vacation_house_inside",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "The last place I think to check is the balcony. The glass doors lead to an incredible view of the sunset over the ocean. I hadn't looked there earlier because the sunlight was so bright, it didn't even cross my mind.",
				choiceNext: false,
            },
			"8": {
                bgMusic: {
					name: 'Vacation_sunset',
					command: 'FADE_OUT',
                    insideOfScene: true
				},
                background: "backgrounds/BG_vacation_house_inside",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "When I slide the door open, the sight that greets me is absolutely stunning!",
				choiceNext: false,
			},
			"9": {
                bgMusic: {
					name: 'Hailey_ecchi',
					command: 'START',
				},
                specialSceneNow: true,
				specialSceneId: "hailey_ending_3",
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Hailey is sitting on the balcony, her robe draped open to reveal a jaw-dropping, sexy lingerie set underneath. Her legs are casually spread, and the entire scene is framed by the fiery colors of the setting sun behind her!",
				choiceNext: false,
			},
			"10": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I thought I was completely drained after today's adventures, but wow, this just ignited a fire in me I didn't even know I still had!",
				choiceNext: false,
			},
			"11": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "Well, finally! I was starting to think you'd never show up!",
				choiceNext: false,
			},
			"12": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "You disappeared so suddenly—I had no idea where you went.",
				choiceNext: false,
			},
			"13": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "Well, as you can see, I'm out here. And while the sun's still hanging in the sky, there's no better spot for a romantic view.",
				choiceNext: false,
			},
			"14": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Romantic for you, maybe. For me? It's... bit more than that.",
				choiceNext: false,
			},
			"15": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "\"Just a little more\", huh?",
				choiceNext: false,
			},
			"16": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "O-okay, fine. A lot more!",
				choiceNext: false,
			},
			"17": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "Hehe, now that's what I like to hear.",
				choiceNext: false,
			},
			"18": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "But babe... the robe, okay, I get it. But wide open like that? Anyone could see you out here!",
				choiceNext: false,
			},
			"19": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "Uh-huh, I know. That's kinda the point—it's thrilling, isn't it.",
				choiceNext: false,
			},
			"20": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Wait, what?",
				choiceNext: false,
			},
			"21": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "Relax! I wouldn't actually head down to the beach dressed like this. There are still people around. But from here? You can see everything—the sand, the waves, the sunset. It's all so dreamy and exotic. And then there's me... in this outfit, just for you...",
				choiceNext: false,
			},
			"22": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Oh, I see what you're up to now!",
				choiceNext: false,
			},
            "23": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "Took you a minute, but no worries—it was cute watching you figure it out!",
				choiceNext: false,
			},
			"24": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "You know, if the beach empties out tonight, maybe a little \"Sex on the Beach\" could be on the agenda.",
				choiceNext: false,
			},
			"25": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "Hmm... I do love cocktails, but I wouldn't say that's my—",
				choiceNext: false,
            },
			"26": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "Wait. Ohhh, my gosh! Haha! You totally got me with that one!",
				choiceNext: false,
            },
			"27": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "That's been on my bucket list forever, duh! But right now I want you in this moment to make me the happiest woman in the world!",
				choiceNext: false,
			},
			"28": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Of course, babe. After this view if I don't act now, I might just lose my mind.",
				choiceNext: false,
			},
			"29": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "Yeah? And what would you do if I told you no, and you'd have to wait until I change my mind?",
				choiceNext: false,
			},
			"30": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "That would be cruel. And I don't know how I'd hold it in! My balls would explode!",
				choiceNext: false,
			},
			"31": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "Hmm... you know what? I won't be that cruel to you, hehe! But...",
				choiceNext: false,
			},
			"32": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "Let's not waste everything that would burst out of you on a condom... I want you to shoot everything in me this time, and not a drop goes to waste!",
				choiceNext: false,
			},
			"33": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Hailey... are you sure about this?",
				choiceNext: false,
			},
			"34": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "I've never been this sure about anything. Right now, I'm the happiest I've ever been, here, with you! I want this to be perfect, not just for me, but for you too. And I'm not saying it just for you—because I want this too!",
				choiceNext: false,
			},
			"35": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Wow, Hailey! After this, there's no turning back!",
				choiceNext: false,
			},
			"36": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "Good! Only forward and only into me! It's the only way!",
				choiceNext: false,
			},
			"37": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "My body and soul are yours, Tyler!",
				choiceNext: false,
			},
			"38": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Up until now, I've been able to cope with my sanity, from now on my instincts will take over, and I will have a complete tunnel vision, in which I can only see Hailey in front of me. I ignore everything else around me.",
				choiceNext: false,
			},
			"39": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Up until now, most of our matings have been quite intense and passionate, but this one promises to be even more intense because of this special location, so I don't know what exactly I'm doing, we just instinctively devour each other.",
				choiceNext: false,
			},
			"40": {
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "If the next two weeks continue to be like this, then I might as well pack my bags and move off Earth, because I feel like I've reached the peak of my life, with nearly all my dreams and desires fulfilled.",
				choiceNext: false,
			},
			"41": {
                bgMusic: {
					name: 'Unexpected_ecchi_moment_occurs',
					command: 'FADE_OUT',
				},
                background: "special_scenes/hailey_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "It's all wonderful and perfect... However...",
				choiceNext: false,
			},
		},
    },
];