export const hailey_good_2 = [
    {
        sceneId: "",
        lengthNum: 30,
		endingSceneType: '',
        story: {
			"1": {
				bgMusic: {
					name: 'Hailey_good_ending',
					command: 'START'
				},
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Weeks and months pass, and my relationship with Hailey only grows stronger.",
				choiceNext: false,
            },
 			"2": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "It didn't take her long to gather up the courage to tell her, well, now ex-boyfriend what she'd had enough and it was time to go their separate ways.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "He wasn't exactly thrilled, but honestly, he didn't seem all that shaken by it either. He let Hailey go pretty quickly—maybe a sign that he really did see her as more of a „trophy” than an actual person.",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "That, if anything, made moving on even easier for Hailey, just reinforcing that she'd made the right call.",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "At work, we didn't keep things hidden for long; soon enough, we officially told people we were together. It wasn't easy, but I explained to my boss that, even though workplace policy frowns on relationships like this, it wasn't something I'd initiated—Hailey, the guest, had.",
				choiceNext: false,
			},
			"6": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "We were on thin ice, but thankfully, he accepted it. For now, I got to keep my job; we just have to be discreet around other guests.",
				choiceNext: false,
			},
			"7": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "And to properly celebrate the New Year, where else would we go than...",
				choiceNext: false,
            },
			"8": {
                otherSoundEffect: "beach-waves",
                background: "backgrounds/BG_beach_sunny",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "The Caribbean!",
				choiceNext: false,
			},
			"9": {
                background: "backgrounds/BG_beach_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Yep, that's right. Turns out, back when Hailey was still with her ex, she was practically begging him to go on a New Year's getaway. He finally agreed, but aside from handing over his credit card, he left all the planning to Hailey.",
				choiceNext: false,
			},
			"10": {
                background: "backgrounds/BG_beach_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Literally everything. Picking the location, booking the hotel, setting the exact dates so we'd be there over New Year's, even scheduling other services and activities. And since everything was booked with her email, her ex never got a single notification.",
				choiceNext: false,
			},
			"11": {
                background: "backgrounds/BG_beach_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Now that we're here, mid-vacation, it's safe to say he probably hasn't even noticed there was a trip in the works. No sign of him contacting anyone or trying to mess with our plans.",
				choiceNext: false,
			},
			"12": {
                background: "backgrounds/BG_beach_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Sure, switching his flight ticket to my name took a little extra effort, but it wasn't too hard.",
				choiceNext: false,
			},
			"13": {
                background: "backgrounds/BG_beach_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Is it kinda shady that we're here on his dime? Okay, yeah, maybe it is. But if he didn't care about Hailey so much that he even forgot about this vacation without her, does he at deserve this?",
				choiceNext: false,
			},
			"14": {
                background: "backgrounds/BG_beach_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I mean, that's one way to look at it, right? Our take is, if he didn't appreciate his girlfriend, well... that's on him.",
				choiceNext: false,
			},
			"15": {
                background: "backgrounds/BG_beach_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Never thought I'd end up in a place like this. The ocean, blue skies, warm sunshine—all right at the close of the year. I honestly can't think of a better way to wrap up everything this year threw at me.",
				choiceNext: false,
			},
			"16": {
                background: "backgrounds/BG_beach_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Oh wait, actually, there is something better...",
				choiceNext: false,
			},
			"17": {
                specialSceneNow: true,
				specialSceneId: "hailey_ending_2",
				background: "special_scenes/hailey_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Yup. The woman I love, who loves me right back.",
				choiceNext: false,
			},
			"18": {
				background: "special_scenes/hailey_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "It's not her first time in an exotic spot like this, but it's my very first, so I'm letting her take the lead and show me around, whether it's a sight, a food, or anything she thinks I should try.",
				choiceNext: false,
			},
			"19": {
				background: "special_scenes/hailey_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "Hellooo, earth to Tyler!",
				choiceNext: false,
			},
			"20": {
				background: "special_scenes/hailey_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Oh! I'm here!",
				choiceNext: false,
			},
			"21": {
				background: "special_scenes/hailey_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "Sure about that? Because it looked like you were lost in some deep thoughts there.",
				choiceNext: false,
			},
			"22": {
				background: "special_scenes/hailey_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "A little bit, yeah. I was just thinking about how lucky I am to have you here with me. I seriously feel like I've hit the jackpot.",
				choiceNext: false,
			},
            "23": {
				background: "special_scenes/hailey_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "Oh, babe, you're going to make me blush! Honestly, if my ex hadn't been so clueless and remembered this trip, we probably wouldn't even be here. So, I can't really take credit—just a stroke of luck.",
				choiceNext: false,
			},
			"24": {
				background: "special_scenes/hailey_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "True, but it's exactly that lucky twist that makes me feel so grateful to be with you. I never imagined I'd be in a place like this, and who knows when I'll get to come back. So about these two weeks... we need to make every second count.",
				choiceNext: false,
			},
			"25": {
				background: "special_scenes/hailey_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "Couldn't agree more. Two weeks is plenty of time to make memories that'll last a lifetime, so don't even think about snoozing or lazing around all day—the possibilities are endless here!",
				choiceNext: false,
            },
			"26": {
				background: "special_scenes/hailey_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Got it. Since you're the pro, I'm putting myself completely in your hands.",
				choiceNext: false,
            },
			"27": {
				background: "special_scenes/hailey_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "Perfect! Then come on! Shoes off, and let's check out the water!",
				choiceNext: false,
			},
			"28": {
				background: "special_scenes/hailey_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Right behind you.",
				choiceNext: false,
			},
			"29": {
				background: "special_scenes/hailey_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "The water was beautifully warm, crystal-clear, and a gorgeous shade of blue. The weather was pleasantly warm too—not that intense summer heat—so being here was pure bliss!",
				choiceNext: false,
			},
			"30": {
                bgMusic: {
					name: 'Hailey_good_ending',
					command: 'FADE_OUT',
				},
				background: "special_scenes/hailey_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "After our morning splash in the sea, we went back to the hotel for lunch. Then, for the rest of the afternoon, it was all about swimming and lounging on the beach.",
				choiceNext: false,
			},
		},
    },
];