export const hailey_good_1 = [
    {
        sceneId: "",
        lengthNum: 64,
		endingSceneType: '',
        story: {
			"1": {
				bgMusic: {
					name: 'Date_with_Hailey',
					command: 'START'
				},
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "We agreed that Hailey would come over to my place and tell me something important here.",
				choiceNext: false,
            },
 			"2": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "My apartment's pretty tidy, so she's going to see a clean space the first time she steps inside. I hope that scores me some points.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I already knew she was pretty laid-back, so it doesn't surprise me too much that she's willing to just come over, skipping the whole dinner and preamble thing... though it's still a little unexpected.",
				choiceNext: false,
			},
			"4": {
				otherSoundEffect: "tyler-doorbell",
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Anyway, I'm ready to welcome her, and after a short wait, the doorbell rings. I open the door, and it's really her.",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "Hey, Tyler. I'm not coming at a bad time, am I?",
				choiceNext: false,
			},
			"6": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "No. Hi, Hailey. Come on in.",
				choiceNext: false,
			},
			"7": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "Thanks.",
				choiceNext: false,
            },
			"8": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_surprised', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "Oh wow, it's so neat in here! I was expecting to walk into a typical bachelor mess.",
				choiceNext: false,
			},
			"9": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_surprised', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Well, glad I could surprise you in a good way. Want something to drink?",
				choiceNext: false,
			},
			"10": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "No thanks, I'm good.",
				choiceNext: false,
			},
			"11": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Alright... have a seat and let's get into it. Whatever it is you wanted to talk about.",
				choiceNext: false,
			},
			"12": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "Alright.",
				choiceNext: false,
			},
			"13": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "So... it's about us.",
				choiceNext: false,
			},
			"14": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "I mean, over this last week, I feel like we've been getting closer and closer. Almost too close, really, cuz... as you know, I'm in a relationship.",
				choiceNext: false,
			},
			"15": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Exactly. Some of the things you've said or done have totally caught me off guard — especially since you're already in a relationship.",
				choiceNext: false,
			},
			"16": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "Totally get that. I mean, I've surprised myself too. But when I'm with you... I dunno, it's like you flip a switch in me. You kinda just shut off the logical side of my brain, and I just start going on pure vibes, y'know?",
				choiceNext: false,
			},
			"17": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "Which isn't a bad thing... cuz honestly, I think that's a sign of attraction. I had a blast with you, and you showed me a new side of life I haven't seen.",
				choiceNext: false,
			},
			"18": {
				bgMusic: {
					name: 'Date_with_Hailey',
					command: 'STOP'
				},
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "...",
				choiceNext: false,
			},
			"19": {
				bgMusic: {
					name: 'A_happy_outcome',
					command: 'START'
				},
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "And honestly, I feel like letting you get this close to me was probably the best decision I've ever made.",
				choiceNext: false,
			},
			"20": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_smiling', null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "It's not just the attraction or the desire what I get from you, but not from my boyfriend. It is also respect, romance, and the feeling that you actually see me as a person.",
				choiceNext: false,
			},
			"21": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Honestly, I thought there's no way I could compete with everything your boyfriend offers you.",
				choiceNext: false,
			},
			"22": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "Yeah, he gives me a lot, true. But, Tyler, you know... it's not enough to just win a woman over; you have to know how to keep her, too.",
				choiceNext: false,
			},
            "23": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "Sure, he buys me fancy stuff, pays for my spa days, vacations, covers bills for this or that... but that's all I am to him. Nothing more, nothing less.",
				choiceNext: false,
			},
			"24": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "I'm not some puppy you just feed and walk, and then I'm all loyal and happy. And I'm definitely not some houseplant you just water and assume, \"Yup, she's good.\"",
				choiceNext: false,
			},
			"25": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "I might not be known for my brains, but I'm a woman with feelings, and I need to be treated like one... not as just a possession.",
				choiceNext: false,
            },
			"26": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I totally understand that, Hailey. But I still can't help feeling... I dunno, worried that after being with a guy who's so financially, um, comfortable, you might think my lifestyle is... a little lacking.",
				choiceNext: false,
            },
			"27": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "Oh, come on, Tyler, that's just you trying to compensate yourself compared to him and assuming you've lost.",
				choiceNext: false,
			},
			"28": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "But seriously, let that go—forever, okay? You're a great guy, and even though I was in a relationship, I let you get this close. Not only have I not regretted it, I've realized that you're exactly what I need! Because you give me what I actually want.",
				choiceNext: false,
			},
			"29": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_smiling', null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "There's life without designer handbags, you know? And sure, life's possible without love too, but you can live without one of them... but not necessarily without the other one.",
				choiceNext: false,
			},
			"30": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_smiling', null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "So that's why I want out of that relationship. I don't care if my life turns completely upside down—I want to start fresh with you.",
				choiceNext: false,
			},
			"31": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_smiling', null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "I don't know how many ways I have to say this for you to finally get it: you don't have anything to worry about, and you don't need to compare yourself to him.",
				choiceNext: false,
			},
			"32": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_smiling', null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "And for the record, I didn't choose him just for the money—he just tries to keep me around by flashing cash... let's just say, with mixed results.",
				choiceNext: false,
			},
			"33": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Alright, Hailey, I get it. I'll work on really letting this sink in; I just need a little time with it.",
				choiceNext: false,
			},
			"34": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_smiling', null],
				class: [null, "fadeUp", null],
			  	name: "Hailey",
			  	text: "I understand... it's a good start.",
				choiceNext: false,
			},
			"35": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_smiling', null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "Mind if I use the bathroom for a sec?",
				choiceNext: false,
			},
			"36": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Of course.",
				choiceNext: false,
			},
			"37": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_smiling', null],
				class: [null, 'fadeUpOut', null],
			  	name: "",
			  	text: "Hailey heads to the bathroom, and oddly enough, she takes her bag with her. I mean, doesn't she trust me by now? Like, she has to know I'm not about to snoop through her stuff.",
				choiceNext: false,
			},
			"38": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Still, what she said earlier really meant a lot to me. I never thought I'd hear such heartfelt words from a 12/10 woman like her.",
				choiceNext: false,
			},
			"39": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "But even so, I'd be the happiest guy alive if she actually meant it all.",
				choiceNext: false,
			},
			"40": {
                bgMusic: {
					name: 'A_happy_outcome',
					command: 'FADE_OUT',
                    insideOfScene: true
				},
                otherSoundEffect: 'door_noise',
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "A couple of minutes later I hear the bathroom door open again. There's a faint sound of footsteps coming my way—almost like she's sneaking up on me.",
				choiceNext: false,
			},
			"41": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I turn around and...",
				choiceNext: false,
			},
			"42": {
				bgMusic: {
					name: 'Unexpected_ecchi_moment_occurs',
					command: 'START',
				},
                specialSceneNow: true,
				specialSceneId: "hailey_ending_1",
				background: "special_scenes/hailey_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "Hello, handsome!",
				choiceNext: false,
			},
			"43": {
				background: "special_scenes/hailey_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "What... the... heck?!",
				choiceNext: false,
			},
			"44": {
				background: "special_scenes/hailey_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I see her in an outfit that, honestly, I've never seen on anyone, ever!",
				choiceNext: false,
			},
			"45": {
				background: "special_scenes/hailey_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "What's this sweet, pink setup covered in little hearts?",
				choiceNext: false,
			},
			"46": {
				background: "special_scenes/hailey_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "It's like it's walking that perfect line between innocent and adult, cute and incredibly sexy!",
				choiceNext: false,
			},
			"47": {
				background: "special_scenes/hailey_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Hailey... wh-what... what are you wearing?",
				choiceNext: false,
			},
			"48": {
				background: "special_scenes/hailey_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "You like it?",
				choiceNext: false,
			},
			"49": {
				background: "special_scenes/hailey_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I... I... I'm speechless.",
				choiceNext: false,
			},
			"50": {
				background: "special_scenes/hailey_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "Hehe, I can tell that.",
				choiceNext: false,
			},
			"51": {
				background: "special_scenes/hailey_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "I could tell you weren't exactly convinced by what I said earlier. So I figured, if words didn't cut it, then maybe actions would do the trick.",
				choiceNext: false,
			},
			"52": {
				background: "special_scenes/hailey_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "This is definitely playing dirty... but I'm not complaining!",
				choiceNext: false,
			},
			"53": {
				background: "special_scenes/hailey_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "Heh, good! Then it was worth it.",
				choiceNext: false,
			},
			"54": {
				background: "special_scenes/hailey_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "And I hope you like it enough that it makes you ready down there... because I came over here, dressed up in this cute little clothes, and I sure hope you know what's coming next...",
				choiceNext: false,
			},
			"55": {
				background: "special_scenes/hailey_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "After a sight like this, I'm not sure how long I'll last...",
				choiceNext: false,
			},
			"56": {
				background: "special_scenes/hailey_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "That's fine by me! We're not stopping until I'm totally satisfied!",
				choiceNext: false,
			},
			"57": {
				background: "special_scenes/hailey_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "And just so you know... I've got a pretty high sexdrive!",
				choiceNext: false,
			},
			"58": {
				background: "special_scenes/hailey_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "So get ready, because I'm about to put you through some serious... training. By the time I'm done with you, no other girl will even cross your mind!",
				choiceNext: false,
			},
			"59": {
				background: "special_scenes/hailey_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "From now on, I will be the personification of all your dreams and desires, the one you'll want to go all out for, until you are completely dry.",
				choiceNext: false,
			},
			"60": {
				background: "special_scenes/hailey_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Damn, Hailey! Never thought I'd hear such pornographic lines from a real, flesh-and-blood woman!",
				choiceNext: false,
			},
			"61": {
				background: "special_scenes/hailey_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "Heh, better get used to it, babe, 'cause from now on it will be everyday.",
				choiceNext: false,
			},
			"62": {
				background: "special_scenes/hailey_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Alright, let's not waste any more time, then!",
				choiceNext: false,
			},
			"63": {
				background: "special_scenes/hailey_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "What happened after that, well... let's leave that to everyone's imagination.",
				choiceNext: false,
			},
			"64": {
				background: "special_scenes/hailey_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I'll just say, whatever you're picturing, it's probably not far from the truth.",
				choiceNext: false,
			},
			"64": {
                bgMusic: {
					name: 'Unexpected_ecchi_moment_occurs',
					command: 'FADE_OUT',
				},
				background: "special_scenes/hailey_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "The time I had with Hailey was an absolute crazy, an experience I wouldn't trade for anything.",
				choiceNext: false,
                timeSkipNext: {
					content: "Some months later...",
					nextSceneType: "STORY",
					nextSceneNumber: "",
                    isInEnding: true
				}
			},
		},
    },
];