export const daena_good_3 = [
    {
        sceneId: "",
        lengthNum: 21,
		endingSceneType: '',
        story: {
			"1": {
				bgMusic: {
					name: 'Being_in_the_mood',
					command: 'START'
				},
                background: "backgrounds/BG_Daena_hotelroom",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "We get into the room, and Daena has practically thrown all elegance and politeness out the window. She's trying to get our clothes off, one by one—hers, then mine—without a second thought.",
				choiceNext: false,
            },
 			"2": {
                background: "backgrounds/BG_Daena_hotelroom",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I've never seen her act so wild. Sure, I'm not an idiot; I know what to expect when I'm in a love hotel with an excited girl like her. But it's still surprising that she'd imagine her first time to be in a place like this, and under these circumstances.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_Daena_hotelroom",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I'd imagined she'd be a lot more shy at first, maybe even hesitant. I thought she'd need a little coaxing, and that I'd gently guide her as she opened up to the experience.",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_Daena_hotelroom",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "But instead, she's like a fierce, ravenous tigress, pouncing on me with abandon. There's nothing wrong with that, but it's definitely a twist from what I'd expected of her after all this time.",
				choiceNext: false,
			},
			"5": {
                bgMusic: {
					name: 'Being_in_the_mood',
					command: 'FADE_OUT',
                    insideOfScene: true
				},
                background: "backgrounds/BG_Daena_hotelroom",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "And then, in a matter of moments...",
				choiceNext: false,
			},
			"6": {
                bgMusic: {
					name: 'Daena_ecchi',
					command: 'START',
				},
                specialSceneNow: true,
				specialSceneId: "daena_ending_3",
				background: "special_scenes/daena_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "This incredible sight unfolds in front of me!",
				choiceNext: false,
			},
			"7": {
				background: "special_scenes/daena_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "The sweet girl who let me take the lead in so many ways is now pinning me down on the bed, hovering over me with that look in her eyes, like she's about to lose control and devour me whole.",
				choiceNext: false,
            },
			"8": {
				background: "special_scenes/daena_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Daena! What is this? I never would've guessed you had this side to you!",
				choiceNext: false,
			},
			"9": {
				background: "special_scenes/daena_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Oh, but this is me, Tyler.",
				choiceNext: false,
			},
			"10": {
				background: "special_scenes/daena_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Honestly, I've always been this way, but no one's ever brought out this... animal in me before!",
				choiceNext: false,
			},
			"11": {
				background: "special_scenes/daena_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "I've had this huge appetite for you for a long time. I just held back because... I didn't want you thinking I was that kind of girl.",
				choiceNext: false,
			},
			"12": {
				background: "special_scenes/daena_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "But I know you're not that kind of girl.",
				choiceNext: false,
			},
			"13": {
				background: "special_scenes/daena_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Well, good, but if you could feel what I'm feeling right now, all this desire pent up inside me... Hehe... You better get ready, because by the time we're done, this room is going to look like a hurricane tore through it!",
				choiceNext: false,
			},
			"14": {
                background: "special_scenes/daena_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "And there's a good chance you won't even be able to stand.",
				choiceNext: false,
			},
			"15": {
                background: "special_scenes/daena_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Or maybe you won't. For your first time, you're awfully confident! Alright, I accept your challenge.",
				choiceNext: false,
			},
			"16": {
                background: "special_scenes/daena_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Hehe!",
				choiceNext: false,
			},
			"17": {
                background: "special_scenes/daena_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "And so, the moment finally happened. Daena gave me her innocence.",
				choiceNext: false,
			},
			"18": {
                background: "special_scenes/daena_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "It was a beautiful, intensely passionate experience, something I'd only dreamed about in my wildest fantasies.",
				choiceNext: false,
			},
			"19": {
                background: "special_scenes/daena_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I had definitely wanted this, but I never thought it would actually happen.",
				choiceNext: false,
			},
			"20": {
                background: "special_scenes/daena_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Yet here I am, in this moment, and as each piece of clothing comes off and things grow more intense, I can say with certainty that I'd want to relive this over and over!",
				choiceNext: false,
			},
			"21": {
                bgMusic: {
					name: 'Daena_ecchi',
					command: 'FADE_OUT',
				},
                background: "special_scenes/daena_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "However...",
				choiceNext: false,
			},
		},
    },
];