export const daena_good_1 = [
    {
        sceneId: "",
        lengthNum: 62,
		endingSceneType: '',
        story: {
			"1": {
				bgMusic: {
					name: 'Date_with_Daena',
					command: 'START'
				},
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I'm on my way to see Daena now; she wants to meet at her place. I've never been there before, so it's actually kind of exciting. It's been ages since I've had that experience of a teenage girl inviting me into her room.",
				choiceNext: false,
            },
 			"2": {
                background: "backgrounds/BG_Daena_house_sunny",
				backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "When I arrive at her family's house, I ring the doorbell, and after a short wait, Daena steps outside.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I notice a slight smile on her face, but she's not her usual high-energy self. She seems... subdued, which feels a bit strange for her.",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "She walks up to the gate, but instead of letting me in right away, she stops to chat with me first.",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "Hey, Tyler.",
				choiceNext: false,
			},
			"6": {
                background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Hey, Daena. Is something wrong?",
				choiceNext: false,
			},
			"7": {
                background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "Why do you ask?",
				choiceNext: false,
            },
			"8": {
                background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I don't know, you just seem... reserved. Like something's bothering you, and you're holding it in.",
				choiceNext: false,
			},
			"9": {
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "Oh... uh... didn't think it was that obvious.",
				choiceNext: false,
			},
			"10": {
                background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "So, there really is something, then.",
				choiceNext: false,
			},
			"11": {
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "Yeah... there is.",
				choiceNext: false,
			},
			"12": {
                background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "And does it have anything to do with what you messaged me about last night? You said you needed to talk about something important.",
				choiceNext: false,
			},
			"13": {
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "It's not just related to that—it's the whole thing.",
				choiceNext: false,
			},
			"14": {
                background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Alright, so... would you let me in and tell me what's going on?",
				choiceNext: false,
			},
			"15": {
				bgMusic: {
					name: 'Date_with_Daena',
					command: 'STOP'
				},
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "...",
				choiceNext: false,
			},
			"16": {
                background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Daena?",
				choiceNext: false,
			},
			"17": {
				bgMusic: {
					name: 'Yes_at_last',
					command: 'START'
				},
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "Sure... sorry, come on in!",
				choiceNext: false,
			},
			"18": {
                background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_sad', null],
				class: [null, 'fadeUpOut', null],
			  	name: "",
			  	text: "Daena finally opens the gate for me, and we walk into the house.",
				choiceNext: false,
			},
			"19": {
				background: "backgrounds/BG_Daena_livingroom_sunny",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "In the living room, we bump into Angie. I greet her, but she doesn't get a chance to reply, since Daena grabs my arm and quickly pulls me along.",
				choiceNext: false,
			},
			"20": {
				background: "backgrounds/BG_Daena_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "The most Angie can do is give me two thumbs up as if she's cheering me on. But... for what, exactly?",
				choiceNext: false,
			},
			"21": {
				background: "backgrounds/BG_Daena_bedroom_sunny",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Daena leads me to the stairs, which take us to the upper floor. We walk past a couple of doors until we finally enter the last one—a cute bedroom, which obviously must be hers.",
				choiceNext: false,
			},
			"22": {
				background: "backgrounds/BG_Daena_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Daena not only closes the door but locks it too. She looks super nervous, trying to crack her knuckles (kind of unsuccessfully), takes a couple of deep breaths, and finally looks me in the eyes.",
				choiceNext: false,
			},
            "23": {
				background: "backgrounds/BG_Daena_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_embarrassed', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "So... this is my room...",
				choiceNext: false,
			},
			"24": {
				background: "backgrounds/BG_Daena_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_embarrassed', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Yeah... I can see that.",
				choiceNext: false,
			},
			"25": {
				background: "backgrounds/BG_Daena_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_embarrassed', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "Alright... this isn't working... ummm...",
				choiceNext: false,
            },
			"26": {
				background: "backgrounds/BG_Daena_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_embarrassed', null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Welcome to my room! I... I've never brought anyone in here before.",
				choiceNext: false,
            },
			"27": {
                background: "backgrounds/BG_Daena_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_embarrassed', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "...alive.",
				choiceNext: false,
			},
			"28": {
				background: "backgrounds/BG_Daena_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_surprised', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "???",
				choiceNext: false,
			},
			"29": {
				background: "backgrounds/BG_Daena_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_angry', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "Tyler! Here I am, trying to be all serious so you'd be happy and not disappointed in me, and you're just cracking jokes like it's no big deal!",
				choiceNext: false,
			},
			"30": {
				background: "backgrounds/BG_Daena_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_angry', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Daena, you don't have to be so serious about it, really. It's cool I haven't seen your room before, but you know me—there's nothing to worry about.",
				choiceNext: false,
			},
			"31": {
				background: "backgrounds/BG_Daena_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_embarrassed', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "It's not... it's not even about what you'll think of my room, really... It's more about what you're gonna think of... what I want to say.",
				choiceNext: false,
			},
			"32": {
				background: "backgrounds/BG_Daena_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_embarrassed', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Well, I'm all ears, so just take your time. I'm not going anywhere.",
				choiceNext: false,
			},
			"33": {
				background: "backgrounds/BG_Daena_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_embarrassed', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "Hmm... okay, umm... yeah, alright. Take a seat... like, on my bed, go ahead. A-And could you... please close your eyes?",
				choiceNext: false,
			},
			"34": {
				background: "backgrounds/BG_Daena_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_embarrassed', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Close my eyes? But... why?",
				choiceNext: false,
			},
			"35": {
				background: "backgrounds/BG_Daena_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_embarrassed', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "Just go with it, okay? Pretty please!",
				choiceNext: false,
			},
			"36": {
				background: "backgrounds/BG_Daena_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_embarrassed', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Hmm... alright.",
				choiceNext: false,
			},
			"37": {
				background: "backgrounds/BG_Daena_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_embarrassed', null],
				class: [null, null, null],
			  	name: "",
			  	text: "Since she looks so nervous—more like totally freaked out, honestly—I decide to help her out a bit, maybe ease the tension by doing exactly what she asks.",
				choiceNext: false,
			},
			"38": {
                bgMusic: {
					name: 'Bad_ending_with_main_girls',
					command: 'FADE_OUT',
                    insideOfScene: true
				},
				background: "backgrounds/BG_dark",
                backGroundClass: "fadeIn",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_embarrassed', null],
				class: [null, 'fadeUpOut', null],
			  	name: "",
			  	text: "So, I sit on the bed, close my eyes, and wait.",
				choiceNext: false,
			},
			"39": {
                otherSoundEffect: "clothes-down",
				background: "backgrounds/BG_dark",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I can hear a faint shuffling sound in the background, but I resist the urge to peek.",
				choiceNext: false,
			},
			"40": {
				background: "backgrounds/BG_dark",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "When the sound finally stops, I feel the bed dip a little nearby. I figure she's just sat down too.",
				choiceNext: false,
			},
			"41": {
				background: "backgrounds/BG_dark",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I keep waiting for her to tell me I can open my eyes or something, but the room is still dead silent.",
				choiceNext: false,
			},
			"42": {
                otherSoundEffect: "kiss",
				background: "backgrounds/BG_dark",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Then, out of nowhere, her scent gets way stronger, like she's right up close—and then, in the very next second, I feel something soft, sweet, cherry-flavored brush against my lips!",
				choiceNext: false,
			},
			"43": {
				background: "backgrounds/BG_dark",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "It's a sudden, super short kiss, and I'm so shocked I open my eyes right away...",
				choiceNext: false,
			},
			"44": {
                bgMusic: {
					name: 'A_happy_outcome',
					command: 'START',
				},
                specialSceneNow: true,
				specialSceneId: "daena_ending_1",
				background: "special_scenes/daena_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "And there she is, right in front of me, so close our noses are touching. She's gently stroking my chin with one finger, staring deep into my eyes with this intense, completely irresistible look.",
				choiceNext: false,
			},
			"45": {
				background: "special_scenes/daena_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Daena, that was...",
				choiceNext: false,
			},
			"46": {
				background: "special_scenes/daena_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Not my first kiss... sadly. But I've never been this nervous for a kiss ever, and I've definitely never felt this... insanely epic rush afterward.",
				choiceNext: false,
			},
			"47": {
				background: "special_scenes/daena_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "This was just... different, you know!",
				choiceNext: false,
			},
			"48": {
				background: "special_scenes/daena_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I don't wanna ruin the mood, but... what about that other guy you were dating?",
				choiceNext: false,
			},
			"49": {
				background: "special_scenes/daena_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Um, hello? Until I'm, like, officially with someone, I can do whatever I want, can't I?",
				choiceNext: false,
			},
			"50": {
				background: "special_scenes/daena_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Well... yeah, fair enough.",
				choiceNext: false,
			},
			"51": {
				background: "special_scenes/daena_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "It's like she picked up this whole attitude from me.",
				choiceNext: false,
			},
			"52": {
				background: "special_scenes/daena_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "But... but I really hope this kiss changes things. Like, I want you to be the one I get to call my boyfriend from now on, Tyler.",
				choiceNext: false,
			},
			"53": {
				background: "special_scenes/daena_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Because... because... I mean, you totally impressed me, being all patient and nice with me, and... I kinda started to really like you over time.",
				choiceNext: false,
			},
			"54": {
				background: "special_scenes/daena_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "You're something else, Daena. Not just because... wait, are you in your bra?! Uh... I mean... because you kiss me first and only then tell me how you feel.",
				choiceNext: false,
			},
			"55": {
				background: "special_scenes/daena_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Well, my thinking was, if I did it the other way around, I might never get to the kiss part. So I figured... better take a risk.",
				choiceNext: false,
			},
			"56": {
				background: "special_scenes/daena_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "It was definitely a surprise, I'll give you that. But you didn't have to, really, because I've really come to like you too, Daena. When I first started working here, I noticed you right away. But the problem was, you were still... well, underage.",
				choiceNext: false,
			},
			"57": {
				background: "special_scenes/daena_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "You have no idea how crazy it was waiting for you to officially be an adult...! And yeah, I was kinda just hoping no one else would scoop you up in the meantime.",
				choiceNext: false,
			},
			"58": {
				background: "special_scenes/daena_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "There was that close call, sure, but I'm so glad we ended up right here anyway, somehow.",
				choiceNext: false,
			},
			"59": {
				background: "special_scenes/daena_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Oh, it wasn't just somehow, Tyler. It was all you and your charm.",
				choiceNext: false,
			},
			"60": {
				background: "special_scenes/daena_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Oh, Daena...",
				choiceNext: false,
			},
			"61": {
				background: "special_scenes/daena_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "What happened next in that room... well, that's my secret.",
				choiceNext: false,
			},
			"62": {
                bgMusic: {
					name: 'A_happy_outcome',
					command: 'FADE_OUT',
				},
				background: "special_scenes/daena_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "But from that moment on, Daena and I were officially together. A little while later, we went downstairs hand-in-hand to break the news to her family.",
				choiceNext: false,
                timeSkipNext: {
					content: "Some weeks later...",
					nextSceneType: "STORY",
					nextSceneNumber: "",
                    isInEnding: true
				}
			},
		},
    },
];