export const daena_good_2 = [
    {
        sceneId: "",
        lengthNum: 20,
        story: {
			"1": {
				bgMusic: {
					name: 'Daena_good_ending',
					command: 'START'
				},
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Weeks go by, and summer vacation is coming to an end. That means Daena's school is about to start up again, but as for my work, it won't make much of a difference.",
				choiceNext: false,
            },
 			"2": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Up till now, she's only had prep classes, which were more relaxed over the summer, but come September, she'll be a lot busier. Still, we'll find a way to be together somehow.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "We made the most of our summer, planning all sorts of outings to make good use of the time we had before school made things complicated.",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "At work, we didn't keep it a secret for too long—we actually told them we were dating fairly early on. It wasn't easy, but we managed to explain to my boss that even though the rules technically forbid this sort of relationship, it wasn't me who initiated it—it was Daena, as a guest.",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "It was touch-and-go there for a while, but they accepted it. I still have my job, though they expect us to keep things discreet around other guests from now on.",
				choiceNext: false,
			},
			"6": {
                background: "backgrounds/BG_oldtown_sunny",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "By late August, one day, we went on a romantic walk in the old town. We held hands the whole time, with no intention of letting go.",
				choiceNext: false,
			},
			"7": {
                background: "backgrounds/BG_oldtown_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "The walk was Daena's idea—she clearly has something in mind, since it feels like she's leading me somewhere specific. By now, I know her well enough to pick up on her hints.",
				choiceNext: false,
            },
			"8": {
                background: "backgrounds/BG_oldtown_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Daena, where are we...",
				choiceNext: false,
			},
			"9": {
                specialSceneNow: true,
				specialSceneId: "daena_ending_2",
				background: "special_scenes/daena_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "She suddenly kisses me, cutting me off before I can finish my question.",
				choiceNext: false,
			},
			"10": {
				background: "special_scenes/daena_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Don't ask anything, Tyler. I have a surprise, and I don't want to spoil it.",
				choiceNext: false,
			},
			"11": {
				background: "special_scenes/daena_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Alright, then—just lead the way, I'm right behind you.",
				choiceNext: false,
			},
			"12": {
				background: "special_scenes/daena_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "I'm so glad you're so loyal!",
				choiceNext: false,
			},
			"13": {
                background: "special_scenes/daena_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "She kisses me again.",
				choiceNext: false,
			},
			"14": {
                background: "special_scenes/daena_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "That's how our relationship is—tons of kisses and snuggling. Sometimes it feels like a lot, but I chalk it up to her being young, me being her first serious, grown-up love, and her still being very much in that honeymoon phase.",
				choiceNext: false,
			},
			"15": {
                background: "special_scenes/daena_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Guys around my age—and especially the younger ones—often give me these envious and slightly judging looks, like, \"How'd he manage to land a girl like her?\"",
				choiceNext: false,
			},
			"16": {
                background: "special_scenes/daena_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Well... sometimes I wonder the same thing, but one thing's clear: I must be doing something right.",
				choiceNext: false,
			},
			"17": {
                specialSceneNow: true,
				specialSceneOut: true,
				specialSceneId: null,
				background: "backgrounds/BG_oldtown_lovehotel",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "After that kiss, we continued our walk until we stopped in front of a cute little hotel. As soon as we stepped inside, it was obvious this wasn't just any hotel... it was definitely a love hotel!",
				choiceNext: false,
			},
			"18": {
                bgMusic: {
					name: 'Daena_good_ending',
					command: 'FADE_OUT',
				},
				background: "backgrounds/BG_oldtown_lovehotel",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Once I realized that, I pretty much lost all track of time. With the room key in hand, we hurried upstairs, but Daena was already swept up in her feelings the second we got there!",
				choiceNext: false,
			},
		},
    },
];