export const reina_good_3 = [
    {
        sceneId: "",
        lengthNum: 29,
        story: {
			"1": {
				bgMusic: {
					name: 'Being_in_the_mood',
					command: 'START'
				},
                background: "backgrounds/BG_sunset_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "We drove back quickly, and as soon as we stepped through the door, we could finally act like two lovestruck teenagers again.",
				choiceNext: false,
            },
 			"2": {
                background: "backgrounds/BG_sunset_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Sometimes we don’t even make it to the bedroom and just have to deal with our desires wherever we are, but this time Reina asked me to go ahead to the bedroom and wait for her—she had a little surprise planned for me.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_Reina_bedroom_sunny",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I did as she said, making myself comfortable on her bed while I waited. It took about ten minutes before I heard her footsteps approaching and saw the bedroom door finally move.",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_Reina_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I was almost certain she had slipped into some special outfit, which was why she wanted us to separate for a bit, but…",
				choiceNext: false,
			},
			"5": {
                bgMusic: {
					name: 'Determinations_for_Reina',
					command: 'START'
				},
                specialSceneNow: true,
				specialSceneId: "reina_ending_3",
				background: "special_scenes/reina_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "… I was not expecting this outfit at all!",
				choiceNext: false,
			},
			"6": {
				background: "special_scenes/reina_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Hello, Darling! Do you like what you see?",
				choiceNext: false,
			},
			"7": {
				background: "special_scenes/reina_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Uh… well… I don’t even know what to say… I imagined a lot of things you might wear, but this… this didn’t even cross my mind in my wildest dreams!",
				choiceNext: false,
            },
			"8": {
				background: "special_scenes/reina_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "That’s actually a bigger compliment than a simple „yes”, so I’ll take it.",
				choiceNext: false,
			},
			"9": {
				background: "special_scenes/reina_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "But what’s this… this sexy bride outfit? Is it borrowed, just a costume, or…?",
				choiceNext: false,
			},
			"10": {
				background: "special_scenes/reina_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "No, it’s actually part of my wedding outfit from about ten years ago.",
				choiceNext: false,
			},
			"11": {
				background: "special_scenes/reina_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "I didn’t want to drag the full gown down from the attic, because it’s big and heavy, takes ages to put on and take off, and if anything happened to it, cleaning it would be a nightmare. Not to mention explaining why I’m washing a wedding dress.",
				choiceNext: false,
			},
			"12": {
				background: "special_scenes/reina_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Fair point.",
				choiceNext: false,
			},
			"13": {
				background: "special_scenes/reina_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "But everything else you see on me, I really did wear on my wedding day. In this, I said „I do” to my husband… though I wish I’d said it to you instead!",
				choiceNext: false,
			},
			"14": {
				background: "special_scenes/reina_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "And that’s exactly what gave me the idea. While we can’t get married—yet—I wanted to relive that experience with you, at least symbolically. In the very same outfit where I once pledged eternal loyalty to someone else, I want to overwrite that vow and redirect it toward you instead…",
				choiceNext: false,
			},
			"15": {
				background: "special_scenes/reina_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "And seal it with actions to make it \"’til death do us part\".",
				choiceNext: false,
			},
			"16": {
				background: "special_scenes/reina_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Wow… I don’t even know what to say. I understand how much emotional weight a wedding carries for a woman. And most people want to wear their wedding attire only once in their lives.",
				choiceNext: false,
			},
			"17": {
				background: "special_scenes/reina_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "If you’re saying you’re wearing this outfit a second time just to transfer your eternal loyalty to me… because you’re that sure about us… I honestly can’t think of a more determined love confession.",
				choiceNext: false,
			},
			"18": {
				background: "special_scenes/reina_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Neither can I. So, Tyler…",
				choiceNext: false,
			},
			"19": {
				background: "special_scenes/reina_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "I hereby vow to you that I will remain your devoted lover in the future, strive to give you everything you need, and work tirelessly to become more than just your lover—to become your girlfriend, and as soon as possible, your first and only wife.",
				choiceNext: false,
			},
			"20": {
				background: "special_scenes/reina_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "I promise to stand by you, even if you hurt me, because I believe there’s no problem we can’t discuss or solve together.",
				choiceNext: false,
			},
			"21": {
				background: "special_scenes/reina_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Even when generational differences cause disagreements, I’ll do my best to remain open to learning from you, just as you’ve learned from me.",
				choiceNext: false,
			},
			"22": {
				background: "special_scenes/reina_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "I promise to stay forever loyal to you, and you alone will be the one I allow to love me, approach me as my partner, and touch me with that kind of intention.",
				choiceNext: false,
			},
            "23": {
				background: "special_scenes/reina_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "I want you as my one and only love and future husband, and I promise to honor you in good times and bad, in wealth and poverty, in sickness and health, until death do us part.",
				choiceNext: false,
			},
			"24": {
				background: "special_scenes/reina_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "I love you, Tyler!",
				choiceNext: false,
			},
			"25": {
				background: "special_scenes/reina_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I’ve always dreamed of someone saying a vow like this to me. And given how things started between us, I never imagined I’d hear these words from Reina of all people.",
				choiceNext: false,
            },
			"26": {
				background: "special_scenes/reina_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "This isn’t our wedding day, but even so, I can’t describe how happy I am that she’s chosen me as the one she wants to spend her life with, swearing eternal loyalty.",
				choiceNext: false,
            },
			"27": {
				background: "special_scenes/reina_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I want to say something just as meaningful and heartfelt in return, but my thoughts feel so jumbled. Words don’t seem to want to come out—everything feels so heavy!",
				choiceNext: false,
			},
			"28": {
				background: "special_scenes/reina_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "At the very least, I want to tell her that I love her too!",
				choiceNext: false,
			},
			"29": {
                bgMusic: {
					name: 'Determinations_for_Reina',
					command: 'FADE_OUT'
				},
				background: "special_scenes/reina_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "But just as I try to speak…",
				choiceNext: false,
			},
		},
    },
];