export const reina_good_1 = [
    {
        sceneId: "",
        lengthNum: 64,
        story: {
			"1": {
				bgMusic: {
					name: 'Date_with_Reina',
					command: 'START'
				},
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "It's finally Reina's turn. Like Hailey, she wants to come over and talk to me about something important.",
				choiceNext: false,
            },
 			"2": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Reina's been here before, so there won't be any surprises for her this time, but I still have everything ready to welcome an important guest.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "The last time she hinted she had something serious to talk about was right before our first kiss. Then, at the following meetup, she tried to step back from all this, but I managed to convince her to keep this affair going.",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I'm hoping that, once again, she's here to talk because we've reached some big milestone, whatever that might be...",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Maybe our relationship is about to get more intimate, or she's finally decided how things are going to go for us in the future. I don't know.",
				choiceNext: false,
			},
			"6": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "But, damn, I'm so ready to find out!",
				choiceNext: false,
			},
			"7": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Right on time, she arrives at my place. We settle on the couch, and the conversation begins.",
				choiceNext: false,
            },
			"8": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "How are you feeling, Tyler?",
				choiceNext: false,
			},
			"9": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "To be honest, I'm a bit nervous.",
				choiceNext: false,
			},
			"10": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "Really? What about?",
				choiceNext: false,
			},
			"11": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Well, every time you tell me you have something serious to discuss, it usually means some big step forward, and I'm curious to know what's on your mind.",
				choiceNext: false,
			},
			"12": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "Ah, you're right; things have always gone that way, haven't they?",
				choiceNext: false,
			},
			"13": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "So, what do you want to talk about?",
				choiceNext: false,
			},
			"14": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "Well, it's pretty clear—it's about us. I don't think that's a surprise to you.",
				choiceNext: false,
			},
			"15": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_normal', null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "To be specific, I want to talk about our future.",
				choiceNext: false,
			},
			"16": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Oh! That was one of my guesses.",
				choiceNext: false,
			},
			"17": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "Good guess.",
				choiceNext: false,
			},
			"18": {
				bgMusic: {
					name: 'Date_with_Reina',
					command: 'FADE_OUT',
					insideOfScene: true
				},
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_normal', null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "So... I've spent a lot of time thinking about what we've gone through together. How we've handled our meetups, how things could be different in the future, what we've been able to give each other so far, and what more we might be able to share...",
				choiceNext: false,
			},
			"19": {
				bgMusic: {
					name: 'A_happy_outcome',
					command: 'START'
				},
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "And I’ve decided that what I have now... it’s not enough for me. I want more, and I’d like for us to figure out together how to make that happen.",
				choiceNext: false,
			},
			"20": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "You mean... in secret?",
				choiceNext: false,
			},
			"21": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "At first, yes. But over time, without any secrets, and out in the open for everyone to see.",
				choiceNext: false,
			},
			"22": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Are you saying that…?",
				choiceNext: false,
			},
            "23": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "Yes. I’ve decided that I want to spend the rest of my life with you, because I’ve realized that as a married woman, I don’t have to settle for this.",
				choiceNext: false,
			},
			"24": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Life can be so much more exciting and fulfilling, and it wasn’t the role of being a wife or mother that held me back—it’s my marriage itself that hasn’t brought me the happiness I’ve been longing for.",
				choiceNext: false,
			},
			"25": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "But with you, Tyler, I am happy. Of course, I don’t want to give up my daughters, and the divorce will be a huge step. I need to prepare for it carefully so I don’t lose everything I’ve worked so hard to build.",
				choiceNext: false,
            },
			"26": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "That’s why I’m saying we’ll need to keep this a secret at first. Once the divorce is finalized and my girls have come to terms with the fact that their parents are no longer together, then we can go public.",
				choiceNext: false,
            },
			"27": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "I know this will take time and energy from you as well, but... with all my heart, I’m asking you to please be patient with me.",
				choiceNext: false,
			},
			"28": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "You know, Reina, people always say that good things are worth the wait. And to me, you’re the best thing that’s ever happened in my life.",
				choiceNext: false,
			},
			"29": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "So even if it takes years, I’ll wait. In the meantime, we can still meet and be together. If we’ve managed to keep our meetings secret this far, we can keep making it work.",
				choiceNext: false,
			},
			"30": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_grin', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "Oh, Tyler!",
				choiceNext: false,
			},
			"31": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_grin', null],
				class: [null, null, null],
			  	name: "",
			  	text: "Reina hugs me tighter than she ever has before. For a fleeting moment, I think I see her eyes glisten. Just a few seconds pass in silent embrace when... ",
				choiceNext: false,
			},
			"32": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "I love you!",
				choiceNext: false,
			},
			"33": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "…!",
				choiceNext: false,
			},
			"34": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Wait, what? Did I hear that right?",
				choiceNext: false,
			},
			"35": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_embarrassed', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "Oh, um… I’m sorry, maybe I shouldn’t have said that yet.",
				choiceNext: false,
			},
			"36": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_embarrassed', null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "It just slipped out, but I don’t want to push or rush you. So if you’re not ready to feel the same way yet, I completely understand.",
				choiceNext: false,
			},
			"37": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_embarrassed', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "No, no, Reina, it’s nothing like that. I’m so glad you said it, because I’ve been feeling for a while now that my initial admiration for you has grown into love. I just didn’t know if saying it first, considering you’re married and all, would feel like a relief for you or more of a burden.",
				choiceNext: false,
			},
			"38": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "I completely understand your concern, but it seems we can both breathe a little easier now, because it’s mutual.",
				choiceNext: false,
			},
			"39": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Yes, and it’s such a relief to finally say it and to know exactly how you feel.",
				choiceNext: false,
			},
			"40": {
                bgMusic: {
					name: 'A_happy_outcome',
					command: 'FADE_OUT',
                    insideOfScene: true
				},
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "Oh, you have no idea how much of a relief it is for me too.",
				choiceNext: false,
			},
			"41": {
                bgMusic: {
					name: 'Reina_ecchi',
					command: 'START'
				},
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_seductive', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "Tyler… don’t you want to continue this in your room?",
				choiceNext: false,
			},
			"42": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_seductive', null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "My goodness! How long have I been waiting to hear her say those words? Stay calm, stay composed!",
				choiceNext: false,
			},
			"43": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_seductive', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Hmm… of course.",
				choiceNext: false,
			},
			"44": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_seductive', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "Come here, you…!",
				choiceNext: false,
			},
			"45": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_seductive', null],
				class: [null, 'fadeUpOut', null],
			  	name: "",
			  	text: "Reina doesn’t even finish her sentence before we’re kissing each other nonstop. At the same time, we’re taking small, unsteady steps toward my room, trying to pull each other’s clothes off along the way.",
				choiceNext: false,
			},
			"46": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "As the distance to the bed shortens, so do the layers of clothing. By the time we finally reach the bed, I’m greeted with a sight that leaves me utterly speechless…",
				choiceNext: false,
			},
            "47": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "This moment isn’t just about the outer beatuy. I’ve fought so hard for it because I desire Reina deeply, both body and soul.",
				choiceNext: false,
			},
            "48": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "While the emotional fulfillment is something I know I’ll need to wait longer for, the physical connection is right here and now. And in this moment, I can say it’s all been worth it.",
				choiceNext: false,
			},
            "49": {
                specialSceneNow: true,
				specialSceneId: "reina_ending_1",
				background: "special_scenes/reina_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I’ve never seen her like this before. I’ve imagined it countless times, sure, but seeing her in real life is far better than anything my mind or even a photograph could ever capture.",
				choiceNext: false,
			},
            "50": {
				background: "special_scenes/reina_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I have no idea how much time passes while I’m just being there, mesmerized by her body. She’s so captivating that I can’t get enough of her!",
				choiceNext: false,
			},
            "51": {
				background: "special_scenes/reina_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Hmm… what’s the matter? Do you like what you see that much?",
				choiceNext: false,
			},
            "52": {
				background: "special_scenes/reina_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "There aren’t words to describe just how much!",
				choiceNext: false,
			},
            "53": {
				background: "special_scenes/reina_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Hehe. Well, part of this is thanks to you, Tyler—keeping me in such good shape! This body is partly your doing, which is why I want to share it with you, and only with you.",
				choiceNext: false,
			},
            "54": {
				background: "special_scenes/reina_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "But your…",
				choiceNext: false,
			},
            "55": {
				background: "special_scenes/reina_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Don’t even try to bring up my husband! He had his chance, but after two kids, it was like he stopped caring. I thought maybe childbirth had changed my body so much that he didn’t find me attractive anymore, and eventually, I just accepted it.",
				choiceNext: false,
			},
            "56": {
				background: "special_scenes/reina_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Then you came along. You brought out the best from this body. You made me believe in myself again. You gave me back my confidence. You made me feel like a woman again. And as it turns out, I can still be desirable if I managed to seduce a young guy like you, despite all the girls your age who must be after you.",
				choiceNext: false,
			},
            "57": {
				background: "special_scenes/reina_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "So, you’re the one who deserves all of this. You’re the one who gets to touch it, and you’re the one who will have the best and most intense experiences of your life with it. Trust me—I know what I’m capable of.",
				choiceNext: false,
			},
            "58": {
				background: "special_scenes/reina_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "And I’ve noticed something else too. My body only responds to you now, whether it’s the sight of you or your touch… and the way it responds is no small thing.",
				choiceNext: false,
			},
            "59": {
				background: "special_scenes/reina_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Do you even know how long I have to go to trainings with a couple of panties? Not because you make me sweat that much... but because during the hour I spend there, my panties get so wet that they could be squeezed!",
				choiceNext: false,
			},
            "60": {
				background: "special_scenes/reina_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Reina… this is all incredibly enticing, but it feels too good to be true.",
				choiceNext: false,
			},
            "61": {
				background: "special_scenes/reina_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Does it now? Then take a good look! Here I am, lying in your bed, half-naked, completely yours! Whether you take a look with your hands or your mouth… that’s entirely up to you.",
				choiceNext: false,
			},
            "62": {
				background: "special_scenes/reina_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "She’s presented me with quite the difficult choice, but I didn’t hesitate for long. And let me tell you… she wasn’t lying.",
				choiceNext: false,
			},
            "63": {
				background: "special_scenes/reina_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "As for what happened in my room after that, well, it would take too long to recount in detail, and honestly, no words could ever truly capture the experience.",
				choiceNext: false,
			},
            "64": {
                bgMusic: {
					name: 'Reina_ecchi',
					command: 'FADE_OUT',
				},
				background: "special_scenes/reina_ending_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "The essence of it is this: it felt as though our souls had once been one, split into two halves, and in that moment, amidst a whirlwind of emotions, they reunited again.",
				choiceNext: false,
                timeSkipNext: {
					content: "Some months later...",
					nextSceneType: "STORY",
					nextSceneNumber: "",
                    isInEnding: true
				}
			},
		},
    },
];