export const reina_good_2 = [
    {
        sceneId: "",
        lengthNum: 32,
		endingSceneType: '',
        story: {
			"1": {
				bgMusic: {
					name: 'Reina_good_ending',
					command: 'START'
				},
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Months pass, and while my relationship with Reina grows stronger, we still have to meet in secret. Of course, it's understandable—divorces don’t happen overnight.",
				choiceNext: false,
            },
 			"2": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "What has happened, though, is that Reina has started planting the seeds of her divorce with her husband. Initially, she told him that since he often comes home late from work, when she’s already asleep (which isn’t necessarily true), he shouldn’t disturb her in the bedroom but should sleep in the study instead.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I don’t know what kind of persuasion it took, but somehow she managed to convince him. So, they haven’t been sleeping in the same bed for quite some time now. They even replaced the double bed, and bought two smaller ones, one for the bedroom and one for the study.",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "And as for the double bed? Well, Reina has embarked on a little extra money-making opportunity. Teaming up with some acquaintances, they managed to scrape together enough capital to start buying rental properties in the area, renovating them, and either renting them out or selling them at a good price.",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Maybe our relationship is about to get more intimate, or she's finally decided how things are going to go for us in the future. I don't know.",
				choiceNext: false,
			},
			"6": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "The first few were done on a shoestring budget and through favors, but as the initial revenue started rolling in, Reina became less reliant on her acquaintances' goodwill—or her husband’s money. Now she can buy and renovate rental properties with her own capital.",
				choiceNext: false,
			},
			"7": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Among these, there’s one property that isn’t particularly large or luxurious, but no one’s renting it because we’ve started designing and shaping it as our shared future home. That double bed ended up here.",
				choiceNext: false,
            },
			"8": {
                background: "backgrounds/BG_coffeshop_outside1_sunny",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "That brings us to where we are now, near the end of autumn, on a date in this cozy café.",
				choiceNext: false,
			},
			"9": {
                background: "backgrounds/BG_coffeshop_outside1_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "As our relationship strengthens, we’ve slowly begun to appear together more often in public, though we’re still keeping things discreet.",
				choiceNext: false,
			},
			"10": {
                background: "backgrounds/BG_coffeshop_outside1_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "This weekend, her husband is away at an overnight conference, and she left the kids with their grandmother for the entire day, claiming she needed to inspect some of the properties.",
				choiceNext: false,
			},
			"11": {
                background: "backgrounds/BG_coffeshop_outside1_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "So practically the whole day is ours—we’re not constrained by time, which allows for a leisurely coffee date.",
				choiceNext: false,
			},
			"12": {
                specialSceneNow: true,
				specialSceneId: "reina_ending_2",
				background: "special_scenes/reina_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "How’s your coffee, Tyler?",
				choiceNext: false,
			},
			"13": {
				background: "special_scenes/reina_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Not bad. Considering I don’t usually drink coffee, you were right—these autumn flavors are actually pretty good.",
				choiceNext: false,
			},
			"14": {
				background: "special_scenes/reina_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "See? I told you—listen to the wise old fox because the old fox always knows where to lick the salt first.",
				choiceNext: false,
			},
			"15": {
				background: "special_scenes/reina_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "That… that’s a saying I’ve never heard before. What does it even mean?",
				choiceNext: false,
			},
			"16": {
				background: "special_scenes/reina_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "I have no idea. I just made it up.",
				choiceNext: false,
			},
			"17": {
				background: "special_scenes/reina_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Reina!",
				choiceNext: false,
			},
			"18": {
				background: "special_scenes/reina_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Hehe! But I guess it could mean something like older or more experienced people already know what’s good, so it’s worth listening to them.",
				choiceNext: false,
			},
			"19": {
                background: "special_scenes/reina_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "You’ve got a point there. I mean, even in bed, you move like a total pro.",
				choiceNext: false,
			},
			"20": {
				background: "special_scenes/reina_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "If you don’t mind, let’s not bring that up in such a public place… but yes.",
				choiceNext: false,
			},
			"21": {
				background: "special_scenes/reina_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "I know what I need, and I’ve never had any complaints so far. Plus, you have everything that can take it to the next level. We fit together perfectly…",
				choiceNext: false,
			},
			"22": {
				background: "special_scenes/reina_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "It’s just a shame you weren’t born sooner, or I later, because my life would’ve been so much happier if I could have married you.",
				choiceNext: false,
			},
            "23": {
				background: "special_scenes/reina_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Yeah, don’t even get me started. Not a day goes by where I don’t think about that at least once.",
				choiceNext: false,
			},
			"24": {
				background: "special_scenes/reina_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Well, here we are. We found each other, and while we can’t change the past, we still have time to connect our futures and enjoy life the way we want to.",
				choiceNext: false,
			},
			"25": {
				background: "special_scenes/reina_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I really hope everything works out.",
				choiceNext: false,
            },
			"26": {
				background: "special_scenes/reina_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Trust me, it will. You know, listen to the wise old fox.",
				choiceNext: false,
            },
			"27": {
				background: "special_scenes/reina_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Alright, then I’ll listen.",
				choiceNext: false,
			},
			"28": {
				background: "special_scenes/reina_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Good. If you’re done with your coffee, we can head back to my place. Let’s make the most of the time while the house is free.",
				choiceNext: false,
			},
			"29": {
				background: "special_scenes/reina_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "In that case, I’m not wasting another second!",
				choiceNext: false,
			},
			"30": {
				background: "special_scenes/reina_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "In that case, I’m not wasting another second!",
				choiceNext: false,
			},
			"31": {
				background: "special_scenes/reina_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "As soon as Reina said that, I downed the rest of my coffee in one go. She just smiled, but I could see how pleased she was that I prioritized her and spending quality time together.",
				choiceNext: false,
			},
			"32": {
                bgMusic: {
					name: 'Reina_good_ending',
					command: 'FADE_OUT',
				},
				background: "special_scenes/reina_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "The sun was already setting—it is autumn, after all—but she didn’t need to pick up the girls until dinner, so we still had a few hours to enjoy our private time.",
				choiceNext: false,
			},
		},
    },
];