export const final_normal = [
	{
		sceneId: "",
		lengthNum: 11,
		story: {
			"1": {
				otherSoundEffect: "alarm-clock",
				background: "backgrounds/BG_dark",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "*bip-bip* *bip-bip*",
			},
			"2": {
				background: "backgrounds/BG_dark",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "???",
				choiceNext: false,
			},
			"3": {
				bgMusic: {
					name: 'Left_alone',
					command: 'START'
				},
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Huh? Morning already?",
				choiceNext: false,
			},
			"4": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Waking up feels heavy and strange, and it takes me a few tries to shut off my alarm.",
				choiceNext: false,
			},
			"5": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I need a few seconds for my brain to catch up, to process what just happened. ",
				choiceNext: false,
			},
			"6": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I had a dream about the four girls and Lindsay—so real that I was completely immersed, lost in a blur between dream and reality.",
				choiceNext: false,
			},
			"7": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I’d like to say it taught me something valuable, but it didn’t. It was my dream, my mind, my rules.",
				choiceNext: false,
			},
			"8": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "In reality, things don’t happen my way most of the time, so if I want to get in sync with others, so I have to somehow pick up the rhythm with others if I want to swing on the same page as them.",
				choiceNext: false,
			},
			"9": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "But as an alternate story? It was perfect. Some parts were almost too good to be true... but that doesn’t mean that at least some of it can’t become real.",
				choiceNext: false,
			},
			"10": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
				textClass: "italic",
			  	text: "I just have to be smart about it, and I can’t forget: right now, I have only Reina in this reality.",
				choiceNext: false,
			},
			"11": {
				bgMusic: {
					name: 'Left_alone',
					command: 'FADE_OUT'
				},
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
				textClass: "italic",
			  	text: "I’ve got one chance… and I can’t mess it up.",
				choiceNext: false,
                outroNext: ''
			},
		},
	},
];