export const final_bad = [
	{
		sceneId: "0032",
		lengthNum: 8,
		endingSceneType: '',
		story: {
			"1": {
				bgMusic: {
					name: 'Sadly_alone',
					command: 'START'
				},
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "*Heavy breathing*",
			},
			"2": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Suddenly, I wake up in my bed again! My heart is pounding furiously as I get up.",
				choiceNext: false,
			},
			"3": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "But there's no hangover, my room is in order, no smell of sex, and I'm alone in my apartment! It seems the whole thing was just a dream.",
				choiceNext: false,
			},
			"4": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Thank goodness! That was horrible!",
				choiceNext: false,
			},
			"5": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I just dreamed up an entire week with these guests... and my unwelcome ex.",
				choiceNext: false,
			},
			"6": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "That dream went horribly wrong by the end; it couldn't have been worse, with everyone confronting me all at once and attacking me for what I'd done.",
				choiceNext: false,
			},
			"7": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
				textClass: "italic",
			  	text: "This time I got lucky that it was just a dream, but in real life, I'd better be careful not to end up in a situation like that.",
				choiceNext: false,
			},
			"8": {
				bgMusic: {
					name: 'Sadly_alone',
					command: 'FADE_OUT'
				},
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
				textClass: "italic",
			  	text: "Though I guess I wouldn't, since Reina is the only one I have...",
				choiceNext: false,
                outroNext: 'Lindsay'
			},
		},
	},
];