export const reina_bad = [
	{
		sceneId: "",
		lengthNum: 43,
		endingSceneType: '',
		story: {
			"1": {
				bgMusic: {
					name: 'Date_with_Reina',
					command: 'START'
				},
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "It's finally Reina's turn. Like Hailey, she wants to come over and talk to me about something important.",
				choiceNext: false,
            },
 			"2": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Reina's been here before, so there won't be any surprises for her this time, but I still have everything ready to welcome an important guest.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "The last time she hinted she had something serious to talk about was right before our first kiss. Then, at the following meetup, she tried to step back from all this, but I managed to convince her to keep this affair going.",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I'm hoping that, once again, she's here to talk because we've reached some big milestone, whatever that might be...",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Maybe our relationship is about to get more intimate, or she's finally decided how things are going to go for us in the future. I don't know.",
				choiceNext: false,
			},
			"6": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "But, damn, I'm so ready to find out!",
				choiceNext: false,
			},
			"7": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Right on time, she arrives at my place. We settle on the couch, and the conversation begins.",
				choiceNext: false,
            },
			"8": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "How are you feeling, Tyler?",
				choiceNext: false,
			},
			"9": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "To be honest, I'm a bit nervous.",
				choiceNext: false,
			},
			"10": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "Really? What about?",
				choiceNext: false,
			},
			"11": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Well, every time you tell me you have something serious to discuss, it usually means some big step forward, and I'm curious to know what's on your mind.",
				choiceNext: false,
			},
			"12": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "Ah, you're right; things have always gone that way, haven't they?",
				choiceNext: false,
			},
			"13": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "So, what do you want to talk about?",
				choiceNext: false,
			},
			"14": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "Well, it's pretty clear—it's about us. I don't think that's a surprise to you.",
				choiceNext: false,
			},
			"15": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_normal', null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "To be specific, I want to talk about our future.",
				choiceNext: false,
			},
			"16": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Oh! That was one of my guesses.",
				choiceNext: false,
			},
			"17": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "Good guess.",
				choiceNext: false,
			},
			"18": {
				bgMusic: {
					name: 'Date_with_Reina',
					command: 'FADE_OUT',
					insideOfScene: true
				},
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_normal', null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "So... I've spent a lot of time thinking about what we've gone through together. How we've handled our meetups, how things could be different in the future, what we've been able to give each other so far, and what more we might be able to share...",
				choiceNext: false,
			},
			"19": {
				bgMusic: {
					name: 'Bad_ending_with_main_girls',
					command: 'START'
				},
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_sad', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "But the hard truth is, when I look ahead into that future... all I see is darkness.",
				choiceNext: false,
			},
			"20": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_sad', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "No... Reina... don't do this to me!",
				choiceNext: false,
			},
			"21": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_sad', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "I'm sorry, Tyler. I've risked so much of the life I've built, and I don't feel like it's worth throwing most of that away for someone else.",
				choiceNext: false,
			},
			"22": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_sad', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "So... does that mean everything that happened between us didn't mean anything to you?",
				choiceNext: false,
			},
            "23": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_sad', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "No, it meant something to me.",
				choiceNext: false,
			},
			"24": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_sad', null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "But Tyler, I have my childhood family... and now, my own family... My life has been built around that, in a whole system.",
				choiceNext: false,
			},
			"25": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_sad', null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Sure, I'm not endlessly happy in this marriage, and yes, you are incredibly exciting to me... But, unfortunately, I don't see that you're fully ready or mature enough for the kind of serious, responsible relationship I need...",
				choiceNext: false,
            },
			"26": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_sad', null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "...And that would make it worth giving up the life I have, to build something new and stable, where the only difference from now is that I'd be happier.",
				choiceNext: false,
            },
			"27": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_sad', null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "I don't doubt that you'd make me happy. But choosing you would mean a huge step back in every other area of my life, and I'm really sorry, but I didn't work this hard just to let it all go to waste.",
				choiceNext: false,
			},
			"28": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_sad', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "But Reina... you're the perfect woman for me. No one else could make my heart race the way you do—just by being you!",
				choiceNext: false,
			},
			"29": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "That's... very flattering... but sadly, I can't say the feeling is mutual.",
				choiceNext: false,
			},
			"30": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_normal', null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "I'm sure you'll find someone else, though, who matches you better in age, maturity, and shared goals. And not to mention, she won't be married or involved with someone else, so... things will be easier for you.",
				choiceNext: false,
			},
			"31": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "There's no guarantee I'll find anyone like that after everything that's happened between us.",
				choiceNext: false,
			},
			"32": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "But you'll have to give it a shot because I need that guarantee myself to leave my marriage. And I just don't see that with you right now.",
				choiceNext: false,
			},
			"33": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_sad', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "So... with a heavy heart, I have to say the final word...",
				choiceNext: false,
			},
			"34": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_sad', null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "It's over.",
				choiceNext: false,
			},
			"35": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_sad', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "...",
				choiceNext: false,
			},
			"36": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_sad', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "...",
				choiceNext: false,
			},
			"37": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_sad', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "...",
				choiceNext: false,
			},
			"38": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_sad', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "I understand your feelings. But don't even try to think of something smart to say because there really isn't anything you could say in a situation like this.",
				choiceNext: false,
			},
			"39": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_sad', null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "But now... I think it's best if I leave.",
				choiceNext: false,
			},
			"40": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_sad', null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "I doubt we'll see each other again since working out together would just be too awkward after this, so... please take care of yourself. And good luck in the future.",
				choiceNext: false,
			},
			"41": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_sad', null],
				class: [null, 'fadeUpOut', null],
			  	name: "",
			  	text: "Reina leaves my apartment, but I'm still sitting on the couch, stunned, trying to process what just happened.",
				choiceNext: false,
			},
			"42": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "There's no one in the world like her. No one will ever be as good as her, and honestly, it's a miracle if I'll ever be able to love anyone again after this.",
				choiceNext: false,
			},
			"43": {
				bgMusic: {
					name: 'Bad_ending_with_main_girls',
					command: 'FADE_OUT',
				},
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "A major chapter of my life has closed, and now, I have no idea what's next...",
				choiceNext: false,
			},
		},
	},
];