export const hailey_bad = [
	{
		sceneId: "",
		lengthNum: 42,
		story: {
			"1": {
				bgMusic: {
					name: 'Date_with_Hailey',
					command: 'START'
				},
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "We agreed that Hailey would come over to my place and tell me something important here.",
				choiceNext: false,
            },
 			"2": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "My apartment's pretty tidy, so she's going to see a clean space the first time she steps inside. I hope that scores me some points.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I already knew she was pretty laid-back, so it doesn't surprise me too much that she's willing to just come over, skipping the whole dinner and preamble thing... though it's still a little unexpected.",
				choiceNext: false,
			},
			"4": {
				otherSoundEffect: "tyler-doorbell",
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Anyway, I'm ready to welcome her, and after a short wait, the doorbell rings. I open the door, and it's really her.",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "Hey, Tyler. I'm not coming at a bad time, am I?",
				choiceNext: false,
			},
			"6": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "No. Hi, Hailey. Come on in.",
				choiceNext: false,
			},
			"7": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "Thanks.",
				choiceNext: false,
            },
			"8": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_surprised', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "Oh wow, it's so neat in here! I was expecting to walk into a typical bachelor mess.",
				choiceNext: false,
			},
			"9": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_surprised', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Well, glad I could surprise you in a good way. Want something to drink?",
				choiceNext: false,
			},
			"10": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "No thanks, I'm good.",
				choiceNext: false,
			},
			"11": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Alright... have a seat and let's get into it. Whatever it is you wanted to talk about.",
				choiceNext: false,
			},
			"12": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "Alright.",
				choiceNext: false,
			},
			"13": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "So... it's about us.",
				choiceNext: false,
			},
			"14": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "I mean, over this last week, I feel like we've been getting closer and closer. Almost too close, really, cuz... as you know, I'm in a relationship.",
				choiceNext: false,
			},
			"15": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Exactly. Some of the things you've said or done have totally caught me off guard — especially since you're already in a relationship.",
				choiceNext: false,
			},
			"16": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "Totally get that. I mean, I've surprised myself too. But when I'm with you... I dunno, it's like you flip a switch in me. You kinda just shut off the logical side of my brain, and I just start going on pure vibes, y'know?",
				choiceNext: false,
			},
			"17": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "Which isn't a bad thing... cuz honestly, I think that's a sign of attraction. I had a blast with you, and you showed me a new side of life I haven't seen.",
				choiceNext: false,
			},
			"18": {
				bgMusic: {
					name: 'Date_with_Hailey',
					command: 'STOP'
				},
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "...",
				choiceNext: false,
			},
			"19": {
				bgMusic: {
					name: 'Bad_ending_with_main_girls',
					command: 'START'
				},
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_sad', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "But I feel like letting you get so close was kinda a mistake.",
				choiceNext: false,
			},
			"20": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_sad', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Wait, what?",
				choiceNext: false,
			},
			"21": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_sad', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "At the time, it seemed like a fun idea to play along. I was curious about you, wanted to see how you'd react if I turned up the charm and teased you a bit...",
				choiceNext: false,
			},
			"22": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_sad', null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "But I didn't always get the response or reaction I was kinda hoping for. It made me feel like maybe you weren't as into my little attempts as I thought.",
				choiceNext: false,
			},
            "23": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_sad', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "But I do appreciate everything you've done! I'm so proud of you, even during our workouts!",
				choiceNext: false,
			},
			"24": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_sad', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Sure, you can be a bit bold sometimes, but that's what I like about you!",
				choiceNext: false,
			},
			"25": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_sad', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "You say that with words, but honestly... your actions didn't always back it up. My partner might not appreciate me as much as I'd like, but at least he's a stable part of my life.",
				choiceNext: false,
            },
			"26": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_sad', null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "So... sorry, but I'd rather not give up that security for a similar kinda vibe but with way more uncertainty.",
				choiceNext: false,
            },
			"27": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_sad', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "So you'd rather stay in a relationship where you don't feel valued just to avoid risking something new that could actually be better?",
				choiceNext: false,
			},
			"28": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "Look, if there was no risk, and I knew for sure it'd be worth it, I'd switch over in a heartbeat.",
				choiceNext: false,
			},
			"29": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "But unfortunately, that's not how it is, and right now, I just can't afford to take that risk.",
				choiceNext: false,
			},
			"30": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "So... I'm sorry, but my decision's final. I came here knowing I had to tell you that I should've drawn the line way earlier. And whatever's been going on between us — it's better if we end it now.",
				choiceNext: false,
			},
			"31": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Wait, you mean... even our workouts?",
				choiceNext: false,
			},
			"32": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "Exactly. After this, I don't think I could look you in the eye — or my partner either — knowing I kept meeting with someone I almost... well, cheated on him with. This'll help me keep a clear conscience.",
				choiceNext: false,
			},
			"33": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "There's no way I can change your mind, is there?",
				choiceNext: false,
			},
			"34": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "I'm sorry, but no.",
				choiceNext: false,
			},
			"35": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "Thanks for everything, the hospitality, and the time you spent with me... I'm sorry to bring such bad news, but I figured it was best to clear things up.",
				choiceNext: false,
			},
			"36": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Well... I'm really disappointed right now.",
				choiceNext: false,
			},
			"37": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "I understand, but it's probably best if I go. Don't want to make things worse by sticking around, so... yeah, maybe you need to let it out.",
				choiceNext: false,
			},
			"38": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "So... bye.",
				choiceNext: false,
			},
			"39": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, 'fadeUpOut', null],
			  	name: "",
			  	text: "Hailey quickly leaves my apartment.",
				choiceNext: false,
			},
			"40": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "She might not have been the woman of my dreams, but she was definitely a wild one. I could totally see us together, mostly because she didn't feel unattainable.",
				choiceNext: false,
			},
			"41": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Guess I messed up somewhere for her to end it like this. Wish I knew what went wrong, but it's too late now, because I can't chang the past.",
				choiceNext: false,
			},
			"42": {
				bgMusic: {
					name: 'Bad_ending_with_main_girls',
					command: 'FADE_OUT',
				},
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "So it looks like this is goodbye with Hailey — for good.",
				choiceNext: false,
			},
		},
	},
];