export const lindsay_bad_1 = [
	{ sceneId: "0000" },
	{ sceneId: "0001" },
	{ sceneId: "0002" },
	{ sceneId: "0003" },
	{ sceneId: "0004" },
	{ sceneId: "0005" },
	{ sceneId: "0006" },
	{ sceneId: "0007" },
	{ sceneId: "0008" },
	{ sceneId: "0009" },
	{ sceneId: "0010" },
	{ sceneId: "0011" },
	{ sceneId: "0012" },
	{ sceneId: "0013" },
	{ sceneId: "0014" },
	{ sceneId: "0015" },
	{ sceneId: "0016" },
	{ sceneId: "0017" },
	{ sceneId: "0018" },
	{ sceneId: "0019" },
	{ sceneId: "0020" },
	{ sceneId: "0021" },
	{ sceneId: "0022" },
	{ sceneId: "0023" },
	{ sceneId: "0024" },
	{ sceneId: "0025" },
	{ sceneId: "0026" },
	{ sceneId: "0027" },
	{ sceneId: "0028" },
	{ sceneId: "0029" },
	{ sceneId: "0030" },
	{
		sceneId: "0031",
		lengthNum: 84,
		story: {
			"1": {
				bgMusic: {
					name: 'Lindsay_bad_ending_start',
					command: 'START'
				},
                background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
				textClass: "italic",
			  	text: "Whoa, that was one intense night... shame so much of it's a blur. Probably went a bit overboard with the wine.",
				choiceNext: false,
            },
			"2": {
                background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Morning greets me with a mild hangover in my room, though the scent of last night's activities still lingers in the air.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "As I come to, I realize I'm alone. Lindsay's nowhere to be seen. I muster the strength to pull myself out of bed and stumble out into the living room, still a bit disoriented.",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "The morning light hits my eyes and head like a sledgehammer, but once my vision clears, I see Lindsay sitting on my couch, back turned toward me.",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Mmm... good morning.",
				choiceNext: false,
			},
			"6": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Lindsay",
			  	text: "Good morning?",
				choiceNext: false,
			},
			"7": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_normal', null],
				class: [null, null, null],
			  	name: "",
			  	text: "Lindsay stands up from the couch and turns to face me, but her expression isn't exactly welcoming.",
				choiceNext: false,
            },
			"8": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_angry', null],
				class: [null, 'fadeUp', null],
			  	name: "Lindsay",
			  	text: "It might be a good morning for me, but for you, Tyler, you'd better start praying for your life!",
				choiceNext: false,
			},
			"9": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_angry', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Wait, what?",
				choiceNext: false,
			},
			"10": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_angry', null],
				class: [null, 'fadeUp', null],
			  	name: "Lindsay",
			  	text: "Not only has your apartment stayed exactly the same since our breakup, but your phone security is just as predictable and easy to crack as it was back then.",
				choiceNext: false,
			},
			"11": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_angry', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Why did you even take my phone?",
				choiceNext: false,
			},
			"12": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_angry', null],
				class: [null, 'fadeUp', null],
			  	name: "Lindsay",
			  	text: "Why? I'm your partner... or at least, I was. What's yours is mine too. So I had every right to look into my “super smooth Casanova” partner's phone and see just how much of a player he's been—at work or otherwise.",
				choiceNext: false,
			},
			"13": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_angry', null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "And I sure found a few interesting things... Daena, Hailey, Brianna... but most of all, a Reina. You've really been sweet-talking these ladies, huh? Even though most of them were already in relationships to start with.",
				choiceNext: false,
			},
			"14": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_angry', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Lindsay, you had no right to do that!",
				choiceNext: false,
			},
			"15": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_grin', null],
				class: [null, 'fadeUp', null],
			  	name: "Lindsay",
			  	text: "Oh, I absolutely had the right!",
				choiceNext: false,
			},
			"16": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_grin', null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "I deserve to know the truth. And the truth is, while I was ready to give everything up for you, you were busy chasing after taken women behind my back!",
				choiceNext: false,
			},
			"17": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_grin', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "But we weren't even together back then!",
				choiceNext: false,
			},
			"18": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Lindsay",
			  	text: "That doesn't matter. How could I trust someone who keeps so many irons in the fire? And we're not just talking about two here. What do you think they'll say when they find out?",
				choiceNext: false,
			},
			"19": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "There's no rule saying I can't get to know multiple women until something becomes official with one of them!",
				choiceNext: false,
			},
			"20": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_grin', null],
				class: [null, 'fadeUp', null],
			  	name: "Lindsay",
			  	text: "Save that line for them! You'll get the chance soon enough, because they're on their way here to hear your confession straight from you.",
				choiceNext: false,
			},
			"21": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_grin', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "What?! You invited them here?",
				choiceNext: false,
			},
			"22": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_creepy', null],
				class: [null, 'fadeUp', null],
			  	name: "Lindsay",
			  	text: "Of course! If you're such a big ladies' man, then talk your way out of this one. Let's see just how smooth you are now!",
				choiceNext: false,
			},
            "23": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_creepy', null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "I can't wait to watch you beg on your knees for forgiveness.",
				choiceNext: false,
			},
			"24": {
				bgMusic: {
					name: 'Lindsay_bad_ending_start',
					command: 'STOP'
				},
				otherSoundEffect: "knock-on-door",
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_creepy', null],
				class: [null, null, null],
			  	name: "",
			  	text: "*Knock-knock*",
				choiceNext: false,
			},
			"25": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_creepy', null],
				class: [null, null, null],
			  	name: "",
			  	text: "It seems I barely have time to process, let alone escape this situation, because someone's already at the door.",
				choiceNext: false,
            },
			"26": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_creepy', null],
				class: [null, "fadeUp", null],
			  	name: "Lindsay",
			  	text: "Well, let's see who's here to take your head off first!",
				choiceNext: false,
            },
			"27": {
				bgMusic: {
					name: 'Worst_ending',
					command: 'START'
				},
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Lindsay/Lindsay_elegant_creepy', 'Lindsay/Lindsay_elegant_creepy', 'Hailey/Hailey_casual_scared'],
				class: ['fadeLeft', "fadeUpOut", 'fadeRight'],
			  	name: "Hailey",
			  	text: "Tyler! What the... what is all this? I was hoping this was some kind of prank, but it looks like it's real!",
				choiceNext: false,
			},
			"28": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Lindsay/Lindsay_elegant_creepy', null, 'Hailey/Hailey_casual_scared'],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "What?!",
				choiceNext: false,
			},
			"29": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Lindsay/Lindsay_elegant_creepy', null, 'Hailey/Hailey_casual_sad'],
				class: [null, null, 'fadeRight'],
			  	name: "Hailey",
			  	text: "I'm guessing this chick here next to me is your ex? The one who messaged me through your SocialSync account to let me know about your cozy night together? And what about the rest? That I'm not the only one you've been messing around with?",
				choiceNext: false,
			},
			"30": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Lindsay/Lindsay_elegant_creepy', null, 'Hailey/Hailey_casual_sad'],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Well...",
				choiceNext: false,
			},
			"31": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Lindsay/Lindsay_elegant_creepy', 'Daena/Daena_casual_surprised', 'Hailey/Hailey_casual_sad'],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "Tyler! Hailey? And you...?",
				choiceNext: false,
			},
			"32": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Lindsay/Lindsay_elegant_grin', 'Daena/Daena_casual_surprised', 'Hailey/Hailey_casual_sad'],
				class: ['fadeLeft', null, null],
			  	name: "Lindsay",
			  	text: "Yep. The ex. Nice to meet you all.",
				choiceNext: false,
			},
			"33": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Lindsay/Lindsay_elegant_grin', 'Daena/Daena_casual_normal', 'Hailey/Hailey_casual_sad'],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "The feeling's not mutual.",
				choiceNext: false,
			},
			"34": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Lindsay/Lindsay_elegant_grin', 'Daena/Daena_casual_sad', 'Hailey/Hailey_casual_sad'],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "But Tyler, how could you do this to me? I trusted you! I put my heart and soul into our sessions, trying to reciprocate with a dedication I'd never shown anyone else! And this is how you repay me? By stringing along others too?",
				choiceNext: false,
			},
			"35": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Lindsay/Lindsay_elegant_grin', 'Daena/Daena_casual_sad', 'Hailey/Hailey_casual_sad'],
				class: [null, null, 'fadeRight'],
			  	name: "Hailey",
			  	text: "I could say the same... I was ready to leave my boyfriend for you, let you into my life in ways no one else has, and now I feel absolutely humiliated for letting myself be tricked by a guy like you!",
				choiceNext: false,
			},
			"36": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Brianna/Brianna_casual_surprised', 'Daena/Daena_casual_sad', 'Hailey/Hailey_casual_sad'],
				class: ['fadeLeft', null, null],
			  	name: "Brianna",
			  	text: "What the...? Oh... so that message wasn't a joke, then.",
				choiceNext: false,
			},
			"37": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Brianna/Brianna_casual_surprised', 'Daena/Daena_casual_sad', 'Hailey/Hailey_casual_surprised'],
				class: [null, null, 'fadeRight'],
			  	name: "Hailey",
			  	text: "Brianna?",
				choiceNext: false,
			},
			"38": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Brianna/Brianna_casual_surprised', 'Daena/Daena_casual_surprised', 'Hailey/Hailey_casual_surprised'],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "She's involved too?",
				choiceNext: false,
			},
			"39": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Brianna/Brianna_casual_normal', 'Daena/Daena_casual_surprised', 'Hailey/Hailey_casual_surprised'],
				class: ['fadeLeft', null, null],
			  	name: "Brianna",
			  	text: "Yeah... two familiar faces from the gym... and the infamous ex who sent the message.",
				choiceNext: false,
			},
			"40": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Brianna/Brianna_casual_normal', 'Daena/Daena_casual_surprised', 'Lindsay/Lindsay_elegant_grin'],
				class: [null, null, 'fadeRight'],
			  	name: "Lindsay",
			  	text: "Correct. Hello!",
				choiceNext: false,
			},
			"41": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Brianna/Brianna_casual_sad', 'Daena/Daena_casual_surprised', 'Lindsay/Lindsay_elegant_grin'],
				class: ['fadeLeft', null, null],
			  	name: "Brianna",
			  	text: "Tyler... I can't even put into words how deeply disappointed I am right now. After so much heartbreak, I finally found someone who made my heart race again, who I wanted to give a chance to. And yet... it ends the same way—another letdown.",
				choiceNext: false,
			},
			"42": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Brianna/Brianna_casual_sad', 'Daena/Daena_casual_surprised', 'Lindsay/Lindsay_elegant_grin'],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "It's breaking my heart.",
				choiceNext: false,
			},
			"43": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Brianna/Brianna_casual_sad', 'Daena/Daena_casual_surprised', 'Lindsay/Lindsay_elegant_smiling'],
				class: [null, null, 'fadeRight'],
			  	name: "Lindsay",
			  	text: "He's not worth it, believe me. You can see he's been playing with all of your hearts, casually, without any remorse. Don't let him break your little heart.",
				choiceNext: false,
			},
			"44": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Brianna/Brianna_casual_sad', 'Daena/Daena_casual_normal', 'Lindsay/Lindsay_elegant_smiling'],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "So... this is it? We're the four you've been stringing along, each of us completely in the dark?",
				choiceNext: false,
			},
			"45": {
				bgMusic: {
					name: 'Worst_ending',
					command: 'FADE_OUT',
					insideOfScene: true
				},
				otherSoundEffect: 'walking-up-the-stairs',
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Brianna/Brianna_casual_sad', 'Daena/Daena_casual_normal', 'Lindsay/Lindsay_elegant_smiling'],
				class: [null, null, null],
			  	name: "",
			  	text: "*Steps*",
				choiceNext: false,
			},
			"46": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Brianna/Brianna_casual_sad', 'Daena/Daena_casual_normal', 'Lindsay/Lindsay_elegant_smiling'],
				class: [null, null, null],
			  	name: "",
				textClass: 'italic',
			  	text: "Oh no... I can tell by elimination who's approaching... this is going to hurt.",
				choiceNext: false,
			},
			"47": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Brianna/Brianna_casual_sad', 'Daena/Daena_casual_normal', 'Reina/Reina_casual_surprised'],
				class: [null, null, 'fadeRight'],
			  	name: "Reina",
			  	text: "!!!",
				choiceNext: false,
			},
			"48": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Brianna/Brianna_casual_surprised', 'Daena/Daena_casual_normal', 'Reina/Reina_casual_surprised'],
				class: ['fadeLeft', null, null],
			  	name: "Brianna",
			  	text: "Reina?",
				choiceNext: false,
			},
			"49": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Brianna/Brianna_casual_surprised', 'Daena/Daena_casual_surprised', 'Reina/Reina_casual_surprised'],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "Her too?",
				choiceNext: false,
			},
			"50": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_surprised', 'Daena/Daena_casual_surprised', 'Reina/Reina_casual_surprised'],
				class: ['fadeLeft', null, null],
			  	name: "Hailey",
			  	text: "Wow!",
				choiceNext: false,
			},
			"51": {
				bgMusic: {
					name: 'Under_pressure',
					command: 'START',
					insideOfScene: true
				},
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_surprised', 'Daena/Daena_casual_surprised', 'Reina/Reina_casual_sad'],
				class: [null, null, 'fadeRight'],
			  	name: "Reina",
			  	text: "Tyler... You miserable... sneaky...!",
				choiceNext: false,
			},
			"52": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_surprised', 'Daena/Daena_casual_surprised', 'Lindsay/Lindsay_elegant_grin'],
				class: [null, null, 'fadeRight'],
			  	name: "Lindsay",
			  	text: "It's such a joy to welcome you all here, right in this scoundrel's apartment, so you can see for yourselves what a con artist he really is and what poor little victims you all were.",
				choiceNext: false,
			},
			"53": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_angry', 'Daena/Daena_casual_surprised', 'Lindsay/Lindsay_elegant_grin'],
				class: ['fadeLeft', null, null],
			  	name: "Hailey",
			  	text: "You think this is funny, honey?!",
				choiceNext: false,
			},
			"54": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_angry', 'Daena/Daena_casual_surprised', 'Lindsay/Lindsay_elegant_creepy'],
				class: [null, null, 'fadeRight'],
			  	name: "Lindsay",
			  	text: "Yes, I do! I've wanted an opportunity like this for so long, so I could finally make this dirtbag's life so miserable that he'll never be able to recover!",
				choiceNext: false,
			},
			"55": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_angry', 'Daena/Daena_casual_angry', 'Lindsay/Lindsay_elegant_creepy'],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "You're sick!",
				choiceNext: false,
			},
			"56": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_angry', 'Brianna/Brianna_casual_angry', 'Lindsay/Lindsay_elegant_creepy'],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "Even if your intention was noble, your methods and your worldview are seriously twisted.",
				choiceNext: false,
			},
			"57": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_angry', 'Brianna/Brianna_casual_angry', 'Lindsay/Lindsay_elegant_creepy'],
				class: [null, null, 'fadeRight'],
			  	name: "Lindsay",
			  	text: "Who cares, as long as I get what I want!",
				choiceNext: false,
			},
			"58": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_angry', 'Brianna/Brianna_casual_angry', 'Lindsay/Lindsay_elegant_creepy'],
				class: ['fadeLeft', null, null],
			  	name: "Hailey",
			  	text: "Fine, you got it. Now you can leave, because the four of us need a private chat with Tyler.",
				choiceNext: false,
			},
			"59": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_angry', 'Brianna/Brianna_casual_angry', 'Lindsay/Lindsay_elegant_creepy'],
				class: [null, null, 'fadeRight'],
			  	name: "Lindsay",
			  	text: "I'm still here to enjoy the show for now. And I have a feeling not all of you would agree with that.",
				choiceNext: false,
			},
			"60": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_angry', 'Brianna/Brianna_casual_angry', 'Lindsay/Lindsay_elegant_creepy'],
				class: [null, null, null],
			  	name: "",
				textClass: "italic",
			  	text: "Yes, because Reina is very quiet and seems sad.",
				choiceNext: false,
			},
			"61": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_angry', 'Reina/Reina_casual_angry', 'Lindsay/Lindsay_elegant_creepy'],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "I... have nothing to discuss with this man. I was ready to set aside my married life for him, all that I'd built with my husband, and this goes back years.",
				choiceNext: false,
			},
			"62": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_angry', 'Reina/Reina_casual_angry', 'Lindsay/Lindsay_elegant_creepy'],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "It hurts so much that my sacrifice meant so little to you—that you toyed with me at the gym while also fooling others, and to top it off, you were such a fool that you went back to the ex who's already broken your heart multiple times! How could you be so stupid and naive?",
				choiceNext: false,
			},
			"63": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_angry', 'Reina/Reina_casual_angry', 'Lindsay/Lindsay_elegant_creepy'],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "So this is the last time I'll speak to you, Tyler, because from now on, we're over! I won't look for you, and don't even think of looking for me, because from now on, I have zero interest in you.",
				choiceNext: false,
			},
			"64": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_angry', 'Reina/Reina_casual_angry', 'Lindsay/Lindsay_elegant_creepy'],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Forget me... forever!",
				choiceNext: false,
			},
			"65": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_angry', 'Reina/Reina_casual_angry', 'Lindsay/Lindsay_elegant_creepy'],
				class: [null, 'fadeUpOut', null],
			  	name: "",
			  	text: "With that, Reina leaves my apartment, giving me no chance to say anything. Not that there's anything I could say, really.",
				choiceNext: false,
			},
			"66": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_angry', 'Brianna/Brianna_casual_sad', 'Lindsay/Lindsay_elegant_creepy'],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "...",
				choiceNext: false,
			},
			"67": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_angry', 'Brianna/Brianna_casual_sad', 'Lindsay/Lindsay_elegant_creepy'],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Actually, she's right. We could scream at Tyler, slap him, or trash his place... but that wouldn't solve anything. What's done is done, and after all this, I don't want anything from him either.",
				choiceNext: false,
			},
			"68": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_angry', 'Brianna/Brianna_casual_sad', 'Lindsay/Lindsay_elegant_creepy'],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "I'll survive somehow. But the fact is, he doesn't deserve my attention, my energy, my patience... or my love.",
				choiceNext: false,
			},
			"69": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_angry', 'Brianna/Brianna_casual_sad', 'Lindsay/Lindsay_elegant_creepy'],
				class: [null, 'fadeUpOut', null],
			  	name: "",
			  	text: "Brianna leaves too, and it looks like the others feel the same way.",
				choiceNext: false,
			},
			"70": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_sad', null, 'Lindsay/Lindsay_elegant_creepy'],
				class: ['fadeLeft', null, null],
			  	name: "Hailey",
			  	text: "It was nice, it was good... too bad I believed I could be that “one and only” for you.",
				choiceNext: false,
			},
			"71": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_sad', 'Daena/Daena_casual_sad', 'Lindsay/Lindsay_elegant_creepy'],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "It was a hard lesson for me to learn about men as I'm growing up. But somehow, I'll pick myself up from this slap in the face, too.",
				choiceNext: false,
			},
			"72": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_sad', 'Daena/Daena_casual_sad', 'Lindsay/Lindsay_elegant_creepy'],
				class: ['fadeLeftOut', 'fadeUpOut', null],
			  	name: "",
			  	text: "And with that, everyone left the apartment, except for Lindsay.",
				choiceNext: false,
			},
			"73": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', 'char-right'],
				image: [null, 'Lindsay/Lindsay_elegant_sad', 'Lindsay/Lindsay_elegant_creepy'],
				class: [null, 'fadeUp', 'fadeRightOut'],
			  	name: "Lindsay",
			  	text: "Aww... I was expecting a much more amusing scene! These girls are such weaklings; none of them had the guts to finish you off.",
				choiceNext: false,
			},
			"74": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_sad', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Alright, Lindsay, you got what you wanted. Now you can get out too!",
				choiceNext: false,
			},
			"75": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Lindsay",
			  	text: "Oh, really? And what will you do if I say no?",
				choiceNext: false,
			},
			"76": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I didn't commit any crime, so I'll call the cops on you to throw you out!",
				choiceNext: false,
			},
			"77": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_seductive', null],
				class: [null, 'fadeUp', null],
			  	name: "Lindsay",
			  	text: "And how will you call them if I have your phone?",
				choiceNext: false,
			},
			"78": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_seductive', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Give it back!",
				choiceNext: false,
			},
			"79": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_seductive', null],
				class: [null, 'fadeUp', null],
			  	name: "Lindsay",
			  	text: "Hmm... nope! If you want it back, you'll have to take it from me by force! Then go ahead and call the cops; they'll see all the damage you've done to me, and you'll definitely have some uncomfortable questions to answer.",
				choiceNext: false,
			},
			"80": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_seductive', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Lindsay!",
				choiceNext: false,
			},
			"81": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_creepy', null],
				class: [null, 'fadeUp', null],
			  	name: "Lindsay",
			  	text: "Hehe! You're not getting rid of me that easily! Your love life is over, it'll be found out, and then your career will be over too! So basically, your whole life is over!",
				choiceNext: false,
			},
			"82": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_creepy', null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "Hehe-Hahaha!",
				choiceNext: false,
			},
			"83": {
				bgMusic: {
					name: 'Under_pressure',
					command: 'STOP',
				},
				otherSoundEffect: "scream",
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_scared', null],
				class: [null, 'fadeUp', null],
			  	name: "",
			  	text: "At this point, my last nerve snaps, and I lose all control, attacking Lindsay.",
				choiceNext: false,
			},
			"84": {
				background: "backgrounds/BG_dark",
				backGroundClass: "fadeIn",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_scared', null],
				class: [null, 'fadeUpOut', null],
			  	name: "",
			  	text: "But then...",
				choiceNext: false,
			},
		},
	},
];