export const scene_27 = [
    { sceneId: "0026" },
	{
		sceneId: "0027",
		lengthNum: 54,
		story: {
			"1": {
				bgMusic: {
					name: 'Onsen_daily',
					command: 'START'
				},
                background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "It's Friday morning. It's been a week since I woke up to find Reina at my place, and we took a walk in the park. Since then, a lot has happened, not just with her but with the others as well. It's incredible how much my relationships with each of them have evolved.",
				choiceNext: false,
            },
			"2": {
                background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Just like last week, this Friday morning I have plans with Reina—a pleasant soak at the thermal bath. I'm really looking forward to this, though I have a few reservations about the plans I have later in the evening.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "But this day is already set, so much for a relaxing day off. Whatever happens, happens.",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_onsen_outside_sunny",
                backGroundClass: 'fadeIn',
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "At 8 a.m., as we agreed, Reina and I meet at the entrance of the bath and head to the counter to buy our tickets together.",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_onsen_outside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Maybe because it's still early, the ticket seller doesn't seem to bat an eye or ask questions about why we're both going into the mixed bath. Typically, it's couples and families with young kids, or older folks who don't mind sharing the space.",
				choiceNext: false,
			},
			"6": {
                background: "backgrounds/BG_onsen_outside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "We're neither elderly nor a mother-son pair, so we narrow down the possibilities, yet I don't notice any curious stares.",
				choiceNext: false,
			},
			"7": {
                background: "backgrounds/BG_onsen_changing_room",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Even with the mixed bath, the changing rooms are still separated by gender. Inside, there are clearly marked directions leading to either the men-only bath or the mixed area.",
				choiceNext: false,
            },
			"8": {
                background: "backgrounds/BG_onsen_changing_room",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "While I'm changing into swim trunks, I realize that I'll be spending time with Reina with her in nothing but a swimsuit.",
				choiceNext: false,
			},
			"9": {
                background: "backgrounds/BG_onsen_changing_room",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "Hmm... I've already seen her in lingerie once; it was made of materials that didn't hide much. And when her gym clothes get a bit sheer, she's not the type to wear full briefs either—just normal or Brazilian thongs.",
				choiceNext: false,
			},
			"10": {
                background: "backgrounds/BG_onsen_changing_room",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "But lingerie is one thing; it's not exactly something people usually see. Would she be as confident and bold when it comes to swimsuits? Same person, same taste—it wouldn't be a bad thing!",
				choiceNext: false,
			},
			"11": {
                background: "backgrounds/BG_onsen_changing_room",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "But let's not forget, she's a mom. She should probably set an example for her daughters, and you can be feminine without wearing revealing outfits. Besides, she mostly comes to the baths with her family, so maybe her bikinis are more modest.",
				choiceNext: false,
			},
			"12": {
                background: "backgrounds/BG_onsen_changing_room",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "Then again, there's the option of a one-piece swimsuit. Reina's not old, but she's not entirely in my age group either; she might still be of the generation that prefers one-piece suits, having mostly seen that style on her parents.",
				choiceNext: false,
			},
			"13": {
                background: "backgrounds/BG_onsen_changing_room",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "Hmm... I'm not sure which is most likely...",
				choiceNext: true,
			},
			"14": {
                background: "backgrounds/BG_onsen_changing_room",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'reina~notImportants~0027-13',
			  	name: "",
                textClass: "italic",
			  	text: [
                    "Hmm... maybe I could imagine her in a more daring bikini since she doesn't exactly dress to hide herself in everyday life.",
                    "She's not too modest to cover herself up, but as a model mother, she'd likely avoid showing too much skin—so I'd say a classic bikini is more her style.",
                    "Actually, a one-piece wouldn't look bad on her. At that time, most little girls had a one-piece swimsuits as their first anyway, so she may still have something like that nowadays."
                ],
				choiceNext: false,
			},
			"15": {
                background: "backgrounds/BG_onsen_changing_room",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "I wonder if this is my wishful thinking or my best guess at what she'd really wear? Either way, I'll know soon enough.",
				choiceNext: false,
			},
			"16": {
                background: "backgrounds/BG_onsen_inside_sunny",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Once I'm changed, I grab my towel and head to the mixed bath area. Stepping outside, the very traditional ambiance of the thermal bath unfolds before me.",
				choiceNext: false,
			},
			"17": {
                otherSoundEffect: "walk-in-water",
                background: "backgrounds/BG_onsen_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "The water is crystal clear, decorated with stones, and it's peaceful and quiet in these early hours. I don't see Reina just yet, though there's a part of the bath hidden from view, so I wade into the warm water and take a stroll while waiting for her to come out or until I find her.",
				choiceNext: false,
			},
			"18": {
                background: "backgrounds/BG_onsen_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Finally, behind one of the large decorative stones, I spot her... but not quite as I'd expected.",
				choiceNext: false,
			},
			"19": {
                bgMusic: {
					name: 'Unexpected_ecchi_moment_occurs',
					command: 'START'
				},
                specialSceneNow: true,
				specialSceneId: "0027-19",
				background: "special_scenes/0027-19",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Oh... hey there, Tyler...",
				choiceNext: false,
			},
			"20": {
				background: "special_scenes/0027-19",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "R-Reina!?",
				choiceNext: false,
			},
			"21": {
				background: "special_scenes/0027-19",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: 'italic',
			  	text: "What is this?",
				choiceNext: false,
			},
			"22": {
				background: "special_scenes/0027-19",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: 'italic',
			  	text: "She's entirely naked, with only a towel wrapped around her body to cover what's necessary! But why?",
				choiceNext: false,
			},
			"23": {
				background: "special_scenes/0027-19",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Yes? What's wrong?",
				choiceNext: false,
			},
			"24": {
				background: "special_scenes/0027-19",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "What's wrong? Are you kidding? Why... are you wearing nothing underneath?",
				choiceNext: false,
			},
			"25": {
				background: "special_scenes/0027-19",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Oh, but I am.",
				choiceNext: false,
            },
			"26": {
				background: "special_scenes/0027-19",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "But why just a towel?",
				choiceNext: false,
            },
			"27": {
				background: "special_scenes/0027-19",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Why? Is it bothering you that it covers too much?",
				choiceNext: false,
			},
			"28": {
				background: "special_scenes/0027-19",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "It's not about how much it covers; it's that there's nothing underneath!",
				choiceNext: false,
			},
			"29": {
				background: "special_scenes/0027-19",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "The rules don't forbid it. You can go \"commando\" as long as nothing shows in public.",
				choiceNext: false,
			},
			"30": {
				background: "special_scenes/0027-19",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Wow... and this... is comfortable for you?",
				choiceNext: false,
			},
			"31": {
                background: "special_scenes/0027-19",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "I just wanted to surprise you with something, but it looks like I might've done too good a job at throwing you off balance.",
				choiceNext: false,
			},
			"32": {
				background: "special_scenes/0027-19",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Well, that's... quite an understatement.",
				choiceNext: false,
			},
			"33": {
                background: "special_scenes/0027-19",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'reina~notImportants~0027-13',
			  	name: "Tyler",
			  	text: [
                    "But judging by your underwear, I thought you'd be showing up here in a sexy bikini.",
                    "But I thought you'd at least have a classic bikini on, like most people",
                    "Honestly, I even imagined you might wear a one-piece suit, given the traditional vibe of this bath."
                ],
				choiceNext: false,
			},
			"34": {
                background: "special_scenes/0027-19",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Well, I won't deny that I have one at home, but I figured I'd go with something unexpected. Something no one can say is “too daring” but that'd still surprise you.",
				choiceNext: false,
			},
			"35": {
                background: "special_scenes/0027-19",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Showing up in just a towel in a mixed bath is pretty bold, even so.",
				choiceNext: false,
			},
			"36": {
                specialSceneId: "0027-36",
                background: "special_scenes/0027-36",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Oh, I'm more than willing to take that chance because I know you well enough to guess what effect this will have on you. So... I hope you like what you see.",
				choiceNext: false,
			},
			"37": {
                background: "special_scenes/0027-36",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I-I do. Absolutely...",
				choiceNext: false,
			},
			"38": {
                background: "special_scenes/0027-36",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "So tell me, do you find me sexy enough that you might, uh... stiffen up a little despite the hot water?",
				choiceNext: false,
			},
			"39": {
                background: "special_scenes/0027-36",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "You're a lot, lot hotter than this water!",
				choiceNext: false,
			},
			"40": {
                background: "special_scenes/0027-36",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Hehe... I'll take that as a yes. So... what's on your mind? What would you want to do with me?",
				choiceNext: true,
			},
			"41": {
                background: "special_scenes/0027-36",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'reina~importants~0027-40',
			  	name: ["", "Tyler"],
			  	text: [
                    "That's it, I can't take it any longer, and my hand instinctively moves towards Reina, reaching for a more sensitive spot to feel her body's warmth.",
                    "What I'd do to you right now... the list is endless, Reina. I'm barely holding it together to stay a gentleman in this situation!"
                ],
				choiceNext: false,
			},
			"42": {
                bgMusic: {
					name: ['Unexpected_ecchi_moment_occurs', 'Unexpected_ecchi_moment_occurs'],
					command: ['STOP', 'START']
				},
                specialSceneId: ["0027-42", "0027-36"],
                background: ["special_scenes/0027-42", "special_scenes/0027-36"],
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'reina~importants~0027-40',
			  	name: "Reina",
			  	text: [
                    "Tyler, what are you doing?!",
                    "Oh, poor thing... I can see just how much you're suffering from all the desire and instincts building up inside. And if I shake my hips like this, that's still not enough to make you pounce?"
                ],
				choiceNext: false,
			},
            "43": {
                background: ["special_scenes/0027-42", "special_scenes/0027-36"],
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'reina~importants~0027-40',
			  	name: "Tyler",
			  	text: [
                    "What do you mean, \"what\"? You're practically serving yourself up on a silver platter! I thought you... I thought you were ready.",
                    "Aaaahhh!"
                ],
				choiceNext: false,
			},
			"44": {
                otherSoundEffect: [null, "punch"],
                bgMusic: {
					name: ['Sad_mood_wih_a_girl', 'Unexpected_ecchi_moment_occurs'],
					command: ['START', 'STOP']
				},
                specialSceneId: ["0027-44", "0027-36"],
                background: ["special_scenes/0027-44", "special_scenes/0027-36"],
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'reina~importants~0027-40',
			  	name: ["Reina", ""],
			  	text: [
                    "Hmm... I'm sorry if that was too much for you. Of course, I'm happy you want me this much, but I just wanted to tease you a bit. You have to understand—this isn't the place for that!",
                    "That was it—I couldn't hold back anymore... one more second, and I'd have taken her right there in the bath. But that wouldn't be right for so many reasons, so there was only one thing I could do to stop myself: I punched myself... there... and hard."
                ],
				choiceNext: false,
			},
			"45": {
                specialSceneId: ["0027-44", "0027-42"],
                background: ["special_scenes/0027-44", "special_scenes/0027-42"],
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'reina~importants~0027-40',
			  	name: ["Tyler", "Reina"],
			  	text: [
                    "But Reina... it's so unfair that you keep teasing me, and just when I think the time is right, you always pull back and say no!",
                    "Oh my god, Tyler! Are you alright?"
                ],
				choiceNext: false,
			},
			"46": {
                bgMusic: {
					name: ['Sad_mood_wih_a_girl', 'Sad_mood_wih_a_girl'],
					command: ['START', 'START']
				},
                background: ["special_scenes/0027-44", "special_scenes/0027-42"],
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'reina~importants~0027-40',
			  	name: ["Reina", "Tyler"],
			  	text: [
                    "Trust me, I'm not trying to mess with you or lead you on; I just want to deepen the desire and connection between us.",
                    "Well... I might not be able to have kids after this, but I'll live..."
                ],
				choiceNext: false,
			},
			"47": {
                background: ["special_scenes/0027-44", "special_scenes/0027-42"],
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'reina~importants~0027-40',
			  	name: ["Tyler", "Reina"],
			  	text: [
                    "I already feel so deeply for you; we don't need to drag this out anymore.",
                    "And what was the point of that?"
                ],
				choiceNext: false,
			},
			"48": {
                background: ["special_scenes/0027-44", "special_scenes/0027-42"],
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'reina~importants~0027-40',
			  	name: [ "Reina", "Tyler"],
			  	text: [
                    "I don't doubt your physical desire, but your love and commitment mean so much to me, too.",
                    "If I hadn't stopped, trust me—the whole bathhouse would be echoing with your moans by now."
                ],
				choiceNext: false,
			},
			"49": {
                specialSceneId: "0027-44",
                background: ["special_scenes/0027-44", "special_scenes/0027-44"],
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'reina~importants~0027-40',
			  	name: ["Tyler", "Reina"],
			  	text: [
                    "But I don't want only that from you...!",
                    "Oh... did I go a little too far with the teasing?"
                ],
				choiceNext: false,
			},
			"50": {
                otherSoundEffect: "walk-in-water",
                background: "special_scenes/0027-44",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Just then, we both hear others stepping into the water, their footsteps echoing closer.",
				choiceNext: false,
			},
			"51": {
                background: "special_scenes/0027-44",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "We don't have time for this now—let's behave ourselves!",
				choiceNext: false,
			},
			"52": {
                background: "special_scenes/0027-44",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Of course.",
				choiceNext: false,
			},
			"53": {
                background: "backgrounds/BG_onsen_inside_sunny",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Though Reina is still only wearing her towel, she no longer draws attention with how little fabric she has on, and from this point, we simply sit together, relaxing in the warm water in front of others.",
				choiceNext: false,
			},
			"54": {
                bgMusic: {
					name: 'Sad_mood_wih_a_girl',
					command: 'FADE_OUT'
				},
                background: "backgrounds/BG_onsen_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "But beneath the surface, where no one could see, we held hands the entire time. We never once thought of letting go until we finally stepped out of the water.",
				choiceNext: false,
                timeSkipNext: {
					content: "Later in the afternoon...",
					nextSceneType: "MOBILE",
					nextSceneNumber: "0028",
				}
			},
		},
	},
];