export const scene_3 = [
	{
		sceneId: "0003",
		lengthNum: 48,
		story: {
			"1": {
				bgMusic: {
					name: 'Date_with_Reina',
					command: 'START'
				},
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "About an hour later, we were already at the park on the outskirts of Vensea. It's usually well-visited, but according to Reina, there aren't too many people here in the mornings and early afternoons, and that seems to be true.",
				choiceNext: false,
            },
			"2": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "We're not the only ones here, but there's hardly anyone else around, and luckily, we haven't run into a single familiar face so far. So after the initial nervousness, we both started to relax and focus more on each other.",
				choiceNext: false,
			},
			"3": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_smiling", null],
				class: [null, "fadeUp", null],
			  	name: "",
			  	text: "As I watch her, it's clear that Reina is really enjoying herself. She's constantly smiling, talkative, and full of energy. I've never seen her like this at the gym, though that's understandable since there are always others around, at least my boss, and that's enough to make us maintain a discreet distance.",
				choiceNext: false,
			},
			"4": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_smiling", null],
				class: [null, null, null],
			  	name: "",
			  	text: "But now, it's as if she's a completely different person, and I don't mind at all that I get to experience this side of her.",
				choiceNext: false,
			},
			"5": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_smiling", null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Reina, I've never seen you this happy before.",
				choiceNext: false,
			},
			"6": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_grin", null],
				class: [null, "fadeUp", null],
			  	name: "Reina",
			  	text: "Really? Well, whenever I'm with you, I'm always this happy inside, I just never had the chance to show it until now.",
				choiceNext: false,
			},
			"7": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_grin", null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "But how come? I mean, we're just walking side by side in a park. I haven't even bought you a drink, a meal, or anything like that...",
				choiceNext: false,
			},
			"8": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_smiling", null],
				class: [null, "fadeUp", null],
			  	name: "Reina",
			  	text: "I don't need those things. Of course, I appreciate it if you want to treat me to something, but honestly, I'm already incredibly happy and excited just to be with you.",
				choiceNext: false,
			},
			"9": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_smiling", null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "I think it's something people rarely experience in their lives... maybe we're kindred spirits, or we knew each other in a past life... who knows, but this feeling overwhelms me inexplicably every time I see you.",
				choiceNext: false,
			},
			"10": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_smiling", null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I see. But if there's anything you want, don't hesitate to ask. I'd be more than happy to add something special to this date if it makes you feel even better.",
				choiceNext: false,
			},
			"11": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_smiling", null],
				class: [null, "fadeUp", null],
			  	name: "Reina",
			  	text: "Thank you, Tyler, but I'm already feeling great. And what about you?",
				choiceNext: false,
			},
			"12": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_smiling", null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I-I'm happy too, to spend some private time with you. I just wish we could do something as simple and intimate as holding hands while we walk.",
				choiceNext: false,
			},
			"13": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_normal", null],
				class: [null, "fadeUp", null],
			  	name: "Reina",
			  	text: "I agree with you. But I hope you understand that I can't take that kind of risk in such a public place. You never know when a familiar face might pop up from behind the next bush. It's already hard enough to explain why I'm in a park with my trainer on a Friday morning, but it would be even harder if they saw how close I am to you.",
				choiceNext: false,
			},
			"14": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_normal", null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Of course, I understand… but it still feels like torture, and is a bit unfair. Not from you, but from life.",
				choiceNext: false,
			},
			"15": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_normal", null],
				class: [null, "fadeUp", null],
			  	name: "Reina",
			  	text: "Yes, you're right. But hey! Does that mean kids these days still walk around holding hands?",
				choiceNext: false,
			},
			"16": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_normal", null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Ye-What kids? Reina, I'm 24, and there's no way you could be old enough to be my mother!",
				choiceNext: false,
			},
			"17": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_grin", null],
				class: [null, "fadeUp", null],
			  	name: "Reina",
			  	text: "I know, I just couldn't resist.",
				choiceNext: false,
			},
			"18": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_grin", null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Oh, there's a bench. Shall we sit for a bit?",
				choiceNext: false,
			},
			"19": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_grin", null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Sure.",
				choiceNext: false,
			},
			"20": {
                specialSceneNow: true,
				specialSceneId: "0003-20",
				background: "special_scenes/0003-20",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_grin", null],
				class: [null, "fadeUpOut", null],
			  	name: "Reina",
			  	text: "And how does it feel?",
				choiceNext: false,
			},
			"21": {
                background: "special_scenes/0003-20",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "What?",
				choiceNext: false,
			},
			"22": {
				background: "special_scenes/0003-20",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "To be on an official, yet secret, date with a married mom?",
				choiceNext: true,
			},
			"23": {
				background: "special_scenes/0003-20",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'reina~notImportants~0003-22',
			  	name: "Tyler",
			  	text: [
					"It feels quite different.",
					"I don't really feel much of a difference."
				],
				choiceNext: false,
			},
			"24": {
				background: "special_scenes/0003-20",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'reina~notImportants~0003-22',
			  	name: "Reina",
			  	text: "What do you mean by that?",
				choiceNext: false,
			},
			"25": {
				background: "special_scenes/0003-20",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'reina~notImportants~0003-22',
			  	name: "Tyler",
			  	text: [
					"On one hand, I mean what we were just talking about — there are basic things we can't do, and I miss that. But it's also different because… your values are entirely different from the girls my age. Their expectations are so high that it's almost impossible to meet them.",
					"I can have a pleasant conversation with you just the same. There aren't really any awkward silences between us… and even if there is a pause, it's not awkward, it's comfortable."
				],
				choiceNext: false,
			},
			"26": {
				background: "special_scenes/0003-20",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'reina~notImportants~0003-22',
			  	name: "Reina",
			  	text: [
					"As a woman, I see that most girls spend a good part of their teens and twenties like that. But as time goes by, everyone eventually realizes what they truly need for real happiness.",
					"Yes, I'm really glad that this generational gap hasn't created such a divide between us that we couldn't understand each other.",
				],
				choiceNext: false,
			},
			"27": {
				background: "special_scenes/0003-20",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'reina~notImportants~0003-22',
			  	name: "Tyler",
			  	text: [
					"And what do you truly need for happiness?",
					"Have you never thought that I'm too… young, or immature, or energetic for you, and maybe that's not what you need?"
				],
				choiceNext: false,
			},
			"28": {
				background: "special_scenes/0003-20",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Since I'm already in a different phase of life, of course, security, trust, and peace are all important to me… But I don't feel like I have to be some burnt-out, stuck-in-her-ways suburban mom. I still have a lot of energy, I want to enjoy life and… let's not forget… I have my needs too… And I feel like I can finally get that from you.",
				choiceNext: false,
			},
			"29": {
				background: "special_scenes/0003-20",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "But your husband…?",
				choiceNext: false,
			},
			"30": {
				background: "special_scenes/0003-20",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "I love and respect him... But I don't feel the fire and passion anymore like I used to. And your kiss, well, it's entirely different. Speaking of kisses! What did you feel when I kissed you for the first time? How did it feel?",
				choiceNext: true,
			},
			"31": {
				background: "special_scenes/0003-20",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'reina~importants~0003-30',
			  	name: "Tyler",
			  	text: [
					"It was the kiss of my life, nothing will ever top it!",
					"It was so hot and passionate that even now my legs tremble when I think about it.",
					"I couldn't believe it was actually happening. I thought I was imagining it or dreaming. It felt like… I was walking on clouds and didn't want to come down.",
					"It caught me by surprise. You had just told me about your husband and how you couldn't give me what I wanted, but then you hugged me and kissed me… I was a little confused at the time.",
				],
				choiceNext: false,
			},
			"32": {
				background: "special_scenes/0003-20",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'reina~importants~0003-30',
			  	name: "Reina",
			  	text: [
					"O-kay, Tyler. I might be good, but not that good.",
					"Well… it was a special kiss, and our first kiss, but I know I can do even better if I'm really head over heels for someone.",
					"Awww… that was really sweet! And how poetically you put it!",
					"Y-yeah, I understand. But I hoped I left a more positive memory of that kiss with you.",
				],				
				choiceNext: false,
			},
			"33": {
				specialSceneId: "0003-33",
				background: "special_scenes/0003-33",
				backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "You know, it took me a huge amount of determination, and I can't even put into words how much I struggled internally about whether or not to go through with it. Because the loyal wife inside me was protesting, I'd never done anything like this before. But the... woman, or the bad girl who feels neglected, really wanted it!",
				choiceNext: false,
			},
			"34": {
				background: "special_scenes/0003-33",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "So it was a battle between heart and mind.",
				choiceNext: false,
			},
			"35": {
				background: "special_scenes/0003-33",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "If we simplify it that much, then yes, that's true, but it's not entirely accurate. But then it just happened, and even I don't know what made me decide. After that, everything became blurry...",
				choiceNext: false,
			},
			"36": {
				background: "special_scenes/0003-33",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Because I was happy it happened — I had been curious for so long about what your lips would taste like, what a kiss would feel like with someone I felt such a strong attraction toward. I can't even remember the last time I felt something like that...",
				choiceNext: false,
			},
			"37": {
				specialSceneId: "0003-37",
				background: "special_scenes/0003-37",
				backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "But at the same time, I regretted it in the next moment, because I felt like I had just thrown 20 years of loyalty and 10 years of marriage out the window.",
				choiceNext: false,
			},
			"38": {
				background: "special_scenes/0003-37",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "I felt like the whore wife, who's unable to control herself at the most critical moment, and all these images flashed through my mind about how this would somehow come out, and that would be the end of my life… because I was too selfish!",
				choiceNext: false,
			},
			"39": {
				background: "special_scenes/0003-37",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "I was holding back for so long to be a good wife and mom, but I wanted to be felt as a woman again.",
				choiceNext: false,
			},
			"40": {
				background: "special_scenes/0003-37",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I've never been on the same boat with you, so I can't say I've experienced your situation, but I understand the dilemma you went through. Afterwards, you left so abruptly, turning on your heel, that I didn't even know what was going on. Everything happened so quickly and confusingly.",
				choiceNext: false,
			},
			"41": {
				background: "special_scenes/0003-37",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "That's why I wanted to clear things up the next time we met, to figure out what really happened and what's the situation with us.",
				choiceNext: false,
			},
			"42": {
				background: "special_scenes/0003-37",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "I'm glad you did. Because if you hadn't reassured me then, and shown me that the feelings were mutual, we wouldn't be sitting here on this bench together right now.",
				choiceNext: false,
			},
			"43": {
				background: "special_scenes/0003-37",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I'm glad it turned out this way, and that you've opened a new chapter in my life.",
				choiceNext: false,
			},
			"44": {
				background: "special_scenes/0003-37",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "And you've opened one in mine too.",
				choiceNext: false,
			},
			"45": {
				background: "special_scenes/0003-37",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Well, we still have a little time before we have to head back. Shall we continue our walk?",
				choiceNext: false,
			},
			"46": {
				background: "special_scenes/0003-37",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Of course.",
				choiceNext: false,
			},
			"47": {
				background: "backgrounds/BG_outskirt_park_sunny",
				specialSceneNow: true,
				specialSceneOut: true,
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "We walked for another half hour, then Reina drove me home before heading off to pick up her daughters.",
				choiceNext: false,
			},
			"48": {
				bgMusic: {
					name: 'Date_with_Reina',
					command: 'FADE_OUT'
				},
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I thought that was the end of my plans for the day, but someone else was about to rewrite that assumption.",
				choiceNext: false,
				timeSkipNext: {
					content: "A few hours later...",
					nextSceneType: "MOBILE",
					nextSceneNumber: "0004",
				}
			},
		},
	},
];