export const scene_19 = [
    { sceneId: "0017" }, //storyScene: 0014
    { sceneId: "0018" }, //storyScene: 0015
    {
		sceneId: "0019",
        startTime: "20:48",
        endTime: "00:50",
        timeSkipNext: {
            content: "Wednesday morning",
            nextSceneType: "STORY",
            nextSceneNumber: "0020",
        },
        keepOut: [],
        bgMusic: {
            name: 'Mobile_night_normal',
            command: 'START',
        },
		textingPartner: {
            Brianna: {
                isMandatory: true,
                sheStartsAt: "20:50",
                sheEndsAt: "23:20",
                messages: [
                    {
                        id: 0, 
                        isFromHer: true, 
                        text: "Hey Tyler 🙂", 
                        waitingTime: 0,
                        typingTime: 0.5,
                    },
                    {
                        id: 1, 
                        isFromHer: true, 
                        text: "Are you free right now?", 
                        waitingTime: 2,
                        typingTime: 2,
                    },
                    {
                        id: 2, 
                        isFromHer: false, 
                        text: "Hey Brianna, yeah, what's up?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 3, 
                        isFromHer: true, 
                        text: "...", 
                        waitingTime: 4,
                        typingTime: 1,
                    },
                    {
                        id: 4, 
                        isFromHer: true, 
                        text: "I was just thinking...", 
                        waitingTime: 3,
                        typingTime: 2,
                    },
                    {
                        id: 5, 
                        isFromHer: true, 
                        text: "Okay, it seemed like a fun idea to speak ambiguously today in front of that young girl...", 
                        waitingTime: 2,
                        typingTime: 8,
                    },
                    {
                        id: 6, 
                        isFromHer: true, 
                        text: "But how did what I said actually affect you?", 
                        waitingTime: 2,
                        typingTime: 4.5,
                        bgMusic: {
                            name: 'Mobile_night_romantic',
                            command: 'START',
                        },
                    },
                    {
                        id: 7, 
                        isFromHer: true, 
                        text:"Let's put all the jokes aside now", 
                        waitingTime: 3,
                        typingTime: 3.5,
                    },
                    {
                        id: 8, 
                        isFromHer: false, 
                        text: "I'll be honest, I didn't expect it. And I spent some time wondering if you were serious or just joking around", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 9, 
                        isFromHer: true, 
                        text: "And what if I was serious? 😣", 
                        waitingTime: 4,
                        typingTime: 3,
                    },
                    {
                        id: 10, 
                        isFromHer: true, 
                        text: "Would that make you happy?", 
                        waitingTime: 2,
                        typingTime: 3,
                    },
                    {
                        id: 11, 
                        isFromHer: false, 
                        text: "I'd be really surprised. And I'd have to ask: why me, of all people?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 12, 
                        isFromHer: true, 
                        text: "I don't know...", 
                        waitingTime: 4,
                        typingTime: 1.5,
                    },
                    {
                        id: 13, 
                        isFromHer: true, 
                        text: "For one, you care about me", 
                        waitingTime: 3,
                        typingTime: 3,
                    },
                    {
                        id: 14, 
                        isFromHer: true, 
                        text: "Sure, other men offer their help sometimes...", 
                        waitingTime: 4,
                        typingTime: 5,
                    },
                    {
                        id: 15, 
                        isFromHer: true, 
                        text: "But most of them are all talk 😤", 
                        waitingTime: 2,
                        typingTime: 3,
                    },
                    {
                        id: 16, 
                        isFromHer: true, 
                        text: "You make sure I stay fresh and healthy, and I'm really grateful for that😊", 
                        waitingTime: 2,
                        typingTime: 7,
                    },
                    {
                        id: 17, 
                        isFromHer: true, 
                        text: "Plus, you're the only one I let close enough to actually touch me😏", 
                        waitingTime: 2,
                        typingTime: 6,
                    },
                    {
                        id: 18, 
                        isFromHer: false, 
                        text: "Well, when correcting your movements, I prefer to adjust you manually", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 19, 
                        isFromHer: true, 
                        text: "And there's nothing wrong with that", 
                        waitingTime: 3,
                        typingTime: 4,
                    },
                    {
                        id: 20, 
                        isFromHer: true, 
                        text: "Of course, it's helpful...", 
                        waitingTime: 2,
                        typingTime: 3,
                    },
                    {
                        id: 21, 
                        isFromHer: true, 
                        text: "But it also feels good to be touched by you😋", 
                        waitingTime: 5,
                        typingTime: 4.5,
                    },
                    {
                        id: 22, 
                        isFromHer: false, 
                        text: "Are you serious right now?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 23, 
                        isFromHer: true, 
                        text: "I don't know... maybe", 
                        waitingTime: 3,
                        typingTime: 3.5,
                    },
                    {
                        id: 24,
                        isFromHer: false, 
                        text: "Maybe? You were quite naughty earlier, and now you're leaving me in this uncertainty ", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 25, 
                        isFromHer: false, 
                        text: "I didn't wake up today expecting to ride this emotional rollercoaster with you", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 26, 
                        isFromHer: true, 
                        text: "I'm a woman, I have needs too😞", 
                        waitingTime: 3,
                        typingTime: 3.5,
                    },
                    {
                        id: 27, 
                        isFromHer: true, 
                        text: "The question is, do you want to be the one to fulfill those needs?", 
                        waitingTime: 3,
                        typingTime: 6.5,
                    },
                    {
                        id: 28, 
                        isFromHer: false, 
                        text: [
                            "Of course, that's not even a question",
                            "I'm not sure… it sounds nice, but I don't want to push any boundaries",
                            "I appreciate the offer, but there are limits we just can't cross",
                        ], 
                        waitingTime: null,
                        typingTime: null,
                        choiceNow: true,
                        choicePath: "brianna~mobileImportants~0019-b-28",
                    },
                    {
                        id: 29, 
                        isFromHer: true, 
                        text: [
                            "Oh… okay...🤨",
                            "Hey, that's not fair!😠",
                            "You really stick to the rules of your profession😞",
                            "I see...😞",
                        ], 
                        waitingTime: 3,
                        typingTime: [2, 3, 5, 1.5],
                        choicePath: "brianna~mobileImportants~0019-b-28",
                        bgMusic: {
                            name: ['Mobile_night_sad', 'Mobile_night_romantic', 'Mobile_night_sad', 'Mobile_night_sad'],
                            command: 'START',
                        },
                    },
                    {
                        isFromHer: true, 
                        text: [
                            "That was too easy",
                            "Finally, I'm being straight with you, and now you're the one playing games?",
                            "You could loosen up a bit sometimes",
                            "I take it as a no😢",
                        ], 
                        waitingTime: 2,
                        typingTime: [3, 7, 4, 3],
                        choicePath: "brianna~mobileImportants~0019-b-28",
                    },
                    {
                        id: 31, 
                        isFromHer: false, 
                        text: [
                            "It's rare to get such an offer, I should take advantage",
                            "Sorry, I'm not that easy",
                            "I still need to make a living",
                            "No, it's not",
                        ], 
                        waitingTime: null,
                        typingTime: null,
                        choicePath: "brianna~mobileImportants~0019-b-28",
                    },
                    {
                        id: 32, 
                        isFromHer: true, 
                        text: [
                            "Well... okay... if you say so...",
                            "Well, fine, you asked for it...",
                            "If the rules are that strict, maybe you should consider looking for another job",
                            "Then what?",
                        ], 
                        waitingTime: 3,
                        typingTime: [3, 3, 7, 1.5],
                        choicePath: "brianna~mobileImportants~0019-b-28",
                    },
                    {
                        id: 33, 
                        isFromHer: true, 
                        text: [
                            "Then I guess we've said all we needed to",
                            null,
                            "You're smart, you'll find something better",
                            "Why won't you answer me?😩",
                        ],
                        sentPicture: "0019-b-33",
                        waitingTime: 3,
                        typingTime: [3, 3, 7, 1.5],
                        choicePath: "brianna~mobileImportants~0019-b-28",
                        bgMusic: {
                            name: ['Mobile_night_sad', 'Mobile_night_ecchi', 'Mobile_night_sad', 'Mobile_night_sad'],
                            command: ['START', 'START', 'START', 'START'],
                        },
                    },
                    {
                        id: 34, 
                        isFromHer: false, 
                        text: [
                            "So, what should we do next?",
                            "Hey, that was a low blow!",
                            "I'm not going to be a trainer forever",
                            "I'm just shocked by your question",
                        ],
                        waitingTime: null,
                        typingTime: null,
                        choicePath: "brianna~mobileImportants~0019-b-28",
                    },
                    {
                        id: 35, 
                        isFromHer: true, 
                        text: [
                            "We'll talk again on Thursday, let's discuss it then",
                            "That was the point...😉🤭",
                            "Maybe then you'll finally be free",
                            "I see... we'll get back to this later then",
                        ],
                        waitingTime: 4,
                        typingTime: [5, 2.5, 3.5, 4],
                        choicePath: "brianna~mobileImportants~0019-b-28",
                    },
                    {
                        id: 36, 
                        isFromHer: true, 
                        text: [
                            "But for now, I'll say farewell",
                            "To stir up something on low level that can be blown by me😜👅",
                            "Anyway, that's all for now",
                            "But for now, I'll say farewell",
                        ],
                        waitingTime: 2,
                        typingTime: [3.5, 5.5, 3.5, 3.5],
                        choicePath: "brianna~mobileImportants~0019-b-28",
                    },
                    {
                        id: 37, 
                        isFromHer: true,
                        text: [
                            "Goodnight🌒",
                            "Well, I got what I wanted, so goodnight😚🌒",
                            "Goodnight🌒",
                            "Goodnight🌒",
                        ],
                        waitingTime: 3,
                        typingTime: [1, 3.5, 1, 1],
                        choicePath: "brianna~mobileImportants~0019-b-28",
                        canSpeedUp: [true, "23:20"]
                    },
                ],
            },
            Reina: {
                isMandatory: true,
                sheStartsAt: "23:23",
                sheEndsAt: "00:48",
                messages: [
                    {
                        id: 0, 
                        isFromHer: true, 
                        text: "Hey sweetheart😘", 
                        waitingTime: 0,
                        typingTime: 0.5,
                        bgMusic: {
                            name: 'Mobile_daily_normal',
                            command: 'START',
                        },
                    },
                    {
                        id: 1, 
                        isFromHer: true, 
                        text: "How are you?", 
                        waitingTime: 2,
                        typingTime: 2,
                    },
                    {
                        id: 2, 
                        isFromHer: false, 
                        text: "Hey darling😊 a bit tired, but I'm good. What's up?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 3, 
                        isFromHer: true, 
                        text: "Everything's fine, just been thinking...", 
                        waitingTime: 3,
                        typingTime: 4,
                    },
                    {
                        id: 4, 
                        isFromHer: true, 
                        text: "You're off tomorrow, right?", 
                        waitingTime: 2,
                        typingTime: 3,
                    },
                    {
                        id: 5, 
                        isFromHer: false, 
                        text: "That's right", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 6, 
                        isFromHer: true, 
                        text: "How about we go on a date in the morning?😇", 
                        waitingTime: 4,
                        typingTime: 4,
                    },
                    {
                        id: 7, 
                        isFromHer: false, 
                        text: "I'd love that, but how are we going to manage it this time?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 8, 
                        isFromHer: true, 
                        text: "I think we could be a bit braver and go out in public🙂", 
                        waitingTime: 3,
                        typingTime: 5,
                    },
                    {
                        id: 9, 
                        isFromHer: true, 
                        text: "Of course, we'll keep a little physical distance so no one gets suspicious", 
                        waitingTime: 2,
                        typingTime: 7,
                    },
                    {
                        id: 10, 
                        isFromHer: true, 
                        text: "But I was thinking, what if we visit the mall?", 
                        waitingTime: 2,
                        typingTime: 4,
                    },
                    {
                        id: 11, 
                        isFromHer: false, 
                        text: "Fine by me", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 12, 
                        isFromHer: true, 
                        text: "You don't sound too thrilled", 
                        waitingTime: 4,
                        typingTime: 3,
                    },
                    {
                        id: 13, 
                        isFromHer: false, 
                        text: "No, I'm happy for any chance I get to spend time with you", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 14, 
                        isFromHer: false, 
                        text: "I just really want some one-on-one time, just the two of us", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 15, 
                        isFromHer: true, 
                        text: "Oh, sweetheart...🥺", 
                        waitingTime: 5,
                        typingTime: 2,
                    },
                    {
                        id: 16, 
                        isFromHer: true, 
                        text: "That time will come, you'll see😉😘", 
                        waitingTime: 3,
                        typingTime: 3.5,
                    },
                    {
                        id: 17, 
                        isFromHer: true, 
                        text: "But okay, tomorrow after I drop off the girls, I'll head over", 
                        waitingTime: 3,
                        typingTime: 6,
                    },
                    {
                        id: 18, 
                        isFromHer: true, 
                        text: "Let's meet at the benches by the entrance🙂", 
                        waitingTime: 2,
                        typingTime: 4,
                    },
                    {
                        id: 19, 
                        isFromHer: false, 
                        text: "Alright, I'll be there", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 20, 
                        isFromHer: true, 
                        text: "Good. See you tomorrow then😘", 
                        waitingTime: 3,
                        typingTime: 3,
                    },
                    {
                        id: 21, 
                        isFromHer: true, 
                        text: "Goodnight🌙", 
                        waitingTime: 2,
                        typingTime: 2,
                        canSpeedUp: [true, "00:48"]
                    }
                ]
            }
        }
    },
];