export const scene_33 = [
    { sceneId: "0029" }, //storyScene: 0029
    { sceneId: "0030" }, //storyScene: 0030
    { sceneId: "0031" }, //storyScene: 0031
    { sceneId: "0032" }, //storyScene: 0032
    {
		sceneId: "0033",
        startTime: "14:16",
        endTime: "17:57",
        timeSkipNext: {
            content: "In the late afternoon...",
            nextSceneType: "STORY",
            nextSceneNumber: "0034",
        },
        keepOut: ['Lindsay Lawrie'],
        bgMusic: {
            name: 'Mobile_daily_normal',
            command: 'START',
        },
		textingPartner: {
            Daena: {
                isMandatory: false,
                sheStartsAt: "14:18",
                sheEndsAt: "16:09",
                messages: [
                    {
                        id: 0, 
                        isFromHer: true, 
                        text: "Hey Tyler!😊", 
                        waitingTime: 0,
                        typingTime: 0.5,
                    },
                    {
                        id: 1, 
                        isFromHer: true, 
                        text: "Mind if I bug u for a bit?🙂", 
                        waitingTime: 2,
                        typingTime: 2,
                    },
                    {
                        id: 2, 
                        isFromHer: false, 
                        text: "Hey Daena!🙂", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 3, 
                        isFromHer: false, 
                        text: "Ofc, what's up?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 4, 
                        isFromHer: true, 
                        text: "Today's swim day ended so fast, and we had to split all sudden-like... didn't really get a chance to say thx properly", 
                        waitingTime: 4,
                        typingTime: 8,
                    },
                    {
                        id: 5, 
                        isFromHer: true, 
                        text: "So, thx for coming w/ me—I had a blast!😌😘", 
                        waitingTime: 2,
                        typingTime: 3.5,
                    },
                    {
                        id: 6, 
                        isFromHer: false, 
                        text: "I also thank you for the invite! It was great to unwind", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 7, 
                        isFromHer: true, 
                        text: "Happy to hear that!😊😊", 
                        waitingTime: 3,
                        typingTime: 2,
                    },
                    {
                        id: 8, 
                        isFromHer: true, 
                        text: "Got a question tho...", 
                        waitingTime: 4,
                        typingTime: 2,
                    },
                    {
                        id: 9, 
                        isFromHer: true, 
                        text: "Was I like... too much for you today?", 
                        waitingTime: 2,
                        typingTime: 3.5,
                    },
                    {
                        id: 10, 
                        isFromHer: false, 
                        text: "What do u mean?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 11, 
                        isFromHer: true, 
                        text: "I mean, did I push it too hard on that topic we started about Hailey?", 
                        waitingTime: 2,
                        typingTime: 6,
                    },
                    {
                        id: 12, 
                        isFromHer: true, 
                        text: "Was I like, over-the-top or annoying with wanting to know what kind of girls u like?", 
                        waitingTime: 2,
                        typingTime: 7,
                    },
                    {
                        id: 13, 
                        isFromHer: false,
                        text: [
                            "You're just full of energy right now, but as you mature, things'll probably mellow out",
                            "Didn't bother me, but if you wanna change, I can teach you some patience",
                            "If this is who you are, Daena, that's cool. Gotta love you for it."
                        ], 
                        waitingTime: null,
                        typingTime: null,
                        choiceNow: true,
                        choicePath: "daena~mobileImportants~0033-d-13",
                    },
                    {
                        id: 14, 
                        isFromHer: true,
                        text: [
                            "Sooo... that kinda sounds like I was annoying😒",
                            "I can't ask for help with everything, and I def don't need it on this",
                            "Really? Do you like me?😮😮"
                        ], 
                        waitingTime: 4,
                        typingTime: [3.5, 6, 2],
                        choicePath: "daena~mobileImportants~0033-d-13",
                    },
                    {
                        id: 15, 
                        isFromHer: false,
                        text: [
                            "Didn't mean it like that, just speaking from experience",
                            "Just offering, take it or leave it",
                            "I can feel something special... but I'm not saying it here first"
                        ], 
                        waitingTime: null,
                        typingTime: null,
                        choicePath: "daena~mobileImportants~0033-d-13",
                    },
                    {
                        id: 16, 
                        isFromHer: true,
                        text: [
                            "I'd believe that",
                            "I know u that well by now",
                            "Yeah, I get it😔"
                        ], 
                        waitingTime: 3,
                        typingTime: [2, 2.5, 2],
                        choicePath: "daena~mobileImportants~0033-d-13",
                    },
                    {
                        id: 17, 
                        isFromHer: true,
                        text: "Oh, and btw, about that body check...", 
                        waitingTime: 2,
                        typingTime: 3.5,
                    },
                    {
                        id: 18, 
                        isFromHer: true,
                        text: "You haven't given any feedback on the look I showed off today😒", 
                        waitingTime: 2,
                        typingTime: 5,
                    },
                    {
                        id: 19, 
                        isFromHer: false,
                        text: "Oh, sorry... I was so into the moment that I totally spaced on that", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 20, 
                        isFromHer: true,
                        text: "Haha, no worries", 
                        waitingTime: 3,
                        typingTime: 2,
                    },
                    {
                        bgMusic: {
                            name: ['Mobile_daily_normal', 'Mobile_daily_normal', 'Mobile_daily_ecchi'],
                            command: ['START', 'START', 'START']
                        },
                        id: 21, 
                        isFromHer: true,
                        sentPicture: [null, null, "0033-d-22"],
                        text: [
                            "Next time, then🙂",
                            "Next time, then🙂",
                            null
                        ], 
                        waitingTime: 4,
                        typingTime: 2,
                        choicePath: "daena~mobileImportants~0033-d-13",
                    },
                    {
                        id: 22, 
                        isFromHer: false,
                        text: [
                            "I'll try not to forget",
                            "I'll try not to forget",
                            "OMG! Wasn't expecting that at all!"
                        ], 
                        waitingTime: null,
                        typingTime: null,
                        choicePath: "daena~mobileImportants~0033-d-13",
                    },
                    {
                        id: 23, 
                        isFromHer: true,
                        text: [
                            "I'd appreciate that",
                            "I'd appreciate that",
                            "Like it?🫣"
                        ], 
                        waitingTime: 3,
                        typingTime: [2, 2, 1],
                        choicePath: "daena~mobileImportants~0033-d-13",
                        chatSkip: [2, 2, 0],
                    },
                    {
                        id: 24, 
                        isFromHer: false,
                        text: [
                            null,
                            null,
                            "Already saved it for myself"
                        ], 
                        waitingTime: null,
                        typingTime: null,
                        choicePath: "daena~mobileImportants~0033-d-13",
                    },
                    {
                        id: 25, 
                        isFromHer: true,
                        text: [
                            null,
                            null,
                            "Hehe...😅 glad to know u like me that much😜😜"
                        ], 
                        waitingTime: 3,
                        typingTime: 3.5,
                        choicePath: "daena~mobileImportants~0033-d-13",
                    },
                    {
                        id: 26, 
                        isFromHer: true,
                        text: "Gotta run now, tho!", 
                        waitingTime: 3,
                        typingTime: 2,
                    },
                    {
                        id: 27, 
                        isFromHer: true,
                        text: "Ttyl", 
                        waitingTime: 2,
                        typingTime: 1,
                    },
                    {
                        id: 28, 
                        isFromHer: true,
                        text: "Bye😘😘", 
                        waitingTime: 3,
                        typingTime: 1,
                    },
                ],
            },
            Reina: {
                isMandatory: false,
                sheStartsAt: "14:53",
                sheEndsAt: "17:50",
                messages: [
                    {
                        id: 0, 
                        isFromHer: true, 
                        text: "Hi, Sweetie!🥰🥰", 
                        waitingTime: 0,
                        typingTime: 0.5,
                        bgMusic: {
                            name: 'Date_with_Reina',
                            command: 'START',
                        },
                    },
                    {
                        id: 1, 
                        isFromHer: true, 
                        text: "How's your day going?", 
                        waitingTime: 2,
                        typingTime: 2,
                    },
                    {
                        id: 2, 
                        isFromHer: false, 
                        text: "Hi Reina, not too bad so far. And yours? 🙂", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 3, 
                        isFromHer: true, 
                        text: "Hmm... just the usual", 
                        waitingTime: 2,
                        typingTime: 2,
                    },
                    {
                        id: 4, 
                        isFromHer: true, 
                        text: "Keeping up with the house, and the kids are super energetic again😏", 
                        waitingTime: 2,
                        typingTime: 5.5,
                    },
                    {
                        id: 5, 
                        isFromHer: true, 
                        text: "A little helping hand would be nice🤗", 
                        waitingTime: 3,
                        typingTime: 3.5,
                    },
                    {
                        id: 6, 
                        isFromHer: false, 
                        text: "Should I take that as an invitation?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 7, 
                        isFromHer: true, 
                        text: "Happy to hear that😊", 
                        waitingTime: 3,
                        typingTime: 2,
                    },
                    {
                        id: 8, 
                        isFromHer: true, 
                        text: "You're so sweet, and it would be amazing...😍", 
                        waitingTime: 4,
                        typingTime: 4,
                    },
                    {
                        id: 9, 
                        isFromHer: true, 
                        text: "But my husband's coming back from his run soon, so I might get a little help then", 
                        waitingTime: 2,
                        typingTime: 7,
                    },
                    {
                        id: 10, 
                        isFromHer: false, 
                        text: "Ah, I see", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 11, 
                        isFromHer: true, 
                        text: "Are you that free for the rest of the day?", 
                        waitingTime: 5,
                        typingTime: 4,
                    },
                    {
                        id: 12, 
                        isFromHer: false, 
                        text: "I do have one thing: meeting up with my friends", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 13, 
                        isFromHer: true,
                        text: "Good. You need to hang out with them sometimes; you can't just work all the time... at work and at home", 
                        waitingTime: 3,
                        typingTime: 8,
                    },
                    {
                        id: 14, 
                        isFromHer: true,
                        text: "Everyone needs a bit of a break🙂", 
                        waitingTime: 2,
                        typingTime: 3,
                    },
                    {
                        id: 15, 
                        isFromHer: false,
                        text: "You're my break too, Reina", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 16, 
                        isFromHer: true,
                        text: "You're so sweet!😘", 
                        waitingTime: 4,
                        typingTime: 2,
                    },
                    {
                        id: 17, 
                        isFromHer: true,
                        text: "And yesterday's time in the bath was really nice😊", 
                        waitingTime: 2,
                        typingTime: 4,
                    },
                    {
                        id: 18, 
                        isFromHer: true,
                        text: "It was so intimate, but also incredibly exciting🥵", 
                        waitingTime: 2,
                        typingTime: 4,
                    },
                    {
                        id: 19, 
                        isFromHer: true,
                        text: "I kind of regret that things didn't go further...", 
                        waitingTime: 3,
                        typingTime: 4,
                    },
                    {
                        id: 20, 
                        isFromHer: true,
                        text: "Because if I think about it, if I hadn't held back that day...", 
                        waitingTime: 3,
                        typingTime: 5,
                    },
                    {
                        id: 21, 
                        isFromHer: true,
                        text: "I'm almost constantly having to change my panties because they get wet😝", 
                        waitingTime: 4,
                        typingTime: 6,
                    },
                    {
                        id: 22, 
                        isFromHer: false,
                        text: [
                            "But you turned me down when I made a move",
                            "So, was it a waste for me to stay a gentleman?"
                        ], 
                        waitingTime: null,
                        typingTime: null,
                        choicePath: "reina~importants~0027-40",
                    },
                    {
                        id: 23, 
                        isFromHer: true,
                        text: [
                            "Yes, at that moment, it felt right...",
                            "No, I'm glad you could control yourself...🙂"
                        ], 
                        waitingTime: 3,
                        typingTime: 4,
                        choicePath: "reina~importants~0027-40",
                    },
                    {
                        id: 24, 
                        isFromHer: true,
                        text: "It's just that, looking back, knowing how many chances we would have had...", 
                        waitingTime: 2,
                        typingTime: 6,
                    },
                    {
                        id: 25, 
                        isFromHer: true,
                        text: "And you can't just do it anytime in a place like that...", 
                        waitingTime: 2,
                        typingTime: 5,
                    },
                    {
                        id: 26, 
                        isFromHer: true,
                        text: "It gets me so worked up that if no one were home right now, I'd invite you over and devour you without hesitation😜😜", 
                        waitingTime: 3,
                        typingTime: 8,
                    },
                    {
                        id: 27, 
                        isFromHer: false,
                        text: [
                            "Yeah, it really is a pity",
                            "Hmm... so, should I cancel my plans, just in case we can make something work?",
                            "The thing is, even if you were free, I can't cancel my plans with my friends now",
                            "I'm already bursting because of you... if only you knew what I'd do with you..."
                        ], 
                        waitingTime: null,
                        typingTime: null,
                        choiceNow: true,
                        choicePath: "reina~mobileImportants~0033-r-27",
                    },
                    {
                        id: 28, 
                        isFromHer: true,
                        text: [
                            "That's it?",
                            "No, Tyler, like I said, it's pointless, we're all gonna be home today",
                            "I'd never ask you to ditch your friends for me",
                            "Haha...😄 I don't doubt it for a second...😊"
                        ], 
                        waitingTime: 4,
                        typingTime: [1, 6, 4.5, 3.5],
                        choicePath: "reina~mobileImportants~0033-r-27",
                        bgMusic: {
                            name: ['Mobile_daily_sad', 'Mobile_daily_sad', 'Mobile_daily_sad', 'Date_with_Reina'],
                            command: ['START', 'START', 'START', 'START'],
                        },
                    },
                    {
                        id: 29, 
                        isFromHer: true,
                        text: [
                            "Nothing else to add?",
                            "I'd never ask you to skip out on your friends for me",
                            "I never want to be that naggy person keeping you on a short leash",
                            "And maybe... I'd let you😋"
                        ], 
                        waitingTime: 2,
                        typingTime: [2, 5, 5.5, 2],
                        choicePath: "reina~mobileImportants~0033-r-27",
                    },
                    {
                        id: 30, 
                        isFromHer: false,
                        text: [
                            "Yes, because right now, I'm helpless in this situation",
                            "Well... would have been worth a shot",
                            "Sometimes you seem a little jealous of some people, though",
                            "You say things like that, and I'm going to hold you to it"
                        ], 
                        waitingTime: null,
                        typingTime: null,
                        choicePath: "reina~mobileImportants~0033-r-27",
                    },
                    {
                        id: 31, 
                        isFromHer: true,
                        text: [
                            "It would've been nice to hear that you wanted it too",
                            "Of course, I do appreciate that",
                            "You bet!",
                            "So let it be"
                        ], 
                        waitingTime: 3,
                        typingTime: [5, 3, 1, 1],
                        choicePath: "reina~mobileImportants~0033-r-27",
                    },
                    {
                        id: 32, 
                        isFromHer: [false, true, true, true],
                        sentPicture: [null, null, null, "0033-r-33"],
                        text: [
                            "I thought that kind of thing went without saying",
                            "But you could trust me a little more, you know",
                            "You're mine; no one else can have you from now on!",
                            null
                        ], 
                        waitingTime: [null, 2, 2, 2],
                        typingTime: [null, 5, 5, 2],
                        choicePath: "reina~mobileImportants~0033-r-27",
                        bgMusic: {
                            name: ['Mobile_daily_sad', 'Mobile_daily_sad', 'Mobile_daily_sad', 'Mobile_daily_ecchi'],
                            command: ['START', 'START', 'START', 'START'],
                        },
                    },
                    {
                        id: 33, 
                        isFromHer: [true, false, false, false],
                        text: [
                            "Just because I know doesn't mean it's not nice to hear—or read—what you think or feel sometimes",
                            "I'll do my best",
                            "So, when can you finally be mine too?",
                            "Whoa! What did I do to deserve this?"
                        ], 
                        waitingTime: [4, null, null, null],
                        typingTime: [8, null, null, null],
                        choicePath: "reina~mobileImportants~0033-r-27",
                    },
                    {
                        id: 34, 
                        isFromHer: [false, true, true, true],
                        text: [
                            "Ah, I get it",
                            "Good",
                            "That will take more time, Tyler",
                            "A little preview for the next time we meet...🤫"
                        ], 
                        waitingTime: [null, 3, 3, 3],
                        typingTime: [null, 1, 3, 4],
                        choicePath: "reina~mobileImportants~0033-r-27",
                    },
                    {
                        id: 35, 
                        isFromHer: true,
                        text: [
                            "Alright...",
                            "Now that that's settled...",
                            "That would be a serious milestone, and I'd like to take things one step at a time",
                            "But you'll have to hold on until then, so don't even think about using this picture for... that!"
                        ], 
                        waitingTime: 4,
                        typingTime: [1, 2.5, 7, 8],
                        choicePath: "reina~mobileImportants~0033-r-27",
                    },
                    {
                        id: 36, 
                        isFromHer: true,
                        text: "When we finally meet again, I promise, we'll leave no stone unturned😍😍", 
                        waitingTime: 3,
                        typingTime: 6,
                        bgMusic: {
                            name: 'Mobile_daily_romantic',
                            command: 'START',
                        },
                    },
                    {
                        id: 37, 
                        isFromHer: true,
                        text: "We can unleash our wild sides then🤪", 
                        waitingTime: 3,
                        typingTime: 3.5,
                    },
                    {
                        id: 38, 
                        isFromHer: true,
                        text: "So hold onto everything until then...", 
                        waitingTime: 2,
                        typingTime: 3.5,
                    },
                    {
                        id: 39, 
                        isFromHer: true,
                        text: "Because I want it to be unforgettable!🥵🥵", 
                        waitingTime: 2,
                        typingTime: 3.5,
                    },
                    {
                        id: 40, 
                        isFromHer: false,
                        text: "With messages like this, it's a lot harder to wait", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 41, 
                        isFromHer: true,
                        text: "I might have said it a few times already...", 
                        waitingTime: 3,
                        typingTime: 4,
                    },
                    {
                        id: 42, 
                        isFromHer: true,
                        text: "But this really will be worth the wait😉", 
                        waitingTime: 2,
                        typingTime: 4,
                    },
                    {
                        id: 43, 
                        isFromHer: false,
                        text: "I don't doubt that", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 44, 
                        isFromHer: true,
                        text: "Good😊", 
                        waitingTime: 3,
                        typingTime: 1,
                    },
                    {
                        id: 45, 
                        isFromHer: true,
                        text: "Sorry, but I still have so much to do today", 
                        waitingTime: 4,
                        typingTime: 4,
                    },
                    {
                        id: 46, 
                        isFromHer: true,
                        text: "I'll check in again later", 
                        waitingTime: 2,
                        typingTime: 2.5,
                    },
                    {
                        id: 47, 
                        isFromHer: true,
                        text: "Kisses💋💋❤️❤️", 
                        waitingTime: 2,
                        typingTime: 1,
                        canSpeedUp: [true, "19:20"]
                    }
                ],
            },
        }
    },
];