export const scene_17 = [
    { sceneId: "0016" }, //storyScene: 0016
	{
		sceneId: "0017",
		lengthNum: 75,
		story: {
			"1": {
				bgMusic: {
					name: 'Morning_normal',
					command: 'START'
				},
                background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "It's Tuesday, another workday. But I only have to survive this day, and tomorrow I can finally take a big rest.",
				choiceNext: false,
            },
			"2": {
                background: "backgrounds/BG_gym_inside_sunny",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I love it when two or more of my more talented clients end up in the same group workout because that's when the results of my hard work really start to show.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "This is exactly what happened during one of my morning sessions today—Reina and Hailey ended up working out together. From afar, you can already tell that these two are miles ahead of the others, but there seems to be a bit of rivalry between them.",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "They've never worked out together before, though they've crossed paths during class switches. So, Hailey doesn't know much about Reina, but Reina has heard a lot about Hailey—mostly from me when I talk about work.",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "For some reason, Reina finds Hailey unlikable, so I have a feeling that her strong desire to prove herself today might stem from wanting to outdo Hailey out of spite. On the other hand, Hailey seems to misinterpret this as motivation, so she's pushing herself harder, which in turn pushes Reina to give even more effort.",
				choiceNext: false,
			},
			"6": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "If I had to summarize, Hailey is a bit more energetic and faster, but Reina is more technical and handles the weights better. So, it's hard to say which of them is the better one.",
				choiceNext: false,
			},
			"7": {
                background: "backgrounds/BG_reception_sunny",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "By the end of the session, both of them are sweating heavily, and I can only hope they won't start bickering in the women's locker room—but there's no way I can step in there, no matter what happens.",
                choiceNext: false,
            },
			"8": {
                bgMusic: {
					name: 'Morning_normal',
					command: 'FADE_OUT',
                    insideOfScene: true
				},
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Luckily, it seems like there wasn't an issue because they both walk out of the locker room at about the same time and come over to hand me their locker keys.",
				choiceNext: false,
			},
			"9": {
                bgMusic: {
					name: 'SunnyDay_normal_daily',
					command: 'START'
				},
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, null],
				image: ['Hailey/Hailey_casual_grin', null, null],
				class: ['fadeLeft', null, null],
			  	name: "Hailey",
			  	text: "Thanks, Tyler, that was so good again!",
				choiceNext: false,
			},
			"10": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_grin', null, 'Reina/Reina_casual_smiling'],
				class: [null, null, 'fadeRight'],
			  	name: "Reina",
			  	text: "Yeah, you really worked us hard!",
				choiceNext: false,
			},
			"11": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_grin', null, 'Reina/Reina_casual_smiling'],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Thanks, girls, but the credit goes to you. You're the ones who really put in the effort.",
				choiceNext: false,
			},
			"12": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_smiling', null, 'Reina/Reina_casual_smiling'],
				class: ['fadeLeft', null, null],
			  	name: "Tyler",
			  	text: "Totally! You're way better than that other chick from yesterday!",
				choiceNext: false,
			},
			"13": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_smiling', null, 'Reina/Reina_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: "Reina",
			  	text: "Other chick? Should I know her?",
				choiceNext: false,
			},
			"14": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_smiling', null, 'Reina/Reina_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Hailey",
			  	text: "Oh, for sure! What was her name again, Tyler? B… Br… Brianna?",
				choiceNext: false,
			},
			"15": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_smiling', null, 'Reina/Reina_casual_sad'],
				class: [null, null, 'fadeRight'],
			  	name: "Reina",
			  	text: "Ohhh, her! Yeah, I remember. You worked out with her yesterday?",
				choiceNext: false,
			},
			"16": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_smiling', null, 'Reina/Reina_casual_sad'],
				class: ['fadeLeft', null, null],
			  	name: "Hailey",
			  	text: "Yup. She wasn't bad, better than most. I even complimented her, but then she started arguing with me.",
				choiceNext: false,
			},
			"17": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_smiling', null, 'Reina/Reina_casual_surprised'],
				class: [null, null, 'fadeRight'],
			  	name: "Reina",
			  	text: "Really? Why?",
				choiceNext: false,
			},
			"18": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_smiling', null, 'Reina/Reina_casual_surprised'],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Basically, I told her she was doing great for her age. And she totally freaked out about me mentioning her age. One thing led to another, and Tyler had to step in and stop the whole thing.",
				choiceNext: false,
			},
			"19": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_smiling', null, 'Reina/Reina_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: "Reina",
			  	text: "Yeah? How did you do that?",
				choiceNext: false,
			},
			"20": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_smiling', null, 'Reina/Reina_casual_normal'],
				class: [null, null, null],
                choicePath: 'hailey~importants~0014-38',
			  	name: "Tyler",
			  	text: [
                    "I told Brianna she was overreacting about the age thing.",
                    "I told Hailey she should be more careful about what she says and when.",
                    "I didn't want them fighting in the gym, so I sent both of them out.",
                ],
				choiceNext: false,
			},
			"21": {
                bgMusic: {
					name: 'SunnyDay_normal_daily',
					command: 'FADE_OUT',
                    insideOfScene: true
				},
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_smiling', null, 'Reina/Reina_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: "Reina",
			  	text: "I see...",
				choiceNext: false,
			},
			"22": {
                bgMusic: {
					name: 'Girls_argument',
					command: 'START'
				},
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_smiling', null, 'Reina/Reina_casual_normal'],
				class: [null, null, null],
                choicePath: 'hailey~importants~0014-38',
			  	name: "Reina",
			  	text: [
                    "I don't entirely agree with you, Tyler, and I never thought I'd side with Brianna on anything... but I don't think she overreacted to the age comment.",
                    "Well, that's true. You might've gotten away with it in the gym this time, Hailey, but if you're not careful, a comment like that could land you in serious trouble someday, in the wrong place or with the wrong people.",
                    "I'm not sure that was the best way to handle it, Tyler. But I agree that the argument needed to stop. Still, I don't think Brianna overreacted about her age."
                ],
				choiceNext: false,
			},
			"23": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_smiling', null, 'Reina/Reina_casual_normal'],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "I don't know exactly how old Brianna is—she's a bit older than me—so I'd say she's maybe about two decades older than you, and I'm about a decade older than you.",
				choiceNext: false,
			},
			"24": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_smiling', null, 'Reina/Reina_casual_normal'],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Now, look at me! What do you see?",
				choiceNext: false,
			},
			"25": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_smiling', null, 'Reina/Reina_casual_normal'],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "This is what I look like after a little over a decade and two pregnancies. Would you have guessed that?",
				choiceNext: false,
            },
			"26": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_normal', null, 'Reina/Reina_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Hailey",
			  	text: "No, but...",
				choiceNext: false,
			},
			"27": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_normal', null, 'Reina/Reina_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: "Reina",
			  	text: "Exactly! Tyler thought I was 4-5 years younger when we first met, and that felt amazing. He's played a big part in helping me stay fit, healthy, and youthful, but I also put in a lot of work in my own time to look this way.",
				choiceNext: false,
			},
			"28": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_normal', null, 'Reina/Reina_casual_normal'],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "And trust me, it's not easy! When you step outside, you see plenty of overweight moms and neglected wives. It's rare to find women who still look like you do now!",
				choiceNext: false,
			},
			"29": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_normal', null, 'Reina/Reina_casual_normal'],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "You've got it easy for now because you're still young. Genetically, you're at your peak right now, but just wait until you're past 30. Things will start changing inside, and if you're not careful, you'll gain weight and the aging process will kick in fast!",
				choiceNext: false,
			},
			"30": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Reina/Reina_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Hailey",
			  	text: "Whoa, hold up! I worked hard to look like this! It wasn't always easy!",
				choiceNext: false,
			},
			"31": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Reina/Reina_casual_angry'],
				class: [null, null, 'fadeRight'],
			  	name: "Reina",
			  	text: "Oh yeah? Must've been super tough standing or lying in a tanning bed for 10-20 minutes three times a week. And I'm sure your boobs didn't just grow on their own either—it was your plastic surgeon doing the work, not you. And I'm guessing some guy worked hard to pay for all that, not you. All you had to do was spread your legs.",
				choiceNext: false,
			},
			"32": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Reina/Reina_casual_angry'],
				class: ['fadeLeft', null, null],
			  	name: "Hailey",
			  	text: "Hey! That's so not cool! I've never been with someone just for their money! And why is everyone so obsessed with my boobs?!",
				choiceNext: false,
			},
			"33": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Reina/Reina_casual_angry'],
				class: [null, null, 'fadeRight'],
			  	name: "Reina",
			  	text: "Bet it's nice to have them, though, right? As a simple hairdresser, I doubt you could afford all that on your own.",
				choiceNext: false,
			},
			"34": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Reina/Reina_casual_angry'],
				class: ['fadeLeft', null, null],
			  	name: "Hailey",
			  	text: "Wait—how do you know I'm a hairdresser?",
				choiceNext: false,
			},
			"35": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Reina/Reina_casual_angry'],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "Please, don't tell her you heard it from me!",
				choiceNext: false,
			},
			"36": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Reina/Reina_casual_angry'],
				class: ['fadeLeft', null, null],
			  	name: "Hailey",
			  	text: "And besides, what about you? It's morning work hours, so why are you here at the gym and not sitting behind a computer in some office?",
				choiceNext: false,
			},
			"37": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Reina/Reina_casual_angry'],
				class: [null, null, 'fadeRight'],
			  	name: "Reina",
			  	text: "Because I'm a full-time mom.",
				choiceNext: false,
			},
			"38": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Reina/Reina_casual_angry'],
				class: ['fadeLeft', null, null],
			  	name: "Hailey",
			  	text: "Aha! So, you're freeloading too!",
				choiceNext: false,
			},
			"39": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Reina/Reina_casual_angry'],
				class: [null, null, 'fadeRight'],
			  	name: "Reina",
			  	text: "Excuse me?",
				choiceNext: false,
			},
			"40": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Reina/Reina_casual_angry'],
				class: ['fadeLeft', null, null],
			  	name: "Hailey",
			  	text: "Unless you're divorced, you're living off your husband's money, not the money you worked for.",
				choiceNext: false,
			},
			"41": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Reina/Reina_casual_angry'],
				class: [null, null, 'fadeRight'],
			  	name: "Reina",
			  	text: "My husband makes the money, and I run the household and raise our kids. It's called teamwork.",
				choiceNext: false,
			},
			"42": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Reina/Reina_casual_angry'],
				class: ['fadeLeft', null, null],
			  	name: "Hailey",
			  	text: "Yeah, if you say so. The chick from yesterday's gotta raise her kids on her own and work to make sure they have a roof over their heads. Compared to her, your life's like a vacation. She works harder than most, yet still looks as good as you, so don't come at me about how hard it is to look good at your age!",
				choiceNext: false,
			},
			"43": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Reina/Reina_casual_angry'],
				class: [null, null, 'fadeRight'],
			  	name: "Reina",
			  	text: "At least I'm not draining my husband's wallet for body modifications. I'm 100% natural!",
				choiceNext: false,
			},
			"44": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Reina/Reina_casual_angry'],
				class: ['fadeLeft', null, null],
			  	name: "Hailey",
			  	text: "But you've got all the time in the world. Especially if neither your husband nor your kids are home. You don't work, and yet the money rolls in. That's the real luxury life.",
				choiceNext: false,
			},
			"45": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Reina/Reina_casual_angry'],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "What do you think, Tyler?",
				choiceNext: false,
			},
			"46": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Reina/Reina_casual_angry'],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "Ugh, not again! They're trying to drag me into a fight I have nothing to do with, but now I've gotta settle things between them. What on earth should I say?",
				choiceNext: true,
			},
			"47": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Reina/Reina_casual_angry'],
				class: [null, null, null],
                choicePath: 'reina~importants~0017-46',
			  	name: "Tyler",
			  	text: [
                    "I think Reina has more of a \"golden life.\" She has a husband, money, and doesn't have to work, at least not while her daughters are in school or daycare. Sure, she has work waiting at home, but overall, it seems like she has fewer worries in life than most people.",
                    "I think, Hailey, you're in an even luckier position than anyone else. Okay, you work a bit in a salon, that's true. But you make some money, and your partner makes a lot. After work, you have no other responsibilities—no housework, no kids to care for, no cooking for the family. You can do whatever you want and travel to exotic places often.",
                ],
				choiceNext: false,
			},
			"48": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Reina/Reina_casual_angry'],
				class: [[null, 'fadeLeft'], null, ['fadeRight', null]],
                choicePath: 'reina~importants~0017-46',
			  	name: ["Reina", "Hailey"],
			  	text: [
                    "Alright, Tyler. Just take over my place at home for one day, I'd love to see how you'd manage all these tasks and responsibilities!",
                    "Even if that's true, there's one thing you can't buy with money: love and genuine care from my partner. That's what really matters, and that's why I don't feel so lucky.",
                ],
				choiceNext: false,
			},
            "49": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Reina/Reina_casual_angry'],
				class: [['fadeLeft', null], null, [null, 'fadeRight']],
                choicePath: 'reina~importants~0017-46',
			  	name: ["Hailey", "Reina"],
			  	text: [
                    "Don't attack Tyler with that—attack me! He's a guy, he can't replace the mother of your daughters, but I could try. I'd like to be a mom one day, and I often bring it up to my partner. It's just up to him now when it'll happen. But I could prove to you that I can handle your daily routine!",
                    "Then, darling... you must be doing something very wrong. Maybe you're abusing your partner's money too much, and he's noticed and doesn't see you as anything more than a gold digger.",
                ],
				choiceNext: false,
			},
			"50": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Reina/Reina_casual_angry'],
				class: [[null, 'fadeLeft'], null, ['fadeRight', null]],
                choicePath: 'reina~importants~0017-46',
                name: ["Reina", "Hailey"],
			  	text: [
                    "I wouldn't be so sure, but you two probably know better than me... even though it's not your life.",
                    "No way, I always try to give him everything!",
                ],
				choiceNext: false,
			},
			"51": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Reina/Reina_casual_angry'],
				class: [[null, null], null, [null, 'fadeRight']],
                choicePath: 'reina~importants~0017-46',
                name: "Reina",
			  	text: [
                    "I have nothing more to say in this argument, so I'm going to head out. I've got a few errands to run before picking up my girls.",
                    "Sometimes, even when you give everything, they don't appreciate it... Anyway, I've gotta go, I've got some errands to run before picking up my girls.",
                ],
				choiceNext: false,
			},
            "52": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Reina/Reina_casual_angry'],
				class: [null, null, null],
                name: "Reina",
			  	text: "See you next time.",
				choiceNext: false,
			},
			"53": {
                bgMusic: {
					name: 'Girls_argument',
					command: 'FADE_OUT',
                    insideOfScene: true
				},
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Reina/Reina_casual_angry'],
				class: ['fadeLeftOut', null, 'fadeRightOut'],
                name: "",
			  	text: "Reina leaves the gym, but Hailey stays at the counter for a bit longer.",
				choiceNext: false,
			},
			"54": {
                bgMusic: {
					name: 'Sad_mood_wih_a_girl',
					command: 'START',
				},
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null,'Hailey/Hailey_casual_sad', null],
				class: [null, 'fadeUp', null],
                choicePath: 'reina~importants~0017-46',
                name: "Hailey",
			  	text: [
                    "Finally, she's gone and realized her place!",
                    "Glad she left, I was struggling to keep calm with all the stuff she was throwing at me.",
                ],
				choiceNext: false,
			},
			"55": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_sad', null],
				class: [null, null, null],
                name: "Tyler",
			  	text: "But are you okay?",
				choiceNext: false,
			},
			"56": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_smiling', null],
				class: [null, 'fadeUp', null],
                name: "Hailey",
			  	text: "Yeah, I'll survive. Oh, by the way, tomorrow's your day off, right?",
				choiceNext: false,
			},
			"57": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_smiling', null],
				class: [null, null, null],
                name: "Tyler",
			  	text: "Yeah, it is.",
				choiceNext: false,
			},
			"58": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_seductive', null],
				class: [null, 'fadeUp', null],
                name: "Hailey",
			  	text: "Great! So, how about we go for that massage program we talked about tomorrow?",
				choiceNext: false,
			},
			"59": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_seductive', null],
				class: [null, null, null],
                name: "Tyler",
			  	text: "Tomorrow? Uh… I don't know, I was kind of thinking about just chilling at home...",
				choiceNext: false,
			},
            "60": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_sad', null],
				class: [null, 'fadeUp', null],
                name: "Hailey",
			  	text: "Oh, come on, Tyler...",
				choiceNext: false,
			},
			"61": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_sad', null],
				class: [null, null, null],
                name: "",
                textClass: "italic",
			  	text: "What is this girl up to now?",
				choiceNext: false,
			},
            "62": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, 'fadeUp', null],
                name: "Hailey",
			  	text: "It's passive relaxation! No working out, no walking, no hiking… nothing. You just lie there while they give you a good massage. Isn't that relaxing enough for you?",
				choiceNext: false,
			},
            "63": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
                name: "Tyler",
			  	text: "W-Well… you've got a point.",
				choiceNext: false,
			},
			"64": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_smiling', null],
				class: [null, 'fadeUp', null],
                name: "Hailey",
			  	text: "See! So, how about a late afternoon appointment then?",
				choiceNext: false,
			},
			"65": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
                name: "Tyler",
			  	text: "I-I guess that could work.",
				choiceNext: false,
			},
            "66": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_grin', null],
				class: [null, 'fadeUp', null],
                name: "Hailey",
			  	text: "Perfect! It's settled then! I'll send you the exact place and time later. We're going to have so much fun, you'll see!",
				choiceNext: false,
			},
			"67": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_grin', null],
				class: [null, null, null],
                name: "Tyler",
			  	text: "I've been to massages before, so I have a good idea of what to expect.",
				choiceNext: false,
			},
			"68": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_seductive', null],
				class: [null, 'fadeUp', null],
                name: "Hailey",
			  	text: "Yeah? But the view this time will be something new for you.",
				choiceNext: false,
			},
			"69": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_seductive', null],
				class: [null, null, null],
                name: "Tyler",
			  	text: "View? What view? I'll have my face down, staring at the floor the whole time, what are you talking about?",
				choiceNext: false,
			},
			"70": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_seductive', null],
				class: [null, 'fadeUp', null],
                name: "Hailey",
			  	text: "Hehe! You'll see! I bet once you do, you won't be able to get it out of your head...",
				choiceNext: false,
			},
			"71": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_smiling', null],
				class: [null, 'fadeUp', null],
                name: "Hailey",
			  	text: "But I gotta go now, my clients will start coming into the salon soon!",
				choiceNext: false,
			},
			"72": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_smiling', null],
				class: [null, null, null],
                name: "Tyler",
			  	text: "O-Okay, go ahead. So, I guess I'll see you there tomorrow.",
				choiceNext: false,
			},
			"73": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_grin', null],
				class: [null, 'fadeUp', null],
                name: "Hailey",
			  	text: "Exactly! See you then, babe!",
				choiceNext: false,
			},
            "74": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_grin', null],
				class: [null, 'fadeUpOut', null],
                name: "",
                textClass: "italic",
			  	text: "Babe? Are we at that level now? And what was she talking about? What kind of view? Is she talking about the room decor? Maybe the place is super luxurious? I don't get it...",
				choiceNext: false,
			},
			"75": {
                bgMusic: {
					name: 'Sad_mood_wih_a_girl',
					command: 'FADE_OUT'
				},
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                name: "",
                textClass: "italic",
			  	text: "Well, everything will be clear tomorrow. For now, time to get back to work and finish up. Lots of clients are still waiting for me.",
				choiceNext: false,
				timeSkipNext: {
					content: "Later that afternoon...",
					nextSceneType: "STORY",
					nextSceneNumber: "0018",
				}
			},
		},
	},
];