export const scene_29 = [
    { sceneId: "0028" },
	{
		sceneId: "0029",
		lengthNum: 54,
		story: {
			"1": {
				bgMusic: {
					name: 'Meeting_with_Lindsay',
					command: 'START'
				},
                background: "backgrounds/BG_night_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "So, the night has finally come. When Lindsay and I broke up, I never thought I'd see her again, let alone have dinner with her. If she just wanted to apologize, she could've done it in a few words—there's no need for a whole dinner.",
				choiceNext: false,
            },
			"2": {
                background: "backgrounds/BG_night_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "So I'm sure there's more going on here, and that selfie she sent doesn't exactly reassure me that this is \"just dinner.\"",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_night_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'lindsay~mobileNotImportants~0026-l-6',
			  	name: "",
			  	text: [
                    "This dinner isn't exactly my dream evening, but if it means we can finally close a stormy chapter in our past, then it was worth coming here.",
                    "I really didn't want to come to this meeting, but she was so persistent that I had no choice but to say yes.",
                    "This dinner wasn't important enough for me even to remember it. But somehow, she managed to talk me into it."
                ],
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_night_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I hope I won't regret this...",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_restaurant_outside_night",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Anyway, here I am at the restaurant. Inside, I confirm the reservation name, and the waitstaff tells me Lindsay is already here and shows me to the table.",
				choiceNext: false,
			},
			"6": {
                bgMusic: {
					name: 'Meeting_with_Lindsay',
					command: 'FADE_OUT',
                    insideOfScene: true
				},
                background: "backgrounds/BG_restaurant_inside_night",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "The moment of truth has arrived, and we spot each other from across the room. I'll admit, she looks elegant and all, but I try to see through any games and figure out her real intentions.",
				choiceNext: false,
			},
			"7": {
                bgMusic: {
					name: 'In_restaurant_with_Lindsay',
					command: 'START'
				},
                specialSceneNow: true,
				specialSceneId: "0029-7",
				background: "special_scenes/0029-7",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "Hey, Tyler! I'm glad you came!",
				choiceNext: false,
            },
			"8": {
				background: "special_scenes/0029-7",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'lindsay~mobileNotImportants~0026-l-6',
			  	name: "Tyler",
			  	text: [
                    "It's the least I could do.",
                    "You didn't exactly leave me with much of a choice.",
                    "Yeah, I'm a bit surprised myself."
                ],
				choiceNext: false,
			},
			"9": {
				background: "special_scenes/0029-7",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'lindsay~mobileNotImportants~0026-l-6',
			  	name: "Lindsay",
			  	text: [
                    "That's kind of you.",
                    "Oh, please, don't start it.",
                    "Don't worry; it'll be fine, you'll see."
                ],
				choiceNext: false,
			},
			"10": {
				background: "special_scenes/0029-7",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "So, how have you been lately? Is work going well at the gym?",
				choiceNext: false,
			},
			"11": {
				background: "special_scenes/0029-7",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Lindsay... Considering we've known each other for quite some time, no matter how much you try to start this dinner off with niceties and chit-chat, I'm not going to buy into this idea that you invited me here just to apologize.",
				choiceNext: false,
			},
			"12": {
				background: "special_scenes/0029-7",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I'm sure you have some other agenda, so I'd appreciate it if we skipped the small talk and got straight to the point—just tell me why we're really here.",
				choiceNext: false,
			},
			"13": {
				background: "special_scenes/0029-7",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "I just wanted to have a nice evening and dinner... and talk through everything slowly.",
				choiceNext: false,
			},
			"14": {
				background: "special_scenes/0029-7",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "But since you've already ruined that idyllic idea of mine, fine. Let's get straight to the point.",
				choiceNext: false,
			},
			"15": {
				background: "special_scenes/0029-7",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Alright, let's hear it.",
				choiceNext: false,
			},
			"16": {
                specialSceneId: "0029-16",
				background: "special_scenes/0029-16",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "I'm sure if you look back on our time together, you could list plenty of things I did, or parts of my personality, that didn't exactly sit well with you. I mean, for example, my quick temper—where I'd say hurtful things, smash plates and glasses, or bombard you with calls and texts.",
				choiceNext: false,
			},
			"17": {
				background: "special_scenes/0029-16",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "The problem is that I'd get so carried away with my emotions, but looking back with a clear mind, I can see how awful my actions were toward you. I've come to realize that this is a major flaw of mine, and I've started working on it.",
				choiceNext: false,
			},
			"18": {
				background: "special_scenes/0029-16",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "I wanted to change, to become a better person, someone my partner could be proud of. In the future, I'd like to be a model wife and mother.",
				choiceNext: false,
			},
			"19": {
				background: "special_scenes/0029-16",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "And how's that going for you?",
				choiceNext: false,
			},
			"20": {
				background: "special_scenes/0029-16",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "Oh, I'm already ready. This self-reflection has been incredibly important. Seeing all my flaws in the mirror, I knew exactly what I needed to work on.",
				choiceNext: false,
			},
			"21": {
				background: "special_scenes/0029-16",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "I feel like I've really calmed down now, and I handle stressful situations with much more awareness. I've matured and grown up a lot through all of this.",
				choiceNext: false,
			},
			"22": {
				background: "special_scenes/0029-16",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Well, congratulations if that's how you feel. But the problem with that is, during our relationship, you often claimed that you were more mature and responsible than I was. If I ever pointed out a flaw of yours, you'd get angry first, and only make a change much later—only to find out that nothing had really changed.",
				choiceNext: false,
			},
            "23": {
                background: "special_scenes/0029-16",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Lindsay",
			  	text: "That's true, but it's been quite a while since our breakup, and these months were enough for me to make real changes—not like back then, when I'd only reflect on things after a few days.",
				choiceNext: false,
			},
			"24": {
                background: "special_scenes/0029-16",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Lindsay",
			  	text: "I'm not claiming to be perfect because I'll never be that, but the number of my flaws has been reduced to a minimum.",
				choiceNext: false,
			},
			"25": {
                background: "special_scenes/0029-16",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Tyler",
			  	text: "Alright, Lindsay, let's say I believe you. But what does that matter? Why are you telling me all this, and what are you expecting from me?",
				choiceNext: false,
            },
			"26": {
                bgMusic: {
					name: 'In_restaurant_with_Lindsay',
					command: 'STOP'
				},
                background: "special_scenes/0029-16",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Lindsay",
			  	text: "...",
				choiceNext: false,
            },
			"27": {
                bgMusic: {
					name: 'Mysterious',
					command: 'START'
				},
                background: "special_scenes/0029-16",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Lindsay",
			  	text: "That we should try again.",
				choiceNext: false,
			},
			"28": {
                background: "special_scenes/0029-16",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Tyler",
			  	text: "Excuse me? Sorry, I must be dreaming... Could you repeat that?",
				choiceNext: false,
			},
			"29": {
                background: "special_scenes/0029-16",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Lindsay",
			  	text: "I said, let's try again.",
				choiceNext: false,
			},
			"30": {
                background: "special_scenes/0029-16",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Tyler",
			  	text: "Aha... so I wasn't dreaming, then.",
				choiceNext: false,
			},
			"31": {
                background: "special_scenes/0029-16",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Tyler",
			  	text: "But damn, you just got married not too long ago! Don't you feel any shame, thinking about stepping out or walking away so soon?",
				choiceNext: false,
			},
			"32": {
                background: "special_scenes/0029-16",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Lindsay",
			  	text: "If you knew what I'm feeling right now, you'd explode from it.",
				choiceNext: false,
			},
			"33": {
                background: "special_scenes/0029-16",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Lindsay",
			  	text: "The truth is, there have only ever been two men in my life: my husband, and you.",
				choiceNext: false,
			},
			"34": {
                background: "special_scenes/0029-16",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Tyler",
			  	text: "Yeah, I know, you always bounced back and forth between us.",
				choiceNext: false,
			},
			"35": {
                background: "special_scenes/0029-16",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Lindsay",
			  	text: "Because I always used my husband as a kind of escape. At first, it was great to have him there, because it gave me a reason to break free from home, move to the city, and live an independent life away from my parents.",
				choiceNext: false,
			},
			"36": {
                background: "special_scenes/0029-16",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Lindsay",
			  	text: "Then, every time we argued or broke up, I only went back to him because... I needed someone with me. And I know that's not good, because it means I'm afraid of being alone.",
				choiceNext: false,
			},
			"37": {
                background: "special_scenes/0029-16",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Lindsay",
			  	text: "Or, I was afraid. I'm not anymore, because in this marriage, I've had to learn that being lonely is far worse than being alone.",
				choiceNext: false,
			},
			"38": {
                background: "special_scenes/0029-16",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Lindsay",
			  	text: "Yes, my husband was always there for me when things ended with you, but... that's all he could offer me—security. But he doesn't bring excitement, kindness, care, or love into my life. Well, he does, but nowhere near as much as I need.",
				choiceNext: false,
			},
			"39": {
                background: "special_scenes/0029-16",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Lindsay",
			  	text: "On the other hand, Tyler... you didn't represent a refuge for me, and I never went back to you because of that. It was because, willingly or not, you always managed to win me back with those vivid emotions that I miss in my husband.",
				choiceNext: false,
			},
			"40": {
                background: "special_scenes/0029-16",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Lindsay",
			  	text: "You're the one who brings out real feelings and attraction in me! And now, seeing all this clearly and recognizing my mistakes, I'm certain—you're the one I should've married!",
				choiceNext: false,
			},
			"41": {
                background: "special_scenes/0029-16",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Lindsay",
			  	text: "I made a bad, hasty decision. But now I know what I want, and who I long for in this life...",
				choiceNext: false,
			},
			"42": {
                background: "special_scenes/0029-16",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Lindsay",
			  	text: "It's you, Tyler. I want you; I want to build my life with you! I hope you'll give me a chance, so we can start over... this time, for life.",
				choiceNext: false,
			},
            "43": {
                background: "special_scenes/0029-16",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "",
                textClass: "italic",
			  	text: "Alright, now I know what this is about. The only question left is, do I want to try again with her?",
				choiceNext: true,
			},
			"44": {
                background: "special_scenes/0029-16",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                choicePath: 'lindsay~importants~0029-43',
                name: "Tyler",
			  	text: [
                    "Well... since we already have a past together, and it's not like we're starting from scratch... I guess, why not?",
                    "I'm sorry, Lindsay. But the past should stay in the past; let's not stir it up again."
                ],
				choiceNext: false,
			},
			"45": {
                bgMusic: {
					name: 'Mysterious',
					command: 'STOP'
				},
                specialSceneId: "0029-45",
                background: "special_scenes/0029-45",
                backGroundClass: "fadeIn",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                choicePath: 'lindsay~importants~0029-43',
                name: "Lindsay",
			  	text: [
                    "Sorry? Did I hear that right? You said yes?",
                    "What did you say?"
                ],
				choiceNext: false,
			},
			"46": {
                background: "special_scenes/0029-45",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                choicePath: 'lindsay~importants~0029-43',
                name: "Tyler",
			  	text: [
                    "Yes, you heard right.",
                    "If it were just one chance, I might still give it to you. But you've had many, and it always ended the same way, and I'm done playing this game with you. Enough is enough."
                ],
				choiceNext: false,
			},
			"47": {
                bgMusic: {
					name: ['In_restaurant_with_Lindsay', 'Under_pressure'],
					command: ['START', 'START']
				},
                background: ["special_scenes/0029-16", "special_scenes/0029-45"],
                backGroundClass: "fadeIn",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                choicePath: 'lindsay~importants~0029-43',
                name: "Lindsay",
			  	text: [
                    "This... this is wonderful! I was afraid you'd say no, but I can't even tell you how happy I am right now!",
                    "You can't be serious! It took me so long to pull myself together and find the courage and determination to lay everything out for you. I gave this long, emotional speech, and you just casually tell me, \"Sorry, but no\"?"
                ],
				choiceNext: false,
			},
			"48": {
                background: ["special_scenes/0029-16", "special_scenes/0029-45"],
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                choicePath: 'lindsay~importants~0029-43',
                name: "Tyler",
			  	text: [
                    "I hope that happiness lasts a long time for you.",
                    "Sorry, but it is what it is."
                ],
				choiceNext: false,
			},
			"49": {
                specialSceneId: ['0029-16', '0029-49'],
                background: ["special_scenes/0029-16", "special_scenes/0029-49"],
                backGroundClass: "fadeIn",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                choicePath: 'lindsay~importants~0029-43',
                name: "Lindsay",
			  	text: [
                    "I'm sure of it.",
                    "You're sorry my ass! I know you too well!"
                ],
				choiceNext: false,
			},
			"50": {
                specialSceneId: ['0029-50', '0029-49'],
                background: ["special_scenes/0029-50", "special_scenes/0029-49"],
                backGroundClass: "fadeIn",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                choicePath: 'lindsay~importants~0029-43',
                name: "Lindsay",
			  	text: [
                    "So... what would you say if we continued the evening at your place after dinner? After all, you said it yourself, we already know each other, so we can skip the typical getting-to-know-you stuff.",
                    "I'm so disappointed in you! I was hoping that after all this time, you'd have changed for the better too. But it seems you could use some serious self-reflection yourself because you're not exactly a dream guy either! You'll have to put in some work if you want a woman, because right now, I don't see a bright future ahead for you!"
                ],
				choiceNext: false,
			},
			"51": {
                background: ["special_scenes/0029-50", "special_scenes/0029-49"],
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                choicePath: 'lindsay~importants~0029-43',
                name: "Tyler",
			  	text: [
                    "True. And how could I say no to such an irresistible offer?",
                    "You don't have to worry about my future."
                ],
				choiceNext: false,
			},
			"52": {
                background: ["special_scenes/0029-50", "special_scenes/0029-49"],
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                choicePath: 'lindsay~importants~0029-43',
                name: "Lindsay",
			  	text: [
                    "See? I told you we'd have a great time if you came... hehe!",
                    "Fine, Tyler... I've had enough of this! Enjoy your fucking dinner, and don't ever want to see you again! I'll make your life hell, you bastard!"
                ],
				choiceNext: false,
			},
			"53": {
                specialSceneNow: true,
				specialSceneOut: true,
				specialSceneId: null,
				background: "backgrounds/BG_restaurant_inside_night",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                choicePath: 'lindsay~importants~0029-43',
                name: "",
			  	text: [
                    "After that, the dinner went very well. Lindsay and I quickly got back on the same wavelength, and we left the restaurant full and burning with passion.",
                    "Lindsay storms off from the table and out of the restaurant. It turns out what she said wasn't true, as her hot temper remains the same. Although it's good that I found it out, my wallet is the only one paying for this dinner..."
                ],
				choiceNext: false,
			},
			"54": {
                bgMusic: {
					name: ['In_restaurant_with_Lindsay', 'Under_pressure'],
					command: ['FADE_OUT', 'FADE_OUT']
				},
				background: "backgrounds/BG_restaurant_inside_night",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                choicePath: 'lindsay~importants~0029-43',
                name: "",
			  	text: "After an evening like this, all I can hope for is a better ending.",
				choiceNext: false,
				extraSceneNext: {
					choiceConditions: ['lindsay~importants~0029-43'],
					minGoodAnswer: 1,
					sceneSkipNumber: 1
				},
				endingNext: 'lindsay'
			},
		},
	},
];