export const scene_14 = [
    { sceneId: "0013" }, //storyScene: 0013
	{
		sceneId: "0014",
		lengthNum: 51,
		story: {
			"1": {
				bgMusic: {
					name: 'FittnessRoom_normal_daily',
					command: 'START'
				},
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "It's Monday again, the start of a new workweek. At least that's how most people see it after a relaxing weekend, but since I sometimes work on weekends, Mondays doesn't feel like such a burden to me.",
				choiceNext: false,
            },
			"2": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "However, I can see it on my clients—the Monday blues hit them hard. This morning, several of them are moving a bit sluggishly, but due to their work schedules, some have no choice but to come in this early.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Brianna is no exception. She barely made it to her morning workout on time, and I can see that empty look in her eyes—her body is awake, but mentally, she's still asleep.",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "On the other hand, Hailey's a different story. She's not at her peak either, but compared to the others, she's much more energetic. You can still tell she's out to crush it.",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "She's taking on slightly heavier weights than the others, and she's finishing her sets faster, eagerly waiting for the next challenge. But this is a group session, not personal training, so she has to wait for the others to catch up.",
				choiceNext: false,
			},
			"6": {
				background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "This is the first time Brianna and Hailey have ended up in the same class, seeing each other's performance for the first time. Brianna seems to be particularly affected by it.",
				choiceNext: false,
			},
			"7": {
				background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "It's as if Hailey's performance is either motivating or provoking Brianna, but it's definitely pushing her to step up her game too.",
				choiceNext: false,
			},
			"8": {
				background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Although she can't quite keep up with Hailey, she's definitely close, and it's clear that these two are leaving the rest of the group behind. By the end of the session, they're both drenched in sweat, and they're the last ones to leave the locker room after showering, handing in their locker keys.",
				choiceNext: false,
			},
			"9": {
				background: "backgrounds/BG_reception_sunny",
                backGroundClass: "fadeIn",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_smiling', null, 'Brianna/Brianna_casual_smiling'],
				class: ['fadeLeft', null, 'fadeRight'],
			  	name: "Hailey",
			  	text: "Here ya go, Tyler, my key.",
				choiceNext: false,
			},
			"10": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_smiling', null, 'Brianna/Brianna_casual_smiling'],
				class: [null, null, 'fadeRight'],
			  	name: "Brianna",
			  	text: "And mine, too.",
				choiceNext: false,
			},
			"11": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_smiling', null, 'Brianna/Brianna_casual_smiling'],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Thanks, girls. Here's your deposit back.",
				choiceNext: false,
			},
			"12": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_smiling', null, 'Brianna/Brianna_casual_smiling'],
				class: ['fadeLeft', null, null],
			  	name: "Hailey",
			  	text: "Thanks, and for the workout, too. That was so good!",
				choiceNext: false,
			},
			"13": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_smiling', null, 'Brianna/Brianna_casual_surprised'],
				class: [null, null, 'fadeRight'],
			  	name: "Brianna",
			  	text: "Really? That was brutal for me. I felt like I was about to cough up my soul!",
				choiceNext: false,
			},
			"14": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_smiling', null, 'Brianna/Brianna_casual_surprised'],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Brianna, I can be the toughest trainer out there, but it's all pointless if someone's just cruising through the workout... though, that's on them.",
				choiceNext: false,
			},
			"15": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_smiling', null, 'Brianna/Brianna_casual_surprised'],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "But if someone pushes hard, it's gonna feel tough. And that's how you grow. I've honestly never seen you go at it like this before, so it was great to see that side of you today.",
				choiceNext: false,
			},
			"16": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_grin', null, 'Brianna/Brianna_casual_surprised'],
				class: ['fadeLeft', null, null],
			  	name: "Hailey",
			  	text: "Totally! Tyler's right. For someone your age, you crushed it!",
				choiceNext: false,
			},
			"17": {
                bgMusic: {
					name: 'FittnessRoom_normal_daily',
					command: 'STOP'
				},
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_grin', null, 'Brianna/Brianna_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: "Brianna",
			  	text: "...!",
				choiceNext: false,
			},
			"18": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_grin', null, 'Brianna/Brianna_casual_normal'],
				class: [null, null, null],
			  	name: "",
                textClass: 'italic',
			  	text: "Oh crap...",
				choiceNext: false,
			},
			"19": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_grin', null, 'Brianna/Brianna_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: "Brianna",
			  	text: "Excuse me? Would you mind repeating what you just said?",
				choiceNext: false,
			},
			"20": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_normal', null, 'Brianna/Brianna_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Hailey",
			  	text: "What? That, despite your age...",
				choiceNext: false,
			},
			"21": {
                bgMusic: {
					name: 'Girls_argument',
					command: 'START'
				},
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_normal', null, 'Brianna/Brianna_casual_angry'],
				class: [null, null, 'fadeRight'],
			  	name: "Brianna",
			  	text: "What do you mean, \"despite my age\"?! Do you even know how old I am?",
				choiceNext: false,
			},
			"22": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_scared', null, 'Brianna/Brianna_casual_angry'],
				class: ['fadeLeft', null, null],
			  	name: "Hailey",
			  	text: "No idea, but you're definitely older than me, that's a fact! So, like, why are you freaking out?",
				choiceNext: false,
			},
			"23": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_scared', null, 'Brianna/Brianna_casual_angry'],
				class: [null, null, 'fadeRight'],
			  	name: "Brianna",
			  	text: "First off, you should respect your elders, and I can bet I'm almost two decades older than you!",
				choiceNext: false,
			},
			"24": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_scared', null, 'Brianna/Brianna_casual_angry'],
				class: ['fadeLeft', null, null],
				name: "Hailey",
				text: "Girl, it was just a compliment! Why are you getting so worked up?",
				choiceNext: false,
			},
			"25": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_scared', null, 'Brianna/Brianna_casual_angry'],
				class: [null, null, 'fadeRight'],
			  	name: "Brianna",
                text: "Oh, you'll get it one day—when people start calling you old. Trust me, it's coming sooner than you think, especially for you. With your over-tanned skin, all those blinged-out body piercings… and I'd bet money your boobs aren't even real. In a few years, you'll regret all the stuff you did to your body just because it seemed like a good idea at the time!",
                choiceNext: false,
            },
			"26": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Brianna/Brianna_casual_angry'],
				class: ['fadeLeft', null, null],
			  	name: "Hailey",
			  	text: "Well, my boyfriend likes it, so, sorry not sorry! I respect that maybe your husband loves you natural or whatever.",
				choiceNext: false,
			},
			"27": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Brianna/Brianna_casual_angry'],
				class: [null, null, 'fadeRight'],
			  	name: "Lindsay",
			  	text: "I don't have a husband, I'm divorced.",
				choiceNext: false,
			},
			"28": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Brianna/Brianna_casual_angry'],
				class: ['fadeLeft', null, null],
			  	name: "Hailey",
			  	text: "Oh... my bad. Well, at least I've got someone who loves me for who I am. It's not my fault you couldn't keep a man for life!",
				choiceNext: false,
			},
			"29": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Brianna/Brianna_casual_angry'],
				class: [null, null, 'fadeRight'],
			  	name: "Brianna",
			  	text: "Please. If you've changed this much for your man, he doesn't love you for who you are. And if you haven't even been married, you're the last person I'd take advice from on how to be a good wife or find a decent husband!",
				choiceNext: false,
			},
			"30": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Brianna/Brianna_casual_angry'],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "You have no clue what price I've had to pay after marrying the wrong guy! Raising three kids as a single mom… and the struggles don't end until they're out of the house. You don't know how hard it is to do it all alone while still having to work to make ends meet!",
				choiceNext: false,
			},
			"31": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Brianna/Brianna_casual_angry'],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "I'd love to see you in 15-20 years, in the same situation, and how you would look, how you'd handle it, and where you'd be. It's not easy staying put-together and fit under those circumstances!",
				choiceNext: false,
			},
			"32": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Brianna/Brianna_casual_angry'],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "But when I look at you, all I see is someone who's had everything handed to her on a silver platter, living it up on someone else's dime!",
				choiceNext: false,
			},
			"33": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Brianna/Brianna_casual_angry'],
				class: ['fadeLeft', null, null],
			  	name: "Hailey",
			  	text: "Look, I get that doing all that by yourself sucks, but just 'cause life dealt you that hand (which, by the way, has nothing to do with me), doesn't mean you get to take out all your pent-up frustrations on me!",
				choiceNext: false,
			},
			"34": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Brianna/Brianna_casual_angry'],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "Or are you low-key jealous that I've had more opportunities than you did?",
				choiceNext: false,
			},
			"35": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Brianna/Brianna_casual_angry'],
				class: [null, null, 'fadeRight'],
			  	name: "Brianna",
			  	text: "Jealous? Not a chance! I'd rather work for everything I have!",
				choiceNext: false,
			},
			"36": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Brianna/Brianna_casual_angry'],
				class: ['fadeLeft', null, null],
			  	name: "Hailey",
			  	text: "Well, I'm not ashamed to lean on others if it means I get to live my best life. I'll at least have cool stories to tell my kids, unlike you!",
				choiceNext: false,
			},
			"37": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Brianna/Brianna_casual_angry'],
				class: [null, null, 'fadeRight'],
			  	name: "Brianna",
			  	text: "Yeah, well, my kids will grow up knowing that hard work gets you far, not that freeloading off others is the best way to live!",
				choiceNext: false,
			},
			"38": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Brianna/Brianna_casual_angry'],
				class: [null, null, null],
			  	name: "",
                textClass: 'italic',
			  	text: "This is spiraling out of control. What started as a casual remark has turned into something much bigger. They're ripping into each other for completely different reasons now. I need to step in, fast.",
				choiceNext: true,
			},
			"39": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Brianna/Brianna_casual_angry'],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Alright, girls, that's enough!",
				choiceNext: false,
			},
			"40": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, 'Brianna/Brianna_casual_angry'],
				class: [null, null, null],
                choicePath: 'brianna~importants~0014-38',
			  	name: "Tyler",
			  	text: [
                    "Brianna, come on! Hailey probably didn't mean to call you old, don't get so worked up over it!",
                    "Hailey, maybe you should think before you speak, or at least hear yourself sometimes!",
                    "This isn't the place for this argument. If you two wanna sort things out, do it outside!"
                ],
				choiceNext: false,
			},
			"41": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_angry', null, ['Brianna/Brianna_casual_angry', 'Brianna/Brianna_casual_angry', 'Brianna/Brianna_casual_sad']],
				class: [['fadeLeft', null, null], null, [null, 'fadeRight', 'fadeRight']],
                choicePath: 'brianna~importants~0014-38',
			  	name: ["Hailey", "Brianna", "Brianna"],
			  	text: [
                    "Yeah, like I said, it was a compliment! Don't get all mad just 'cause you don't like your age!",
                    "Exactly. Words can hurt too, just like piercings on your ear, nose, or belly.",
                    "Wow, Tyler, seriously? I thought you'd have my back here instead of calling us both out and sending us away!"
                ],
				choiceNext: false,
			},
			"42": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: [['Hailey/Hailey_casual_angry', 'Hailey/Hailey_casual_sad', 'Hailey/Hailey_casual_sad'], null, ['Brianna/Brianna_casual_angry', 'Brianna/Brianna_casual_angry', 'Brianna/Brianna_casual_sad']],
				class: [[null, 'fadeLeft', 'fadeLeft'], null, ['fadeRight', null, null, ]],
                choicePath: 'brianna~importants~0014-38',
			  	name: ["Brianna", "Hailey", "Hailey"],
			  	text: [
                    "It's not about that… it's about rubbing it in my face when I'm already feeling bad enough!",
                    "So, you're siding with her, Tyler. I expected better, thought you'd stick up for me at least…",
                    "Or my back!"
                ],
				choiceNext: false,
			},
			"43": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: [['Hailey/Hailey_casual_angry', 'Hailey/Hailey_casual_sad', 'Hailey/Hailey_casual_sad'], null, ['Brianna/Brianna_casual_angry', 'Brianna/Brianna_casual_angry', 'Brianna/Brianna_casual_sad']],
				class: [['fadeLeft', null, null], null, [null, null, null, ]],
                choicePath: 'brianna~importants~0014-38',
			  	name: ["Hailey", "Tyler", "Tyler"],
			  	text: [
                    "Not my fault if the truth stings a little.",
                    "Sorry, Hailey, but when I see both sides of this argument, that's my stance.",
                    "Sorry, girls, but this started over something small and now you're going too far, and it's not cool in a gym. Take this outside if you wanna keep going."
                ],
				choiceNext: false,
			},
			"44": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: [['Hailey/Hailey_casual_angry', 'Hailey/Hailey_casual_angry', 'Hailey/Hailey_casual_sad'], null, ['Brianna/Brianna_casual_angry', 'Brianna/Brianna_casual_angry', 'Brianna/Brianna_casual_angry']],
				class: [[null, 'fadeLeft', null], null, ['fadeRight', null, 'fadeRight']],
                choicePath: 'brianna~importants~0014-38',
			  	name: ["Brianna", "Hailey", "Brianna"],
			  	text: [
                    "Whatever, I don't need this. I gotta go anyway, work's waiting. Bye.",
                    "Wow, this sucks… Well, if you're not backing me up, I'm out. Got clients waiting at the salon. Later.",
                    "That wasn't fair."
                ],
				choiceNext: false,
			},
			"45": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: [['Hailey/Hailey_casual_angry', 'Hailey/Hailey_casual_angry', 'Hailey/Hailey_casual_angry'], null, ['Brianna/Brianna_casual_angry', 'Brianna/Brianna_casual_angry', 'Brianna/Brianna_casual_angry']],
				class: [['fadeLeft', null, 'fadeLeft'], null, [null, 'fadeRight', null]],
                choicePath: 'brianna~importants~0014-38',
			  	name: ["Hailey", "Brianna", "Hailey"],
			  	text: [
                    "Bye-bye!",
                    "Good riddance.",
                    "You're unbelievable."
                ],
				choiceNext: false,
			},
			"46": {
                bgMusic: {
					name: 'Girls_argument',
					command: 'FADE_OUT',
                    insideOfScene: true
				},
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: [['Hailey/Hailey_casual_angry', 'Hailey/Hailey_casual_angry', 'Hailey/Hailey_casual_angry'], null, ['Brianna/Brianna_casual_angry', 'Brianna/Brianna_casual_angry', 'Brianna/Brianna_casual_angry']],
				class: [['fadeLeftOut', 'fadeLeftOut', 'fadeLeftOut'], null, ['fadeRightOut', 'fadeRightOut', 'fadeRightOut']],
                choicePath: 'brianna~importants~0014-38',
			  	name: ["", "", ""],
			  	text: [
                    "And with that, Brianna leaves the gym.",
                    "And with that, Hailey leaves the gym.",
                    "And with that, both of them leave the gym."
                ],
				choiceNext: false,
			},
			"47": {
                bgMusic: {
					name: 'Left_alone',
					command: 'START'
				},
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, ['char-middle', 'char-middle', null], null],
				image: [null, ['Hailey/Hailey_casual_normal', 'Brianna/Brianna_casual_normal', null], null],
				class: [null, ['fadeUp', 'fadeUp', null], null],
                choicePath: 'brianna~importants~0014-38',
			  	name: ["Tyler", "Tyler", ""],
                textClass: [null, null, 'italic'],
			  	text: [
                    "Look, Hailey, you weren't totally innocent either. But between the two of you, I'm siding with you.",
                    "Look, Brianna, you weren't totally innocent either. But between the two of you, I'm siding with you.",
                    "And now I'm left standing here alone. This ain't my problem—I've got no place to get involved in beauty routines, marriage, or motherhood. Not my business, and the other clients don't need to hear this."
                ],
				choiceNext: false,
			},
			"48": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, ['char-middle', 'char-middle', null], null],
				image: [null, ['Hailey/Hailey_casual_normal', 'Brianna/Brianna_casual_normal', null], null],
				class: [null, ['fadeUp', 'fadeUp', null], null],
                choicePath: 'brianna~importants~0014-38',
			  	name: ["Hailey", "Brianna", ""],
                textClass: [null, null, 'italic'],
			  	text: [
                    "Yeah, I get it. I'll try to be more considerate next time, but the way she clapped back? No way I was lettin' that slide.",
                    "Maybe you're right, 'cause you're seein' this more objectively than me or her. But she opened old wounds, and I had to put her in her place.",
                    "I'm not their mom, their dad, or a cop to break 'em up. I'm just a trainer here, and if there's a fight, I'm the one who gets in trouble for it."
                ],
				choiceNext: false,
			},
            "49": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, ['char-middle', 'char-middle', null], null],
				image: [null, ['Hailey/Hailey_casual_normal', 'Brianna/Brianna_casual_normal', null], null],
				class: [null, [null, null, null], null],
                choicePath: 'brianna~importants~0014-38',
			  	name: ["Tyler", "Tyler", ""],
                textClass: [null, null, 'italic'],
			  	text: [
                    "I heard that, but just try to be a little more careful next time, okay?",
                    "I heard that, but just try to be a little more careful next time, okay?",
                    "Maybe they dont like it, but I need my job, so this has gotta stop."
                ],
				choiceNext: false,
			},
			"50": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, ['char-middle', 'char-middle', null], null],
				image: [null, ['Hailey/Hailey_casual_smiling', 'Brianna/Brianna_casual_smiling', null], null],
				class: [null, ['fadeUp', 'fadeUp', null], null],
                choicePath: 'brianna~importants~0014-38',
			  	name: ["Hailey", "Brianna", ""],
                textClass: [null, null, 'italic'],
			  	text: [
                    "Okay, I'll try. But if you don't mind, I gotta jet—clients are waitin' at the salon. We'll chat later!",
                    "Okay, I'll try. But if you don't mind, I gotta run—work's callin'. Catch you later!",
                    "Hope they cool off soon, even if they don't make up."
                ],
				choiceNext: false,
			},
			"51": {
                bgMusic: {
					name: 'Left_alone',
					command: 'FADE_OUT'
				},
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, ['char-middle', 'char-middle', null], null],
				image: [null, ['Hailey/Hailey_casual_smiling', 'Brianna/Brianna_casual_smiling', null], null],
				class: [null, [null, null, null], null],
                choicePath: 'brianna~importants~0014-38',
			  	name: ["Tyler", "Tyler", "Tyler"],
			  	text: [
                    "Sure thing!",
                    "Sure thing!",
                    "Well, that's that. Back to work."
                ],
				choiceNext: false,
			}
		},
	},
];