export const scene_34 = [
    { sceneId: "0033" },
	{
		sceneId: "0034",
		lengthNum: 73,
		story: {
			"1": {
				bgMusic: {
					name: 'Left_alone',
					command: 'START'
				},
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "The past week has been... intense, to say the least, especially when it comes to my love life.",
				choiceNext: false,
            },
 			"2": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Becoming a trainer was never about meeting girls at work—especially at a place that has strict no-dating rules. But a few months back, something started with Reina, and now, just over the past week, things have suddenly heated up with three other clients.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "As for Lindsay... well, let's not even go there.",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Never thought I'd turn into a Casanova, and honestly, it's starting to feel like I'm taking on way more than I can handle. I need to get it all off my chest, talk to someone who'll give it to me straight.",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_coffeshop_outside2_sunny",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "That's where my friends come in—the ones I trust unconditionally, who I can tell anything to.",
				choiceNext: false,
			},
			"6": {
                background: "backgrounds/BG_coffeshop_outside2_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "If I'm in trouble, they've got my back; if I mess up, they call me out with no hesitation. That's how I know our friendship's solid—it's all about honesty, no strings attached.",
				choiceNext: false,
			},
			"7": {
                background: "backgrounds/BG_coffeshop_outside2_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "So, I asked them—Don and Sam—to meet up later this afternoon at a café so I could lay it all out and hear what they think. I'm the last to show up, and they're already settled at a table.",
				choiceNext: false,
            },
			"8": {
                background: "backgrounds/BG_coffeshop_inside_sunny",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Hey, guys!",
				choiceNext: false,
			},
			"9": {
                background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_grin', null, 'Samantha/Samantha_casual_smiling'],
				class: ['fadeLeft', null, 'fadeRight'],
			  	name: "Donald",
			  	text: "Yo, Tyler! What's up, man? Feels like it's been ages!",
				choiceNext: false,
			},
			"10": {
                background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_grin', null, 'Samantha/Samantha_casual_smiling'],
				class: [null, null, 'fadeRight'],
			  	name: "Samantha",
			  	text: "Hey, Tyler, everything alright?",
				choiceNext: false,
			},
			"11": {
                background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_grin', null, 'Samantha/Samantha_casual_smiling'],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Yeah, you guys already know the gist of it, but I could use a fresh perspective on all this.",
				choiceNext: false,
			},
			"12": {
                background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_grin', null, 'Samantha/Samantha_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: "Samantha",
			  	text: "You mean your secret relationship with Reina?",
				choiceNext: false,
			},
			"13": {
                background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_grin', null, 'Samantha/Samantha_casual_normal'],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Yeah, but...",
				choiceNext: false,
			},
			"14": {
                background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_grin', null, 'Samantha/Samantha_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Donald",
			  	text: "Dude, I was just messin' around calling you \"milf hunter\" back at the start—but I never thought this fling of yours would last this long.",
				choiceNext: false,
			},
			"15": {
                background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_grin', null, 'Samantha/Samantha_casual_normal'],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Well, it has, and it's actually starting to get serious.",
				choiceNext: false,
			},
			"16": {
                background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_surprised', null, 'Samantha/Samantha_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Donald",
			  	text: "No way! You're messin' with us, right?",
				choiceNext: false,
			},
			"17": {
                bgMusic: {
					name: 'Under_pressure',
					command: 'START'
				},
                otherSoundEffect: "hitTheTable",
                specialSceneNow: true,
				specialSceneId: '0034-17',
				background: "special_scenes/0034-17",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_surprised', null, 'Samantha/Samantha_casual_normal'],
				class: ['fadeLeftOut', null, 'fadeRightOut'],
			  	name: "Samantha",
			  	text: "Tyler... seriously? You really feel like she's the one you'd want to spend the rest of your life with? Even with that more than a decade's age difference?",
				choiceNext: false,
			},
			"18": {
				background: "special_scenes/0034-17",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Age is just a number...",
				choiceNext: false,
			},
			"19": {
				background: "special_scenes/0034-17",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Samantha",
			  	text: "This isn't just about age, Tyler. It's about your future!",
				choiceNext: false,
			},
			"20": {
				background: "special_scenes/0034-17",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Donald",
			  	text: "Hey, Sam! Ease up a bit.",
				choiceNext: false,
			},
			"21": {
				background: "special_scenes/0034-17",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Samantha",
			  	text: "She's at least ten years older; a full-time mom; and married! Every morning, she wakes up next to someone else, who's not you! She makes him breakfast, lunch, or dinner, not you! She's raising his kids, not yours! She tells him “I love you” multiple times a day, not you! And then there's...",
				choiceNext: false,
			},
			"22": {
				background: "special_scenes/0034-17",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Donald",
			  	text: "Hold up, man! She's really never told you she loves you? Or, aside from that surprise kiss, has there even been anything more between you two?",
				choiceNext: false,
			},
            "23": {
				background: "special_scenes/0034-17",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "No... not... not yet, at least.",
				choiceNext: false,
			},
			"24": {
				background: "special_scenes/0034-17",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Donald",
			  	text: "Oh, dude!",
				choiceNext: false,
			},
			"25": {
				background: "special_scenes/0034-17",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Samantha",
			  	text: "See? That's exactly what I'm talking about! This thing's been going on for months, it's taken up so much of your time, and what have you gotten out of it? Is it really worth it?",
				choiceNext: false,
            },
			"26": {
				background: "special_scenes/0034-17",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Samantha",
			  	text: "I get it, Tyler, you see something in her that maybe Don and I, as outsiders, don't. But I don't see this turning into a stable, healthy relationship for you in the long run! I just don't want you getting too invested, only to end up heartbroken.",
				choiceNext: false,
            },
			"27": {
				background: "special_scenes/0034-17",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I know, Sam! I know... If it were that simple, I wouldn't be wrestling with this or even asking for your advice. But like you said, there's something here, something you two might not see yet. That's what I want to explain, so you can understand where I'm coming from.",
				choiceNext: false,
			},
			"28": {
				background: "special_scenes/0034-17",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Donald",
			  	text: "Then lay it out! I've never been anyone's secret lover, so I have no clue what that's like.",
				choiceNext: false,
			},
			"29": {
				background: "special_scenes/0034-17",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Samantha",
			  	text: "Neither do I. But I also can't imagine doing that to my partner—or my future husband. So I'm really curious to hear why we shouldn't judge her for making you her side piece, when you can only be with her within such strict limits.",
				choiceNext: false,
			},
			"30": {
                bgMusic: {
					name: 'Left_alone',
					command: 'START'
				},
                specialSceneNow: true,
				specialSceneOut: true,
				specialSceneId: null,
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_normal', null, 'Samantha/Samantha_casual_normal'],
				class: ['fadeLeft', null, 'fadeRight'],
			  	name: "Tyler",
			  	text: "We'll get to that, but... there's something else I need to tell you both.",
				choiceNext: false,
			},
			"31": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_surprised', null, 'Samantha/Samantha_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Donald",
			  	text: "Oh, no, man. Don't tell me she's already pregnant with your kid!",
				choiceNext: false,
			},
			"32": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_normal', null, 'Samantha/Samantha_casual_angry'],
				class: [null, null, 'fadeRight'],
			  	name: "Samantha",
			  	text: "Don, he just said they're not there yet!",
				choiceNext: false,
			},
			"33": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_grin', null, 'Samantha/Samantha_casual_angry'],
				class: ['fadeLeft', null, null],
			  	name: "Donald",
			  	text: "Oh, right. Fair point. So... what's this about?",
				choiceNext: false,
			},
			"34": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_grin', null, 'Samantha/Samantha_casual_angry'],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Well, uh... she's not the only one I might consider a potential partner.",
				choiceNext: false,
			},
			"35": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_grin', null, 'Samantha/Samantha_casual_smiling'],
				class: [null, null, 'fadeRight'],
			  	name: "Samantha",
			  	text: "Really? So, who's this other girl?.",
				choiceNext: false,
			},
			"36": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_grin', null, 'Samantha/Samantha_casual_smiling'],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "-s...",
				choiceNext: false,
			},
			"37": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_grin', null, 'Samantha/Samantha_casual_surprised'],
				class: [null, null, 'fadeRight'],
			  	name: "Samantha",
			  	text: "Excuse me?",
				choiceNext: false,
			},
			"38": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_grin', null, 'Samantha/Samantha_casual_surprised'],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "There's more than one.",
				choiceNext: false,
			},
			"39": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_surprised', null, 'Samantha/Samantha_casual_surprised'],
				class: ['fadeLeft', null, null],
			  	name: "Donald",
			  	text: "Whaaaaaat?!",
				choiceNext: false,
			},
			"40": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_surprised', null, 'Samantha/Samantha_casual_surprised'],
				class: ['fadeLeftOut', null, 'fadeRightOut'],
			  	name: "",
			  	text: "It takes me almost an hour to explain everything about each one of them, making sure they understand the whole situation. Naturally, Reina's story took up the most time.",
				choiceNext: false,
			},
			"41": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Sometimes they ask questions, but mostly they sit there quietly, absorbing the tidal wave of information I'm unleashing. By the end, they seem a bit exhausted, understandably.",
				choiceNext: false,
			},
			"42": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_normal', null, 'Samantha/Samantha_casual_normal'],
				class: ['fadeLeft', null, 'fadeRight'],
			  	name: "Samantha",
			  	text: "Alright... that was a lot to take in all at once, but I think I have a better grasp of your situation now.",
				choiceNext: false,
			},
			"43": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_sad', null, 'Samantha/Samantha_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Samantha",
			  	text: "Yeah, man, you're going through a lot. No wonder you reached out for help—it's gotta be rough carrying all this on your own.",
				choiceNext: false,
			},
            "44": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_sad', null, 'Samantha/Samantha_casual_normal'],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "It is. Even just getting it off my chest helped, but I'd really appreciate your advice.",
				choiceNext: false,
			},
			"45": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_smiling', null, 'Samantha/Samantha_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Donald",
			  	text: "As a guy, I gotta say I'm impressed by how many doors seem to be open for you. And yeah, maybe a little jealous, considering you've basically got a harem now.",
				choiceNext: false,
			},
			"46": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_sad', null, 'Samantha/Samantha_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Donald",
			  	text: "But it's gotta be a pain juggling your schedule to avoid clashes between them, and that you and Reina have to keep it so undercover.",
				choiceNext: false,
            },
			"47": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_sad', null, 'Samantha/Samantha_casual_sad'],
				class: [null, null, 'fadeRight'],
			  	name: "Samantha",
			  	text: "From a woman's perspective, I'd be hurt if I found out my partner was keeping other people in the wings. And I still can't approve of Reina's choice to keep a lover while being a wife and mother.",
				choiceNext: false,
			},
			"48": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_sad', null, 'Samantha/Samantha_casual_sad'],
				class: [null, null, null],
			  	name: "Samantha",
			  	text: "You need to decide soon who you truly want to be with, because this constant hiding and organizing your days around avoiding them is exhausting!",
				choiceNext: false,
			},
			"49": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_sad', null, 'Samantha/Samantha_casual_sad'],
				class: [null, null, null],
			  	name: "Samantha",
			  	text: "If you want to stay with Reina, then she needs to decide soon how she wants to live her life, because things can't stay like this forever! She can't keep you in a holding pattern forever; it would deny you the chance to live a full and happy life with someone.",
				choiceNext: false,
			},
			"50": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_sad', null, 'Samantha/Samantha_casual_sad'],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I know, I know.",
				choiceNext: false,
			},
			"51": {
                bgMusic: {
					name: 'Mobile_night_trouble',
					command: 'START',
				},
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_normal', null, 'Samantha/Samantha_casual_sad'],
				class: ['fadeLeft', null, null],
			  	name: "Donald",
			  	text: "Alright, Tyler, keep it real: do you prefer younger or older women?",
				choiceNext: true,
			},
			"52": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_normal', null, 'Samantha/Samantha_casual_sad'],
				class: [null, null, null],
                choicePath: 'friends~notImportants~0034-51',
			  	name: "Tyler",
			  	text: [
                    "The younger crowd, including women my age.",
                    "I find I connect better with the older crowd somehow."
                ],
				choiceNext: false,
			},
			"53": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_normal', null, 'Samantha/Samantha_casual_sad'],
				class: ['fadeLeft', null, null],
			  	name: "Donald",
			  	text: "Alright, so how much does it matter to you that the one you choose is physically at her best?",
				choiceNext: true,
			},
            "54": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_normal', null, 'Samantha/Samantha_casual_sad'],
				class: [null, null, null],
                choicePath: 'friends~notImportants~0034-53',
			  	name: "Tyler",
			  	text: [
                    "I'm a trainer, so I'm definitely into sporty women. Plus, if she works out with me, it would be great if she'd listen to my advice—it'd only benefit her.",
                    "Just because I'm a trainer doesn't mean I'm only looking for a fitness model. I'm open to different body types in a partner."
                ],
				choiceNext: false,
			},
            "55": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_normal', null, 'Samantha/Samantha_casual_sad'],
				class: ['fadeLeft', null, null],
			  	name: "Donald",
			  	text: "Yeah, I can see some truth in that.",
				choiceNext: false,
			},
            "56": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_normal', null, 'Samantha/Samantha_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: "Samatha",
			  	text: "And do you think you could support your partner from a coaching salary, or would you rather he contribute to the common wealth?",
				choiceNext: true,
			},
            "57": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_normal', null, 'Samantha/Samantha_casual_normal'],
				class: [null, null, null],
                choicePath: 'friends~notImportants~0034-56',
			  	name: "Tyler",
			  	text: [
                    "I'd definitely have to make some big changes in my life, but I think I could manage. Who knows—I might not stay a trainer forever.",
                    "I couldn't do it alone, especially if kids are already or will be in the picture."
                ],
				choiceNext: false,
			},
            "58": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_normal', null, 'Samantha/Samantha_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: "Samantha",
			  	text: "I agree. So, are you okay with your partner being in another relationship, or not?",
				choiceNext: true,
			},
            "59": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_normal', null, 'Samantha/Samantha_casual_normal'],
				class: [null, null, null],
                choicePath: 'friends~notImportants~0034-58',
			  	name: "Tyler",
			  	text: [
                    "I can hang on a bit longer. In the end, it'll feel worth it, knowing I was enough for her to leave someone else for me.",
                    "No, it would be better if we didn't have to hide anything from anyone and could make it official as soon as possible."
                ],
				choiceNext: false,
			},
            "60": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_smiling', null, 'Samantha/Samantha_casual_normal'],
				class: ["fadeLeft", null, null],
			  	name: "Donald",
			  	text: "Alright, I think this all gives a pretty good picture of who you'd rather be with—without saying it outright, anyway.",
				choiceNext: false,
			},
            "61": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_smiling', null, 'Samantha/Samantha_casual_normal'],
				class: [null, null, "fadeRight"],
			  	name: "Samantha",
			  	text: "But you're not getting away that easily. So, who's it gonna be out of the four?",
				choiceNext: true,
			},
            "62": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_smiling', null, 'Samantha/Samantha_casual_normal'],
				class: [null, null, null],
                choicePath: 'friends~notImportants~0034-61',
			  	name: "Tyler",
			  	text: [
                    "I'd rather be with Reina.",
                    "I'd rather be with Brianna.",
                    "I'd rather be with Hailey.",
                    "I'd rather be with Daena.",
                ],
				choiceNext: false,
			},
            "63": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_smiling', null, 'Samantha/Samantha_casual_normal'],
				class: [null, null, "fadeRight"],
			  	name: "Samantha",
			  	text: "I see... Well, I really hope she's the one you truly want, and I wish for you that your dream comes true!",
				choiceNext: false,
			},
            "64": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_smiling', null, 'Samantha/Samantha_casual_normal'],
				class: ["fadeLeft", null, null],
			  	name: "Donald",
			  	text: "Look, I know it won't be easy, but if you're serious about building a life with her, you're gonna have to let go of the others.",
				choiceNext: false,
			},
            "65": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_smiling', null, 'Samantha/Samantha_casual_normal'],
                class: [null, null, "fadeRight"],
			  	name: "Samatha",
			  	text: "Yeah, don't become one of those who cheats on their partner! It's unfair, it's wrong!",
				choiceNext: false,
			},
            "66": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_normal', null, 'Samantha/Samantha_casual_normal'],
                class: ["fadeLeft", null, null],
			  	name: "Donald",
			  	text: "And honestly, if you did, we probably wouldn't want to give you any advice because we don't support that!",
				choiceNext: false,
			},
            "67": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_normal', null, 'Samantha/Samantha_casual_normal'],
                class: [null, null, "fadeRight"],
			  	name: "Samatha",
			  	text: "Exactly.",
				choiceNext: false,
			},
            "68": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_normal', null, 'Samantha/Samantha_casual_normal'],
                class: [null, null, null],
			  	name: "Tyler",
			  	text: "Understood. Anyway, thanks for listening and giving me your honest thoughts.",
				choiceNext: false,
			},
            "69": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_normal', null, 'Samantha/Samantha_casual_normal'],
                class: ["fadeLeft", null, null],
			  	name: "Donald",
			  	text: "Anytime, man. Just don't let this wreck you or change who you are. No relationship is worth losing yourself or becoming someone you're not.",
				choiceNext: false,
			},
            "70": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_normal', null, 'Samantha/Samantha_casual_normal'],
                class: [null, null, null],
			  	name: "Tyler",
			  	text: "I'll keep that in mind.",
				choiceNext: false,
			},
            "71": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_normal', null, 'Samantha/Samantha_casual_normal'],
                class: [null, null, null],
			  	name: "Tyler",
			  	text: "Thanks again. I'll catch up with you guys soon.",
				choiceNext: false,
			},
            "72": {
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_normal', null, 'Samantha/Samantha_casual_smiling'],
                class: [null, null, "fadeRight"],
			  	name: "Samantha",
			  	text: "Keep us posted on how it all turns out. Good luck!",
				choiceNext: false,
			},
            "73": {
				bgMusic: {
					name: 'Mobile_night_trouble',
					command: 'FADE_OUT',
				},
				background: "backgrounds/BG_coffeshop_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Donald/Donald_casual_normal', null, 'Samantha/Samantha_casual_smiling'],
                class: [null, null, null],
			  	name: "Tyler",
			  	text: "Thanks, take care!",
				choiceNext: false,
                timeSkipNext: {
					content: "Later that evening...",
					nextSceneType: "MOBILE",
					nextSceneNumber: "0035",
				}
			},
		},
	},
];