export const scene_1 = [
	{
		sceneId: "0001",
		lengthNum: 7,
		story: {
			"1": {
				bgMusic: {
					name: 'ClearDay_normal_night',
					command: 'START'
				},
				background: "backgrounds/BG_Tyler_bedroom_night",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "Ahh... man. What a tough day...",
				choiceNext: false,
			},
			"2": {
				background: "backgrounds/BG_Tyler_bedroom_night",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
				textClass: "italic",
			  	text: "There's never been such a crowd at the gym all day! People kept pouring in one after the other, I barely had time to go to the bathroom between sessions!",
				choiceNext: false,
			},
			"3": {
				background: "backgrounds/BG_Tyler_bedroom_night",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
				textClass: "italic",
			  	text: "It really drained me mentally. But at least I'm finally home. I don't even know what's been going on in the world, I didn't even have time to check my phone, and I almost fell asleep several times on the way back.",
				choiceNext: false,
			},
			"4": {
				background: "backgrounds/BG_Tyler_bedroom_night",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
				textClass: "italic",
			  	text: "Hmm... It's almost midnight... Ah, I'd better just go to bed, I'm too tired. I'll check my messages tomorrow morning since I'll have a day off anyway.",
				choiceNext: false,
			},
			"5": {
				background: "backgrounds/BG_Tyler_bedroom_night",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
				textClass: "italic",
			  	text: "So, off to bed and... good night!",
				choiceNext: false,
			},
			"6": {
				background: "backgrounds/BG_Tyler_bedroom_night",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "With that, I slip into bed. Maybe I should have taken a shower first, but I'm too exhausted to care.",
				choiceNext: false,
			},
			"7": {
				bgMusic: {
					name: 'ClearDay_normal_night',
					command: 'FADE_OUT'
				},
				background: "backgrounds/BG_Tyler_bedroom_night",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I didn't have to toss and turn for long, as my brain shut off in an instant and I was sound asleep in no time.",
				choiceNext: false,
			},
		},
	},
];