export const scene_10 = [
    { sceneId: "0009" }, //mobileScene: 0009
	{
		sceneId: "0010",
		lengthNum: 24,
		story: {
			"1": {
				bgMusic: {
					name: 'FittnessRoom_normal_daily',
					command: 'START'
				},
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "It was really strange and unexpected. Lindsay is the kind of ex-girlfriend I wouldn't wish on my worst enemies.",
				choiceNext: false,
            },
			"2": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "At first glance, she seems cute and sweet, and if you look closely, you can even see the sexy side of her. But beneath the surface, there's something completely different.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "She's short-tempered, impulsive, and throws tantrums whenever things don't go her way. She apologizes afterward, which is promising, but the problem is she never learns from it and doesn't try to be calmer the next time.",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I'm worried this time won't be any different. She probably regrets how she dumped me and wants to make up for it. But there are some things that can't be taken back once they're said or done. Some things can be forgiven, but never forgotten.",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "We'll find out today if she just wants to ease her conscience or if there's something else going on, so I'll need to be cautious.",
				choiceNext: false,
			},
			"6": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "But for now, I need to focus on work. And who else could I be training today but my favorite client...",
				choiceNext: false,
			},
			"7": {
                specialSceneNow: true,
				specialSceneId: "0010-7",
				background: "special_scenes/0010-7",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Reina!",
				choiceNext: false,
			},
			"8": {
				background: "special_scenes/0010-7",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
                textClass: "italic",
			  	text: "She's in incredible shape today, as always, but I can tell from her behavior that yesterday's conversation is still on her mind. I'll need to choose my words carefully.",
				choiceNext: false,
			},
			"9": {
				background: "special_scenes/0010-7",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Come on, Reina, a little harder!",
				choiceNext: false,
			},
			"10": {
				background: "special_scenes/0010-7",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "This? Harder? You can give me something tougher, I could do this for hours!",
				choiceNext: false,
			},
			"11": {
				background: "special_scenes/0010-7",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Oh yeah? Okay, you asked for it.",
				choiceNext: false,
			},
			"12": {
				background: "special_scenes/0010-7",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Alright, I'll give you a weight that's 6 kg heavier, and continue the exercise like this: one bent-over row, then one bent-over lateral raise. I want 16 reps on one side, then switch to the other side.",
				choiceNext: false,
			},
			"13": {
				background: "special_scenes/0010-7",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Got it.",
				choiceNext: false,
			},
			"14": {
				background: "special_scenes/0010-7",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Reina swaps out her kettlebell for one that's 6 kg heavier, just like I asked, and gets to work. She was really confident at first, but by the second rep, she realized she bit off more than she could chew.",
				choiceNext: false,
			},
			"15": {
                specialSceneId: "0010-15",
				background: "special_scenes/0010-15",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Oh my god! This is crazy tough! The row is fine, but that lateral raise is brutal!",
				choiceNext: false,
			},
			"16": {
				background: "special_scenes/0010-15",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I know, but you asked for it. No backing out now—finish it up! I know you've got this.",
				choiceNext: false,
			},
			"17": {
				background: "special_scenes/0010-15",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "She fights hard to get through all 16 reps. When I see her hip starting to shift to the side, I step in and gently guide her back to center.",
				choiceNext: false,
			},
			"18": {
				background: "special_scenes/0010-15",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Ah–!",
				choiceNext: false,
			},
			"19": {
				background: "special_scenes/0010-15",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "Okay, I guess she's not too mad at me, since she still reacts like this sometimes when I touch her during workouts.",
				choiceNext: false,
			},
			"20": {
				background: "special_scenes/0010-15",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Keep your hips centered! Stay straight!",
				choiceNext: false,
			},
			"21": {
				background: "special_scenes/0010-15",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Mmmm… I'm trying.",
				choiceNext: false,
			},
			"22": {
				background: "special_scenes/0010-15",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Once she finishes on the left side, she moves on to the right. The first rep, she keeps her hips straight, but by the second, she's tipping to the side again as quickly as if she's doing it on purpose. And honestly… maybe she is.",
				choiceNext: false,
			},
			"23": {
				background: "special_scenes/0010-15",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "This feels like an invitation to play along. I glance around and see that no one's watching us, so I go along with her little game and, instead of adjusting her at the waist, I correct her by placing my hand on her butt.",
				choiceNext: false,
			},
			"24": {
                bgMusic: {
					name: 'FittnessRoom_normal_daily',
					command: 'FADE_OUT'
				},
                background: "special_scenes/0010-15",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				name: "Reina",
				text: "Eek–!",
				choiceNext: false,
			}
		},
	},
];