export const scene_26 = [
    { sceneId: "0023" }, //storyScene: 0023
    { sceneId: "0024" }, //storyScene: 0024
    { sceneId: "0025" }, //storyScene: 0025
    {
		sceneId: "0026",
        startTime: "20:00",
        endTime: "00:53",
        timeSkipNext: {
            content: "Friday morning",
            nextSceneType: "STORY",
            nextSceneNumber: "0027",
        },
        keepOut: [],
        bgMusic: {
            name: 'Mobile_night_normal',
            command: 'START',
        },
		textingPartner: {
            Reina: {
                isMandatory: true,
                sheStartsAt: "20:02",
                sheEndsAt: "21:02",
                messages: [
                    {
                        id: 0, 
                        isFromHer: true, 
                        text: "Hi Tyler😘", 
                        waitingTime: 0,
                        typingTime: 0.5,
                    },
                    {
                        id: 1, 
                        isFromHer: true, 
                        text: "I don't have much time today, the girls are keeping me really busy 😔", 
                        waitingTime: 2,
                        typingTime: 6,
                    },
                    {
                        id: 2, 
                        isFromHer: true, 
                        text: "But there's something I'd like to discuss", 
                        waitingTime: 2,
                        typingTime: 4,
                    },
                    {
                        id: 3, 
                        isFromHer: false, 
                        text: "Hi Reina", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 4, 
                        isFromHer: false, 
                        text: "I'm here and available", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 5, 
                        isFromHer: true, 
                        text: "Great 🙂", 
                        waitingTime: 4,
                        typingTime: 1,
                    },
                    {
                        id: 6, 
                        isFromHer: true, 
                        text: "So, about tomorrow morning's spa visit...", 
                        waitingTime: 3,
                        typingTime: 4,
                    },
                    {
                        id: 7, 
                        isFromHer: true, 
                        text: "I'll be dropping off the girls by 7:45 at the latest, then heading straight to the thermal baths", 
                        waitingTime: 2,
                        typingTime: 8,
                    },
                    {
                        id: 8, 
                        isFromHer: true, 
                        text: "I know it's super early, but can you be there by 8?", 
                        waitingTime: 3,
                        typingTime: 5,
                    },
                    {
                        id: 9, 
                        isFromHer: false, 
                        text: "Of course. I'll be tired, but I can get up earlier", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 10, 
                        isFromHer: true, 
                        text: "Thank you so much! I'll make it up to you, you'll see😘", 
                        waitingTime: 3,
                        typingTime: 5,
                    },
                    {
                        id: 11, 
                        isFromHer: true, 
                        text: "Alright, that's all from me for now. We'll meet tomorrow morning for the spa, then😊", 
                        waitingTime: 4,
                        typingTime: 7,
                    },
                    {
                        id: 12, 
                        isFromHer: true, 
                        text: "And try to get to bed early", 
                        waitingTime: 2,
                        typingTime: 3,
                    },
                    {
                        id: 13, 
                        isFromHer: false, 
                        text: "Will do", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 14, 
                        isFromHer: true,
                        text: "Good night😘❤️", 
                        waitingTime: 3,
                        typingTime: 1,
                        canSpeedUp: [true, "21:02"]
                    },
                ],
            },
            Daena: {
                isMandatory: true,
                sheStartsAt: "21:03",
                sheEndsAt: "22:51",
                messages: [
                    {
                        id: 0, 
                        isFromHer: true, 
                        text: "Hey Tyler😊😊", 
                        waitingTime: 0,
                        typingTime: 0.5,
                    },
                    {
                        id: 1, 
                        isFromHer: true, 
                        text: "I'm not bothering ya, am I?", 
                        waitingTime: 2,
                        typingTime: 3,
                    },
                    {
                        id: 2, 
                        isFromHer: false, 
                        text: "Hey Daena, not at all", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 3, 
                        isFromHer: true, 
                        text: "Sweet!👌🍬", 
                        waitingTime: 4,
                        typingTime: 1,
                    },
                    {
                        id: 4, 
                        isFromHer: true, 
                        text: "So, was just wondering if maybe... you'd be free...", 
                        waitingTime: 2,
                        typingTime: 4.5,
                    },
                    {
                        id: 5, 
                        isFromHer: true, 
                        text: "In the morning?🙏", 
                        waitingTime: 2,
                        typingTime: 2,
                    },
                    {
                        id: 6, 
                        isFromHer: true, 
                        text: "Saturday?🙏🙏", 
                        waitingTime: 4,
                        typingTime: 1,
                    },
                    {
                        id: 7, 
                        isFromHer: false, 
                        text: "Saturday morning works, yeah", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 8, 
                        isFromHer: false, 
                        text: "What's up?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 9, 
                        isFromHer: true, 
                        text: "Well, I wanted it to be a surprise, but that's kinda impossible",
                        waitingTime: 3,
                        typingTime: 5.5,
                    },
                    {
                        id: 10, 
                        isFromHer: true, 
                        text: "So here it is...",
                        waitingTime: 2,
                        typingTime: 2,
                    },
                    {
                        id: 11, 
                        isFromHer: true, 
                        text: "I wanna go to the spa with you🫢🌊",
                        waitingTime: 3,
                        typingTime: 3.5,
                    },
                    {
                        id: 12, 
                        isFromHer: false, 
                        text: "Oh... you mean the thermal spa?",
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 13, 
                        isFromHer: true, 
                        text: "Nah, that's more for the older crowd, you're not quite there yet either", 
                        waitingTime: 3,
                        typingTime: 6,
                    },
                    {
                        id: 14, 
                        isFromHer: true, 
                        text: "Nope, I'm thinking the water park🌊👙🔫", 
                        waitingTime: 3,
                        typingTime: 4,
                        bgMusic: {
                            name: 'Mobile_night_romantic',
                            command: 'START',
                        },
                    },
                    {
                        id: 15, 
                        isFromHer: false, 
                        text: "Ah, I got ya. And where'd this idea come from?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 16, 
                        isFromHer: true, 
                        text: "Hmm... it's good manners to accept gifts without asking questions, y'know", 
                        waitingTime: 4,
                        typingTime: 6,
                    },
                    {
                        id: 17, 
                        isFromHer: false, 
                        text: "Ahha... okay, I accept, I'd love to go with you", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 18, 
                        isFromHer: true, 
                        text: "Really?😯", 
                        waitingTime: 2,
                        typingTime: 1,
                    },
                    {
                        id: 19, 
                        isFromHer: true, 
                        text: "Awww, awesome!🤩🤩🤩", 
                        waitingTime: 3,
                        typingTime: 2,
                    },
                    {
                        id: 20, 
                        isFromHer: true, 
                        text: "Alright then, how's 11 a.m. in front of the water park entrance?😉", 
                        waitingTime: 3,
                        typingTime: 5,
                    },
                    {
                        id: 21, 
                        isFromHer: false, 
                        text: "Could we make it a bit earlier? I actually have plans at noon", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 22, 
                        isFromHer: true, 
                        text: "Hmm... then how's 9 a.m.?🤔", 
                        waitingTime: 4,
                        typingTime: 3,
                    },
                    {
                        id: 23, 
                        isFromHer: true, 
                        text: "I'd like more than just an hour there", 
                        waitingTime: 4,
                        typingTime: 3,
                    },
                    {
                        id: 24, 
                        isFromHer: false, 
                        text: "That works perfectly",
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 25,  
                        isFromHer: true, 
                        text: "Great!👍",
                        waitingTime: 2,
                        typingTime: 1,
                    },
                    {
                        id: 26, 
                        isFromHer: true, 
                        text: "Thanks for comin' with me, see ya there😉",
                        waitingTime: 2,
                        typingTime: 4,
                    },
                    {
                        id: 27, 
                        isFromHer: false, 
                        text: "Sounds good",
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 28, 
                        isFromHer: true, 
                        text: "Thanks a bunch!🙏",
                        waitingTime: 3,
                        typingTime: 2,
                    },
                    {
                        id: 29,  
                        isFromHer: true, 
                        text: "Kisses!💋💋",
                        waitingTime: 2,
                        typingTime: 1,
                    },
                    {
                        id: 30, 
                        isFromHer: true, 
                        text: "Bye😚",
                        waitingTime: 3,
                        typingTime: 1,
                        canSpeedUp: [true, "22:51"]
                    },
                ]
            },
            Lindsay: {
                isMandatory: true,
                sheStartsAt: "22:55",
                sheEndsAt: "00:51",
                messages: [
                    {
                        id: 0, 
                        isFromHer: true, 
                        text: "Hey Tyler😇", 
                        waitingTime: 0,
                        typingTime: 0.5,
                        bgMusic: {
                            name: 'Mobile_night_trouble',
                            command: 'START',
                        },
                    },
                    {
                        id: 1, 
                        isFromHer: true, 
                        text: "How's it goin'?😊", 
                        waitingTime: 2,
                        typingTime: 2,
                    },
                    {
                        id: 2, 
                        isFromHer: false, 
                        text: "Hey Lindsay", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 3, 
                        isFromHer: false, 
                        text: "So far, so good...", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 4, 
                        isFromHer: true, 
                        text: "C'mon, don't be so harsh😞", 
                        waitingTime: 3,
                        typingTime: 3.5,
                    },
                    {
                        id: 5, 
                        isFromHer: true, 
                        text: "So, have ya thought about that dinner we talked about?", 
                        waitingTime: 3,
                        typingTime: 5,
                    },
                    {
                        id: 6, 
                        isFromHer: false, 
                        text: [
                            "Yeah, decided I'll give it a shot",
                            "Nah, I'm still not feelin' it, really don't want to go to dinner",
                            "Oh shoot... I totally forgot about it"
                        ], 
                        waitingTime: null,
                        typingTime: null,
                        choiceNow: true,
                        choicePath: "lindsay~mobileNotImportants~0026-l-6",
                    },
                    {
                        id: 7, 
                        isFromHer: true, 
                        text: [
                            "Really? Well, glad to hear it😊",
                            "C'mon... I'm not rude with you, so would be nice if you stopped bein' like that with me😔",
                            "Ah... okay, no problem",
                            "Your silence isn't helping😞"
                        ], 
                        waitingTime: 3,
                        typingTime: [3.5, 7, 2.5, 3],
                        choicePath: "lindsay~mobileNotImportants~0026-l-6",
                    },
                    {
                        id: 8, 
                        isFromHer: true, 
                        text: [
                            "Anyway, hope I'm tellin' ya in time—I managed to book a spot for tomorrow night🍴",
                            "Anyway, hope I'm lettin' ya know in time—I got us a spot for tomorrow night🍴",
                            "So I hope I'm givin' ya a heads-up in time—I managed to get us a spot for tomorrow night🍴",
                            "Anyway, hope I'm tellin' ya in time—I managed to book a spot for tomorrow night🍴"
                        ], 
                        waitingTime: 4,
                        typingTime: [6, 6, 7, 6],
                        choicePath: "lindsay~mobileNotImportants~0026-l-6",
                    },
                    {
                        id: 9, 
                        isFromHer: false, 
                        text: "Tomorrow night? That's cutting it close",
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 10, 
                        isFromHer: true, 
                        text: "Sorry, I've got a life too, and the restaurant's pretty packed...",
                        waitingTime: 3,
                        typingTime: 5.5,
                    },
                    {
                        id: 11, 
                        isFromHer: true, 
                        text: "It's the best I could do",
                        waitingTime: 2,
                        typingTime: 3,
                    },
                    {
                        id: 12, 
                        isFromHer: true, 
                        text: "Hope you're not booked for that time",
                        waitingTime: 3,
                        typingTime: 4,
                    },
                    {
                        id: 13, 
                        isFromHer: false, 
                        text: "As of now, I'm free tomorrow night", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 14, 
                        isFromHer: false, 
                        text: [
                            "Well, then, maybe this'll finally settle things between us for good",
                            "Doesn't mean I actually wanna go anywhere with you, still",
                            "It's just dinner and nothing else, right?",
                            "It's just dinner and nothing else, right?"
                        ], 
                        waitingTime: null,
                        typingTime: null,
                        choicePath: "lindsay~mobileNotImportants~0026-l-6",
                    },
                    {
                        id: 15, 
                        isFromHer: true, 
                        text: [
                            "I'm hoping the same😊",
                            "Maybe this'll soften that stone heart of yours a bit😊",
                            "Guess we'll see...?",
                            "Guess we'll see...?"
                        ], 
                        waitingTime: 4,
                        typingTime: [2.5, 5, 2.5, 2.5],
                        choicePath: "lindsay~mobileNotImportants~0026-l-6",
                    },
                    {
                        id: 16, 
                        isFromHer: true,
                        sentPicture: "0026-l-16",
                        text: null, 
                        waitingTime: 4,
                        typingTime: 1,
                        bgMusic: {
                            name: 'Mobile_night_ecchi',
                            command: 'START',
                        },
                    },
                    {
                        id: 17, 
                        isFromHer: false, 
                        text: "Lindsay! What's that for?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 18, 
                        isFromHer: true, 
                        text: "A little teaser for tomorrow night😇😜", 
                        waitingTime: 3,
                        typingTime: 4,
                    },
                    {
                        id: 19, 
                        isFromHer: false, 
                        text: "Teaser? For what? And besides, you're a married woman—shouldn't send pics like this to someone who isn't your partner!", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 20, 
                        isFromHer: true, 
                        text: "Oh, but I can, Tyler", 
                        waitingTime: 2,
                        typingTime: 3,
                    },
                    {
                        id: 21, 
                        isFromHer: true, 
                        text: "We've spent enough time together for you to know exactly what I'm like underneath...", 
                        waitingTime: 2,
                        typingTime: 6,
                    },
                    {
                        id: 22, 
                        isFromHer: true, 
                        text: "At this point, this picture doesn't make a difference", 
                        waitingTime: 2,
                        typingTime: 4,
                    },
                    {
                        id: 23, 
                        isFromHer: false, 
                        text: "This isn't about how much the pic shows!", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 24, 
                        isFromHer: false, 
                        text: "It's that you shouldn't be sending that type of pic to anyone but your partner!",
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 25,  
                        isFromHer: true, 
                        text: "That's for me to decide—who's worthy of what, in my life",
                        waitingTime: 4,
                        typingTime: 4.5,
                    },
                    {
                        id: 26, 
                        isFromHer: true, 
                        text: "Anyway, just wanted to get our plans locked in for tomorrow",
                        waitingTime: 4,
                        typingTime: 5,
                    },
                    {
                        id: 27, 
                        isFromHer: true, 
                        text: "Hope you'll be there—I'm really lookin' forward to it🙂",
                        waitingTime: 2,
                        typingTime: 4,
                    },
                    {
                        id: 28, 
                        isFromHer: true, 
                        text: "Goodnight🌙🌙",
                        waitingTime: 3,
                        typingTime: 1,
                        canSpeedUp: [true, "00:51"]
                    },
                ]
            }
        }
    },
];