export const scene_22 = [
    { sceneId: "0020" }, //storyScene: 0020
    { sceneId: "0021" }, //storyScene: 0021
    {
		sceneId: "0022",
        startTime: "19:34",
        endTime: "22:23",
        timeSkipNext: {
            content: "Thursday morning",
            nextSceneType: "STORY",
            nextSceneNumber: "0023",
        },
        keepOut: [],
        bgMusic: {
            name: 'Mobile_night_normal',
            command: 'START',
        },
		textingPartner: {
            Hailey: {
                isMandatory: false,
                sheStartsAt: "19:36",
                sheEndsAt: "22:21",
                messages: [
                    {
                        id: 0, 
                        isFromHer: true, 
                        text: "Heyyy Tyler🥰🥰", 
                        waitingTime: 0,
                        typingTime: 0.5,
                    },
                    {
                        id: 1, 
                        isFromHer: true, 
                        text: "U there?", 
                        waitingTime: 2,
                        typingTime: 1,
                    },
                    {
                        id: 2, 
                        isFromHer: false, 
                        text: "Hey Hailey, yeah I'm here", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 3, 
                        isFromHer: true, 
                        text: "Awesome👌", 
                        waitingTime: 4,
                        typingTime: 1,
                    },
                    {
                        id: 4, 
                        isFromHer: true, 
                        text: "Just wanted 2 say thx 4 coming w me 2day for the massage😊😊", 
                        waitingTime: 2,
                        typingTime: 5,
                    },
                    {
                        id: 5, 
                        isFromHer: true, 
                        text: "We didn't really finish that convo b4 the masseuses showed up", 
                        waitingTime: 3,
                        typingTime: 5.5,
                    },
                    {
                        id: 6, 
                        isFromHer: true, 
                        text: "But we can totally wrap it up now if u want", 
                        waitingTime: 2,
                        typingTime: 4,
                    },
                    {
                        id: 7, 
                        isFromHer: false, 
                        text:"I think it'd be better 2 talk about stuff like that IRL", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 8, 
                        isFromHer: false, 
                        text: "But, like, the gym's not exactly the right place either", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 9, 
                        isFromHer: true, 
                        text: "Yeah, def not😒", 
                        waitingTime: 4,
                        typingTime: 2,
                    },
                    {
                        id: 10, 
                        isFromHer: true, 
                        text: "K", 
                        waitingTime: 3,
                        typingTime: 1,
                    },
                    {
                        id: 11, 
                        isFromHer: true, 
                        text: "I'll find another time 4 us 2 finish what we started🙂", 
                        waitingTime: 2,
                        typingTime: 5,
                    },
                    {
                        id: 12, 
                        isFromHer: true, 
                        text: "But I just wanna make sure u know... u mean a lot 2 me", 
                        waitingTime: 2,
                        typingTime: 5,
                    },
                    {
                        id: 13, 
                        isFromHer: true, 
                        text: "Never thought I'd feel this way w/ someone who's \"just\" my trainer...😳🫣", 
                        waitingTime: 2,
                        typingTime: 7,
                    },
                    {
                        id: 14, 
                        isFromHer: false,
                        text: "Wait, what do u mean by \"feel this way\"?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 15, 
                        isFromHer: true, 
                        text: "Like, I feel I can count on u more than I can on my bf", 
                        waitingTime: 4,
                        typingTime: 5,
                    },
                    {
                        id: 16, 
                        isFromHer: true, 
                        text: "Honestly, sometimes... you're the first guy I think of...😌", 
                        waitingTime: 2,
                        typingTime: 5,
                    },
                    {
                        id: 17, 
                        isFromHer: true, 
                        text: [
                            "Whether or not u feel the same...",
                            "Even if u don't think what I'm doing is \"right\"...",
                            "Even if I'm just one of ur clients..."
                        ], 
                        waitingTime: 3,
                        typingTime: [3.5, 5, 3.5],
                        choicePath: "hailey~importants~0021-27",
                    },
                    {
                        id: 18, 
                        isFromHer: true, 
                        text: "I'd do anything 2 win u over...💪", 
                        waitingTime: 2,
                        typingTime: 3.5,
                    },
                    {
                        id: 19, 
                        isFromHer: true, 
                        text: "Just tell me what I gotta do!", 
                        waitingTime: 4,
                        typingTime: 3.5,
                    },
                    {
                        id: 20, 
                        isFromHer: false, 
                        text: [
                            "Hailey, I never knew you had such a soft, feminine side",
                            "Wait, are you saying you're thinking about leaving your bf? Did I get that right?",
                            "I'm really glad you chose me as your trainer back then..."
                        ], 
                        waitingTime: null,
                        typingTime: null,
                        choiceNow: true,
                        choicePath: "hailey~mobileImportants~0022-h-20",
                    },
                    {
                        id: 21, 
                        isFromHer: [true, true, false], 
                        text: [
                            "Tyler...",
                            "Uh, yeah... maybe...",
                            "I never thought this relationship would evolve this far either",
                        ], 
                        waitingTime: [3, 3, null],
                        typingTime: [1, 2, null],
                        choicePath: "hailey~mobileImportants~0022-h-20",
                        bgMusic: {
                            name: ['Mobile_night_trouble', 'Mobile_night_trouble', 'Mobile_night_normal'],
                            command: ['START', 'START', 'START'],
                        },
                    },
                    {
                        id: 22, 
                        isFromHer: [true, true, false], 
                        text: [
                            "Yo, I'm talkin' real feels here! Like, I don't open up like this, k?",
                            "IDK tho...",
                            "But I can't tell you what to do. That's gotta be your call",
                        ], 
                        waitingTime: [2, 2, null],
                        typingTime: [6, 1, null],
                        choicePath: "hailey~mobileImportants~0022-h-20",
                    },
                    {
                        id: 23, 
                        isFromHer: [true, true, false], 
                        text: [
                            "Least u could do is not roast me right now!😥",
                            "But I def need some kinda vibe from u if I'm gonna risk it all",
                            "I don't wanna turn you into some ideal version of a guy, I just wanna see the real you",
                        ], 
                        waitingTime: [2, 2, null],
                        typingTime: [4, 6, null],
                        choicePath: "hailey~mobileImportants~0022-h-20",
                    },
                    {
                        id: 24, 
                        isFromHer: [false, false, true], 
                        text: [
                            "I'm not mocking you, it's just... I've never seen this side of you before",
                            "I can't give you any guarantees... I'm not exactly a catch",
                            "But like... r u sure that's gonna be enough?🤔",
                        ], 
                        waitingTime: [null, null, 4],
                        typingTime: [null, null, 4],
                        choicePath: "hailey~mobileImportants~0022-h-20",
                    },
                    {
                        id: 25, 
                        isFromHer: true, 
                        text: [
                            "Sooo, r u basically sayin' I'm not girly enough or what?😨",
                            "Wow... that's sooo not convincing me rn😰",
                            "Kinda felt like u didn't even notice me till now, tbh🫢"
                        ], 
                        waitingTime: [3, 3, 4],
                        typingTime: [5, 4, 5],
                        choicePath: "hailey~mobileImportants~0022-h-20",
                    },
                    {
                        id: 26, 
                        isFromHer: [false, true, true], 
                        text: [
                            "I never said that",
                            "U don't gotta be—I'm not askin' for that",
                            "And all this time, I thought I wasn't good enough... or just like, annoyin' u😥",
                        ], 
                        waitingTime: [null, 2, 2],
                        typingTime: [null, 4, 7],
                        choicePath: "hailey~mobileImportants~0022-h-20",
                    },
                    {
                        id: 27, 
                        isFromHer: [true, true, false], 
                        text: [
                            "Whatever, this convo is just goin' nowhere...",
                            "But if u ain't got confidence now, what's gonna happen later?😰",
                            "No, that's definitely not how I see it",
                        ], 
                        waitingTime: [3, 3, null],
                        typingTime: [4, 5.5, null],
                        choicePath: "hailey~mobileImportants~0022-h-20",
                    },
                    {
                        id: 28, 
                        isFromHer: [true, false, true], 
                        text: [
                            "Hope u'll be more put-together and take me srsly IRL",
                            "Still, can't guarantee u'll end up better off with me",
                            "Glad u feel that way😊😊",
                        ], 
                        waitingTime: [3, null, 4],
                        typingTime: [5, null, 2],
                        choicePath: "hailey~mobileImportants~0022-h-20",
                        chatSkip: [7, 0, 0],
                    },
                    {
                        id: 29, 
                        isFromHer: [null, true, true],
                        text: [
                            null,
                            "Whatevs... I can see this convo isn't goin' anywhere",
                            "So, as a token of my gratitude...",
                        ], 
                        waitingTime: [null, 3, 3],
                        typingTime: [null, 5, 3.5],
                        choicePath: "hailey~mobileImportants~0022-h-20",
                    },
                    {
                        id: 30, 
                        isFromHer: [null, true, true],
                        sentPicture: [null, null, "0022-h-30"],
                        text: [
                            null,
                            "Hope u'll be more serious and collected IRL",
                            null,
                        ], 
                        waitingTime: [null, 3, 4],
                        typingTime: [null, 4, 2],
                        choicePath: "hailey~mobileImportants~0022-h-20",
                        chatSkip: [5, 5, 0],
                        bgMusic: {
                            name: ['Mobile_night_trouble', 'Mobile_night_trouble', 'Mobile_night_ecchi'],
                            command: ['START', 'START', 'START'],
                        },
                    },
                    {
                        id: 31, 
                        isFromHer: [null, null, false], 
                        text: [
                            null,
                            null,
                            "Whoa! What did I do to deserve this?",
                        ], 
                        waitingTime: null,
                        typingTime: null,
                        choicePath: "hailey~mobileImportants~0022-h-20",
                    },
                    {
                        id: 32, 
                        isFromHer: [null, null, true], 
                        text: [
                            null,
                            null,
                            "Earlier u said you've never seen me even in a swimsuit, and today's towel scene was a big step up from that...😜",
                        ], 
                        waitingTime: [null, null, 3],
                        typingTime: [null, null, 8],
                        choicePath: "hailey~mobileImportants~0022-h-20",
                    },
                    {
                        id: 33, 
                        isFromHer: [null, null, true], 
                        text: [
                            null,
                            null,
                            "Sooo, I thought I'd make up for that missed moment🤭👙",
                        ], 
                        waitingTime: [null, null, 2],
                        typingTime: [null, null, 4],
                        choicePath: "hailey~mobileImportants~0022-h-20",
                    },
                    {
                        id: 34, 
                        isFromHer: [null, null, false], 
                        text: [
                            null,
                            null,
                            "Uh… thanks... I'm kinda speechless right now...",
                        ], 
                        waitingTime: null,
                        typingTime: null,
                        choicePath: "hailey~mobileImportants~0022-h-20",
                    },
                    {
                        id: 35, 
                        isFromHer: [null, null, true], 
                        text: [
                            null,
                            null,
                            "Your reaction says it all, babe😋😋",
                        ], 
                        waitingTime: [null, null, 3],
                        typingTime: [null, null, 3.5],
                        choicePath: "hailey~mobileImportants~0022-h-20",
                    },
                    {
                        id: 36, 
                        isFromHer: true, 
                        text: "Anyway, I gotta go now",
                        waitingTime: 3,
                        typingTime: 3,
                    },
                    {
                        id: 38, 
                        isFromHer: true, 
                        text: "Hav a lit nite!🌒",
                        waitingTime: 2,
                        typingTime: 2,
                    },
                ],
            },
            Reina: {
                isMandatory: false,
                sheStartsAt: "20:12",
                sheEndsAt: "22:22",
                messages: [
                    {
                        id: 0, 
                        isFromHer: true, 
                        text: "Hey Darling, how are you? 😘", 
                        waitingTime: 0,
                        typingTime: 0.5,
                    },
                    {
                        id: 1, 
                        isFromHer: false, 
                        text: "Hey Honey, I'm good. How about you?😊", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 2, 
                        isFromHer: true, 
                        text: "I'm good too", 
                        waitingTime: 3,
                        typingTime: 2,
                    },
                    {
                        id: 3, 
                        isFromHer: true, 
                        text: "Today's date really added to that🙂", 
                        waitingTime: 3,
                        typingTime: 4,
                    },
                    {
                        id: 4, 
                        isFromHer: true, 
                        text: "Thank you so much for spending the morning with me🙂", 
                        waitingTime: 4,
                        typingTime: 5,
                    },
                    {
                        id: 5, 
                        isFromHer: false, 
                        text: "I had a great time too, thank you", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 6, 
                        isFromHer: true, 
                        text: "How would you rate it overall?", 
                        waitingTime: 4,
                        typingTime: 3,
                    },
                    {
                        id: 7, 
                        isFromHer: true, 
                        text: "I'm trying to push the boundaries of what we can openly show to the world...", 
                        waitingTime: 2,
                        typingTime: 7,
                    },
                    {
                        id: 8, 
                        isFromHer: true, 
                        text: "But I need your feedback—am I doing the right thing?", 
                        waitingTime: 4,
                        typingTime: 5,
                    },
                    {
                        id: 9, 
                        isFromHer: false, 
                        text: [
                            "Well, I thought we were just going to stroll around the mall...",
                            "I wouldn't say I was bored though"
                        ],
                        waitingTime: null,
                        typingTime: null,
                        choiceNow: true,
                        choicePath: "reina~mobileImportants~0022-r-9",
                    },
                    {
                        id: 10, 
                        isFromHer: false, 
                        text: [
                            "But the sight that greeted me... totally worth it!",
                            "So yeah, I had a good time"
                        ],
                        waitingTime: null,
                        typingTime: null,
                        choicePath: "reina~mobileImportants~0022-r-9",
                    },
                    {
                        id: 11, 
                        isFromHer: true, 
                        text: [
                            "I'm so glad I managed to make this date memorable for you😇",
                            "So, it wasn't boring after all..."
                        ],
                        waitingTime: 4,
                        typingTime: [5, 3.5],
                        choicePath: "reina~mobileImportants~0022-r-9",
                    },
                    {
                        id: 12, 
                        isFromHer: true, 
                        text: [
                            "And I'm happy you liked what you saw😋",
                            "I see... well, that's not bad then"
                        ],
                        waitingTime: 2,
                        typingTime: 3.5,
                        choicePath: "reina~mobileImportants~0022-r-9",
                    },
                    {
                        id: 13, 
                        isFromHer: true, 
                        text: "I know you really want us to take it to the next level and get a room...", 
                        waitingTime: 3,
                        typingTime: 7,
                    },
                    {
                        id: 14, 
                        isFromHer: true, 
                        text: "Believe me, I've been playing with the idea myself more and more...😋", 
                        waitingTime: 2,
                        typingTime: 6,
                    },
                    {
                        id: 15, 
                        isFromHer: true, 
                        text: "But I just need a little more, so I feel like I'm going to explode with desire🥵", 
                        waitingTime: 3,
                        typingTime: 7,
                    },
                    {
                        id: 16, 
                        isFromHer: true, 
                        text: "Until then, I ask for just a bit more patience", 
                        waitingTime: 3,
                        typingTime: 4.5,
                    },
                    {
                        id: 17, 
                        isFromHer: true, 
                        text: "It'll be worth the wait, trust me😉", 
                        waitingTime: 4,
                        typingTime: 3.5,
                    },
                    {
                        id: 18, 
                        isFromHer: false, 
                        text: "Alright, I'll try to hold out a bit longer, though you're not exactly making it easy most of the time", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 19, 
                        isFromHer: true, 
                        text: "Hehe, I know...", 
                        waitingTime: 2,
                        typingTime: 2,
                        choicePath: "reina~mobileImportants~0022-r-9",
                        chatSkip: [0, 4],
                    },
                    {
                        id: 20, 
                        isFromHer: [true, null], 
                        sentPicture: ["0022-r-20", null],
                        text: null,
                        waitingTime: [2, null],
                        typingTime: [2, null],
                        choicePath: "reina~mobileImportants~0022-r-9",
                        bgMusic: {
                            name: ['Mobile_daily_ecchi', null],
                            command: ['START', null],
                        },
                    },
                    {
                        id: 21, 
                        isFromHer: [true, null], 
                        text: [
                            "Like just now😜",
                            null
                        ],
                        waitingTime: [2, null],
                        typingTime: [2, null],
                        choicePath: "reina~mobileImportants~0022-r-9",
                    },
                    {
                        id: 22, 
                        isFromHer: [false, null], 
                        text: [
                            "Ah... yeah… you've just made it even harder for me...",
                            null
                        ],
                        waitingTime: null,
                        typingTime: null,
                        choicePath: "reina~mobileImportants~0022-r-9",
                    },
                    {
                        id: 23, 
                        isFromHer: [true, null], 
                        text: [
                            "Hehe, then it was worth it😁",
                            null
                        ],
                        waitingTime: [3, null],
                        typingTime: [3, null],
                        choicePath: "reina~mobileImportants~0022-r-9",
                    },
                    {
                        id: 24, 
                        isFromHer: false, 
                        text: "Though in the middle of summer, I assumed you'd be trying on swimsuits as well",
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 25,  
                        isFromHer: true, 
                        text: "I've got plenty of those, though that's not what held me back...",
                        waitingTime: 3,
                        typingTime: 6,
                    },
                    {
                        id: 26, 
                        isFromHer: true, 
                        text: "It was kind of the same with the lingerie store, I wasn't sure it would've been the smartest decision",
                        waitingTime: 2,
                        typingTime: 8,
                    },
                    {
                        id: 27, 
                        isFromHer: true, 
                        text: "Was it because you really wanted to see me in a swimsuit?",
                        waitingTime: 3,
                        typingTime: 5,
                    },
                    {
                        id: 28, 
                        isFromHer: false, 
                        text: "Yeah, though obviously it'd be better at a beach, to really set the mood",
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 29,  
                        isFromHer: true, 
                        text: "Hmm... we'll make that happen someday, you'll see😋",
                        waitingTime: 4,
                        typingTime: 4.5,
                    },
                    {
                        id: 30, 
                        isFromHer: true, 
                        text: "But for now, I have to go",
                        waitingTime: 3,
                        typingTime: 2.5,
                    },
                    {
                        id: 31, 
                        isFromHer: true, 
                        text: "The girls are super energetic tonight, so it won't be easy to get them to bed😏",
                        waitingTime: 2,
                        typingTime: 7,
                    },
                    {
                        id: 32, 
                        isFromHer: true, 
                        text: "Goodnight😘❤️",
                        waitingTime: 2,
                        typingTime: 1,
                    },
                ]
            }
        }
    },
];