export const scene_12 = [
	{
		sceneId: "0012",
		lengthNum: 57,
		story: {
			"1": {
				bgMusic: {
					name: 'Meeting_with_Lindsay',
					command: 'START'
				},
                background: "backgrounds/BG_city_park_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "My shift is over, but instead of heading home to relax, I have to deal with an uncomfortable meeting first.",
				choiceNext: false,
            },
			"2": {
                background: "backgrounds/BG_city_park_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Lindsay is unpredictable, and I've been racking my brain ever since, wondering if there's some hidden agenda behind this meeting. But no matter how much I think about it, I can't come up with a reasonable answer.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_city_park_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "There's no other choice—I need to dive into this and find out the truth so I can finally close this chapter and get back to my usual life.",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_city_park_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I arrived at the meeting spot a bit early, so I wait, running through possible scenarios in my mind, trying to prepare for anything that might happen.",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_city_park_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "When the time comes, I see a familiar face approaching... it's her.",
				choiceNext: false,
			},
			"6": {
				background: "backgrounds/BG_city_park_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Nostalgic feelings bubble up from deep down as I see her. It reminds me of our first date—her petite, attractive figure with feminine curves, and that mysterious look in her eyes… a mystery I've since discovered all too well.",
				choiceNext: false,
			},
			"7": {
				background: "backgrounds/BG_city_park_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "But this time, I'm much more prepared. Let's get through this, and this time, let's do it smarter.",
				choiceNext: false,
			},
			"8": {
				background: "backgrounds/BG_city_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_casual_grin', null],
				class: [null, 'fadeUp', null],
			  	name: "Lindsay",
			  	text: "Hey Tyler!",
				choiceNext: false,
			},
			"9": {
				background: "backgrounds/BG_city_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_casual_grin', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Hello, Lindsay.",
				choiceNext: false,
			},
			"10": {
				background: "backgrounds/BG_city_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_casual_sad', null],
				class: [null, 'fadeUp', null],
			  	name: "Lindsay",
			  	text: "What, no hug or kiss hello?",
				choiceNext: false,
			},
			"11": {
				background: "backgrounds/BG_city_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_casual_sad', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "We're not together anymore. And correct me if I'm wrong, but I remember you got married to that other guy who ended up taking you from me.",
				choiceNext: false,
			},
			"12": {
				background: "backgrounds/BG_city_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Lindsay",
			  	text: "He didn't take me from you… you lost me. There's a big difference.",
				choiceNext: false,
			},
			"13": {
				background: "backgrounds/BG_city_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "The fact remains that you spent your whole life bouncing between two men: me and him. No matter how you spin it, the result is the same—we're not together anymore. So, no hugs or kisses.",
				choiceNext: false,
			},
			"14": {
				background: "backgrounds/BG_city_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Lindsay",
			  	text: "Looks like this apology's going to be a bit more work than I thought if you're still so mad at me.",
				choiceNext: false,
			},
			"15": {
                background: "backgrounds/BG_city_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "It's not anger… it's indifference.",
				choiceNext: false,
			},
			"16": {
				background: "backgrounds/BG_city_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Lindsay",
			  	text: "Oh, really? Well, that's good. That means this might not be so hard after all! Shall we take a walk?",
				choiceNext: false,
			},
			"17": {
				background: "backgrounds/BG_city_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Fine by me.",
				choiceNext: false,
			},
			"18": {
                specialSceneNow: true,
				specialSceneId: "0012-18",
				background: "special_scenes/0012-18",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_casual_smiling', null],
				class: [null, 'fadeUpOut', null],
			  	name: "",
			  	text: "We walk slowly, side by side, through a beautiful and peaceful part of the city. We've been here before on a date, so it's pretty obvious she wants something from me. But what could it be?",
				choiceNext: false,
			},
			"19": {
				background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "So, are you still working as a trainer in Vensea?",
				choiceNext: false,
			},
			"20": {
				background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Yep.",
				choiceNext: false,
			},
			"21": {
				background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "It's a shame I only got to experience what it's like to date a trainer for a month. Sometimes I think about booking a private session with you, just to see how you're doing.",
				choiceNext: false,
			},
			"22": {
				background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I'd rather you didn't.",
				choiceNext: false,
			},
			"23": {
				background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "Why not? Do you really not want to see me that much?",
				choiceNext: true,
			},
			"24": {
                background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'lindsay~notImportants~0012-23',
				name: "Tyler",
				text: [
                    "Yes, that's right. I don't want to see you at all.",
                    "I've been doing just fine without you. I didn't exactly miss you.",
                    "If you showed up at my work, it would bring back old memories I don't want to relive."
                ],
				choiceNext: false,
			},
			"25": {
                background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'lindsay~notImportants~0012-23',
			  	name: "Lindsay",
                  text: [
                    "Ouch, that hurt. You know very well that you should treat a woman more kindly than that.",
                    "Yet, here you are at this meeting. Can't live without me, huh?",
                    "Oh! You still have buried feelings for me? How adorable! I was starting to think you didn't have a heart."
                ],
                choiceNext: false,
            },
			"26": {
                background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Lindsay, this isn't a game!",
				choiceNext: false,
			},
			"27": {
                background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "Oh, but I think it is! You're so easy to push to extremes, it's almost fun.",
				choiceNext: false,
			},
			"28": {
                background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "You're sick!",
				choiceNext: false,
			},
			"29": {
                background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "Hehe, if you say so… But let's not get sidetracked. I didn't meet up with you to play games—I wanted to apologize for what happened.",
				choiceNext: false,
			},
			"30": {
                background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Well, you're off to a great start...",
				choiceNext: false,
			},
			"31": {
				background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "That was just the introduction. So… yes, I know I said some pretty nasty things when we broke up, and I really want to make it right.",
				choiceNext: false,
			},
			"32": {
				background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I'm usually able to forgive people, but there are limits, Lindsay.",
				choiceNext: false,
			},
			"33": {
				background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "I know. I can't change the past, but maybe I can offer you something that's just as filled with positive energy as the emotional scars I left behind.",
				choiceNext: false,
			},
			"34": {
				background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "What do you mean?",
				choiceNext: false,
			},
			"35": {
				background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "A fancy dinner.",
				choiceNext: false,
			},
			"36": {
				background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "What? Are you out of your mind? Dinner? With me? Your ex? What's your husband going to say about that?",
				choiceNext: false,
			},
			"37": {
				background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "Nothing, because he doesn't need to know.",
				choiceNext: false,
			},
			"38": {
				background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Oh, great. This is getting worse by the second. No, Lindsay, I'm not going along with this.",
				choiceNext: false,
			},
			"39": {
				background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "Why not? What's wrong with a dinner behind my husband's back? Don't tell me you've got a girlfriend who wouldn't let you do this?",
				choiceNext: true,
			},
			"40": {
				background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'lindsay~notImportants~0012-39',
			  	name: "Tyler",
			  	text: [
                    "Yes, actually, I do.",
                    "Well, it's… not that simple.",
                    "Um… no, I don't."
                ],
				choiceNext: false,
			},
			"41": {
				background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'lindsay~notImportants~0012-39',
			  	name: "Lindsay",
			  	text: [
                    "Really? Wow, I didn't know! So, who's the lucky girl?",
                    "Is that so? Hmm… this is getting interesting! So… who's the lucky girl?",
                    "Oh, I saw that hesitation! So… who's the lucky girl?"
                ],
				choiceNext: true,
			},
			"42": {
				background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'lindsay~importants~0012-41',
			  	name: "Tyler",
			  	text: [
                    "That's none of your business!",
                    "I met her at work. That's all you need to know."
                ],
				choiceNext: false,
			},
			"43": {
				background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'lindsay~importants~0012-41',
			  	name: "Lindsay",
			  	text: [
                    "That's not fair! I'm an open book for you, so you could be the same with me!",
                    "Hmm… so she's one of your clients, then."
                ],
				choiceNext: false,
			},
			"44": {
				background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'lindsay~importants~0012-41',
			  	name: "Tyler",
			  	text: [
                    "That doesn't mean I'm obligated to be.",
                    "There are female trainers, you know!"
                ],
				choiceNext: false,
			},
			"45": {
				background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'lindsay~importants~0012-41',
			  	name: "Lindsay",
			  	text: [
                    "Hmm… well, that's not fun…",
                    "Oh, sure… of course…"
                ],
				choiceNext: false,
			},
			"46": {
				background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "Anyway, my offer still stands. Whether you have someone or not, I want you to make it work and come to dinner. It's going to be great, you'll see!",
				choiceNext: false,
			},
			"47": {
				background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I'm still not thrilled about the idea. Why can't you just be satisfied with this one meeting?",
				choiceNext: false,
			},
			"48": {
                background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				name: "Lindsay",
				text: "Because one meeting isn't enough to make up for all the bad things I did.",
				choiceNext: false,
			},
            "49": {
				background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "And what if I say it is? That with this, everything's cleared up?",
				choiceNext: false,
			},
			"50": {
				background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "Did you really think I'd believe that?",
				choiceNext: false,
			},
			"51": {
				background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Damn it… Fine, listen, I'll think about it. Happy now?",
				choiceNext: false,
			},
			"52": {
				background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "Great! That's more than enough for today! I'll get in touch with the details later.",
				choiceNext: false,
			},
			"53": {
				background: "special_scenes/0012-18",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Fine, but I won't be upset if you forget about it… in fact, I'd prefer it.",
				choiceNext: false,
			},
			"54": {
                specialSceneId: "0012-54",
				background: "special_scenes/0012-54",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "Oh, come on! We're going to have a great time... you'll see.",
				choiceNext: false,
			},
			"55": {
                bgMusic: {
					name: 'Meeting_with_Lindsay',
					command: 'STOP'
				},
                otherSoundEffect: "lindsay_chuckles",
				background: "special_scenes/0012-54",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "*chuckles*",
				choiceNext: false,
			},
			"56": {
				background: "special_scenes/0012-54",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "...?",
				choiceNext: false,
			},
			"57": {
				background: "special_scenes/0012-54",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "What was that at the end...?",
				choiceNext: false,
				timeSkipNext: {
					content: "Later that evening...",
					nextSceneType: "MOBILE",
					nextSceneNumber: "0013",
				}
			}
		},
	},
];