export const scene_25 = [
	{
		sceneId: "0025",
		lengthNum: 53,
		story: {
			"1": {
				bgMusic: {
					name: 'ClearDay_normal_night',
					command: 'START'
				},
                background: "backgrounds/BG_reception_night",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I've finished cleaning, all that's left is to change, pack up, and head out.",
				choiceNext: false,
            },
			"2": {
				otherSoundEffect: "walk-on-corridor",
                background: "backgrounds/BG_reception_night",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Just as I'm about to start, I hear someone walk through the door.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_reception_night",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "Hey, Tyler!",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_reception_night",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Oh, Brianna! What brings you here? Did you forget something?",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_reception_night",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "No, not this time. I came to see you.",
				choiceNext: false,
			},
			"6": {
                background: "backgrounds/BG_reception_night",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "M-Me?",
				choiceNext: false,
			},
			"7": {
                background: "backgrounds/BG_reception_night",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "Yes. So, I hope you're not in a hurry, because I'd like to talk with you for a bit.",
				choiceNext: false,
            },
			"8": {
                background: "backgrounds/BG_reception_night",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Well... yeah, sure. But is everything okay?",
				choiceNext: false,
			},
			"9": {
                background: "backgrounds/BG_reception_night",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "There's no major problem, but go ahead and finish up, I'll wait for you.",
				choiceNext: false,
			},
			"10": {
                background: "backgrounds/BG_reception_night",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Alright.",
				choiceNext: false,
			},
			"11": {
                background: "backgrounds/BG_reception_night",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_smiling', null],
				class: [null, 'fadeUpOut', null],
			  	name: "",
			  	text: "I quickly change as fast as possible, and then Brianna and I head out for a little walk.",
				choiceNext: false,
			},
			"12": {
                background: "backgrounds/BG_downtown_night",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "The sky had already darkened by the time we reached one of the parks in town, which oddly feels empty tonight. I don't often come here at this time, but it's usually much busier. It wasn't hard to find an empty bench, so we sat down, and Brianna got to the point.",
				choiceNext: false,
			},
			"13": {
                bgMusic: {
					name: 'Date_with_Brianna',
					command: 'START'
				},
                specialSceneNow: true,
				specialSceneId: "0025-13",
				background: "special_scenes/0025-13",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "How was your day?",
				choiceNext: false,
			},
			"14": {
				background: "special_scenes/0025-13",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Hm... Nothing special. Long and mostly average.",
				choiceNext: false,
			},
			"15": {
				background: "special_scenes/0025-13",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "So, you're not too tired yet?",
				choiceNext: false,
			},
			"16": {
				background: "special_scenes/0025-13",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Doesn't feel like it, no.",
				choiceNext: false,
			},
			"17": {
				background: "special_scenes/0025-13",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Good...",
				choiceNext: false,
			},
			"18": {
				background: "special_scenes/0025-13",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'brianna~importants~0023-44', //reina%brianna
			  	name: "Brianna",
			  	text: [
                    "I'm sorry that I'm not yet at the level you'd want me to be. I'm trying to catch up to those clients of yours who really push themselves, but it takes time.",
                    "What you said this morning when I was with Reina meant a lot to me. I'm glad you see so much potential in me."
                ],
				choiceNext: false,
			},
			"19": {
				background: "special_scenes/0025-13",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'brianna~importants~0023-44', //reina%brianna
			  	name: "Tyler",
			  	text: [
                    "Why are you telling me this?",
                    "I only said what I truly believe. Honesty is the least I can offer my clients."
                ],
				choiceNext: false,
			},
			"20": {
				background: "special_scenes/0025-13",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'brianna~importants~0023-44', //reina%brianna
			  	name: "Brianna",
			  	text: [
                    "Because by now, I've pretty much figured out who your top clients are—the ones you respect the most. I want to be in that circle too!",
                    "I'm glad you're this way and not some people-pleaser or hypocrite who just says what others want to hear."
                ],
				choiceNext: false,
			},
			"21": {
				background: "special_scenes/0025-13",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'brianna~importants~0023-44', //reina%brianna
			  	name: "Tyler",
			  	text: [
                    "Brianna, there's no secret VIP group online or offline where I invite top clients. So, you can forget that idea... especially because, to me, you're already in a special position.",
                    "Well, back then I couldn't really say anything else because there were only two choices: either I say you're more talented, or I say Reina is. Either way, it wouldn't have felt good for the other person."
                ],
				choiceNext: false,
			},
			"22": {
				background: "special_scenes/0025-13",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'brianna~importants~0023-44', //reina%brianna
			  	name: "Brianna",
			  	text: [
                    "Oh, really? Well, it's nice to hear that, but I'd also like it if you showed that to me and to the world in other situations too.",
                    "True, but I'm glad luck was finally on my side, and you chose me."
                ],
				choiceNext: false,
			},
			"23": {
				background: "special_scenes/0025-13",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'brianna~importants~0023-44', //reina%brianna
			  	name: "Tyler",
			  	text: "I see... But I'm guessing that's not the only thing you wanted to talk to me about.",
				choiceNext: false,
			},
			"24": {
				background: "special_scenes/0025-13",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "You guessed right. It's more about something that happened a little earlier.",
				choiceNext: false,
			},
			"25": {
				background: "special_scenes/0025-13",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Are you referring to the conversation with Daena?",
				choiceNext: false,
            },
			"26": {
				background: "special_scenes/0025-13",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "More or less... I just want to know exactly where we stand.",
				choiceNext: false,
            },
			"27": {
				background: "special_scenes/0025-13",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'brianna~mobileImportants~0019-b-28',
			  	name: "Brianna",
			  	text: [
                    "When I asked if you wanted to be the focus of my desires, you immediately said yes... I'm glad you see me as a woman, but I need to know, do you just see me as a piece of meat?",
                    "When I asked if you wanted to be the focus of my desires, you responded like a proper gentleman. I just want to make sure you really meant what you said.",
                    "When I asked if you wanted to be the focus of my desires, you mentioned setting a boundary. I'd like to talk about what it would take for you to change your mind so we could cross that line together.",
                    "That day, I wanted to talk to you about my feelings—how I have desires and needs that I want to explore with you. How would you feel about that?",
                ],
				choiceNext: false,
			},
			"28": {
				background: "special_scenes/0025-13",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'brianna~mobileImportants~0019-b-28',
			  	name: "Tyler",
			  	text: [
                    "What exactly makes you doubt me like this?",
                    "What exactly have I done to make you feel so uncertain?",
                    "Why are you so eager to cross that line? I'm not offended, just curious.",
                    "Me? Hmm... I'll need some time to process this. You have so many men to choose from—why would you want to fulfill your desires with me?",
                ],
				choiceNext: false,
			},
			"29": {
				background: "special_scenes/0025-13",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'brianna~mobileImportants~0019-b-28',
			  	name: "Brianna",
			  	text: [
                    "I just want to be sure, especially after so many past disappointments.",
                    "You've done nothing wrong, and I'm glad. I just want to be certain after everything I've been through.",
                    "Isn't it obvious? I think it's pretty clear.",
                    "Isn't it obvious? I think it's pretty clear.",
                ],
				choiceNext: false,
			},
			"30": {
				background: "special_scenes/0025-13",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Out of all the men who have tried to win me over, somehow you managed to capture my attention. However you did it, this is where we are now.",
				choiceNext: false,
			},
			"31": {
				background: "special_scenes/0025-13",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "As much as I hate bringing up my age, I can't ignore the fact that there's almost a two-decade difference between us, and if things were to get serious, I fear that this could become an insurmountable obstacle between us.",
				choiceNext: false,
			},
			"32": {
				background: "special_scenes/0025-13",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "There's a serious generational gap between us, and it's possible that our interests could be totally different. I want to clear this up because I don't want to get into a relationship that's doomed from the start.",
				choiceNext: true,
			},
			"33": {
				background: "special_scenes/0025-13",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'brianna~importants~0025-32',
			  	name: "Tyler",
			  	text: [
                    "That's exactly why this is so appealing to me, because I've always been into older women.",
                    "I get your concern, but my view is that age is just a number—it only tells us how many times we've orbited the Sun.",
                    "Look… I'm not trying to be a stepdad to your daughters, and I think that's pretty clear, for a lot of reasons."
                ],
				choiceNext: false,
			},
			"34": {
				specialSceneId: "0025-34",
				background: "special_scenes/0025-34",
				backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'brianna~importants~0025-32',
			  	name: "Brianna",
			  	text: [
                    "Umm… okay… that's not quite the answer I was expecting… But if that's true, then this job must be paradise for you, with all the moms coming to see you.",
                    "Yeah. Prison's just a vacation, and Hell is just a sauna. Don't brush off the subject with such an outdated answer! I'm trying to have a serious conversation here!",
                    "I'm not asking you to be their father, but..."
                ],
				choiceNext: false,
			},
			"35": {
				background: "special_scenes/0025-34",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'brianna~importants~0025-32',
			  	name: "Tyler",
			  	text: [
                    "Hey, that doesn't mean I'm interested in every mature woman who's alive and breathing. I'm selective about who really catches my eye. And Brianna… I've had my eye on you for a long time.",
                    "I'm serious. I can't make it any clearer that the age difference just doesn't bother me at all.",
                    "But I will try my best to step up to the role. You'll raise your daughters how you want to. I can offer advice and my opinion, but I won't interfere. In everything else, I'll try to be the partner you deserve."
                ],
				choiceNext: false,
			},
			"36": {
				background: "special_scenes/0025-34",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'brianna~importants~0025-32',
			  	name: "Brianna",
			  	text: [
                    "Really? Well, it's nice to know, but… I'm not sure if I should be happy about that or not.",
                    "You say that now. But you can't keep me young forever. Soon enough, I'll start wrinkling and turning into an old lady. How do I know you won't trade me in for some younger bimbo then?",
                    "I hope you're being honest and not just telling me what I want to hear because you really hit the nail on the head with that!"
                ],
				choiceNext: false,
			},
			"37": {
				background: "special_scenes/0025-34",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'brianna~importants~0025-32',
			  	name: "Tyler",
			  	text: [
                    "I mean that in a positive way—you've already passed a serious filter with that.",
                    "Obviously, I can't offer any guarantees for something like that...",
                    "I'm being totally honest."
                ],
				choiceNext: false,
			},
			"38": {
				background: "special_scenes/0025-34",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I've always liked you, Brianna. I've noticed you for a long time, but in the beginning, you kept your distance. Lately, you've started showing me a whole new side of yourself, and it's really impressive.",
				choiceNext: false,
			},
			"39": {
				background: "special_scenes/0025-34",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I might not be the most perfect guy in the world, and I know your past disappointments left deep scars. But I'm doing everything I can to heal those wounds because I want to get to know the real Brianna—the one hiding behind the mask and her heart's defenses.",
				choiceNext: false,
			},
			"40": {
				background: "special_scenes/0025-34",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Yeah... I want that too. To trust someone again without hesitation and feel like someone genuinely cares for me...",
				choiceNext: false,
			},
			"41": {
				background: "special_scenes/0025-34",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "I never would've imagined that the person capable of this would be someone born around the time I was graduating high school! But I guess… life's unpredictable, and it still has surprises in store.",
				choiceNext: false,
			},
			"42": {
				background: "special_scenes/0025-34",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I'm doing my best to rise to the challenge.",
				choiceNext: false,
			},
            "43": {
				specialSceneId: "0025-43",
				background: "special_scenes/0025-43",
				backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "I can see that… and I appreciate it. So, thank you. I'm sure things will work out slowly but surely.",
				choiceNext: false,
			},
			"44": {
				background: "special_scenes/0025-43",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "How about we start with lunch on Saturday? At my place.",
				choiceNext: false,
			},
			"45": {
				background: "special_scenes/0025-43",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "That sounds like a great plan. I accept your invitation.",
				choiceNext: false,
			},
			"46": {
				background: "special_scenes/0025-43",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Great! Let's make it noon, and don't be late!",
				choiceNext: false,
			},
			"47": {
				background: "special_scenes/0025-43",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "So... should we keep walking for a bit?",
				choiceNext: false,
			},
			"48": {
				background: "special_scenes/0025-43",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Sure, why not?",
				choiceNext: false,
			},
			"49": {
				specialSceneNow: true,
				specialSceneOut: true,
				specialSceneId: null,
				background: "backgrounds/BG_night_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Brianna is now the third woman to confess or show her feelings for me, even though I've been unofficially dating Reina.",
				choiceNext: false,
			},
			"50": {
				background: "backgrounds/BG_night_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Some might ask why I'm juggling so many women at once. Am I just a player? Well, here's how I see it:",
				choiceNext: false,
			},
			"51": {
				background: "backgrounds/BG_night_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Reina is the most direct with me out of the four, and she's probably the closest to my heart… but she's married and doesn't seem likely to get divorced anytime soon, so we have to keep things secret.",
				choiceNext: false,
			},
			"52": {
				background: "backgrounds/BG_night_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "On the other hand, Daena is just casually dating someone, which could easily change. Brianna is divorced, and it's only a matter of breaking through that ice. Hailey's in a relationship, but it seems like she wants out if things don't improve.",
				choiceNext: false,
			},
			"53": {
				bgMusic: {
					name: 'Date_with_Brianna',
					command: 'FADE_OUT'
				},
				background: "backgrounds/BG_night_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "So why keep an eye on these three other women while I'm with Reina? Because I can be honest and open about a relationship with them. And that's not a small detail.",
				choiceNext: false,
				timeSkipNext: {
					content: "Later at home...",
					nextSceneType: "MOBILE",
					nextSceneNumber: "0026",
				}
			},
		},
	},
];