export const scene_20 = [
    { sceneId: "0019" }, //storyScene: 0019
	{
		sceneId: "0020",
		lengthNum: 66,
		story: {
			"1": {
				bgMusic: {
					name: 'Morning_normal',
					command: 'START'
				},
                background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "It's Wednesday. Finally, a day off. While I'd love to relax on my couch and recover from the exhaustion of the past few days, some people have made sure that today won't go that way either.",
				choiceNext: false,
            },
			"2": {
                background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Sure, I enjoy spending time with Reina, but sometimes I wish she'd realize that we're not the same, and not everyone likes it when days just rush by without a break, aside from sleeping at night.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "In the afternoon, I'll have plans with Hailey. Although it's just a massage, I'm hoping that, even if it's just for an hour, I won't have to do anything and can completely relax. Falling asleep while getting a massage would be quite something.",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "It would be nice, especially because yesterday, Brianna said some things to me, both in person and through messages, that kept me up at night. My mind kept racing because of them.",
				choiceNext: false,
			},
			"5": {
                bgMusic: {
					name: 'Morning_normal',
					command: 'FADE_OUT',
                    insideOfScene: true
				},
                background: "backgrounds/BG_mall_sunny",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "So, even though I was tired, I traveled to downtown Vensea and was the first to arrive at the benches. I didn't have to wait long before Reina showed up, just a little ahead of the agreed time.",
				choiceNext: false,
			},
			"6": {
                bgMusic: {
					name: 'Date_with_Reina',
					command: 'START'
				},
                background: "backgrounds/BG_mall_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "Hey Tyler! Have you been waiting long?",
				choiceNext: false,
			},
			"7": {
                background: "backgrounds/BG_mall_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Hey Reina. No, not long. But we both arrived early.",
				choiceNext: false,
            },
			"8": {
                background: "backgrounds/BG_mall_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "Of course, this way we'll have more time together.",
				choiceNext: false,
			},
			"9": {
                background: "backgrounds/BG_mall_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "That's true. So, what's the plan for today?",
				choiceNext: false,
			},
			"10": {
                background: "backgrounds/BG_mall_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "Well... it might not be a good idea to go somewhere where we can eat or drink, as that would feel too much like a date. But there are a few places I've been wanting to visit, and since you're a trainer, it wouldn't seem odd for you to come with me.",
				choiceNext: false,
			},
			"11": {
                background: "backgrounds/BG_mall_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "You lead, I'll follow!",
				choiceNext: false,
			},
			"12": {
                background: "backgrounds/BG_mall_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, 'fadeUpOut', null],
			  	name: "",
			  	text: "As it turned out, Reina had picked out some sports-themed stores. First, we visited a sports shoe store, then a regular sportswear shop, and then we checked out fitness accessories, equipment for home workouts, and so on.",
				choiceNext: false,
			},
			"13": {
                background: "backgrounds/BG_mall_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "We kept chatting all the while, though we couldn't bring up very personal or intimate topics with others around. But now and then, we'd make remarks to each other that could be subtly suggestive.",
				choiceNext: false,
			},
			"14": {
                background: "backgrounds/BG_mall_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "After the umpteenth store, we passed by a lingerie shop. Like in most places, they had mannequins with model-like figures on display, wearing some very eye-catching sets.",
				choiceNext: false,
			},
			"15": {
                background: "backgrounds/BG_mall_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I didn't mean to stare, but it only took a split second for one of the sets to grab my attention, and my gaze got stuck on it. Of course, Reina noticed right away and quickly pieced together what I was looking at so intently.",
				choiceNext: false,
			},
			"16": {
                bgMusic: {
					name: 'Intended_erotic_situation',
					command: 'START'
				},
                background: "backgrounds/BG_mall_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_seductive', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "Oh? Do you like what you see that much?",
				choiceNext: false,
			},
			"17": {
                background: "backgrounds/BG_mall_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_seductive', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Oh... um... no, I wasn't exactly staring at what I saw.",
				choiceNext: false,
			},
			"18": {
                background: "backgrounds/BG_mall_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "W-What do you mean by that?",
				choiceNext: false,
			},
			"19": {
                background: "backgrounds/BG_mall_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I mean, yes, at first, the set caught my attention, but then my brain quickly reworked the image. And soon enough, I was imagining how you would look in that set. And that's what I was really staring at.",
				choiceNext: false,
			},
			"20": {
                background: "backgrounds/BG_mall_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "Ah, now I get it. Hmm… Well, I'm sorry, but we really can't go into a store like this together because places like these are major red zones for the two of us.",
				choiceNext: false,
			},
			"21": {
                background: "backgrounds/BG_mall_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Yeah, I know.",
				choiceNext: false,
			},
			"22": {
                background: "backgrounds/BG_mall_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "But there is another clothing store I want to check out. It's not sports-related, but I don't mind if you come with me, I don't think it'll be an issue.",
				choiceNext: false,
			},
			"23": {
                background: "backgrounds/BG_mall_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "If you're sure, then let's go.",
				choiceNext: false,
			},
			"24": {
                background: "backgrounds/BG_clothing_store",
                backGroundClass: "fadeIn",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, 'fadeOut', null],
			  	name: "",
			  	text: "And that's what we do. We find the store, and once inside, Reina and I go our separate ways. She says she just wants to try on a few pieces but doesn't necessarily plan on buying anything, and she'll find me when she's done. In the meantime, I'll look for something for myself, just in case.",
				choiceNext: false,
			},
			"25": {
                background: "backgrounds/BG_clothing_store",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Barely five minutes pass when my phone vibrates with a message from her on SocialSync: \"Can you come to the fitting rooms? I'm in the farthest one on the left. I need a guy's opinion.\"",
				choiceNext: false,
            },
			"26": {
                background: "backgrounds/BG_clothing_store",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "I thought she felt this store was safe exactly because we were avoiding the fitting rooms together. But despite that, she's inviting me over... well, alright. I head over, making sure to stay alert in case I spot any familiar faces.",
                choiceNext: false,
            },
			"27": {
                background: "backgrounds/BG_clothing_store",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I arrive at the farthest fitting room on the left, though there are barely any in use. Even Reina's curtain is still drawn, so when I get there, I let her know.",
                choiceNext: false,
			},
			"28": {
                background: "backgrounds/BG_clothing_store",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Reina, I'm here.",
                choiceNext: false,
			},
			"29": {
                background: "backgrounds/BG_clothing_store",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Is the coast clear?",
                choiceNext: false,
			},
			"30": {
                background: "backgrounds/BG_clothing_store",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Yeah, I didn't see anyone.",
                choiceNext: false,
			},
			"31": {
                background: "backgrounds/BG_clothing_store",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Alright then...",
                choiceNext: false,
			},
			"32": {
                bgMusic: {
					name: 'Intended_erotic_situation',
					command: 'FADE_OUT',
                    insideOfScene: true
				},
                otherSoundEffect: "curtain",
                background: "backgrounds/BG_clothing_store",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "She pulls the curtain back and...",
                choiceNext: false,
			},
			"33": {
                bgMusic: {
					name: 'Unexpected_ecchi_moment_occurs',
					command: 'START',
				},
                specialSceneNow: true,
				specialSceneId: "0020-33",
				background: "special_scenes/0020-33",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "Oh my God! What am I seeing!?",
                choiceNext: false,
			},
			"34": {
				background: "special_scenes/0020-33",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "This totally caught me off guard—she's standing there in nothing but lingerie. I'm instantly flustered, wanting to look in every direction to make sure no familiar faces pop up... but at the same time, I can't take my eyes off her, nor do I want to. This just made my day.",
                choiceNext: false,
			},
			"35": {
				background: "special_scenes/0020-33",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Hehe. Your face says it all, but I still want to hear it—what do you think?",
                choiceNext: false,
			},
			"36": {
				background: "special_scenes/0020-33",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Well, I... I... I can't find the words. So many emotions are swirling inside me right now, I can't make sense of it—it's total chaos.",
                choiceNext: false,
			},
			"37": {
				background: "special_scenes/0020-33",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Hormones raging? Do you want to touch what you see?",
                choiceNext: false,
			},
			"38": {
				background: "special_scenes/0020-33",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Absolutely! I'm doing everything in my power to stay a gentleman and not pounce on you right here, right now!",
                choiceNext: false,
			},
			"39": {
				background: "special_scenes/0020-33",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Hehe! I've never done it in a dressing room before. It would be a perfect first time, especially with how few people are around—it could totally happen if we're quiet enough!",
                choiceNext: false,
			},
			"40": {
				background: "special_scenes/0020-33",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Would you like that? Do you want us to try each other right here and now, doing what would be absolutely taboo?",
                choiceNext: false,
			},
			"41": {
				background: "special_scenes/0020-33",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "Oh man, she's making this so difficult; she's too good at this!",
                choiceNext: false,
			},
			"42": {
				background: "special_scenes/0020-33",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Reina… I think you know well that I want to… but… well, every guy in the world would probably want to kill me for saying this… but I have to refuse.",
                choiceNext: false,
			},
			"43": {
				background: "special_scenes/0020-33",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Not because of you, but because of the situation. If there's another chance in the future, you can bet I'll take the shot without a second thought. But this is not how I imagined our first time together.",
                choiceNext: false,
			},
			"44": {
				background: "special_scenes/0020-33",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I'm sorry. I hope this doesn't make you lose all interest in me.",
                choiceNext: false,
			},
			"45": {
				background: "special_scenes/0020-33",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Honestly? This wasn't a test, it was just a spur-of-the-moment idea. But I'm glad you made that decision; you're right. I'd also want our first time to be in a more intimate setting.",
                choiceNext: false,
			},
			"46": {
				background: "special_scenes/0020-33",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Really? Oh, I'm so relieved I didn't ruin anything!",
                choiceNext: false,
			},
			"47": {
				background: "special_scenes/0020-33",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "No, no, not at all. I only did it because I saw how you were staring at the lingerie store window. It was the one moment all day that really threw you off during our date—but that's not necessarily a bad thing.",
                choiceNext: false,
			},
			"48": {
				background: "special_scenes/0020-33",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "I thought... if that sight had such an effect on you, I might as well step it up so that the most memorable impression from our date isn't a mannequin or, as you said, your imagination, but me.",
                choiceNext: false,
			},
            "49": {
				background: "special_scenes/0020-33",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "You can bet I'll never forget this sight. My eyes are already hurting from drying out—I'm afraid to blink in case I miss a single millisecond!",
                choiceNext: false,
			},
			"50": {
				background: "special_scenes/0020-33",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Hehe! Come on, no need to be that greedy. If all goes well, you'll see this sight again, and maybe even more...",
                choiceNext: false,
			},
			"51": {
                background: "special_scenes/0020-33",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "And not just see... but feel... and not just with your hands… but with your mouth... and with something a little lower too...",
                choiceNext: false,
			},
            "52": {
                background: "special_scenes/0020-33",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Reina… if you keep this up, I might not be able to hold myself back!",
                choiceNext: false,
            },
            "53": {
                background: "special_scenes/0020-33",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Hehe, okay! I guess I'll stop teasing you now.",
                choiceNext: false,
			},
			"54": {
                bgMusic: {
					name: 'Unexpected_ecchi_moment_occurs',
					command: 'FADE_OUT',
                    insideOfScene: true
				},
                background: "special_scenes/0020-33",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Huh... I wonder what others would think if they saw me in a set like this, looking this hungry?",
                choiceNext: true,
			},
			"55": {
                background: "special_scenes/0020-33",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'reina~importants~0020-54',
			  	name: "Tyler",
			  	text: [
                    "Reina, what matters most is that you feel comfortable and that you want to look good for yourself. Anyone else's opinion is secondary at best.",
                    "I don't want to think about others because I want this sight and this side of you to be my privilege alone.",
                    "Why should anyone else see this? Only your husband and daughters should see you in a set like this, no one else."
                ],
                choiceNext: false,
			},
			"56": {
                bgMusic: {
					name: ['Sad_mood_wih_a_girl', 'Determinations_for_Reina', 'Sad_mood_wih_a_girl'],
					command: ['START', 'START', 'START'],
				},
                specialSceneId: ["0020-56", "0020-33", "0020-56"],
                background: ["special_scenes/0020-56", "special_scenes/0020-33", "special_scenes/0020-56"],
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'reina~importants~0020-54',
			  	name: "Reina",
			  	text: [
                    "I don't completely ignore others' opinions, because constructive criticism has its value. Plus, your opinion matters to me, so please don't belittle yourself like that.",
                    "Oh… I'm starting to feel that you really want me all to yourself and won't share me with anyone. I like it, I'm glad you take me so seriously.",
                    "You forgot one more person… yourself. That's not insignificant. Why do you think I showed myself to you now, after years of marriage, where only my husband has seen me in lingerie?"
                ],
                choiceNext: false,
			},
			"57": {
                background: ["special_scenes/0020-56", "special_scenes/0020-33", "special_scenes/0020-56"],
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'reina~importants~0020-54',
			  	name: "Tyler",
			  	text: [
                    "I'm not belittling myself, but let's be honest—I'm not someone in your life who can tell you what you can or can't do.",
                    "I do, but I often feel uncertain whether I can indulge in these fantasies about you, especially knowing you have your family, and I feel like I'm just an intruder.",
                    "Sometimes I still doubt if I truly deserve this because it all feels so unreal, and I fear it's not really happening."
                ],
                choiceNext: false,
			},
			"58": {
                background: ["special_scenes/0020-56", "special_scenes/0020-33", "special_scenes/0020-56"],
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'reina~importants~0020-54',
			  	name: "Reina",
			  	text: [
                    "I can still ask for your opinion...",
                    "You're not an intruder; I'm the one who kissed you, so I willingly let you into my life.",
                    "It's very real, because I'm serious about this with you."
                ],
                choiceNext: false,
			},
			"59": {
                background: ["special_scenes/0020-56", "special_scenes/0020-33", "special_scenes/0020-56"],
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'reina~importants~0020-54',
			  	name: "Reina",
			  	text: "Think about it… I don't usually go out flaunting my body to the whole city of Vensea, showing off how good I look.",
                choiceNext: false,
			},
			"60": {
                background: ["special_scenes/0020-56", "special_scenes/0020-33", "special_scenes/0020-56"],
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'reina~importants~0020-54',
			  	name: "Reina",
			  	text: "And I don't even have a social media account where I post pictures like this. You are the first and, hopefully, the last reason in my life for breaking the rules. Every day, I'm crossing the lines set by the sacred bond of marriage, risking everything for you.",
                choiceNext: false,
			},
			"61": {
                specialSceneId: "0020-61",
                background: "special_scenes/0020-61",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "I'm doing all of this for you, and sincerely. Not for fun, because you're the only one I deem worthy. And not just worthy, but the one I want to show myself to, the one I want to give everything to, so that you won't even look at anyone else but me.",
                choiceNext: false,
			},
			"62": {
                background: "special_scenes/0020-61",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Alright, I understand, Reina. And I truly appreciate it. I'll work on fully accepting that this is real and it's actually happening.",
                choiceNext: false,
			},
            "63": {
                background: "special_scenes/0020-61",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "But as much as I love the view, I think it's time you pull the curtain back—you've been showing yourself like this for several minutes now.",
                choiceNext: false,
			},
			"64": {
                background: "special_scenes/0020-61",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "You're right, it did seem like a good idea, though. Alright, I'll get dressed, and we can move on.",
                choiceNext: false,
			},
			"65": {
                background: "special_scenes/0020-61",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "This was definitely the highlight of our date. I'll never forget the first time Reina shed a few pieces of clothing just to show more of herself—just for me.",
                choiceNext: false,
			},
            "66": {
                bgMusic: {
					name: ['Sad_mood_wih_a_girl', 'Determinations_for_Reina', 'Sad_mood_wih_a_girl'],
					command: ['FADE_OUT', 'FADE_OUT', 'FADE_OUT']
				},
                background: "special_scenes/0020-61",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'reina~importants~0020-54',
			  	name: "",
			  	text: "Though, to be honest, I still need to work on fully grasping that this isn't just some tease, but that things really are happening as they seem.",
                choiceNext: false,
                timeSkipNext: {
					content: "In the afternoon...",
					nextSceneType: "STORY",
					nextSceneNumber: "0021",
				}
			}
		},
	},
];