export const scene_8 = [
	{
		sceneId: "0008",
		lengthNum: 64,
		story: {
			"1": {
				bgMusic: {
					name: 'SunnyDay_normal_daily',
					command: 'START'
				},
                background: "backgrounds/BG_shop_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "In just about fifteen minutes, the two of us gathered everything Brianna needed, as well as my breakfast.",
				choiceNext: false,
            },
			"2": {
				background: "backgrounds/BG_shop_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Both my hands were full, barely able to see over the groceries, and Brianna's hands were occupied too. I honestly can't imagine how she would've carried all this to her car on her own.",
				choiceNext: false,
			},
			"3": {
				background: "backgrounds/BG_tennis_court_outside_sunny",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'brianna~notImportants~0007-33',
			  	name: "",
			  	text: [
                    "I had to walk a bit more from the store, but shortly after opening, I finally arrived at the entrance of the tennis court.",
                    "Thanks to her, I arrived at the tennis court just a few minutes after it opened.",
                ],
				choiceNext: false,
			},
			"4": {
				background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "It's been ages since I last played tennis. Probably back in my college days. I'm not terrible at it, but I definitely know enough to teach Hailey the basics.",
				choiceNext: false,
			},
			"5": {
				background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "I don't see her around yet, but she might already be inside.",
				choiceNext: false,
			},
			"6": {
				background: "backgrounds/BG_tennis_changing_room",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "At the reception, I signed in, and they told me she was already here and had even rented the court. All I had to do was change, and we'd be ready to go.",
				choiceNext: false,
			},
			"7": {
				bgMusic: {
					name: 'SunnyDay_normal_daily',
					command: 'FADE_OUT',
					insideOfScene: true
				},
				background: "backgrounds/BG_tennis_changing_room",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I walked through the hallways, and when I reached the court, Hailey was already there, bouncing the ball against the wall, practicing her forehand.",
				choiceNext: false,
			},
			"8": {
				bgMusic: {
					name: 'Haileys_competition',
					command: 'START'
				},
                specialSceneNow: true,
				specialSceneId: "0008-8",
				background: "special_scenes/0008-8",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Good morning, Hailey!",
				choiceNext: false,
			},
			"9": {
				background: "special_scenes/0008-8",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "Hey, Tyler! Hiiiii! How are ya?",
				choiceNext: false,
			},
			"10": {
				background: "special_scenes/0008-8",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Still a bit sleepy, but I'm sure I'll wake up once we get moving.",
				choiceNext: false,
			},
			"11": {
				background: "special_scenes/0008-8",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "Awesome! I've already started warming up, but this is different from a gym workout, so I'm not sure what else I should do to avoid getting injured.",
				choiceNext: false,
			},
			"12": {
				background: "special_scenes/0008-8",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Leave that to me.",
				choiceNext: false,
			},
			"13": {
				background: "special_scenes/0008-8",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "Oh, I totally will.",
				choiceNext: false,
			},
			"14": {
				background: "special_scenes/0008-8",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "After about ten minutes of warm-up, we both grab our rackets and start practicing serves. Hailey's a bit clumsy at first, holding her racket the wrong way and missing most of the balls.",
				choiceNext: false,
			},
			"15": {
				background: "special_scenes/0008-8",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "But I keep an eye on her movements, and once I've noted enough of her mistakes, I stop and give her feedback on what to focus on.",
				choiceNext: false,
			},
			"16": {
				background: "special_scenes/0008-8",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "This approach has worked well for her during our gym sessions too. She started training with me this spring, so it's only been a few months, but I quickly figured out that she's super energetic. At first glance, she looks like a spoiled, over-tanned, luxury shopping queen, but she's actually really sweet and full of energy.",
				choiceNext: false,
			},
			"17": {
				background: "special_scenes/0008-8",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "After some initial hesitation, we clicked pretty quickly—maybe because we're in the same age group, though she's a bit older than me. But she's always enthusiastic when she shows up for a workout, always aiming for big results right from the start. I often have to rein her in and correct her form, but she's definitely one of the better types of clients.",
				choiceNext: false,
			},
			"18": {
				background: "special_scenes/0008-8",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "At first, I send her some easy balls so she can get the hang of how I mix things up more than the wall does. As I expected, after making a few adjustments, she quickly picked up the movement style of the sport, and I can now send her faster, stronger shots.",
				choiceNext: false,
			},
			"19": {
				background: "special_scenes/0008-8",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "After a while, we had to pause again since she was still struggling with backhands. But after some practice against the wall, we tried rallying again, and she started to feel more confident. What I love about her is how fast she learns, and you can set real goals with her.",
				choiceNext: false,
			},
			"20": {
				background: "special_scenes/0008-8",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "As she got more into the flow of the game, we moved into a kind of casual match. We didn't bother with scoring, just focused on hitting the ball within the court's boundaries. I had her running back and forth, making her sweat pretty hard, but she held up like a champ.",
				choiceNext: false,
			},
			"21": {
				bgMusic: {
					name: 'Haileys_competition',
					command: 'FADE_OUT',
					insideOfScene: true
				},
				background: "special_scenes/0008-8",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Soon enough, our hour was up, so we had to wrap things up and let others use the court.",
				choiceNext: false,
			},
			"22": {
				bgMusic: {
					name: 'Date_with_Hailey',
					command: 'START'
				},
                background: "backgrounds/BG_tennis_court_outside_sunny",
                specialSceneNow: true,
				specialSceneOut: true,
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Back outside by the entrance, I decided to wait for her, though I knew it would take a bit since she always takes longer to change.",
				choiceNext: false,
			},
			"23": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_grin", null],
				class: [null, "fadeUp", null],
			  	name: "Hailey",
			  	text: "I'm heeere! So sorry to keep you waiting!",
				choiceNext: false,
			},
			"24": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_grin", null],
				class: [null, null, null],
				name: "Tyler",
				text: "No worries, it didn't take long. So, how'd you like it?",
				choiceNext: false,
			},
			"25": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_grin", null],
				class: [null, "fadeUp", null],
				name: "Hailey",
				text: "It was amazing and felt sooo good! Hope I wasn't too terrible!",
				choiceNext: false,
			},
			"26": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_grin", null],
				class: [null, null, null],
				name: "Tyler",
				text: "Not at all. For someone who's playing tennis for the first time, you picked it up pretty fast.",
				choiceNext: false,
			},
			"27": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_smiling", null],
				class: [null, "fadeUp", null],
			  	name: "Hailey",
			  	text: "Thanks, but it wasn't my first time. My boyfriend and I tried it a few times when he took me on vacation, but no one really explained how to play, so I was kinda winging it.",
				choiceNext: false,
			},
			"28": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_smiling", null],
				class: [null, null, null],
				name: "",
                textClass: "italic",
				text: "Her boyfriend, of course… another great girl who's already taken...",
				choiceNext: false,
			},
			"29": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_smiling", null],
				class: [null, null, null],
				name: "Tyler",
				text: "Well, I'm glad I could make it a fun experience for you this time.",
				choiceNext: false,
			},
			"30": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_smiling", null],
				class: [null, "fadeUp", null],
				name: "Tyler",
				text: "Totally!",
				choiceNext: false,
			},
			"31": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_smiling", null],
				class: [null, null, null],
				name: "Hailey",
				text: "Hey, Tyler! So, how much do I owe you?",
				choiceNext: false,
			},
			"32": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_smiling", null],
				class: [null, null, null],
				name: "Tyler",
				text: "Oh, come on, forget about that!",				
				choiceNext: false,
			},
			"33": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_angry", null],
				class: [null, "fadeUp", null],
				name: "Hailey",
				text: "No-no! I told you last minute… you had to get up at some ungodly hour… you gave me a private lesson even though you've got work later today… and on top of all that, it was such a great experience for me! No way I'm letting you get away with all that for free!",	
				choiceNext: false,
			},
			"34": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_angry", null],
				class: [null, null, null],
				name: "Tyler",
				text: "I really don't expect you to pay me. I enjoy working with you because you're so motivated and talented. So, despite the early wake-up, I was happy to do this for you.",	
				choiceNext: false,
			},
			"35": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_embarrassed", null],
				class: [null, "fadeUp", null],
				name: "Hailey",
				text: "Really? Awww, you're sooo sweet! I just love how awesome you are!",
				choiceNext: false,
			},
			"36": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_surprised", null],
				class: [null, "fadeUp", null],
				name: "Tyler",
				text: "Ah, wait! I've got an idea how I can make it up to you!",
				choiceNext: false,
			},
			"37": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_surprised", null],
				class: [null, null, null],
				name: "Tyler",
				text: "I'm listening.",
				choiceNext: false,
			},
            "38": {
				bgMusic: {
					name: 'Date_with_Hailey',
					command: 'STOP'
				},
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_seductive", null],
				class: [null, "fadeUp", null],
			  	name: "Hailey",
			  	text: "How about next time, we do something a little more… comfy and relaxing?",
				choiceNext: false,
            },
			"39": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_seductive", null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Uh… what exactly do you have in mind?",
				choiceNext: false,
			},
			"40": {
                bgMusic: {
					name: 'Hailey_ecchi',
					command: 'START'
				},
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_seductive", null],
				class: [null, "fadeUp", null],
			  	name: "Hailey",
			  	text: "A nice, intimate, sensual massage.",
				choiceNext: false,
			},
			"41": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_seductive", null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "Wait, hold up! A massage?! From a hot girl like Hailey? I definitely didn't hear that wrong… but why would she offer something like that?",
				choiceNext: true,
			},
			"42": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_seductive", null],
				class: [null, null, null],
                choicePath: 'hailey~importants~0008-41',
			  	name: "Tyler",
			  	text: [
                    "Hailey… this is something you should do with your boyfriend, not me.",
                    "Whoa! Wait, you mean… each other? Are you sure that's what you want?",
                    "Thanks, it's sweet of you, but… really, it's not necessary to return the favor.",
                ],
				choiceNext: false,
			},
			"43": {
                bgMusic: {
					name: 'Hailey_ecchi',
					command: 'STOP'
				},
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, ["Hailey/Hailey_casual_angry", "Hailey/Hailey_casual_seductive", "Hailey/Hailey_casual_sad"], null],
				class: [null, "fadeUp", null],
                choicePath: 'hailey~importants~0008-41',
			  	name: "Hailey",
			  	text: [
                    "Don't drag him into this, it's not about him, it's just about us!",
                    "No, silly! I'm sure you'd give a great massage with those strong hands of yours, and my body would totally love that, but that's not what I meant.",
                    "Tyler, that's not fair! You make big sacrifices for me, so why can't I give you something small in return?",
                ],
				choiceNext: false,
			},
			"44": {
				bgMusic: {
					name: 'Left_alone',
					command: 'START'
				},
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_normal", null],
				class: [null, "fadeUp", null],
			  	name: "Hailey",
			  	text: "My boyfriend gave me a couples' massage gift coupon, but he can't come with me because of work. We can't reschedule, and I don't want it to go to waste.",
				choiceNext: false,
			},
			"45": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_normal", null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Is there no one else, like a girlfriend, who could go with you?",
				choiceNext: false,
			},
			"46": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, ["Hailey/Hailey_casual_normal", "Hailey/Hailey_casual_normal", "Hailey/Hailey_casual_sad"], null],
				class: [null, "fadeUp", null],
                choicePath: 'hailey~importants~0008-41',
			  	name: "Hailey",
			  	text: [
                    "This is my gift, and I'll use it how I want.",
                    "A minute ago, you were imagining us massaging each other. Now, suddenly, this offer doesn't seem so appealing?",
                    "Why are you being so cold and distant with me?",
                ],
				choiceNext: false,
			},
			"47": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, ["Hailey/Hailey_casual_normal", "Hailey/Hailey_casual_normal", "Hailey/Hailey_casual_sad"], null],
				class: [null, null, null],
                choicePath: 'hailey~importants~0008-41',
			  	name: "Tyler",
			  	text: [
                    "Alright, alright. I'll accept your offer.",
                    "No… I mean, yes! I mean… ugh, there's no way I'm getting out of this smoothly!",
                    "Fine. I'll accept your offer.",
                ],
				choiceNext: false,
			},
			"48": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, ["Hailey/Hailey_casual_smiling", "Hailey/Hailey_casual_seductive", "Hailey/Hailey_casual_smiling"], null],
				class: [null, "fadeUp", null],
                choicePath: 'hailey~importants~0008-41',
			  	name: "Hailey",
			  	text: [
                    "I'm glad I managed to convince you.",
                    "Hehe! You're so cute when I manage to fluster you like this!",
                    "I'm glad I managed to convince you.",
                ],
				choiceNext: false,
			},
			"49": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, ["Hailey/Hailey_casual_smiling", "Hailey/Hailey_casual_seductive", "Hailey/Hailey_casual_smiling"], null],
				class: [null, null, null],
                choicePath: 'hailey~importants~0008-41',
			  	name: "Tyler",
			  	text: "Alright. So when's your appointment?",
				choiceNext: false,
			},
			"50": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_smiling", null],
				class: [null, "fadeUp", null],
			  	name: "Hailey",
			  	text: "It's for Wednesday afternoon. I believe you're not working then, right?",
				choiceNext: false,
			},
			"51": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_smiling", null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "That's right.",
				choiceNext: false,
			},
			"52": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_smiling", null],
				class: [null, "fadeUp", null],
			  	name: "Hailey",
			  	text: "Awesome! We'll figure out the details later. I'm so looking forward to it!",
				choiceNext: false,
			},
			"53": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_smiling", null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I hope I'll be good enough company for you.",
				choiceNext: false,
			},
			"54": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_smiling", null],
				class: [null, "fadeUp", null],
			  	name: "Hailey",
			  	text: "Sure.",
				choiceNext: false,
			},
			"55": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_embarrassed", null],
				class: [null, "fadeUp", null],
			  	name: "Hailey",
			  	text: "It's no coincidence I invited you.",
				choiceNext: false,
			},
			"56": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_embarrassed", null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Hm? Sorry, what did you say?",
				choiceNext: false,
			},
			"57": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_normal", null],
				class: [null, "fadeUp", null],
			  	name: "Hailey",
			  	text: "Nothing-nothing, it's not important.",
				choiceNext: false,
			},
			"58": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_normal", null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "But I've gotta go now, I'm working at the salon today. Have a great day, and good luck with work at the gym!",
				choiceNext: false,
			},
			"59": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_normal", null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Thanks, and good luck with your clients!",
				choiceNext: false,
			},
			"60": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_smiling", null],
				class: [null, "fadeUp", null],
			  	name: "Hailey",
			  	text: "Will do. Bye!",
				choiceNext: false,
			},
			"61": {
                background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Hailey/Hailey_casual_smiling", null],
				class: [null, "fadeUpOut", null],
				name: "",
                textClass: "italic",
				text: "…",
				choiceNext: false,
			},
			"62": {
				background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				name: "",
                textClass: "italic",
				text: "She's gone. This woman never ceases to surprise me, but this massage thing... That's a move I never saw coming…",
				choiceNext: false,
			},
			"63": {
				background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				name: "Tyler",
                textClass: "italic",
				text: "Okay, that's not entirely true, because I have fantasized about things like that before, but still... I didn't think it would actually happen... Oh well, a free massage never hurt anyone.",
				choiceNext: false,
			},
			"64": {
				bgMusic: {
					name: 'Left_alone',
					command: 'FADE_OUT'
				},
				background: "backgrounds/BG_tennis_court_outside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "I've still got a few hours before work, so I'll find something to pass the time.",
				choiceNext: false,
                timeSkipNext: {
					content: "Later that evening...",
					nextSceneType: "MOBILE",
					nextSceneNumber: "0009",
				}
			},
		},
	},
];