export const scene_9 = [
    { sceneId: "0007" }, //storyScene: 0007
    { sceneId: "0008" }, //storyScene: 0008
    {
		sceneId: "0009",
        startTime: "20:56",
        endTime: "00:17",
        timeSkipNext: {
            content: "Sunday morning",
            nextSceneType: "STORY",
            nextSceneNumber: "0010",
        },
        keepOut: [],
        bgMusic: {
            name: 'Mobile_night_normal',
            command: 'START',
        },
		textingPartner: {
            Reina: {
                isMandatory: true,
                sheStartsAt: "20:58",
                sheEndsAt: "23:16",
                messages: [
                    {
                        id: 0, 
                        isFromHer: true, 
                        text: "Hi Darling. How was your day?", 
                        waitingTime: 0,
                        typingTime: 0.5,
                    },
                    {
                        id: 1, 
                        isFromHer: false, 
                        text: "Hey Reina 😊", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 2, 
                        isFromHer: false, 
                        text: "Nothing special at work, it was a pretty chill Saturday.", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 3, 
                        isFromHer: true, 
                        text: "That's good", 
                        waitingTime: 3,
                        typingTime: 1,
                    },
                    {
                        id: 4, 
                        isFromHer: true, 
                        text: "Is that all?", 
                        waitingTime: 2,
                        typingTime: 1,
                    },
                    {
                        id: 5, 
                        isFromHer: false, 
                        text: "Yeah, why?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 6, 
                        isFromHer: true, 
                        text: "Just wondering...", 
                        waitingTime: 4,
                        typingTime: 1.5,
                        bgMusic: {
                            name: 'Mobile_night_normal',
                            command: 'STOP',
                        },
                    },
                    {
                        id: 7, 
                        isFromHer: true, 
                        text: "Is it possible I saw you today at the tennis courts by any chance?", 
                        waitingTime: 1,
                        typingTime: 3,
                        bgMusic: {
                            name: 'Mobile_night_trouble',
                            command: 'START',
                        },
                    },
                    {
                        id: 8, 
                        isFromHer: false, 
                        text:"This morning? When were you there? I didn't see you", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 9, 
                        isFromHer: true, 
                        text: "So you're not denying it", 
                        waitingTime: 1,
                        typingTime: 2,
                    },
                    {
                        id: 10, 
                        isFromHer: true, 
                        text: [
                            "I know you had an afternoon shift today, so why were you at the tennis courts early in the morning, hours before?",
                            "And I saw you getting out of a car. Who were you with?",
                        ], 
                        waitingTime: 2,
                        typingTime: 5.5,
                        choicePath: 'brianna~notImportants~0007-33',
                    },
                    {
                        id: 11, 
                        isFromHer: false, 
                        text: "Yeah, I got invited to play tennis last night...", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 12, 
                        isFromHer: false, 
                        text: "They really insisted, so I said yes", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 13, 
                        isFromHer: false, 
                        text: [
                            "We played for an hour, then went our separate ways. That's all",
                            "But I ran into another client at the store near the station, and they offered me a ride"
                        ], 
                        waitingTime: null,
                        typingTime: null,
                        choicePath: 'brianna~notImportants~0007-33',
                    },
                    {
                        id: 14, 
                        isFromHer: true, 
                        text: [
                            "And why didn't you tell me about this?", 
                            "Which client was it?"
                        ], 
                        waitingTime: 4,
                        typingTime: 4,
                        choicePath: 'brianna~notImportants~0007-33',
                    },
                    {
                        id: 15, 
                        isFromHer: false, 
                        text: [
                            "I was just talking about work earlier, I hadn't gotten to the rest yet",
                            "Does it matter? But it was Brianna"
                        ], 
                        waitingTime: null,
                        typingTime: null,
                        choicePath: 'brianna~notImportants~0007-33',
                    },
                    {
                        id: 16, 
                        isFromHer: true, 
                        text: [
                           "But when I asked if that was everything, you said yes", 
                           "How did you bump into her at the store?" 
                        ], 
                        waitingTime: 3,
                        typingTime: 3.5,
                        choicePath: 'brianna~notImportants~0007-33',
                    },
                    {
                        id: 17, 
                        isFromHer: false, 
                        text: [
                            "I was still only talking about work at the time",
                            "She's having a big family lunch and needed to do some shopping for it",
                        ], 
                        waitingTime: null,
                        typingTime: null,
                        choicePath: 'brianna~notImportants~0007-33',
                    },
                    {
                        id: 18, 
                        isFromHer: true, 
                        text: [
                            "Or maybe you're just trying to avoid the subject",
                            "I didn't realize you knew her well enough to know so much about her…"
                        ], 
                        waitingTime: 2,
                        typingTime: 3.5,
                        choicePath: 'brianna~notImportants~0007-33',
                    },
                    {
                        id: 19, 
                        isFromHer: false, 
                        text: "Reina, why are you so jealous?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 20, 
                        isFromHer: true, 
                        text: "I'm not jealous, it's just that it doesn't feel good when you don't tell me about something important like this, either beforehand or afterward", 
                        waitingTime: 4,
                        typingTime: 8,
                    },
                    {
                        id: 21, 
                        isFromHer: true, 
                        text: "I feel a little betrayed 😠", 
                        waitingTime: 2,
                        typingTime: 2,
                    },
                    {
                        id: 22, 
                        isFromHer: true, 
                        text: "	But you still haven't told me who you were playing tennis with?", 
                        waitingTime: 2,
                        typingTime: 4.5,
                    },
                    {
                        id: 23, 
                        isFromHer: false, 
                        text: [
                            "Reina, it was just a client...",
                            "I was with Hailey",
                            "Reina, it doesn't feel good that you're being so distrustful of me...",
                        ], 
                        waitingTime: null,
                        typingTime: null,
                        choiceNow: true,
                        choicePath: "reina~mobileImportants~0009-r-23",
                    },
                    {
                        id: 24, 
                        isFromHer: [false, true, false, true], 
                        text: [
                            "Her partner canceled last minute, and she couldn't think of anyone else but me",
                            "You mean that overly tanned bitch you told me about?",
                            "And besides, I don't owe you an explanation about where I am and what I do all the time",
                            "Your silence is only making you more suspicious",
                        ], 
                        waitingTime: [null, 4, null, 4],
                        typingTime: [null, 3, null, 3],
                        choicePath: "reina~mobileImportants~0009-r-23",
                    },
                    {
                        id: 25, 
                        isFromHer: [false, false, true, false], 
                        text: [
                            "And like I said, they really insisted",
                            "That was a bit harsh, don't you think? What did she ever do to you?",
                            "Fine, if that's how it is, then we're done talking for today 😡",
                            "Reina, I'm not going to engage in these baseless accusations",
                        ], 
                        waitingTime: [null, null, 6, null],
                        typingTime: [null, null, 3, null],
                        choicePath: "reina~mobileImportants~0009-r-23",
                        chatSkip: [0, 0, 24, 0],
                    },
                    {
                        id: 26,
                        isFromHer: [true, true, null, true], 
                        text: [
                            "Yeah… and it's not suspicious at all that you were her only thought",
                            "Let's just say she invited my boyfriend behind my back, and not only did you not say no, but you didn't even tell me about it!",
                            null,
                            "If you won't say anything, why shouldn't I feel like they're unfounded?",
                        ], 
                        waitingTime: [2, null, null, 2],
                        typingTime: [3, null, null, 3.5],
                        choicePath: "reina~mobileImportants~0009-r-23",
                    },
                    {
                        id: 27, 
                        isFromHer: false, 
                        text: "Reina, what else could this be but jealousy?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 28, 
                        isFromHer: true, 
                        text: "It's distrust…", 
                        waitingTime: 4,
                        typingTime: 1.5,
                    },
                    {
                        id: 29, 
                        isFromHer: true, 
                        text: [
                            "Because I don't want some fake, plastic woman to take away the man I love",
                            "Because my partner hides things from me",
                            null,
                            "Because my partner hides things from me",
                        ], 
                        waitingTime: [2, 2, null, 2],
                        typingTime: [5, 3, null, 3],
                        choicePath: "reina~mobileImportants~0009-r-23",
                    },
                    {
                        id: 30, 
                        isFromHer: false, 
                        text: [
                            "That's not going to happen...",
                            "I would have told you",
                            null,
                            "I would have told you",
                        ], 
                        waitingTime: null,
                        typingTime: null,
                        choicePath: "reina~mobileImportants~0009-r-23",
                    },
                    {
                        id: 31, 
                        isFromHer: [false, true, null, true], 
                        text: [
                            "It was just a casual tennis session, like trying out a new form of exercise",
                            "Yet, I was the one who had to bring it up",
                            null,
                            "Yet, I was the one who had to bring it up",
                        ], 
                        waitingTime: [null, 2, null, 2],
                        typingTime: [null, 3.5, null, 3.5],
                        choicePath: "reina~mobileImportants~0009-r-23",
                    },
                    {
                        id: 32, 
                        isFromHer: [true, false, null, false], 
                        text: [
                            "Are you absolutely sure?",
                            "Because that's not how I would have started our conversation today",
                            null,
                            "Because that's not how I would have started our conversation today",
                        ], 
                        waitingTime: [4, null, null, null],
                        typingTime: [2, null, null, null],
                        choicePath: "reina~mobileImportants~0009-r-23",
                    },
                    {
                        id: 33, 
                        isFromHer: false, 
                        text: "I swear on my life, it's the truth", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 34, 
                        isFromHer: true, 
                        text: "Alright... fine... 😒", 
                        waitingTime: 5,
                        typingTime: 3,
                    },
                    {
                        id: 35, 
                        isFromHer: true, 
                        text: "Let's drop this topic for today", 
                        waitingTime: 2,
                        typingTime: 3,
                    },
                    {
                        id: 36, 
                        isFromHer: false, 
                        text: "I agree, it doesn't matter anyway", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 37, 
                        isFromHer: true, 
                        text: [
                            "I hope I can trust you...",
                            "I'm going to bed now",
                            null,
                            "I'm going to bed now",
                        ], 
                        waitingTime: [3, 3, null, 3],
                        typingTime: [2.5, 2, null, 2],
                        choicePath: "reina~mobileImportants~0009-r-23",
                    },
                    {
                        id: 38, 
                        isFromHer: true, 
                        text: [
                            "As a little apology, here's a preview for tomorrow",
                            "Goodnight, and I'll see you at training tomorrow",
                            null,
                            "Goodnight, and I'll see you at training tomorrow",
                        ], 
                        waitingTime: [4, 2, null, 2],
                        typingTime: [4, 4, null, 4],
                        choicePath: "reina~mobileImportants~0009-r-23",
                        chatSkip: [0, 11, null, 11],
                        bgMusic: {
                            name: 'Mobile_night_trouble',
                            command: 'FADE_OUT',
                            insideOfScene: true
                        },
                    },
                    {
                        id: 39, 
                        isFromHer: true,
                        sentPicture: "0009-r-39",
                        text: null, 
                        waitingTime: [4, null, null, null],
                        typingTime: [4, null, null, null],
                        choicePath: "reina~mobileImportants~0009-r-23",
                        bgMusic: {
                            name: 'Mobile_night_romantic',
                            command: 'START',
                        },
                    },
                    {
                        id: 40, 
                        isFromHer: false, 
                        text: "Wow, someone looks stunning! 😋", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 41, 
                        isFromHer: false, 
                        text: "Will I see you wearing this tomorrow? 😇", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 42, 
                        isFromHer: true, 
                        text: "Maybe... 🤔", 
                        waitingTime: 3,
                        typingTime: 1.5,
                    },
                    {
                        id: 43, 
                        isFromHer: true, 
                        text: "Maybe it'll help you focus on me and not other women 😉", 
                        waitingTime: 2,
                        typingTime: 4,
                    },
                    {
                        id: 44, 
                        isFromHer: false, 
                        text: "That not neccessary, but I'll definitely keep this picture safe 🤗", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 45, 
                        isFromHer: true, 
                        text: "Glad you like it 😊", 
                        waitingTime: 3,
                        typingTime: 2,
                    },
                    {
                        id: 46, 
                        isFromHer: true, 
                        text: "But now, I'm calling it a night", 
                        waitingTime: 2,
                        typingTime: 3,
                    },
                    {
                        id: 47, 
                        isFromHer: true, 
                        text: "Goodnight, and I'll see you at training tomorrow 😘", 
                        waitingTime: 2,
                        typingTime: 4,
                    },
                    {
                        id: 48, 
                        isFromHer: false, 
                        text: "Absolutely. Goodnight, Reina", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 49, 
                        isFromHer: true, 
                        text: "Kisses 💋💋", 
                        waitingTime: 3,
                        typingTime: 1.5,
                        bgMusic: {
                            name: 'Mobile_night_romantic',
                            command: 'FADE_OUT',
                            insideOfScene: true
                        },
                    },
                ]
            },
            Lindsay: {
                isMandatory: true,
                sheStartsAt: "23:18",
                sheEndsAt: "00:15",
                messages: [
                    {
                        id: 0, 
                        isFromHer: true, 
                        text: "Hey Tyler! 😊", 
                        waitingTime: 0,
                        typingTime: 0.5,
                        bgMusic: {
                            name: 'Mobile_night_sad',
                            command: 'START',
                        },
                    },
                    {
                        id: 1, 
                        isFromHer: false, 
                        text: "Ah… hey Lindsay… what do you want?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 2, 
                        isFromHer: true, 
                        text: "What do you mean, what do I want? I just came to talk, is that a problem? 😟", 
                        waitingTime: 2,
                        typingTime: 5,
                    },
                    {
                        id: 3, 
                        isFromHer: false, 
                        text: "Well, you said some pretty harsh things when we broke up…", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 4, 
                        isFromHer: false, 
                        text: "And let's just say you weren't exactly kind when you sent me packing…", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 5, 
                        isFromHer: false, 
                        text: "And now you're texting me out of the blue… it's weird", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 6, 
                        isFromHer: true, 
                        text: "That's exactly why I'm here", 
                        waitingTime: 4,
                        typingTime: 2,
                    },
                    {
                        id: 7, 
                        isFromHer: true, 
                        text: "You're right, looking back, I said some really cruel things 😣", 
                        waitingTime: 2,
                        typingTime: 5,
                    },
                    {
                        id: 8, 
                        isFromHer: true, 
                        text: "Things you didn't deserve, and I didn't even think through 😢", 
                        waitingTime: 2,
                        typingTime: 5,
                    },
                    {
                        id: 9, 
                        isFromHer: true, 
                        text: "I don't want us to stay on bad terms forever", 
                        waitingTime: 2.5,
                        typingTime: 3.5,
                    },
                    {
                        id: 10, 
                        isFromHer: true, 
                        text: "I want to make things right and apologize 🥺🥺", 
                        waitingTime: 2,
                        typingTime: 3,
                    },
                    {
                        id: 11, 
                        isFromHer: false, 
                        text: "And what do you want from me?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 12, 
                        isFromHer: true, 
                        text: "I want us to meet", 
                        waitingTime: 3,
                        typingTime: 2,
                    },
                    {
                        id: 13, 
                        isFromHer: true, 
                        text: "I think it's only fair to do this in person", 
                        waitingTime: 1,
                        typingTime: 3.5,
                    },
                    {
                        id: 14, 
                        isFromHer: true, 
                        text: "Are you free tomorrow? 🙏", 
                        waitingTime: 3,
                        typingTime: 2,
                    },
                    {
                        id: 15, 
                        isFromHer: false, 
                        text: "I don't mind", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 16, 
                        isFromHer: false, 
                        text: "I work until early afternoon, then we can meet up somewhere", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 17, 
                        isFromHer: true, 
                        text: "Thank you for being so kind 😊", 
                        waitingTime: 2,
                        typingTime: 2.5,
                    },
                    {
                        id: 18, 
                        isFromHer: true, 
                        text: "By then, I'll have a time and place for you if that works", 
                        waitingTime: 2,
                        typingTime: 5,
                    },
                    {
                        id: 19, 
                        isFromHer: false, 
                        text: "Sounds good", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 20, 
                        isFromHer: true, 
                        text: "Alright, see you tomorrow 😌", 
                        waitingTime: 3,
                        typingTime: 2.5,
                    },
                    {
                        id: 21, 
                        isFromHer: true, 
                        text: "Have a great evening! 🌒⭐🌒⭐", 
                        waitingTime: 1,
                        typingTime: 2,
                    },
                ],
            }
        }
    },
];