export const scene_6 = [
    { sceneId: "0005" }, //storyScene: 0005
    {
		sceneId: "0006",
        startTime: "22:37",
        endTime: "00:01",
        timeSkipNext: {
            content: "Saturday morning",
            nextSceneType: "STORY",
            nextSceneNumber: "0007",
        },
        keepOut: ['Lindsay Lawrie'],
        bgMusic: {
            name: 'Mobile_night_normal',
            command: 'START',
        },
		textingPartner: {
            Hailey: {
                isMandatory: true,
                sheStartsAt: "22:39",
                sheEndsAt: "23:59",
                messages: [
                    {
                        id: 0, 
                        isFromHer: true, 
                        text: "Hellooo Coach! 👋", 
                        waitingTime: 0,
                        typingTime: 0.5,
                    },
                    {
                        id: 1, 
                        isFromHer: true, 
                        text: "U still awake? 🤔", 
                        waitingTime: 1,
                        typingTime: 1.5,
                    },
                    {
                        id: 2, 
                        isFromHer: false, 
                        text: "Hey Hailey, yeah I'm still up. What's up?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 3, 
                        isFromHer: true, 
                        text: "Sooo sorryyy, like really, for asking last minute but...", 
                        waitingTime: 2,
                        typingTime: 4,
                    },
                    {
                        id: 4, 
                        isFromHer: true, 
                        text: "Are you free tomorrow morning for a lil' tennis? 😣😣", 
                        waitingTime: 1,
                        typingTime: 3.5,
                    },
                    {
                        id: 5, 
                        isFromHer: false, 
                        text: "Well… I only work in the afternoon tomorrow, but you really are asking kinda late", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 6, 
                        isFromHer: true, 
                        text: "I know, I know, and I'm really sorry! 🥺🥺", 
                        waitingTime: 3,
                        typingTime: 3,
                    },
                    {
                        id: 7, 
                        isFromHer: true, 
                        text: "I swear I'll make it up to you, promise 🤙", 
                        waitingTime: 1,
                        typingTime: 3,
                    },
                    {
                        id: 8, 
                        isFromHer: true, 
                        text:"But my friend canceled last minute, and now I've got no one 😭😭", 
                        waitingTime: 1,
                        typingTime: 4,
                    },
                    {
                        id: 9, 
                        isFromHer: true, 
                        text: "You're like, my only hope!", 
                        waitingTime: 2,
                        typingTime: 2,
                    },
                    {
                        id: 10, 
                        isFromHer: true, 
                        text: "Pleeaaaseee!🙏🙏🙏", 
                        waitingTime: 1,
                        typingTime: 1.5,
                    },
                    {
                        id: 11, 
                        isFromHer: false, 
                        text: "Alright, fine", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 12, 
                        isFromHer: false, 
                        text: "Haven't played tennis in a while anyway", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 13, 
                        isFromHer: true, 
                        text: "OMG, really?!😮😮", 
                        waitingTime: 4,
                        typingTime: 1.5,
                    },
                    {
                        id: 14, 
                        isFromHer: true, 
                        text: "Amaaazing!!!🤩🎉🎾", 
                        waitingTime: 1,
                        typingTime: 1.5,
                    },
                    {
                        id: 15, 
                        isFromHer: true, 
                        text: "Thank you-thank you-thank youuu!🥰🥰", 
                        waitingTime: 1,
                        typingTime: 3,
                    },
                    {
                        id: 16, 
                        isFromHer: true, 
                        text: "You're the best, love ya!😘", 
                        waitingTime: 1.5,
                        typingTime: 2,
                    },
                    {
                        id: 17, 
                        isFromHer: true, 
                        text: "You know where the tennis courts are in Vensea, right?", 
                        waitingTime: 2,
                        typingTime: 4,
                    },
                    {
                        id: 18, 
                        isFromHer: false, 
                        text: "I'll find my way", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 19, 
                        isFromHer: false, 
                        text: "GPS is my friend", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 20, 
                        isFromHer: true, 
                        text: "Perf!👍", 
                        waitingTime: 4,
                        typingTime: 1,
                    },
                    {
                        id: 21, 
                        isFromHer: true, 
                        text: "I'll be there right when they open", 
                        waitingTime: 1,
                        typingTime: 2.5,
                    },
                    {
                        id: 22, 
                        isFromHer: true, 
                        text: "No worries if you're a bit late, I'll prob take forever to change anyway🤣🤣", 
                        waitingTime: 1.5,
                        typingTime: 5,
                    },
                    {
                        id: 23, 
                        isFromHer: false, 
                        text: "I'll try not to be late, but noted", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 24, 
                        isFromHer: true, 
                        text: "Whatever you want", 
                        waitingTime: 3,
                        typingTime: 1.5,
                    },
                    {
                        id: 25, 
                        isFromHer: true, 
                        text: "Alrighty, I'm off then😴😴", 
                        waitingTime: 1,
                        typingTime: 2,
                    },
                    {
                        id: 26, 
                        isFromHer: true, 
                        text: "Thanks sooo much again!😚😚", 
                        waitingTime: 1,
                        typingTime: 2,
                    },
                    {
                        id: 27, 
                        isFromHer: true, 
                        text: "See ya in the morning!⏰", 
                        waitingTime: 1,
                        typingTime: 2,
                    },
                    {
                        id: 28, 
                        isFromHer: true, 
                        text: "Kisses!💋💋", 
                        waitingTime: 2,
                        typingTime: 1.5,
                        canSpeedUp: [true, "23:59"]
                    },
                ]
            }
        }
    },
];