export const scene_16 = [
    { sceneId: "0014" }, //storyScene: 0014
    { sceneId: "0015" }, //storyScene: 0015
    {
		sceneId: "0016",
        startTime: "20:06",
        endTime: "23:26",
        timeSkipNext: {
            content: "Tuesday morning",
            nextSceneType: "STORY",
            nextSceneNumber: "0017",
        },
        keepOut: [],
        bgMusic: {
            name: 'Mobile_night_normal',
            command: 'START',
        },
		textingPartner: {
            Daena: {
                isMandatory: false,
                sheStartsAt: "20:08",
                sheEndsAt: "22:21",
                messages: [
                    {
                        id: 0, 
                        isFromHer: true, 
                        text: "Hey Tyler", 
                        waitingTime: 0,
                        typingTime: 0.5,
                    },
                    {
                        id: 1, 
                        isFromHer: true, 
                        text: "U free rn?", 
                        waitingTime: 1,
                        typingTime: 1.5,
                    },
                    {
                        id: 2, 
                        isFromHer: true, 
                        text: "SOS 😫😫", 
                        waitingTime: 3,
                        typingTime: 1,
                    },
                    {
                        id: 3, 
                        isFromHer: false, 
                        text: "Hey Daena, what's wrong? Is it urgent?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 4, 
                        isFromHer: true, 
                        text: "Kinda big, but not urgent urgent", 
                        waitingTime: 3,
                        typingTime: 3,
                    },
                    {
                        id: 5, 
                        isFromHer: true, 
                        text: "Just need advice😔", 
                        waitingTime: 2,
                        typingTime: 2,
                    },
                    {
                        id: 6, 
                        isFromHer: false, 
                        text: "What happened?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 7, 
                        isFromHer: true, 
                        text:"Is it possible for you to check my body shape online sometimes?", 
                        waitingTime: 5,
                        typingTime: 6,
                    },
                    {
                        id: 8, 
                        isFromHer: true, 
                        text: "I mean, like if I send pics?", 
                        waitingTime: 3,
                        typingTime: 3,
                    },
                    {
                        id: 9, 
                        isFromHer: false, 
                        text: "I can only help if I see what the problem is", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 10, 
                        isFromHer: true, 
                        text: "K, sending it now", 
                        waitingTime: 4,
                        typingTime: 2,
                    },
                    {
                        id: 11, 
                        isFromHer: true, 
                        sentPicture: "0016-d-12",
                        text: null, 
                        waitingTime: 3,
                        typingTime: 2,
                        bgMusic: {
                            name: 'Mobile_night_ecchi',
                            command: 'START',
                        },
                    },
                    {
                        id: 12, 
                        isFromHer: true, 
                        text: "See the issue?", 
                        waitingTime: 4,
                        typingTime: 1.5,
                    },
                    {
                        id: 13, 
                        isFromHer: false, 
                        text: "Not entirely sure what I'm looking for", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 14, 
                        isFromHer: true, 
                        text: "Ugh, it's obvious 😤", 
                        waitingTime: 3,
                        typingTime: 2,
                    },
                    {
                        id: 15, 
                        isFromHer: true, 
                        text: "I tried on my school uniform to see if it still fits for next term...", 
                        waitingTime: 2,
                        typingTime: 6,
                    },
                    {
                        id: 16, 
                        isFromHer: true, 
                        text: "It fits everywhere else, but the buttons at the chest popped open!", 
                        waitingTime: 1.5,
                        typingTime: 6,
                    },
                    {
                        id: 17, 
                        isFromHer: true, 
                        text: "Total disaster!🤬🤬🤬", 
                        waitingTime: 3,
                        typingTime: 1.5,
                    },
                    {
                        id: 18, 
                        isFromHer: true, 
                        text: "My torso's getting wider, and now my shirt doesn't fit!😠", 
                        waitingTime: 2,
                        typingTime: 5,
                    },
                    {
                        id: 19, 
                        isFromHer: true, 
                        text: "What should I do?? Can I even fix this??", 
                        waitingTime: 3,
                        typingTime: 4,
                    },
                    {
                        id: 20, 
                        isFromHer: false, 
                        text: "Daena… it's simpler than that… your breasts have grown since the end of the school year", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 21, 
                        isFromHer: true, 
                        text: "But I didn't even need to buy new bras", 
                        waitingTime: 4,
                        typingTime: 3.5,
                    },
                    {
                        id: 22, 
                        isFromHer: false, 
                        text: "How do they feel to wear now?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 23, 
                        isFromHer: true, 
                        text: "They fit just right", 
                        waitingTime: 3,
                        typingTime: 2,
                    },
                    {
                        id: 24,
                        isFromHer: false, 
                        text: "And before?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 25, 
                        isFromHer: true, 
                        text: "...", 
                        waitingTime: 5,
                        typingTime: 0.5,
                    },
                    {
                        id: 26, 
                        isFromHer: true, 
                        text: "You're right, they did feel a bit roomier😯", 
                        waitingTime: 2,
                        typingTime: 4,
                    },
                    {
                        id: 27, 
                        isFromHer: true, 
                        text: "But I thought it was just because they shrank in the wash😕", 
                        waitingTime: 2,
                        typingTime: 5,
                    },
                    {
                        id: 28, 
                        isFromHer: false, 
                        text: "That's unlikely", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 29, 
                        isFromHer: true, 
                        text: "So, what do I do about this?", 
                        waitingTime: 3,
                        typingTime: 3,
                    },
                    {
                        id: 30, 
                        isFromHer: true, 
                        text: "How long will my breasts keep growing?🤔", 
                        waitingTime: 2,
                        typingTime: 4,
                    },
                    {
                        id: 31, 
                        isFromHer: false, 
                        text: [
                            "Unfortunately, no one can tell for sure, but listen...",
                            "I don't know, but next time, give me a heads-up before sending a photo like that",
                            "Your body is still developing"
                        ], 
                        waitingTime: null,
                        typingTime: null,
                        choiceNow: true,
                        choicePath: "daena~mobileImportants~0016-d-31",
                    },
                    {
                        id: 32, 
                        isFromHer: false, 
                        text: [
                            "The boys are going to love that",
                            "Because if anyone had seen that, I could've been accused of something... unpleasant",
                            "But it's not a bad thing; it could be useful for you"
                        ], 
                        waitingTime: null,
                        typingTime: null,
                        choicePath: "daena~mobileImportants~0016-d-31",
                    },
                    {
                        id: 33, 
                        isFromHer: true, 
                        text: [
                            "I couldn't care less about them, there's only one guy I'm focused on",
                            "Jeez, Tyler… I'm over 18!😞",
                            "Useful? How?😨"
                        ], 
                        waitingTime: 3,
                        typingTime: [5, 2.5, 1.5],
                        choicePath: "daena~mobileImportants~0016-d-31",
                    },
                    {
                        id: 34, 
                        isFromHer: false, 
                        text: [
                            "Yeah… your dating mate, I know",
                            "But that's not always something people can see at first glance",
                            "It can help with dating, picking decorative clothes, boosting your confidence, reproduction, to name a few"
                        ], 
                        waitingTime: null,
                        typingTime: null,
                        choicePath: "daena~mobileImportants~0016-d-31",
                    },
                    {
                        id: 35, 
                        isFromHer: true, 
                        text: [
                            "Yeah... right...😔",
                            "Well, thanks for that",
                            "Really? I didn't know all that😕",
                        ], 
                        waitingTime: 3,
                        typingTime: [2, 2.5, 3],
                        choicePath: "daena~mobileImportants~0016-d-31",
                    },
                    {
                        id: 36, 
                        isFromHer: false, 
                        text: "Can I help you with anything else?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 38, 
                        isFromHer: true,
                        text: "No, thanks", 
                        waitingTime: 4,
                        typingTime: 1,
                    },
                    {
                        id: 39, 
                        isFromHer: true,
                        text: "I have to go now, but I'll be back for tomorrow's workout", 
                        waitingTime: 1,
                        typingTime: 5,
                        choicePath: "daena~mobileImportants~0016-d-31",
                        chatSkip: [0, 1, 0],
                    },
                    {
                        id: 40, 
                        isFromHer: true,
                        text: [
                            "Bye",
                            null,
                            "Thanks for the reassurance, gn8 🌛"
                        ], 
                        waitingTime: 2,
                        typingTime: [0.5, null, 2.5],
                        choicePath: "daena~mobileImportants~0016-d-31",
                    }
                ],
            },
            Brianna: {
                isMandatory: false,
                sheStartsAt: "20:51",
                sheEndsAt: "23:25",
                messages: [
                    {
                        id: 0, 
                        isFromHer: true, 
                        text: "Hi Tyler", 
                        waitingTime: 0,
                        typingTime: 0.5,
                    },
                    {
                        id: 1, 
                        isFromHer: true, 
                        text: "Do you have a moment for a quick chat?🙂", 
                        waitingTime: 2,
                        typingTime: 3.5,
                    },
                    {
                        id: 2, 
                        isFromHer: false, 
                        text: "Hi Brianna, of course. I'm all ears", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 3, 
                        isFromHer: true, 
                        text: "I just wanted to apologize for the argument with Hailey today", 
                        waitingTime: 3,
                        typingTime: 5.5,
                    },
                    {
                        id: 4, 
                        isFromHer: true, 
                        text: "Looking back, I think I overreacted to that age comment😔", 
                        waitingTime: 2,
                        typingTime: 5,
                    },
                    {
                        id: 5, 
                        isFromHer: true, 
                        text: "It's a sensitive issue for me, and I don't always handle it well when it comes up", 
                        waitingTime: 4,
                        typingTime: 6,
                    },
                    {
                        id: 6, 
                        isFromHer: false, 
                        text: "Anyone who can get upset is also capable of forgiveness... I'm glad you're choosing that", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 7, 
                        isFromHer: false, 
                        text: "But the person you really need to apologize to is Hailey", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 8, 
                        isFromHer: true, 
                        text: "I will, when I see her next time", 
                        waitingTime: 3,
                        typingTime: 3.5,
                    },
                    {
                        id: 9, 
                        isFromHer: true, 
                        text: [
                            "She'll probably love that she came out of this looking the best",
                            "Though it'll be tough, especially since you sided with me",
                            "At least we're in the same boat, both of us getting told off"
                        ], 
                        waitingTime: 2,
                        typingTime: 5,
                        choicePath: "brianna~importants~0014-38",
                    },
                    {
                        id: 10, 
                        isFromHer: true, 
                        text: "But I'll try to be more restrained in the future", 
                        waitingTime: 3,
                        typingTime: 4,
                    },
                    {
                        id: 11, 
                        isFromHer: false, 
                        text: "I think you're already holding too much inside as it is", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 12, 
                        isFromHer: false, 
                        text: "If anyone, I can tell you're under a lot of pressure and it weighs on you that there's no one to share it with", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 13, 
                        isFromHer: false, 
                        text: "So, it's understandable that you snapped, it just wasn't the best moment for it", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 14, 
                        isFromHer: true, 
                        text: "Well, you're right... mostly...", 
                        waitingTime: 4,
                        typingTime: 3.5,
                    },
                    {
                        id: 15, 
                        isFromHer: true, 
                        text: "But I don't want to burden others more; everyone has their own problems", 
                        waitingTime: 2,
                        typingTime: 5.5,
                    },
                    {
                        id: 16, 
                        isFromHer: false, 
                        text: "I'm always here to listen if you need it", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 17, 
                        isFromHer: true, 
                        text: "You already do more than enough for me😊", 
                        waitingTime: 4,
                        typingTime: 3.5,
                    },
                    {
                        id: 18, 
                        isFromHer: true, 
                        text: "You're patient and persistent with me", 
                        waitingTime: 2,
                        typingTime: 3.5,
                    },
                    {
                        id: 19, 
                        isFromHer: true, 
                        text: "You adjust my workouts to match my energy levels", 
                        waitingTime: 2,
                        typingTime: 4.5,
                    },
                    {
                        id: 20, 
                        isFromHer: true, 
                        text: "And thanks to you, I'm still fit and healthy to this day😊", 
                        waitingTime: 2,
                        typingTime: 5,
                    },
                    {
                        id: 21, 
                        isFromHer: true, 
                        text: "I can see it in the mirror, and even my male coworkers constantly flirt with me at the office...", 
                        waitingTime: 2,
                        typingTime: 7,
                    },
                    {
                        id: 22, 
                        isFromHer: true, 
                        text: "Which, of course, doesn't make the other women too happy, but I enjoy it😏", 
                        waitingTime: 2,
                        typingTime: 6,
                    },
                    {
                        id: 23, 
                        isFromHer: false, 
                        text: [
                            "I thought you didn't want a man in your life",
                            "Those guys are lucky to have you around",
                            "I'm doing this for you, not for the other guys",
                            "Do you really enjoy being the center of attention that much?"
                        ], 
                        waitingTime: null,
                        typingTime: null,
                        choiceNow: true,
                        choicePath: "brianna~mobileImportants~0016-b-23",
                    },
                    {
                        id: 24, 
                        isFromHer: true, 
                        text: [
                            "I never said I never wanted one",
                            "I see that \"luck\" a bit differently",
                            "Oh, Tyler...😊😇",
                            "I just like the positive attention"
                        ], 
                        waitingTime: 4,
                        typingTime: [3.5, 3.5, 1, 3.5],
                        choicePath: "brianna~mobileImportants~0016-b-23",
                    },
                    {
                        id: 25, 
                        isFromHer: true, 
                        text: [
                            "With the right man, that could change anytime",
                            "I'd feel \"lucky\" for a different reason",
                            "I love how you are... never change😊🤗",
                            "But sometimes it's overwhelming with how they come onto me😩"
                        ], 
                        waitingTime: 2,
                        typingTime: [4, 4, 3.5, 5],
                        choicePath: "brianna~mobileImportants~0016-b-23",
                    },
                    {
                        id: 26, 
                        isFromHer: false, 
                        text: [
                            "Really? You've never said that since I've known you",
                            "Like what?",
                            "I'll do my best",
                            "But couldn't it boost your confidence?"
                        ], 
                        waitingTime: null,
                        typingTime: null,
                        choicePath: "brianna~mobileImportants~0016-b-23",
                    },
                    {
                        id: 27, 
                        isFromHer: true, 
                        text: [
                            "People come and go in my life…",
                            "If not many, but one particular person entered my life",
                            "Speaking of which, I'd like to send you something...",
                            "But it mostly causes awkward moments😞"
                        ], 
                        waitingTime: 3,
                        typingTime: [3.5, 5, 5, 4],
                        choicePath: "brianna~mobileImportants~0016-b-23",
                    },
                    {
                        id: 28, 
                        isFromHer: [true, false, true, false], 
                        sentPicture: [null, null, '0016-b-28', null],
                        text: [
                            "There could be someone who can change everything at any moment",
                            "I'm sure someone will come along sooner or later",
                            null,
                            "Well, it depends on how one sees it"
                        ], 
                        waitingTime: 2,
                        typingTime: [5.5, null, 2, 3],
                        choicePath: "brianna~mobileImportants~0016-b-23",
                        bgMusic: {
                            name: 'Mobile_night_romantic',
                            command: [null, null, 'START', null],
                        },
                    },
                    {
                        id: 29, 
                        isFromHer: [false, true, true, true],  
                        text: [
                            "I'm sure someone will come along sooner or later",
                            "Yes",
                            "I took this one at the office recently😊😊",
                            "Yes"
                        ], 
                        waitingTime: 4,
                        typingTime: [null, 1, 3.5, 1],
                        choicePath: "brianna~mobileImportants~0016-b-23",
                    },
                    {
                        id: 30, 
                        isFromHer: [true, true, false, true], 
                        text: [
                            "Yes… okay, if you don't mind, I'll go now",
                            "But if you don't mind, I'll be off now",
                            "You look really lovely and happy",
                            "But if you don't mind, I'll be off now"
                        ], 
                        waitingTime: 2,
                        typingTime: [4, 4, null, 5],
                        choicePath: "brianna~mobileImportants~0016-b-23",
                    },
                    {
                        id: 31, 
                        isFromHer: true, 
                        text: [
                            "Thanks for your time, goodnight",
                            "Thanks for your time, goodnight",
                            "Thanks, I was😉",
                            "Thanks for your time, goodnight"
                        ], 
                        waitingTime: 3,
                        typingTime: [3, 3, 1.5, 3],
                        choicePath: "brianna~mobileImportants~0016-b-23",
                        chatSkip: [5, 5, 0, 5],
                    },
                    {
                        id: 32, 
                        isFromHer: [null, null, true, null], 
                        text: [
                            null,
                            null,
                            "Got some compliments after a good workout",
                            null
                        ], 
                        waitingTime: 2,
                        typingTime: [null, null, 4, null],
                        choicePath: "brianna~mobileImportants~0016-b-23",
                    },
                    {
                        id: 33, 
                        isFromHer: [null, null, false, null], 
                        text: [
                            null,
                            null,
                            "We'll keep it up, so I can keep seeing you this happy",
                            null
                        ], 
                        waitingTime: null,
                        typingTime: null,
                        choicePath: "brianna~mobileImportants~0016-b-23",
                    },
                    {
                        id: 34, 
                        isFromHer: [null, null, true, null], 
                        text: [
                            null,
                            null,
                            "Okay, I'm in for that😊😊",
                            null
                        ], 
                        waitingTime: 4,
                        typingTime: [null, null, 2.5, null],
                        choicePath: "brianna~mobileImportants~0016-b-23",
                    },
                    {
                        id: 35, 
                        isFromHer: [null, null, true, null], 
                        text: [
                            null,
                            null,
                            "But now, if you don't mind, I'll go",
                            null
                        ], 
                        waitingTime: 2,
                        typingTime: [null, null, 4, null],
                        choicePath: "brianna~mobileImportants~0016-b-23",
                    },
                    {
                        id: 36, 
                        isFromHer: [null, null, true, null], 
                        text: [
                            null,
                            null,
                            "Thanks for your time, see you at the workout tomorrow… goodnight!😚",
                            null
                        ], 
                        waitingTime: 3,
                        typingTime: [null, null, 6, null],
                        choicePath: "brianna~mobileImportants~0016-b-23",
                    },
                    {
                        id: 37, 
                        isFromHer: false, 
                        text: [
                            null,
                            null,
                            "Alright, goodnight",
                            null
                        ], 
                        waitingTime: null,
                        typingTime: null,
                        choicePath: "brianna~mobileImportants~0016-b-23",
                        canSpeedUp: [true, "23:25"]
                    }
                ]
            }
        }
    },
];