export const scene_15 = [
	{
		sceneId: "0015",
		lengthNum: 61,
		story: {
			"1": {
				bgMusic: {
					name: 'FittnessRoom_normal_daily',
					command: 'START'
				},
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "After Hailey and Brianna's conflict, the rest of the workday went by more smoothly. Today, I work until the mid-afternoon, and Daena and her mom, Angie, are among my last clients.",
				choiceNext: false,
            },
			"2": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "As Daena mentioned earlier, she arrived in a rush for today's session. Her mom was already here by then, so I handed her the workout clothes she dropped off yesterday, she changed, and we got started with the workout.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Most of the time, they work out as a duo with me, but sometimes, if schedules don't line up, they come separately. Performance-wise, nothing extraordinary — Angie just wants to stay fit, and Daena is looking to lose weight, though she's not pushing herself too hard.",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "However, after our chat last Friday, Daena seems more determined. I hope her enthusiasm lasts in the long term.",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "The workout goes smoothly without any major events. Daena comes out of the locker room first, and while waiting for her mom, she comes over to the desk to chat.",
				choiceNext: false,
			},
			"6": {
				background: "backgrounds/BG_reception_sunny",
                backGroundClass: "fadeIn",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, 'fadeUp', null],
                choicePath: 'daena~importants~0005-19',
			  	name: "Daena",
			  	text: [
                    "Whew, that was rough. You weren't kiddin' when you said I should expect harder workouts.",
                    "So, what do you think? I tried to change my attitude a bit, hope it showed."
                ],
				choiceNext: false,
			},
			"7": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, null, null],
                choicePath: 'daena~importants~0005-19',
			  	name: "Tyler",
			  	text: [
                    "Daena, have I ever lied to you?",
                    "Yeah, it showed. It's a good start, and we can totally build on that for the future."
                ],
			},
			"8": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, ['Daena/Daena_casual_normal', 'Daena/Daena_casual_smiling'], null],
				class: [null, 'fadeUp', null],
                choicePath: 'daena~importants~0005-19',
			  	name: "Daena",
			  	text: [
                    "Hmm, dunno, never really tested it, but I sure hope not.",
                    "Awesome! This is about all I can handle right now, but fingers crossed you're right, and I can keep pushing myself."
                ],
				choiceNext: false,
			},
			"9": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, [null, 'fadeUp'], null],
                choicePath: 'daena~importants~0005-19',
			  	name: "Daena",
			  	text: "Sooo, can I switch gears for a sec and talk about what went down last time…?",
				choiceNext: false,
			},
			"10": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, ['Daena/Daena_casual_sad', 'Daena/Daena_casual_sad', 'Daena/Daena_casual_normal'], null],
				class: [null, ['fadeUp', 'fadeUp', null], null],
                choicePath: 'daena~importants~0011-40',
			  	name: "Daena",
			  	text: [
                    "Kinda hurt that you treated my personal issue like it was just some work thing, y'know?",
                    "Would've been nice to have some backup during that argument with Reina... just sayin'.",
                    "I love that you see me as one of your special clients, but sometimes I wonder if I really deserve it.",
                ],
				choiceNext: false,
			},
			"11": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, ['Daena/Daena_casual_sad', 'Daena/Daena_casual_sad', 'Daena/Daena_casual_normal'], null],
				class: [null, null, null],
                choicePath: 'daena~importants~0011-40',
			  	name: "Tyler",
			  	text: [
                    "Oh, Daena, are we still stuck on this?",
                    "I'm sorry, but you two were fighting over stuff I couldn't exactly figure out who was right or wrong.",
                    "You've always been special to me, Daena. No question, I'll help you with anything you need.",
                ],
			},
			"12": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, ['Daena/Daena_casual_sad', 'Daena/Daena_casual_sad', 'Daena/Daena_casual_normal'], null],
				class: [null, null, null],
                choicePath: 'daena~importants~0011-40',
			  	name: "Tyler",
			  	text: "I just didn't want you two arguing in the gym. It was getting uncomfortable, and I didn't want any drama. I had to shut it down, however it turned out.",
				choiceNext: false,
			},
			"13": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "Y-Yeah, I get it. Sorry for not thinking about how awkward it might've been for you. I'll try to be more careful next time.",
				choiceNext: false,
			},
			"14": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "But until then, I wanna make it up to you with a personal request. Hope I can count on you for this.",
				choiceNext: false,
			},
			"15": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "What's on your mind?",
				choiceNext: false,
			},
			"16": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "It's about my body shape. I can't really see the changes in the mirror, but I'm sure you've got a better, more objective view. Think you could give me some honest feedback?",
				choiceNext: false,
			},
			"17": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Well... that's doable. You'd just need to wear something more fitted so I can really see your lines and give you an accurate opinion.",
				choiceNext: false,
			},
			"18": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "So, like, you can't really check out my upper body ‘cause I'm wearing this loose top, huh?",
				choiceNext: true,
			},
			"19": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, null, null],
                choicePath: 'daena~notImportants~0015-18',
			  	name: ["", "Tyler"],
                textClass: ["italic", null],
			  	text: [
                    "No way am I saying that out loud!",
                    "Yeah..."
                ],
				choiceNext: false,
			},
			"20": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Unfortunately...",
				choiceNext: false,
			},
			"21": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_surprised', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "Unfortunately?",
				choiceNext: false,
			},
			"22": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_surprised', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I-I mean… unfortunately, it covers too much, so I can't really give you an opinion?",
				choiceNext: false,
			},
			"23": {
                bgMusic: {
					name: 'FittnessRoom_normal_daily',
					command: 'FADE_OUT',
                    insideOfScene: true
				},
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "Hmm… okay… How about this then?",
				choiceNext: false,
			},
			"24": {
                bgMusic: {
					name: 'Intended_erotic_situation',
					command: 'START'
				},
                specialSceneNow: true,
				specialSceneId: "0015-24",
				background: "special_scenes/0015-24",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, 'fadeUpOut', null],
				name: "",
                textClass: "italic",
				text: "Oh my God! What is this girl doing?!",
				choiceNext: false,
			},
			"25": {
				background: "special_scenes/0015-24",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
                text: "These tight jeans show everything just fine, don't they?",
                choiceNext: false,
            },
			"26": {
                background: "special_scenes/0015-24",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
                text: "D-D-Daena! Please turn around!",
				choiceNext: false,
			},
			"27": {
                background: "special_scenes/0015-24",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Why?",
				choiceNext: false,
			},
			"28": {
                background: "special_scenes/0015-24",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Because if someone walks in right now, or if your mom comes out of the locker room, this is gonna look really bad!",
				choiceNext: false,
			},
			"29": {
                background: "special_scenes/0015-24",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "But it's just my thighs and butt that matter, right? You can see my thighs either way, and I can't exactly show you my butt if I'm facing you.",
				choiceNext: false,
			},
			"30": {
                background: "special_scenes/0015-24",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Okay, that's true. But, please, this really isn't the right time!",
				choiceNext: false,
			},
			"31": {
                background: "special_scenes/0015-24",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Is there a better time for my coach to visually assess my butt? What makes another time better? Stripping down to a thong?",
				choiceNext: false,
			},
			"32": {
                background: "special_scenes/0015-24",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "Oh man, I just pictured that… What am I thinking? I need to get out of this quick!",
				choiceNext: false,
			},
			"33": {
                background: "special_scenes/0015-24",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
                text: "Okay, umm… it looks round and firm… from the side, it's got a nice curve, and from behind, you can definitely see the shape.",
				choiceNext: false,
			},
			"34": {
                background: "special_scenes/0015-24",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "And is that good? It's not too big?",
				choiceNext: false,
			},
			"35": {
                background: "special_scenes/0015-24",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "... If it fits in a guy's hand, then it's perfect.",
				choiceNext: false,
			},
			"36": {
                background: "special_scenes/0015-24",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Yeah? Hmm...",
				choiceNext: false,
			},
			"37": {
                background: "special_scenes/0015-24",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "So, could you–",
				choiceNext: false,
			},
			"38": {
                background: "special_scenes/0015-24",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "No!",
				choiceNext: false,
			},
			"39": {
                background: "special_scenes/0015-24",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Sorry, Daena, but you'll have to feel that out for yourself.",
				choiceNext: false,
			},
			"40": {
                background: "special_scenes/0015-24",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "But my hand's not as big as a guy's.",
				choiceNext: false,
			},
			"41": {
                background: "special_scenes/0015-24",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Then trust my word—this butt fits you perfectly.",
				choiceNext: false,
			},
			"42": {
                background: "special_scenes/0015-24",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "So you like it? From a guy's perspective, is it… desirable?",
				choiceNext: false,
			},
			"43": {
                background: "special_scenes/0015-24",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I-I... yeah, it is.",
				choiceNext: false,
			},
			"44": {
                bgMusic: {
					name: 'Intended_erotic_situation',
					command: 'FADE_OUT',
                    insideOfScene: true
				},
                background: "special_scenes/0015-24",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Really? Okay... I'll believe you.",
				choiceNext: false,
			},
			"45": {
                bgMusic: {
					name: 'FittnessRoom_normal_daily',
					command: 'START'
				},
				specialSceneNow: true,
				specialSceneOut: true,
				specialSceneId: null,
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "",
                textClass: 'italic',
			  	text: "Phew, she finally stopped… That was tough. I had to fight not to do something I'd regret later.",
				choiceNext: false,
			},
			"46": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_smiling', null],
				class: [null, null, null],
			  	name: "",
			  	text: "I thought to myself. Angie was just seconds away from missing that whole scene.",
				choiceNext: false,
			},
			"47": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Daena/Daena_casual_smiling', 'Daena/Daena_casual_smiling', 'Angie/Angie_casual_smiling'],
				class: ['fadeLeft', 'fadeUpOut', 'fadeRight'],
			  	name: "Angie",
			  	text: "Thanks for the workout, Tyler. It felt really good.",
				choiceNext: false,
			},
			"48": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_smiling', null, 'Angie/Angie_casual_smiling'],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Of course, it's always a pleasure working with you both.",
				choiceNext: false,
			},
            "49": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_smiling', null, 'Angie/Angie_casual_smiling'],
				class: [null, null, 'fadeRight'],
			  	name: "Angie",
			  	text: "Glad to hear that. Tomorrow it'll just be Daena coming to the session. I'll be busy, so I'll see you another time.",
				choiceNext: false,
			},
			"50": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_smiling', null, 'Angie/Angie_casual_smiling'],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Alright, take care of yourselves!",
				choiceNext: false,
			},
			"51": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_smiling', null, 'Angie/Angie_casual_smiling'],
				class: ['fadeLeft', null, null],
			  	name: "Daena",
			  	text: "Bye, Tyler!",
				choiceNext: false,
			},
            "52": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_smiling', null, 'Angie/Angie_casual_smiling'],
				class: ['fadeLeftOut', null, 'fadeRightOut'],
			  	name: "",
			  	text: "They both left, but just a few seconds later, Angie hurried back to the front desk.",
				choiceNext: false,
			},
			"53": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Did you forget something?",
				choiceNext: false,
			},
			"54": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Angie/Angie_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Angie",
			  	text: "Just a quick question: Do you really like my daughter's butt that much? Was it good to watch from closeup?",
				choiceNext: false,
			},
			"55": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Angie/Angie_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "...?",
				choiceNext: false,
			},
			"56": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Angie/Angie_casual_normal', null],
				class: [null, null, null],
			  	name: "",
                textClass: 'italic',
			  	text: "Oh, crap, I'm done for... How am I gonna talk my way out of this?",
				choiceNext: false,
			},
			"57": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Angie/Angie_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Umm... I mean... well...",
				choiceNext: false,
			},
			"58": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Angie/Angie_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Angie",
			  	text: "Don't worry, this stays between us adults.",
				choiceNext: false,
			},
			"59": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Angie/Angie_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "You're serious?",
				choiceNext: false,
			},
            "60": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Angie/Angie_casual_grin', null],
				class: [null, 'fadeUp', null],
			  	name: "Angie",
			  	text: "Of course! And I hope you meant what you said to her because honestly, I wouldn't mind having you as a son-in-law.",
				choiceNext: false,
			},
			"61": {
                bgMusic: {
					name: 'FittnessRoom_normal_daily',
					command: 'FADE_OUT'
				},
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Angie/Angie_casual_grin', null],
				class: [null, null, null],
			  	name: "",
			  	text: "And that was the moment I nearly fell off my chair, right under the desk... What happened after that? Well, that's all a blur...",
				choiceNext: false,
				timeSkipNext: {
					content: "Later at home...",
					nextSceneType: "MOBILE",
					nextSceneNumber: "0016",
				}
			},
		},
	},
];