export const scene_32 = [
	{
		sceneId: "0032",
		lengthNum: 47,
		story: {
			"1": {
				bgMusic: {
					name: 'SunnyDay_normal_daily',
					command: 'START'
				},
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "As much as we could, Daena and I made the most of our time at the baths. It wasn't as chill, relaxing, or intimate as it was with Reina yesterday, but it definitely had all the visual appeal and thrill that I expected.",
				choiceNext: false,
            },
 			"2": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "This was faster-paced and more youthful—perfectly fitting for Daena—and I still really enjoyed it.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "But as soon as the clock struck 11, I had to leave. I couldn't tell Daena that I already had plans with another woman, a lunch at her place, where it'd just be the two of us, and that things might even continue from there.",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Sometimes, my conscience nags me about whether what I'm doing is right, but I feel that until I'm officially with someone, dating around is fair game. After that, though, a boundary has to be set.",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Still, I'm aware that what I feel and what others might see could be very different, so I'm definitely going to call for an emergency meetup with my closest friends to get their opinions and help me steer in the right direction.",
				choiceNext: false,
			},
			"6": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "So, a little after 11, Daena and I part ways with smiles, and I hurry off to Brianna's, hoping not to miss lunch.",
				choiceNext: false,
			},
			"7": {
                otherSoundEffect: 'doorbell',
                background: "backgrounds/BG_Brianna_house_sunny",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "When I arrive at her house, I press the doorbell right away, but after waiting for what feels like half a minute, there's no response. I can be pretty sure her daughters aren't home, but for even her to be gone...",
				choiceNext: false,
            },
			"8": {
                background: "backgrounds/BG_Brianna_house_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "...Or they're all, like, using the bathroom... at the same time... yeah, right...",
				choiceNext: false,
			},
			"9": {
                otherSoundEffect: 'doorbell',
                background: "backgrounds/BG_Brianna_house_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Just in case, I press the bell again, but still nothing. That's when I decide to change tactics and send her a message, thinking maybe she just didn't hear the bell.",
				choiceNext: false,
			},
			"10": {
                background: "backgrounds/BG_Brianna_house_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Long, suspenseful minutes pass, but she neither responds to my message nor comes to the door.",
				choiceNext: false,
			},
			"11": {
                background: "backgrounds/BG_Brianna_house_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "After this much time, I finally notice that the gate's open. I guess I wouldn't be doing anything too wrong if I just walked through it, so I head up to her door. I knock, ring, and wait a bit more, but still... nothing.",
				choiceNext: false,
			},
			"12": {
                bgMusic: {
					name: 'SunnyDay_normal_daily',
					command: 'STOP'
				},
                background: "backgrounds/BG_Brianna_house_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Just for fun, I check to see if this door is open, too... and, whoa, it totally is! The front door? No way—could it be a break-in?",
				choiceNext: false,
			},
			"13": {
                otherSoundEffect: "door_noise",
                background: "backgrounds/BG_Brianna_livingroom_sunny",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I carefully push the door open and look around for anything out of the ordinary. The house is super clean and tidy inside—no signs of a break-in or struggle, so I guess we can rule that out. Looks like they just accidentally left the gate and the door unlocked.",
				choiceNext: false,
			},
			"14": {
                background: "backgrounds/BG_Brianna_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Brianna! It's Tyler! Are you home?",
				choiceNext: false,
			},
			"15": {
                background: "backgrounds/BG_Brianna_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I call out, but no answer.",
				choiceNext: false,
			},
			"16": {
                background: "backgrounds/BG_Brianna_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Since I don't know my way around this house at all, I start opening doors one by one, hoping it's not empty. Finally, behind one of the last doors, there she is, lying in bed, looking pretty deeply asleep.",
				choiceNext: false,
			},
			"17": {
                bgMusic: {
					name: 'Brianna_ecchi',
					command: 'START'
				},
                specialSceneNow: true,
				specialSceneId: '0032-17',
				background: "special_scenes/0032-17",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "She looks so peaceful and innocent... kinda cute, actually, while she's sleeping. But also kinda... vulnerable. She's got barely anything on, and what she's wearing doesn't cover much. It'd be way too easy to take advantage here, but I'm definitely not about to stoop that low.",
				choiceNext: false,
			},
			"18": {
				background: "special_scenes/0032-17",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Instead, I go for the way better option: sitting down beside her on the bed and calling her name softly, hoping she'll hear me or at least sense I'm here.",
				choiceNext: false,
			},
			"19": {
				background: "special_scenes/0032-17",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Brianna! Wake up! The sun's shining right on you!",
				choiceNext: false,
			},
			"20": {
				background: "special_scenes/0032-17",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "...",
				choiceNext: false,
			},
			"21": {
				background: "special_scenes/0032-17",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Brianna?",
				choiceNext: false,
			},
			"22": {
				background: "special_scenes/0032-17",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "...",
				choiceNext: false,
			},
            "23": {
				background: "special_scenes/0032-17",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Hey, sweetheart, what's for lunch today?",
				choiceNext: false,
			},
			"24": {
				background: "special_scenes/0032-17",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Hmm... Lunch? It's... it's...",
				choiceNext: false,
			},
			"25": {
                specialSceneId: '0032-25',
				background: "special_scenes/0032-25",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Tyler? Is that you?",
				choiceNext: false,
            },
			"26": {
				background: "special_scenes/0032-25",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Well, I'd know if I was supposed to be lunch, right?",
				choiceNext: false,
            },
			"27": {
				background: "special_scenes/0032-25",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "No, no, I didn't mean it like that. But how did you even get in? The door was locked.",
				choiceNext: false,
			},
			"28": {
				background: "special_scenes/0032-25",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Funny thing: neither the door nor the gate were locked. I rang the bell, knocked, even messaged you, but nada. And with everything wide open, I got a little worried, so sorry for just barging in.",
				choiceNext: false,
			},
			"29": {
				background: "special_scenes/0032-25",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "No, no, you don't need to apologize. If everything was open, that just means I forgot to lock up after my daughters left. I was supposed to lock up and start cooking... but I thought I'd lie down for just ten more minutes.",
				choiceNext: false,
			},
			"30": {
				background: "special_scenes/0032-25",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Ten minutes? You stretched that just a bit.",
				choiceNext: false,
			},
			"31": {
				background: "special_scenes/0032-25",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Wait—what time is it?",
				choiceNext: false,
			},
			"32": {
				background: "special_scenes/0032-25",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Well, it's already past noon.",
				choiceNext: false,
			},
			"33": {
				background: "special_scenes/0032-25",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "What? Oh no! So... guess lunch is kinda off the table, huh?",
				choiceNext: false,
			},
			"34": {
				background: "special_scenes/0032-25",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Yeah... doesn't really seem like it's happening.",
				choiceNext: false,
			},
			"35": {
                background: "special_scenes/0032-25",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "You mad at me?",
				choiceNext: false,
			},
			"36": {
				background: "special_scenes/0032-25",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Nah. But I'll step out while you get changed into something... you know, a little more daytime-appropriate.",
				choiceNext: false,
			},
			"37": {
                background: "special_scenes/0032-25",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "No, don't go. Stay. I don't mind if you see me in my nightgown.",
				choiceNext: false,
			},
			"38": {
				background: "special_scenes/0032-25",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "You sure about that?",
				choiceNext: false,
			},
			"39": {
                background: "special_scenes/0032-25",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Of course. You're allowed to do anything.",
				choiceNext: false,
			},
			"40": {
				background: "special_scenes/0032-25",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Anything?",
				choiceNext: true,
			},
			"41": {
				background: "special_scenes/0032-25",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'brianna~importants~0032-40',
			  	name: "Tyler",
			  	text: [
                    "Originally, I came over for a nice lunch... but since things turned out this way, maybe I could stay and relax here with you?",
                    "So... what would you say if I...?"
                ],
				choiceNext: false,
			},
			"42": {
				background: "special_scenes/0032-25",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'brianna~importants~0032-40',
			  	name: ["Brianna", ""],
			  	text: [
                    "Of course. And I'm sorry I didn't get lunch ready. I really wanted to, but I just got too worn out.",
                    "I gently rest my hand on Brianna's thigh, letting it glide up towards her hip, but she gives a tiny shake, letting me know to stop."
                ],
				choiceNext: false,
			},
			"43": {
                bgMusic: {
					name: ['Brianna_ecchi', 'Brianna_ecchi'],
					command: ['START', 'STOP']
				},
				background: "special_scenes/0032-25",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'brianna~importants~0032-40',
			  	name: ["Tyler", "Brianna"],
			  	text: [
                    "Don't worry about it. You're a one-person army at home, and sometimes people just overdo it and need to rest.",
                    "Not now, Tyler. Normally, I'd say ‘okay, let's go for it,' but look at me... I'm too worn out to handle it right now."
                ],
				choiceNext: false,
			},
            "44": {
                bgMusic: {
					name: ['Brianna_ecchi', 'Sadly_alone'],
					command: ['START', 'START']
				},
                specialSceneId: ["0032-44", "0032-25"],
				background: ["special_scenes/0032-44", "special_scenes/0032-25"],
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'brianna~importants~0032-40',
			  	name: "Brianna",
			  	text: [
                    "Thanks for understanding. Would you like to snuggle up here with me?",
                    "I know I said you could do \"anything,\" but there's a time and place for everything."
                ],
				choiceNext: false,
			},
			"45": {
				background: ["special_scenes/0032-44", "special_scenes/0032-25"],
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'brianna~importants~0032-40',
			  	name: "Tyler",
			  	text: [
                    "Of course!",
                    "Ah, okay, sorry about that."
                ],
				choiceNext: false,
			},
			"46": {
                specialSceneId: "0032-46",
				background: "special_scenes/0032-46",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Brianna extends her hand toward me, signaling for me to take it. I do, and she gently pulls me in, lying down face-to-face with her. Shortly after, she drifts back to sleep.",
				choiceNext: false,
            },
			"47": {
                bgMusic: {
					name: ['Brianna_ecchi', 'Sadly_alone'],
					command: ['FADE_OUT', 'FADE_OUT']
				},
				background: "special_scenes/0032-46",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                choicePath: 'brianna~importants~0032-40',
			  	name: "",
			  	text: "I, on the other hand, am already quite awake after the morning swim, but in this calm moment, it felt as though time had stopped. The quiet, the stillness—it was so peaceful that even I felt drowsy, and I might have even dozed off myself for a few minutes.",
				choiceNext: false,
				timeSkipNext: {
					content: "A few hours later...",
					nextSceneType: "MOBILE",
					nextSceneNumber: "0033",
				}
			},
		},
	},
];