export const scene_35 = [
    { sceneId: "0034" }, //storyScene: 0034
    {
		sceneId: "0035",
        startTime: "20:14",
        endTime: "00:00",
        timeSkipNext: {
            content: "Sunday morning",
            nextSceneType: "STORY",
            nextSceneNumber: "0036",
        },
        keepOut: ['Lindsay Lawrie'],
        bgMusic: {
            name: 'Mobile_night_normal',
            command: 'START',
        },
		textingPartner: {
            Daena: {
                isMandatory: true,
                sheStartsAt: "20:16",
                sheEndsAt: "21:24",
                messages: [
                    {
                        id: 0, 
                        isFromHer: true, 
                        text: "Hey, Tyler!", 
                        waitingTime: 0,
                        typingTime: 0.5,
                    },
                    {
                        id: 1, 
                        isFromHer: true, 
                        text: "Do you have a few minutes?", 
                        waitingTime: 2,
                        typingTime: 3,
                    },
                    {
                        id: 2, 
                        isFromHer: false, 
                        text: "Hey, Daena. Sure, what's up?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 3, 
                        isFromHer: true, 
                        text: "I just wanted to thank you for today", 
                        waitingTime: 3,
                        typingTime: 4,
                    },
                    {
                        id: 4, 
                        isFromHer: true, 
                        text: "Even though we didn't have a ton of time, I really enjoyed myself", 
                        waitingTime: 2,
                        typingTime: 5.5,
                    },
                    {
                        id: 5, 
                        isFromHer: false, 
                        text: "Thank you for making it happen", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 6, 
                        isFromHer: true, 
                        text: "Yeah, yeah", 
                        waitingTime: 4,
                        typingTime: 2,
                    },
                    {
                        id: 7, 
                        isFromHer: true, 
                        text: "So...", 
                        waitingTime: 3,
                        typingTime: 1,
                    },
                    {
                        id: 8, 
                        isFromHer: true, 
                        text: "I don't wanna take up all your time", 
                        waitingTime: 3,
                        typingTime: 4,
                    },
                    {
                        id: 9, 
                        isFromHer: true, 
                        text: "But...", 
                        waitingTime: 2,
                        typingTime: 1,
                    },
                    {
                        id: 10, 
                        isFromHer: true, 
                        text: "I really need to see you tomorrow", 
                        waitingTime: 3,
                        typingTime: 4,
                    },
                    {
                        id: 11, 
                        isFromHer: true, 
                        text: "There's something we need to talk about", 
                        waitingTime: 3,
                        typingTime: 4,
                    },
                    {
                        id: 12, 
                        isFromHer: false, 
                        text: "Is everything okay?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 13, 
                        isFromHer: true,
                        text: "Yeah... it's not that. I just... I need to talk to you", 
                        waitingTime: 3,
                        typingTime: 5,
                    },
                    {
                        id: 14, 
                        isFromHer: true,
                        text: "I'll be home all day tomorrow. What time works for you?", 
                        waitingTime: 4,
                        typingTime: 5,
                    },
                    {
                        id: 15, 
                        isFromHer: false,
                        text: "I'll have to let you know tomorrow if that's alright", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 16, 
                        isFromHer: true,
                        text: "Of course... that's fine", 
                        waitingTime: 3,
                        typingTime: 3,
                    },
                    {
                        id: 17, 
                        isFromHer: true,
                        text: "So...", 
                        waitingTime: 4,
                        typingTime: 1,
                    },
                    {
                        id: 18, 
                        isFromHer: true,
                        text: "I'll wait to hear from you then", 
                        waitingTime: 3,
                        typingTime: 4,
                    },
                    {
                        id: 19, 
                        isFromHer: true,
                        text: "Goodnight", 
                        waitingTime: 3,
                        typingTime: 1,
                    },
                ],
            },
            Hailey: {
                isMandatory: true,
                sheStartsAt: "21:27",
                sheEndsAt: "22:14",
                messages: [
                    {
                        id: 0, 
                        isFromHer: true, 
                        text: "Hey, Tyler", 
                        waitingTime: 0,
                        typingTime: 0.5,
                        bgMusic: {
                            name: 'Mobile_daily_sad',
                            command: 'START',
                        },
                    },
                    {
                        id: 1, 
                        isFromHer: true, 
                        text: "How's it going?", 
                        waitingTime: 2,
                        typingTime: 2,
                    },
                    {
                        id: 2, 
                        isFromHer: false, 
                        text: "Hey, Hailey. I'm alright. How about you?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 3, 
                        isFromHer: true, 
                        text: "I'm okay... mostly", 
                        waitingTime: 4,
                        typingTime: 2,
                    },
                    {
                        id: 4, 
                        isFromHer: false, 
                        text: "Mostly?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 5, 
                        isFromHer: true, 
                        text: "I dunno...", 
                        waitingTime: 4,
                        typingTime: 1.5,
                    },
                    {
                        id: 6, 
                        isFromHer: true, 
                        text: "Something's just weighing on me", 
                        waitingTime: 3,
                        typingTime: 3,
                    },
                    {
                        id: 7, 
                        isFromHer: true, 
                        text: "Not like stomach troubles—more like... emotionally", 
                        waitingTime: 3,
                        typingTime: 5,
                    },
                    {
                        id: 8, 
                        isFromHer: false, 
                        text: "Got it. Anything I can do to help?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 9, 
                        isFromHer: true, 
                        text: "Maybe", 
                        waitingTime: 4,
                        typingTime: 1,
                    },
                    {
                        id: 10, 
                        isFromHer: true, 
                        text: "Could I come by tomorrow to... just get it all out?", 
                        waitingTime: 3,
                        typingTime: 5,
                    },
                    {
                        id: 11, 
                        isFromHer: false, 
                        text: "Sure, that works", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 12, 
                        isFromHer: true, 
                        text: "Thank you", 
                        waitingTime: 3,
                        typingTime: 1,
                    },
                    {
                        id: 13, 
                        isFromHer: true,
                        text: "Let me know what time works, and I'll plan around that", 
                        waitingTime: 3,
                        typingTime: 5,
                    },
                    {
                        id: 14, 
                        isFromHer: true,
                        text: "Goodnight", 
                        waitingTime: 4,
                        typingTime: 1,
                    },
                ],
            },
            Brianna: {
                isMandatory: true,
                sheStartsAt: "22:16",
                sheEndsAt: "23:06",
                messages: [
                    {
                        id: 0, 
                        isFromHer: true, 
                        text: "Hey, Tyler", 
                        waitingTime: 0,
                        typingTime: 0.5,
                        bgMusic: {
                            name: 'Mobile_night_sad',
                            command: 'START',
                        },
                    },
                    {
                        id: 1, 
                        isFromHer: true, 
                        text: "You around for a quick question?", 
                        waitingTime: 2,
                        typingTime: 2,
                    },
                    {
                        id: 2, 
                        isFromHer: false, 
                        text: "Hey, Brianna. Yep, go for it", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 3, 
                        isFromHer: true, 
                        text: "Tomorrow, I'd really like to get out for a bit...", 
                        waitingTime: 4,
                        typingTime: 5,
                    },
                    {
                        id: 4, 
                        isFromHer: true, 
                        text: "But not alone, and not with my girls...", 
                        waitingTime: 2,
                        typingTime: 4,
                    },
                    {
                        id: 5, 
                        isFromHer: true, 
                        text: "I'd like you to come with me", 
                        waitingTime: 3,
                        typingTime: 3,
                    },
                    {
                        id: 6, 
                        isFromHer: true, 
                        text: "And... I'd like us to talk about... us...", 
                        waitingTime: 4,
                        typingTime: 4,
                    },
                    {
                        id: 7, 
                        isFromHer: false, 
                        text: "Combining business with pleasure, huh?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 8, 
                        isFromHer: true, 
                        text: "Exactly! Is that okay?", 
                        waitingTime: 3,
                        typingTime: 2.5,
                    },
                    {
                        id: 9, 
                        isFromHer: false, 
                        text: "Yeah, I can do that", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 10, 
                        isFromHer: true, 
                        text: "Great, thank you!", 
                        waitingTime: 3,
                        typingTime: 2,
                    },
                    {
                        id: 11, 
                        isFromHer: true, 
                        text: "Just let me know what time works for you, and I'll plan around it", 
                        waitingTime: 3,
                        typingTime: 6,
                    },
                    {
                        id: 12, 
                        isFromHer: false, 
                        text: "Will do", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 13, 
                        isFromHer: true,
                        text: "Thanks", 
                        waitingTime: 3,
                        typingTime: 1,
                    },
                    {
                        id: 14, 
                        isFromHer: true,
                        text: "Goodnight", 
                        waitingTime: 2,
                        typingTime: 1,
                    },
                ],
            },
            Reina: {
                isMandatory: true,
                sheStartsAt: "23:09",
                sheEndsAt: "23:57",
                messages: [
                    {
                        id: 0, 
                        isFromHer: true, 
                        text: "Hi, darling", 
                        waitingTime: 0,
                        typingTime: 0.5,
                        bgMusic: {
                            name: 'Night_dates_with_Reina',
                            command: 'START',
                        },
                    },
                    {
                        id: 1, 
                        isFromHer: true, 
                        text: "How are you?", 
                        waitingTime: 2,
                        typingTime: 2,
                    },
                    {
                        id: 2, 
                        isFromHer: false, 
                        text: "Hey, Reina. Doing alright. How about you?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 3, 
                        isFromHer: true, 
                        text: "Uh, today was rough, but I made it through", 
                        waitingTime: 3,
                        typingTime: 4,
                    },
                    {
                        id: 4, 
                        isFromHer: true, 
                        text: "Anyway, I think we're... at a turning point with our relationship...", 
                        waitingTime: 4,
                        typingTime: 5,
                    },
                    {
                        id: 5, 
                        isFromHer: true, 
                        text: "But I'd really rather talk about this in person", 
                        waitingTime: 3,
                        typingTime: 4,
                    },
                    {
                        id: 6, 
                        isFromHer: true, 
                        text: "Could we meet tomorrow sometime?", 
                        waitingTime: 3,
                        typingTime: 3,
                    },
                    {
                        id: 7, 
                        isFromHer: false, 
                        text: "Uh, depends. How flexible can you be tomorrow?", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 8, 
                        isFromHer: true, 
                        text: "The girls are at their grandma's, and my husband will probably be out cold after back-to-back conferences", 
                        waitingTime: 3,
                        typingTime: 8,
                    },
                    {
                        id: 9, 
                        isFromHer: true, 
                        text: "So, I'd say I'm pretty flexible", 
                        waitingTime: 2,
                        typingTime: 3.5,
                    },
                    {
                        id: 10, 
                        isFromHer: false, 
                        text: "Alright. I'll shuffle my plans and let you know when I can make it", 
                        waitingTime: null,
                        typingTime: null,
                    },
                    {
                        id: 11, 
                        isFromHer: true, 
                        text: "Sounds good. I'll be waiting", 
                        waitingTime: 4,
                        typingTime: 3,
                    },
                    {
                        id: 12, 
                        isFromHer: true, 
                        text: "See you tomorrow!", 
                        waitingTime: 3,
                        typingTime: 2,
                    },
                ],
            },
        }
    },
];