export const scene_30 = [
	{
		sceneId: "0030",
		endingSceneType: 'lindsay_1',
		lengthNum: 34,
		story: {
			"1": {
				bgMusic: {
					name: 'Being_in_the_mood',
					command: 'START'
				},
                background: "backgrounds/BG_night_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Honestly, when I woke up this morning, I never thought my night would end like this. Here I am, in bed with a woman who's not even a stranger but... my ex.",
				choiceNext: false,
            },
			"2": {
                background: "backgrounds/BG_night_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Sure, it's the easier route—no need for the small talk, skipping straight to the point—but it still feels a bit strange. Not that I mind; this is what I wanted, after all. I'm the one who gave Lindsay the chance.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_night_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "As for the others at the gym... well, that's just tough luck for them. They all had their shot, but there was always some major barrier that kept anything serious from forming. Lindsay just managed to beat them to it; it's their loss.",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_Tyler_livingroom_night",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "After dinner, we came up to my apartment. It wasn't the stereotypical messy bachelor pad, but it could have used a bit more tidying up. It's not like I expected to bring anyone back tonight.",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_Tyler_livingroom_night",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Lindsay",
			  	text: "Hmm... I see you haven't changed much since I was last here.",
				choiceNext: false,
			},
			"6": {
                background: "backgrounds/BG_Tyler_livingroom_night",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "And why would I?",
				choiceNext: false,
			},
			"7": {
                background: "backgrounds/BG_Tyler_livingroom_night",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Lindsay",
			  	text: "I don't know... maybe it's a phase of your life coming to an end, and you'd wanna shake things up, get a fresh start.",
				choiceNext: false,
            },
			"8": {
                background: "backgrounds/BG_Tyler_livingroom_night",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "That sounds more like a girl thing than a guy thing.",
				choiceNext: false,
			},
			"9": {
                background: "backgrounds/BG_Tyler_livingroom_night",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Lindsay",
			  	text: "Oh yeah? Well, let me appeal to that “guy side” of yours and ask if you'd be so kind as to get us a nice bottle of wine to toast our fresh start.",
				choiceNext: false,
			},
			"10": {
                background: "backgrounds/BG_Tyler_livingroom_night",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "On it.",
				choiceNext: false,
			},
			"11": {
                background: "backgrounds/BG_Tyler_livingroom_night",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Lindsay/Lindsay_elegant_normal', null],
				class: [null, 'fadeUpOut', null],
			  	name: "",
                textClass: "italic",
			  	text: "Seems like she hasn't quite let go of that habit of always asking for something or giving directions. But whatever, no one's perfect. It's a small price to pay for an unforgettable night.",
				choiceNext: false,
			},
			"12": {
                background: "backgrounds/BG_Tyler_livingroom_night",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "It's exciting knowing her already, remembering exactly what awaits underneath her clothes, but at the same time, it feels brand new—it's been so long since I last saw her like this.",
				choiceNext: false,
			},
			"13": {
                background: "backgrounds/BG_Tyler_livingroom_night",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "And now, finally, there's hope for a real, solid relationship. Sure, there's the matter of a quick divorce with her husband, but that's her issue to handle. The marriage isn't a problem—it's practically over, there are no kids to complicate things, no need to sneak around... it's perfect.",
				choiceNext: false,
			},
			"14": {
                background: "backgrounds/BG_Tyler_livingroom_night",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Luckily, I found a sweet red wine in my fridge, something that should suit Lindsay's mood. I grab two glasses and slowly make my way back to the bedroom.",
				choiceNext: false,
			},
			"15": {
                bgMusic: {
					name: 'Being_in_the_mood',
					command: 'FADE_OUT',
                    insideOfScene: true
				},
                background: "backgrounds/BG_Tyler_bedroom_night",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I half-expected Lindsay to still be looking around the room or waiting politely on the edge of the bed, but instead...",
				choiceNext: false,
			},
			"16": {
                bgMusic: {
					name: 'Lindsay_ecchi',
					command: 'START'
				},
                specialSceneNow: true,
				specialSceneId: '0030-16',
				background: "special_scenes/0030-16",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "Oh! Hey, Sweetheart! Took you long enough!",
				choiceNext: false,
			},
			"17": {
				background: "special_scenes/0030-16",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "She's sprawled out on my bed in nothing but a lingerie set! Wow, she's blown my expectations out of the water!",
				choiceNext: false,
			},
			"18": {
				background: "special_scenes/0030-16",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "My god, Lindsay! I'm speechless!",
				choiceNext: false,
			},
			"19": {
				background: "special_scenes/0030-16",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "Oh yeah? You like it?",
				choiceNext: false,
			},
			"20": {
				background: "special_scenes/0030-16",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Not just a little... a lot.",
				choiceNext: false,
			},
			"21": {
				background: "special_scenes/0030-16",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "Thanks for the wine, but we won't need that now. All I need is you.",
				choiceNext: false,
			},
			"22": {
				background: "special_scenes/0030-16",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "As I set the wine and glasses aside, she practically tears my shirt off, then uses her whole weight to pull me down onto the bed.",
				choiceNext: false,
			},
            "23": {
				background: "special_scenes/0030-16",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "It's been ages since I've seen her this close... that familiar scent... those intense eyes filled with desire... I can hardly take it! It feels like finally coming home from a long journey, a comforting warmth to go along with the passion.",
				choiceNext: false,
			},
			"24": {
				background: "special_scenes/0030-16",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "Tyler... I'm so glad we're here.",
				choiceNext: false,
			},
			"25": {
				background: "special_scenes/0030-16",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Really?",
				choiceNext: false,
            },
			"26": {
				background: "special_scenes/0030-16",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "Yes. Ever since we met up again, these long-buried feelings have come rushing back to the surface, stronger and faster than I ever thought possible. I just didn't want to throw myself at you right away—I was worried I'd scare you off. So, I tried to keep my cool and take things slow with you.",
				choiceNext: false,
            },
			"27": {
				background: "special_scenes/0030-16",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "But now, here we are, and I don't have to hold back anymore. I can finally let out the wild bad girl I've been hiding, and let me tell you, tonight is going to be unforgettable.",
				choiceNext: false,
			},
			"28": {
				background: "special_scenes/0030-16",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Lindsay",
			  	text: "If it takes six rounds, we'll do six rounds. If it takes breaking the bed, then so be it. I want you with such fierce, reckless passion that you'll be holding on for dear life!",
				choiceNext: false,
			},
			"29": {
				background: "special_scenes/0030-16",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Challenge accepted. Don't hold back!",
				choiceNext: false,
			},
			"30": {
				background: "special_scenes/0030-16",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "And with that, it happens.",
				choiceNext: false,
			},
			"31": {
				background: "special_scenes/0030-16",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Lindsay wasn't exaggerating—we really did manage to break a few things in the room. Not just parts of my bed or anything around it; after all, who says passion needs to be confined to just the bed, right?",
				choiceNext: false,
			},
			"32": {
				background: "special_scenes/0030-16",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "The night mostly played out like this: a round, some wine and romance, then another round, more wine, and so on. Whatever was left in the box of condoms was completely used up...",
				choiceNext: false,
			},
			"33": {
				background: "special_scenes/0030-16",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Or at least I think so, because with all the wine and the heat of the moment, the second half of the night got pretty hazy. The closer I try to remember toward the end, the blurrier the memories get.",
				choiceNext: false,
			},
			"34": {
                bgMusic: {
					name: 'Lindsay_ecchi',
					command: 'FADE_OUT'
				},
				background: "special_scenes/0030-16",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "But there's not a single complaint I can make about how the night turned out.",
				choiceNext: false,
                endingNext: 'lindsay',
			},
		},
	},
];