export const scene_18 = [
	{
		sceneId: "0018",
		lengthNum: 52,
		story: {
			"1": {
				bgMusic: {
					name: 'FittnessRoom_normal_daily',
					command: 'START'
				},
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "The rest of the afternoon passes uneventfully until an interesting duo is paired up for one of the group training sessions.",
				choiceNext: false,
            },
			"2": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "They aren't my two strongest clients, but I can definitely say they're two of my regulars. Brianna and Daena have never trained together before, but today that changes. Of course, Angie is here too, but she and her daughter will go their separate ways after the session, so by the end of my shift, it's just my two favorites left to hand in their keys before I can clock out.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, null],
				image: ['Brianna/Brianna_casual_smiling', null, null],
				class: ['fadeLeft', null, null],
			  	name: "Brianna",
			  	text: "Here's my key, Tyler. That was a good workout today.",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_smiling', null, 'Daena/Daena_casual_smiling'],
				class: [null, null, 'fadeRight'],
			  	name: "Daena",
			  	text: "So, what do you think of my performance today?",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_smiling', null, 'Daena/Daena_casual_smiling'],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "It wasn't worse than last time, so that's definitely a positive. But you need to be a bit more patient when learning new exercises. If you focus more on technique, the exercises will be more effective.",
				choiceNext: false,
			},
			"6": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_smiling', null, 'Daena/Daena_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: "Daena",
			  	text: "Okay, I'll try. I'm just in such a hurry to hit my goals, that's why I get a bit impatient sometimes.",
				choiceNext: false,
			},
			"7": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_normal', null, 'Daena/Daena_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Brianna",
			  	text: "Are you new here? I mean, why are you asking Tyler for feedback like that?",
				choiceNext: false,
            },
			"8": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_normal', null, 'Daena/Daena_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: "Daena",
			  	text: "What? No way! I've been coming here since before Tyler even started working here. We just made a little agreement, you know? I'm trying to switch up my training, and I want feedback to see if I'm doing things right.",
				choiceNext: false,
			},
			"9": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_surprised', null, 'Daena/Daena_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Brianna",
			  	text: "Really? Can we actually get these extra \"services\" from you, Tyler?",
				choiceNext: false,
			},
			"10": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_surprised', null, 'Daena/Daena_casual_normal'],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I wouldn't call it a service. It's just natural that I help out. Sure, Daena asked for it, but it's part of my job as a trainer to support where I can.",
				choiceNext: false,
			},
			"11": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_normal', null, 'Daena/Daena_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Brianna",
			  	text: "But if it's an \"agreement,\" then what do you give in return for Tyler's extra attention?",
				choiceNext: false,
			},
			"12": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_normal', null, 'Daena/Daena_casual_scared'],
				class: [null, null, 'fadeRight'],
			  	name: "Daena",
			  	text: "Umm… in return?",
				choiceNext: false,
			},
			"13": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_surprised', null, 'Daena/Daena_casual_scared'],
				class: ['fadeLeft', null, null],
			  	name: "Brianna",
			  	text: "Wait a minute! You're asking for extra attention from Tyler and not giving anything in return? That's not an agreement, that's taking advantage.",
				choiceNext: false,
			},
			"14": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_normal', null, 'Daena/Daena_casual_scared'],
				class: ['fadeLeft', null, null],
			  	name: "Brianna",
			  	text: "Even I offered him a ride the other day after he helped me with my shopping.",
				choiceNext: false,
			},
			"15": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_normal', null, 'Daena/Daena_casual_surprised'],
				class: [ null, null, 'fadeRight'],
			  	name: "Daena",
			  	text: "Shopping? You guys meet outside the gym too?",
				choiceNext: false,
			},
			"16": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_normal', null, 'Daena/Daena_casual_surprised'],
				class: ['fadeLeft', null, null],
			  	name: "Brianna",
			  	text: "I had to, for grocery shopping. But wait, what do you mean by \"you guys too\"? Why, do you?",
				choiceNext: false,
			},
			"17": {
                bgMusic: {
					name: 'FittnessRoom_normal_daily',
					command: 'FADE_OUT',
                    insideOfScene: true
				},
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_normal', null, 'Daena/Daena_casual_normal'],
				class: [ null, null, 'fadeRight'],
			  	name: "Daena",
			  	text: "Yeah, I invited him out for a drink last week to talk about how we're going to move forward with my training plan.",
				choiceNext: false,
			},
			"18": {
                bgMusic: {
					name: 'Brianna_ecchi',
					command: 'START'
				},
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_normal', null, 'Daena/Daena_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Brianna",
			  	text: "Really? Hmm... And if I asked you out, Tyler, would you come for a drink with me too?",
				choiceNext: false,
			},
			"19": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_normal', null, 'Daena/Daena_casual_normal'],
				class: [ null, null, 'fadeRight'],
			  	name: "Daena",
			  	text: "And how would you repay that favor?",
				choiceNext: false,
			},
			"20": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_smiling', null, 'Daena/Daena_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Brianna",
			  	text: "Hmm... let me think. My daughters always compliment my cooking, so in return, I'd invite him over for dinner.",
				choiceNext: false,
			},
			"21": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_smiling', null, 'Daena/Daena_casual_normal'],
				class: [ null, null, 'fadeRight'],
			  	name: "Daena",
			  	text: "Really? O-Okay... I'd have to ask my mom first, but I'm sure she'd be cool with Tyler joining us for dinner!",
				choiceNext: false,
			},
			"22": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_grin', null, 'Daena/Daena_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Brianna",
			  	text: "And, since he's already been to my house, I don't see why we couldn't make the evening a bit more exciting while the girls aren't home.",
				choiceNext: false,
			},
			"23": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_grin', null, 'Daena/Daena_casual_embarrassed'],
				class: [ null, null, 'fadeRight'],
			  	name: "Daena",
			  	text: "Well... my room is pretty big and soundproof, so we could, you know... do that there if needed.",
				choiceNext: false,
			},
			"24": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_seductive', null, 'Daena/Daena_casual_embarrassed'],
				class: ['fadeLeft', null, null],
			  	name: "Brianna",
			  	text: "Exactly, and since we're both in on it, I wouldn't feel shy. I'd work hard, really putting in the effort until we're both satisfied.",
				choiceNext: false,
			},
			"25": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_seductive', null, 'Daena/Daena_casual_embarrassed'],
				class: [null, null, 'fadeRight'],
			  	name: "Daena",
			  	text: "I-I could even moan loudly if needed. Like I said, my room is soundproof.",
				choiceNext: false,
            },
			"26": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_seductive', null, 'Daena/Daena_casual_embarrassed'],
				class: ['fadeLeft', null, null],
			  	name: "Brianna",
			  	text: "And in the end, if he offers, I'd gladly accept what he has to give. I'd make sure not a single drop goes to waste.",
				choiceNext: false,
			},
			"27": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_seductive', null, 'Daena/Daena_casual_scared'],
				class: [null, null, 'fadeRight'],
			  	name: "Daena",
			  	text: "Eww! I mean... okay, I've never tasted cum before, but for Tyler, fine, I'll do it!",
				choiceNext: false,
			},
			"28": {
                bgMusic: {
					name: 'Brianna_ecchi',
					command: 'STOP'
				},
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_normal', null, 'Daena/Daena_casual_scared'],
				class: ['fadeLeft', null, null],
			  	name: "Brianna",
			  	text: "...",
				choiceNext: false,
			},
			"29": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_normal', null, 'Daena/Daena_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: "Daena",
			  	text: "...?",
				choiceNext: false,
			},
			"30": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_scared', null, 'Daena/Daena_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Brianna",
			  	text: "What are you talking about?",
				choiceNext: false,
			},
			"31": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_scared', null, 'Daena/Daena_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: "Daena",
			  	text: "The same thing you are! Why?",
				choiceNext: false,
			},
			"32": {
                bgMusic: {
					name: 'Being_in_the_mood',
					command: 'START'
				},
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_normal', null, 'Daena/Daena_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Brianna",
			  	text: "No, no, sweetheart, you've totally misunderstood something here! I was talking about cooking whatever fits Tyler's diet, so he doesn't have to order takeout—he can come have dinner at my place.",
				choiceNext: false,
			},
			"33": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_normal', null, 'Daena/Daena_casual_normal'],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "And since he'd be at my place, we could also do a home workout while my girls aren't around, so we wouldn't disturb them, and they wouldn't disturb us either.",
				choiceNext: false,
			},
			"34": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_normal', null, 'Daena/Daena_casual_normal'],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "I'm usually not comfortable getting sweaty in front of others, but at home, no one would see, so I'd feel free to push myself to the limit. And by the way, I was talking about a protein shake, not anything else.",
				choiceNext: false,
			},
			"35": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_normal', null, 'Daena/Daena_casual_angry'],
				class: [null, null, 'fadeRight'],
			  	name: "Daena",
			  	text: "No way, I don't buy it! You were talking in such a suggestive way the whole time—you totally made this up to explain yourself afterward!",
				choiceNext: false,
			},
			"36": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_angry', null, 'Daena/Daena_casual_angry'],
				class: ['fadeLeft', null, null],
			  	name: "Brianna",
			  	text: "No, sweetie, sorry, but you're the only one here with a dirty mind. Tyler, correct me if I'm wrong, but you understood what I meant the whole time, right?",
				choiceNext: true,
			},
			"37": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_angry', null, 'Daena/Daena_casual_angry'],
				class: [null, null, null],
                choicePath: 'brianna~importants~0018-36',
			  	name: "Tyler",
			  	text: [
                    "Sorry, Brianna, but apparently, I have just as dirty a mind as Daena.",
                    "Of course, we adults understand what's meant between the lines.",
                    "I didn't want to interrupt because it was too fun watching you both playfully escalate with those double meanings."
                ],
				choiceNext: false,
			},
			"38": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Brianna/Brianna_casual_angry', null, ['Daena/Daena_casual_angry', 'Daena/Daena_casual_surprised', 'Daena/Daena_casual_angry']],
				class: [[null, null, 'fadeLeft'], null, ['fadeRight', 'fadeRight', null]],
                choicePath: 'brianna~importants~0018-36',
			  	name: ["Daena", "Daena", "Brianna"],
			  	text: [
                    "See? It's not my fault! Maybe next time, you won't find yourself in such awkward situations when you talk a bit more carefully with people!",
                    "Seriously? Is this how adult life really works?",
                    "Come on, Tyler! That wasn't fair! This isn't some harem where everyone fights for your favor. I was just talking about how I imagine ideal personal training sessions at my house!"
                ],
				choiceNext: false,
			},
			"39": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: [['Brianna/Brianna_casual_angry', 'Brianna/Brianna_casual_normal', 'Brianna/Brianna_casual_angry'], null, ['Daena/Daena_casual_angry', 'Daena/Daena_casual_surprised', 'Daena/Daena_casual_angry']],
				class: [['fadeLeft', 'fadeLeft', null], null, [null, null, 'fadeRight']],
                choicePath: 'brianna~importants~0018-36',
			  	name: ["Brianna", "Brianna", "Daena"],
			  	text: [
                    "Tch! Fine, whatever… I still stand by my point—if your hormones are raging this much, that's not my problem.",
                    "See, darling? You might've just turned 18, but there are still things about adult life you don't know yet. You'll learn them eventually. But until then, don't expect to have a serious, mature relationship anytime soon.",
                    "You could've saved me from looking like a perv, but instead, you just enjoyed playing along with the confusion!"
                ],
				choiceNext: false,
			},
			"40": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: [['Brianna/Brianna_casual_angry', 'Brianna/Brianna_casual_normal', 'Brianna/Brianna_casual_angry'], null, ['Daena/Daena_casual_grin', 'Daena/Daena_casual_sad', 'Daena/Daena_casual_sad']],
				class: [null, null, 'fadeRight'],
                choicePath: 'brianna~importants~0018-36',
			  	name: "Daena",
			  	text: [
                    "Yaaay! 5 points to Daena! But I've got another thing to do, so I'm out! Byeee!",
                    "Really? Well... okay, I guess I'll go now since today's clearly not my day. Bye, guys.",
                    "This is super embarrassing... I think I'll just leave now... sorry!"
                ],
				choiceNext: false,
			},
			"41": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: [['Brianna/Brianna_casual_angry', 'Brianna/Brianna_casual_normal', 'Brianna/Brianna_casual_angry'], null, ['Daena/Daena_casual_grin', 'Daena/Daena_casual_sad', 'Daena/Daena_casual_sad']],
				class: ['fadeLeftOut', null, 'fadeRightOut'],
                choicePath: 'brianna~importants~0018-36',
			  	name: "",
			  	text: "Daena leaves the gym, but Brianna stays at the counter for a little while to chat.",
				choiceNext: false,
			},
			"42": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, ['Brianna/Brianna_casual_sad', 'Brianna/Brianna_casual_smiling', 'Brianna/Brianna_casual_sad'], null],
				class: [null, 'fadeUp', null],
                choicePath: 'brianna~importants~0018-36',
			  	name: "Brianna",
			  	text: [
                    "You know, Tyler… you could've been a bit more cooperative. I just wanted to put that little girl in her place a bit, show her that you and I are much more in sync.",
                    "Thanks for playing along, Tyler. I hope you realized I was bluffing and speaking ambiguously on purpose.",
                    "Tyler, I wasn't just doing this for fun. Yes, I was being vague on purpose, but I wanted to show her that you and I understand each other much better."
                ],
				choiceNext: false,
			},
			"43": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, ['Brianna/Brianna_casual_sad', 'Brianna/Brianna_casual_smiling', 'Brianna/Brianna_casual_sad'], null],
				class: [null, null, null],
                choicePath: 'brianna~importants~0018-36',
			  	name: "Tyler",
			  	text: "But tell me, why? Why did you go through all that, being so vague?",
				choiceNext: false,
			},
			"44": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "You really don't know? Or do you just not want to accept it?",
				choiceNext: false,
			},
			"45": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I think… it's more the first one.",
				choiceNext: false,
			},
			"46": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "Heh. Well, you'll have to figure this out on your own! Just don't take too long, or it might not matter by the time you do.",
				choiceNext: false,
			},
			"47": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Anyway, I should go too. My girls will start trickling home soon, and I need to start making dinner. See you at Thursday morning! Bye!",
				choiceNext: false,
			},
			"48": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "B-Bye...",
				choiceNext: false,
			},
            "49": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, 'fadeUpOut', null],
			  	name: "",
			  	text: "Brianna also leaves the gym.",
				choiceNext: false,
			},
			"50": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: 'italic',
			  	text: "\"Don't know\" or \"don't want to accept it\"? Is it that I don't know because I'm misunderstanding… or do I know, and just can't believe it's actually happening?",
				choiceNext: false,
			},
			"51": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: 'italic',
			  	text: "No, I really can't imagine Brianna is purposely messing with me in such a confusing way because she wants something from me. I must be reading into this, and it's probably just some generational joke that I don't quite get.",
				choiceNext: false,
			},
            "52": {
                bgMusic: {
					name: 'Being_in_the_mood',
					command: 'FADE_OUT'
				},
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: 'italic',
			  	text: "But I can't just ask outright—that would be super embarrassing. Oh well. That's it for work today. Time to clean up, change, and enjoy the next day and a half of freedom as much as possible!",
				choiceNext: false,
                timeSkipNext: {
					content: "On the same evening...",
					nextSceneType: "MOBILE",
					nextSceneNumber: "0019",
				}
			}
		},
	},
];