export const scene_5 = [
    { sceneId: "0004" }, //mobileScene: 0004
	{
		sceneId: "0005",
		lengthNum: 47,
		story: {
			"1": {
				bgMusic: {
					name: 'Date_with_Daena',
					command: 'START'
				},
                background: "backgrounds/BG_balcony_bar_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                textClass: "italic",
			  	name: "",
			  	text: "Yeah, I really didn't see this coming. Daena's one of those clients who was already going to the gym before I even got hired.",
				choiceNext: false,
            },
			"2": {
				background: "backgrounds/BG_balcony_bar_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
                textClass: "italic",
			  	name: "",
			  	text: "Her performance has never been extraordinary, but as for her body... well, that's a whole other story.",
				choiceNext: false,
			},
			"3": {
				background: "backgrounds/BG_balcony_bar_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				textClass: "italic",
			  	name: "",
			  	text: "Sure, I've seen bolder girls her age, but Daena's the kind who's got great potential, and she either doesn't notice it, or she knows but doesn't bother using it.",
				choiceNext: false,
			},
			"4": {
				background: "backgrounds/BG_balcony_bar_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				textClass: "italic",
			  	name: "",
			  	text: "Either way, she's a really sweet girl, and it's always been a pleasure to watch her train… The only problem is, until now, she's been underage. I had to hold back for quite a while, but now that she's an adult and the field is open, she's dating someone already… yeah, life can be shit.",
				choiceNext: false,
			},
			"5": {
				background: "backgrounds/BG_balcony_bar_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				textClass: "italic",
			  	name: "",
			  	text: "And now she's telling me she wants to quit? Of course, I'm just her trainer, I can't force her to stay, but at least I want to know why she made this decision. There aren't many clients I'm willing to go this far for, but Daena is definitely one of them.",
				choiceNext: false,
			},
			"6": {
				background: "backgrounds/BG_balcony_bar_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Daena/Daena_casual_normal", null],
				class: [null, "fadeUp", null],
			  	name: "Daena",
			  	text: "Hey, Coach!",
				choiceNext: false,
			},
			"7": {
				background: "backgrounds/BG_balcony_bar_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Daena/Daena_casual_normal", null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Hey, Daena. You can drop the “Coach”. I'm not that much older than you, and you just turned 18. I never expected you to call me that anyway.",
				choiceNext: false,
			},
			"8": {
				background: "backgrounds/BG_balcony_bar_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Daena/Daena_casual_normal", null],
				class: [null, "fadeUp", null],
			  	name: "Daena",
			  	text: "Yeah, yeah… I'm trying! And thanks for making time for me on your day off. I ordered a drink for you too, hope you don't mind.",
				choiceNext: false,
			},
			"9": {
				background: "backgrounds/BG_balcony_bar_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Daena/Daena_casual_normal", null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Not at all, thanks a lot. So, let's sit down, and you can tell me what's going on.",
				choiceNext: false,
			},
			"10": {
				bgMusic: {
					name: 'Date_with_Daena',
					command: 'FADE_OUT',
					insideOfScene: true
				},
				background: "backgrounds/BG_balcony_bar_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Daena/Daena_casual_normal", null],
				class: [null, "fadeUp", null],
			  	name: "Daena",
			  	text: "Alright.",
				choiceNext: false,
			},
			"11": {
				bgMusic: {
					name: 'Sadly_alone',
					command: 'START'
				},
				specialSceneNow: true,
				specialSceneId: "0005-11",
				background: "special_scenes/0005-11",
				charContainer: [null, 'char-middle', null],
				image: [null, "Daena/Daena_casual_normal", null],
				class: [null, "fadeUpOut", null],
			  	name: "Daena",
			  	text: "Sooo, I decided to quit training 'cause I'm just not seeing any progress. Actually, it feels like the opposite is happening.",
				choiceNext: false,
			},
			"12": {
				background: "special_scenes/0005-11",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "What do you mean?",
				choiceNext: false,
			},
			"13": {
				background: "special_scenes/0005-11",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Like, nine months ago, when you started working at the gym and I began training with you, I could see and feel the changes in my body. I was super happy about that.",
				choiceNext: false,
			},
			"14": {
				background: "special_scenes/0005-11",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "But as time went on, those positive changes slowed down, then just stopped. And now, I feel like I'm going backwards. I want a slim body, but my thighs, butt, and even my boobs keep getting bigger! And my hips are getting wider!",
				choiceNext: false,
			},
			"15": {
				background: "special_scenes/0005-11",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				textClass: "italic",
			  	name: "",
			  	text: "Ah, so that's what this is about… I thought maybe I had done something wrong.",
				choiceNext: false,
			},
			"16": {
				background: "special_scenes/0005-11",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Daena… this is completely normal. You just turned 18, your body's still developing.",
				choiceNext: false,
			},
			"17": {
				background: "special_scenes/0005-11",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Can't we… like, stop that development somehow? I already don't feel comfortable in my body, I don't wanna get any bigger or wider!",
				choiceNext: false,
			},
			"18": {
				background: "special_scenes/0005-11",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "But nothing seems to be working! I was planning to train with you at least until graduation, 'cause who knows what the future holds after that, but I just don't see the point now. Plus, it'd make things easier with Mom. She wouldn't have to work around my schedule anymore, she could hit the gym whenever she feels like it.",
				choiceNext: false,
			},
			"19": {
				background: "special_scenes/0005-11",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				textClass: "italic",
			  	name: "",
			  	text: "I think I see what the real issue is here... now I just have to figure out how to explain it to her.",
				choiceNext: true,
			},
			"20": {
				background: "special_scenes/0005-11",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'daena~importants~0005-19',
			  	name: "Tyler",
			  	text: [
					"In my opinion, we need to get really strict about your diet. I'll also revamp your workout plan, but you'll need to put in like five times more effort during the sessions.",
					"Don't get me wrong, Daena, but I think the issue isn't with your body, it's in your mind."
				],
				choiceNext: false,
			},
			"21": {
				specialSceneId: "0005-21",
                background: "special_scenes/0005-21",
				backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'daena~importants~0005-19',
			  	name: "Daena",
			  	text: [
					"Five times?! Dude, I already feel like I'm about to die half the time!",
					"Wait, are you saying I'm crazy or something?"
				],
				choiceNext: false,
			},
			"22": {
				background: "special_scenes/0005-21",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'daena~importants~0005-19',
			  	name: "Tyler",
			  	text: [
					"I get that, but you've gotta understand too — if you really wanna be slim, you've gotta burn as much as you can… obviously within healthy limits.",
					"No, no, I'm not saying you're crazy. I'm saying it sounds like a self-esteem issue, maybe even the start of a body image problem."
				],
				choiceNext: false,
			},
			"23": {
				background: "special_scenes/0005-21",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'daena~importants~0005-19',
			  	name: ["Tyler", "Daena"],
			  	text: [
					"I'll put together a new plan focused mainly on cardio. I know you hate it, but if this goal is important to you, you've gotta go all in, no half-assing!",
					"A self-esteem problem? But everyone keeps telling me not to live up to other people's expectations, just my own. And I'm not happy with what I see in the mirror, that's why I wanna lose weight!"
				],
				choiceNext: false,
			},
			"24": {
				background: "special_scenes/0005-21",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'daena~importants~0005-19',
				name: ["Daena", "Tyler"],
				text: [
				  	"Isn't there, like, a less painful way to do this?",
				  	"Yeah, it's true that you should mainly want to satisfy yourself. But ignoring the feedback from the world around you isn't the answer either. You can't just listen to your own thoughts, especially when they're constantly dragging you down into a negative spiral."
			  	],
				choiceNext: false,
			},
			"25": {
				background: "special_scenes/0005-21",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'daena~importants~0005-19',
				name: "Tyler",
				text: [
				  	"Right now, there's no workout method that'll target specific fat areas. You gotta fire up everything if you wanna get slim and toned.",
				  	"Think about it. What does your mom, Angie, usually say about your appearance?"
			  	],
				choiceNext: false,
			},
			"26": {
				bgMusic: {
					name: ['Sadly_alone', 'Sadly_alone'],
					command: ['FADE_OUT', 'START'],
					insideOfScene: true
				},
				background: "special_scenes/0005-21",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'daena~importants~0005-19',
				name: "Daena",
				text: [
				  	"Slim and toned… like those athletic girls, right? Is that the type of girl you're into as a trainer?",
				  	"She always says I'm cute, and that my figure suits my height."
			  	],
				choiceNext: false,
				stepSkip: [11, 0]
			},
			"27": {
				background: "special_scenes/0005-21",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'daena~importants~0005-19',
			  	name: [null, "Tyler"],
			  	text: [
					null,
					"Good. Do guys hit on you a lot?"
				],
				choiceNext: false,
			},
			"28": {
				background: "special_scenes/0005-21",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'daena~importants~0005-19',
				name: [null, "Daena"],
				text: [
					null,
					"Oh, totally. Like, I get compliments from them multiple times a day, and they're always trying, but they don't get that I'm already dating someone."
				],
				choiceNext: false,
			},
			"29": {
				background: "special_scenes/0005-21",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'daena~importants~0005-19',
				name: [null, "Tyler"],
				text: [
					null,
					"Yeah, you've mentioned that... But look, Angie's proud of your figure, you've got guys wrapped around your finger, you're dating… and honestly, I think your body's great too. You look amazing just the way you are. It suits you perfectly."
				],
				choiceNext: false,
			},
			"30": {
				bgMusic: {
					name: 'Sadly_alone',
					command: 'FADE_OUT',
					insideOfScene: true
				},
				background: "special_scenes/0005-21",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'daena~importants~0005-19',
				name: [null, "Daena"],
				text: [
					null,
					"Oh… um… thanks..."
				],
				choiceNext: false,
			},
			"31": {
				bgMusic: {
					name: 'Daena_ecchi',
					command: 'START'
				},
				specialSceneId: "0005-31",
				background: "special_scenes/0005-31",
				backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'daena~importants~0005-19',
				name: [null, "Daena"],
				text: [
					null,
					"So, I look perfectly good, huh?"
				],
				choiceNext: false,
			},
			"32": {
				background: "special_scenes/0005-31",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'daena~importants~0005-19',
				name: [null, "Tyler"],
				text: [
					null,
					"I don't like repeating myself, but yeah, you heard me."
				],				
				choiceNext: false,
			},
			"33": {
				background: "special_scenes/0005-31",
				backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'daena~importants~0005-19',
				name: [null, "Daena"],
				text: [
					null,
					"But isn't it true that guys usually prefer slimmer girls?"
				],	
				choiceNext: false,
			},
			"34": {
				background: "special_scenes/0005-31",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'daena~importants~0005-19',
				name: [null, "Tyler"],
				text: [
					null,
					"Everyone's got their own taste. If someone likes skinny girls, that's their choice."
				],	
				choiceNext: false,
			},
			"35": {
				background: "special_scenes/0005-31",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'daena~importants~0005-19',
				name: [null, "Tyler"],
				text: [
					null,
					"But, there's a saying among us guys: \"A good woman always has something juicy. Only dogs like to play with bones.\""
				],
				choiceNext: false,
			},
			"36": {
				background: "special_scenes/0005-31",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'daena~importants~0005-19',
				name: [null, "Tyler"],
				text: [
					null,
					"I know that's pretty blunt, but it's the truth."
				],
				choiceNext: false,
			},
			"37": {
				bgMusic: {
					name: 'Date_with_Daena',
					command: 'FADE_OUT',
					insideOfScene: true
				},
				background: "special_scenes/0005-11",
				backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'daena~importants~0005-19',
				name: [null, "Daena"],
				text: [
					null,
					"I've never heard that before. But don't you, as a trainer, prefer those sporty, fitness gals?"
				],
				choiceNext: false,
			},
			"38": {
				bgMusic: {
					name: 'Date_with_Daena',
					command: 'START'
				},
				background: "special_scenes/0005-11",
				backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'daena~importants~0005-19',
			  	name: "Tyler",
			  	text: "You don't necessarily need a fitness model's body, but they usually have some nice curves, you know? Which is hot. But you don't have to be an athlete for that.",
				choiceNext: false,
				backStepSkip: [11, 0],
			},
			"39": {
				background: "special_scenes/0005-11",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Ahh… okay, I think I get what you mean. Alright, thanks for the help, really. I'm already feeling a bit better.",
				choiceNext: false,
			},
			"40": {
				background: "special_scenes/0005-11",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Really?",
				choiceNext: false,
			},
			"41": {
				background: "special_scenes/0005-11",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Yeah. You kinda brought my motivation back, so you can count on me for Sunday's session, as usual.",
				choiceNext: false,
			},
			"42": {
				background: "special_scenes/0005-11",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I'm glad you changed your mind. See you Sunday, then.",
				choiceNext: false,
			},
			"43": {
				background: "special_scenes/0005-11",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Oh… Oops!",
				choiceNext: false,
			},
			"44": {
				background: "special_scenes/0005-11",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "What now?",
				choiceNext: false,
			},
			"45": {
				background: "special_scenes/0005-11",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "I think… I might've miscalculated how much cash I brought with me…",
				choiceNext: false,
			},
			"46": {
				background: "special_scenes/0005-11",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Wait, you're telling me you ordered two drinks without even checking if you had enough money? Daena!",
				choiceNext: false,
			},
			"47": {
				bgMusic: {
					name: 'Date_with_Daena',
					command: 'FADE_OUT'
				},
				background: "special_scenes/0005-21",
				backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Sooooryyy!",
				choiceNext: false,
				timeSkipNext: {
					content: "Later that evening...",
					nextSceneType: "MOBILE",
					nextSceneNumber: "0006",
				}
			}
		},
	},
];