export const scene_11 = [
	{
		sceneId: "0011",
		lengthNum: 63,
		story: {
			"1": {
				bgMusic: {
					name: 'FittnessRoom_normal_daily',
					command: 'START'
				},
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "The training session is over, and Reina is still in the locker room.",
				choiceNext: false,
            },
			"2": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I've got a little time before my next session. There are some clients around, but the boss isn't here, so I figured I'd have a few minutes to talk to Reina in person. At least, that was the plan…",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Because in the next moment, Daena walks through the gym doors. Strange, since she doesn't have a session today, yet she's carrying a gym bag.",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Daena/Daena_casual_smiling", null],
				class: [null, "fadeUp", null],
			  	name: "Daena",
			  	text: "Hey, Coach... I mean, Tyler!",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Daena/Daena_casual_smiling", null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Hey, Daena. What brings you here? Did you mix up your schedule?",
				choiceNext: false,
			},
			"6": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Daena/Daena_casual_smiling", null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "I need to find a way to send her off quickly. I definitely don't want her and Reina bumping into each other.",
				choiceNext: false,
			},
			"7": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Daena/Daena_casual_normal", null],
				class: [null, "fadeUp", null],
			  	name: "Daena",
			  	text: "No, no, I know I'm supposed to come in tomorrow. But my schedule is crazy packed tomorrow, I'll literally be running from one place to another, and it'd be easier if I didn't have to lug my gym stuff around all day.",
				choiceNext: false,
			},
			"8": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Daena/Daena_casual_normal", null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Can I leave my bag here until tomorrow?",
				choiceNext: false,
			},
			"9": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Daena/Daena_casual_normal", null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I don't mind. Hand it over, and we're good to go!",
				choiceNext: false,
			},
			"10": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Daena/Daena_casual_surprised", null],
				class: [null, "fadeUp", null],
			  	name: "Daena",
			  	text: "O-kay… thanks.",
				choiceNext: false,
			},
			"11": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Daena/Daena_casual_surprised", null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "Please, just leave quickly...",
				choiceNext: false,
			},
			"12": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Daena/Daena_casual_smiling", null],
				class: [null, "fadeUp", null],
			  	name: "Daena",
			  	text: "By the way, I really appreciate what you did for me on Friday. It means a lot that you put so much effort into helping me!",
				choiceNext: false,
			},
			"13": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Daena/Daena_casual_smiling", null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "Oh no, not now! Please don't start getting all emotional right now!",
				choiceNext: false,
			},
			"14": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Daena/Daena_casual_smiling", null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "It was really nothing, happy to help!",
				choiceNext: false,
			},
			"15": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Daena/Daena_casual_normal", null],
				class: [null, "fadeUp", null],
			  	name: "Daena",
			  	text: "But you've got so many other clients, I seriously don't want you thinking I'm some kinda problem, like I expect you to do special stuff just for me!",
				choiceNext: false,
			},
			"16": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Daena/Daena_casual_normal", null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "Please go already! Please, please!",
				choiceNext: false,
			},
			"17": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Daena/Daena_casual_normal", null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Don't worry, I don't think that at all.",
				choiceNext: false,
			},
			"18": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Daena/Daena_casual_normal", null],
				class: [null, "fadeUpOut", null],
			  	name: "",
			  	text: "And there she is... Reina steps out of the women's locker room, and her expression says it all—she's not thrilled to see people hanging around the front desk, especially a young girl.",
				choiceNext: false,
			},
			"19": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ["Daena/Daena_casual_normal", null, "Reina/Reina_casual_normal"],
				class: ['fadeLeft', null, 'fadeRight'],
			  	name: "Reina",
			  	text: "Oh, I see you're busy, Tyler.",
				choiceNext: false,
			},
			"20": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ["Daena/Daena_casual_normal", null, "Reina/Reina_casual_normal"],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Uh… not really, Daena just dropped off her gym stuff for tomorrow since she's got a busy day and will be rushing in for her session.",
				choiceNext: false,
			},
			"21": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ["Daena/Daena_casual_normal", null, "Reina/Reina_casual_normal"],
				class: ['fadeLeft', null, null],
			  	name: "Daena",
			  	text: "Yeah, it's way easier if I don't have to drag this stuff around with me all day.",
				choiceNext: false,
			},
			"22": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ["Daena/Daena_casual_normal", null, "Reina/Reina_casual_normal"],
				class: [null, null, null],
			  	name: "",
                textClass: 'italic',
			  	text: "If I'm lucky, maybe Daena will keep it brief and hand over the counter to the actual clients…",
				choiceNext: false,
			},
			"23": {
                bgMusic: {
					name: 'FittnessRoom_normal_daily',
					command: 'STOP'
				},
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ["Daena/Daena_casual_smiling", null, "Reina/Reina_casual_normal"],
				class: ['fadeLeft', null, null],
			  	name: "Daena",
			  	text: "And I was just thanking him for what he did for me on Friday.",
				choiceNext: false,
			},
			"24": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ["Daena/Daena_casual_smiling", null, "Reina/Reina_casual_normal"],
				class: [null, null, null],
			  	name: "",
                textClass: 'italic',
			  	text: "...Why did I ever think I'd get lucky...?",
				choiceNext: false,
			},
            "25": {
				bgMusic: {
					name: 'Girls_argument',
					command: 'START'
				},
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ["Daena/Daena_casual_smiling", null, "Reina/Reina_casual_surprised"],
				class: [null, null, 'fadeRight'],
			  	name: "Reina",
			  	text: "Friday? What did he do for you?",
				choiceNext: false,
            },
			"26": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ["Daena/Daena_casual_smiling", null, "Reina/Reina_casual_surprised"],
				class: ['fadeLeft', null, null],
			  	name: "Daena",
			  	text: "Well, I was about to quit training ‘cause I haven't been feeling any progress for a while. I wanted to tell him in person, but Tyler convinced me to give it another shot and motivated me to keep going.",
				choiceNext: false,
			},
			"27": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ["Daena/Daena_casual_smiling", null, "Reina/Reina_casual_sad"],
				class: [null, null, 'fadeRight'],
			  	name: "Reina",
			  	text: "Really?",
				choiceNext: false,
			},
			"28": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ["Daena/Daena_casual_smiling", null, "Reina/Reina_casual_sad"],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "I didn't know, Tyler, that you meet with your clients outside of work and fight so hard to keep them around!",
				choiceNext: false,
			},
			"29": {
				background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ["Daena/Daena_casual_smiling", null, "Reina/Reina_casual_sad"],
				class: [null, null, null],
			  	name: "",
                textClass: 'italic',
			  	text: "Pot calling the kettle black... But this conversation is getting more awkward by the second. How am I going to get out of this one?",
				choiceNext: false,
			},
			"30": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ["Daena/Daena_casual_normal", null, "Reina/Reina_casual_sad"],
				class: ['fadeLeft', null, null],
			  	name: "Daena",
			  	text: "What's the big deal? There's no rule that says a trainer can't talk to their clients outside of training hours!",
				choiceNext: false,
			},
			"31": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ["Daena/Daena_casual_normal", null, "Reina/Reina_casual_normal"],
				class: [null, null, 'fadeRight'],
			  	name: "Reina",
			  	text: "But if the other clients found out, they'd have every right to demand a piece of Tyler's private life too, to help or motivate them.",
				choiceNext: false,
			},
			"32": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ["Daena/Daena_casual_normal", null, "Reina/Reina_casual_normal"],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "And if he says no, who knows who might report him to the bosses, and that could cost him his job!",
				choiceNext: false,
			},
			"33": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ["Daena/Daena_casual_surprised", null, "Reina/Reina_casual_normal"],
				class: ['fadeLeft', null, null],
			  	name: "Daena",
			  	text: "Why would they fire him just for meeting up with someone outside of work?",
				choiceNext: false,
			},
			"34": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ["Daena/Daena_casual_surprised", null, "Reina/Reina_casual_sad"],
				class: [null, null, 'fadeRight'],
			  	name: "Reina",
			  	text: "You might not be aware, but it's unethical for a trainer to hit on their clients. That's why it's prohibited here. But Tyler meeting with a female client outside of work, someone around his age... doesn't that sound a little suspicious to you?",
				choiceNext: false,
			},
			"35": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ["Daena/Daena_casual_surprised", null, "Reina/Reina_casual_sad"],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "It only takes a snap of the fingers for them to make a rule saying trainers can't have any personal relationships with clients outside of the gym—strictly trainer-client relationships only. Otherwise, it's goodbye.",
				choiceNext: false,
			},
			"36": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ["Daena/Daena_casual_angry", null, "Reina/Reina_casual_sad"],
				class: ['fadeLeft', null, null],
			  	name: "Daena",
			  	text: "Well, I'm not gonna feel guilty, if that's your goal with all this scary speculation! I'm 18, not stupid.",
				choiceNext: false,
			},
			"37": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ["Daena/Daena_casual_angry", null, "Reina/Reina_casual_sad"],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Sure, what you're saying could happen, but it's pretty unlikely. Plus, I've seen you two talking before workouts or afterwards multiple times, so you're kind of contradicting yourself. If you're so afraid of them making a rule and firing Tyler, why are you doing the same thing?",
				choiceNext: false,
			},
			"38": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ["Daena/Daena_casual_angry", null, "Reina/Reina_casual_angry"],
				class: [null, null, 'fadeRight'],
			  	name: "Reina",
			  	text: "That's different because I respect his personal life. I don't drag him out of his home behind everyone's back and ask him for work-related favors. I could do that right here at the gym.",
				choiceNext: false,
			},
			"39": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ["Daena/Daena_casual_angry", null, "Reina/Reina_casual_angry"],
				class: ['fadeLeft', null, null],
			  	name: "Daena",
			  	text: "I didn't force him at gunpoint to meet up with me, he could've said no. It's a free country, free people, and he can decide what he does with his free time!",
				choiceNext: false,
			},
			"40": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ["Daena/Daena_casual_angry", null, "Reina/Reina_casual_angry"],
				class: [null, null, 'fadeRight'],
			  	name: "Reina",
			  	text: "Tyler, say something! You took a big risk for an 18-year-old girl, didn't you?",
				choiceNext: true,
			},
			"41": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ["Daena/Daena_casual_angry", null, "Reina/Reina_casual_angry"],
				class: [null, null, null],
                choicePath: 'reina~importants~0011-40', //reina%daena
			  	name: "Tyler",
			  	text: [
                    "No need to jump to conclusions. I was just fulfilling my duty as a trainer. One of my clients was losing confidence, I helped her, and that's all. Nothing more.",
                    "Girls, I really don't want to be part of this argument!",
                    "Daena's right. They can't control what I do in my free time as long as it's legal. Meeting with someone from my client base doesn't count as anything wrong."
                ],
				choiceNext: false,
			},
			"42": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: [["Daena/Daena_casual_angry", "Daena/Daena_casual_angry", "Daena/Daena_casual_smiling"], null, ["Reina/Reina_casual_angry", "Reina/Reina_casual_angry", "Reina/Reina_casual_angry"]],
				class: [[null, null, 'fadeLeft'], null, ['fadeRight', 'fadeRight', null]],
                choicePath: 'reina~importants~0011-40', //reina%daena
			  	name: ["Reina", "Reina", "Daena"],
			  	text: [
                    "That's all? Are you sure I don't need to worry about you disappearing one day?",
                    "Oh no, you don't get to stay silent! This is about you, so you better stand up and decide who's right!",
                    "See, even he agrees. So, there's nothing wrong with spending a little time together outside of work."
                ],
				choiceNext: false,
			},
			"43": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: [["Daena/Daena_casual_angry", "Daena/Daena_casual_angry", "Daena/Daena_casual_smiling"], null, ["Reina/Reina_casual_angry", "Reina/Reina_casual_angry", "Reina/Reina_casual_sad"]],
				class: [[null, 'fadeLeft', null], null, [null, null, 'fadeRight']],
                choicePath: 'reina~importants~0011-40', //reina%daena
			  	name: ["Tyler", "Daena", "Reina"],
			  	text: [
                    "I'm sure. I'm just doing my job. I also write training plans in my free time because there's no time for it here, so this was nothing more than an extra task.",
                    "For once, I agree with her. You're the best judge of who's right, so don't back out of this!",
                    "I see. If that's how it is, I won't interrupt your “free time” any longer. But if anything happens in the future, Tyler, I hope you'll take responsibility for it!"
                ],
				choiceNext: false,
			},
			"44": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: [["Daena/Daena_casual_sad", "Daena/Daena_casual_angry", "Daena/Daena_casual_smiling"], null, ["Reina/Reina_casual_angry", "Reina/Reina_casual_angry", "Reina/Reina_casual_sad"]],
				class: [['fadeLeft', null, 'fadeLeftOut'], null, [null, null, 'fadeRightOut']],
                choicePath: 'reina~importants~0011-40', //reina%daena
			  	name: ["Daena", "", ""],
                textClass: [null, 'italic', null],
			  	text: [
                    "Just a task? That sounded… so cold, Tyler...",
                    "What the fuck did I do to deserve this, seriously?",
                    "Reina leaves the gym, clearly upset and disappointed."
                ],
				choiceNext: false,
			},
			"45": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [['char-left', 'char-left', null], [null, null, 'char-middle'], ['char-right', 'char-right', null]],
				image: [["Daena/Daena_casual_sad", "Daena/Daena_casual_angry", null], [null, null, "Daena/Daena_casual_surprised"], ["Reina/Reina_casual_normal", "Reina/Reina_casual_angry", null]],
				class: [[null, null, null], [null, null, 'fadeUp'], ['fadeRight', null, null]],
                choicePath: 'reina~importants~0011-40', //reina%daena
			  	name: ["Reina", "Tyler", "Daena"],
			  	text: [
                    "Now you can see what's going on and where your place is. Tyler doesn't mix work with his personal life. Right?",
                    "Girls, I've got bigger things to worry about than whether I'll get punished for meeting clients outside of work! If you really want an answer, go ask my boss... well, the one I have!",
                    "Why did she get so worked up about this?"
                ],
				choiceNext: false,
			},
			"46": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [['char-left', 'char-left', null], [null, null, 'char-middle'], ['char-right', 'char-right', null]],
				image: [["Daena/Daena_casual_sad", "Daena/Daena_casual_angry", null], [null, null, "Daena/Daena_casual_surprised"], ["Reina/Reina_casual_normal", "Reina/Reina_casual_angry", null]],
				class: [[null, null, null], [null, null, null], [null, 'fadeRight', null]],
                choicePath: 'reina~importants~0011-40', //reina%daena
			  	name: ["Tyler", "Reina", "Tyler"],
			  	text: [
                    "Y-Yeah, that's right.",
                    "I see. If it bothers you that someone's trying to have your back, just let me know and I'll stop, so you can fall into the biggest messes on your own!",
                    "I get why she's worried, but… she'll calm down with time."
                ],
				choiceNext: false,
			},
			"47": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [['char-left', 'char-left', null], [null, null, 'char-middle'], ['char-right', 'char-right', null]],
				image: [["Daena/Daena_casual_sad", "Daena/Daena_casual_angry", null], [null, null, "Daena/Daena_casual_normal"], ["Reina/Reina_casual_normal", "Reina/Reina_casual_angry", null]],
				class: [['fadeLeft', null, null], [null, null, 'fadeUp'], [null, null, null]],
                choicePath: 'reina~importants~0011-40', //reina%daena
			  	name: ["Daena", "Reina", "Daena"],
			  	text: [
                    "I see… Okay, well… I gave you what I came here for. Sorry for taking up your time, Tyler. I'll see you at training tomorrow.",
                    "Good luck!",
                    "Maybe. I've never talked to her, but I didn't expect her to be this paranoid. It's like she treats you like her possession and doesn't want anyone to take you away from her."
                ],
				choiceNext: false,
			},
			"48": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [['char-left', 'char-left', null], [null, null, 'char-middle'], ['char-right', 'char-right', null]],
				image: [["Daena/Daena_casual_sad", "Daena/Daena_casual_angry", null], [null, null, "Daena/Daena_casual_normal"], ["Reina/Reina_casual_normal", "Reina/Reina_casual_angry", null]],
				class: [[null, 'fadeLeftOut', null], [null, null, null], [null, 'fadeRightOut', null]],
                choicePath: 'reina~importants~0011-40', //reina%daena
			  	name: ["Tyler", null, "Tyler"],
			  	text: [
                    "Will do. Take care until then!",
                    "Reina leaves the gym… pretty angry",
                    "You've got a point. Officially, I'm not anyone's—no girlfriend to tell me what I can and can't do, who I can be with, or when and where I can go."
                ],
				choiceNext: false,
			},
            "49": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [['char-left', null, null], [null, 'char-middle', 'char-middle'], ['char-right', null, null]],
				image: [["Daena/Daena_casual_sad", null, null], [null, "Daena/Daena_casual_sad", "Daena/Daena_casual_normal"], ["Reina/Reina_casual_normal", null, null]],
				class: [['fadeLeftOut', null, null], [null, 'fadeUp', 'fadeUp'], ['fadeRightOut', null, null]],
                choicePath: 'reina~importants~0011-40', //reina%daena
			  	name: [null, "Daena", "Daena"],
			  	text: [
                    "Daena leaves the gym… looking a little sad.",
                    "I tried hard to stand up for you against an adult woman. I wasn't expecting this answer from you… sorry. I think I'd better leave now. Bye.",
                    "Exactly."
                ],
				choiceNext: false,
            },
			"50": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, ['char-middle', 'char-middle', 'char-middle'], null],
				image: [null, ["Reina/Reina_casual_normal", "Daena/Daena_casual_sad", "Daena/Daena_casual_normal"], null],
				class: [null, ['fadeUp', 'fadeUpOut', null], null],
                choicePath: 'reina~importants~0011-40', //reina%daena
			  	name: ["Reina", null, "Daena"],
			  	text: [
                    "She better be careful, because I don't like that a young chick is trying to get with my lover!",
                    "And Daena leaves the gym… looking a little disappointed.",
                    "This wasn't how I expected this visit to go, but it is what it is. At least I'm glad you sided with me and didn't just see me as another \"task.\""
                ],
				choiceNext: false,
			},
			"51": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, ['char-middle', null, 'char-middle'], null],
				image: [null, ["Reina/Reina_casual_normal", null, "Daena/Daena_casual_smiling"], null],
				class: [null, [null, null, 'fadeUp'], null],
                choicePath: 'reina~importants~0011-40', //reina%daena
			  	name: ["Tyler", null, "Daena"],
                textClass: [null, 'italic', null],
			  	text: [
                    "I hope, Reina, that we both managed to read between the lines and you understand now that there's no need to worry about Daena—or anyone else for that matter.",
                    "Well, thit is not what was supposed to happen.",
                    "But now, if you don't mind, I'll get going. We'll meet tomorrow! I'm really looking forward to it!"
                ],
				choiceNext: false,
			},
			"52": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, ['char-middle', null, 'char-middle'], null],
				image: [null, ["Reina/Reina_casual_smiling", null, "Daena/Daena_casual_smiling"], null],
				class: [null, ['fadeUp', null, null], null],
                choicePath: 'reina~importants~0011-40', //reina%daena
			  	name: ["Reina", null, "Tyler"],
                textClass: [null, 'italic', null],
			  	text: [
                    "I hope so too. I'm so happy to have you in my life because you've made me so much happier. I'm trying to give you as much of myself as I can, and I don't want anyone to ruin what we have!",
                    "I never thought I'd end up caught between two chairs just because I didn't want to get involved in a fight. What would have been the right thing to say?",
                    "Alright. Me too. Take care of yourself."
                ],
				choiceNext: false,
                stepSkip: [0, 8, 0]
			},
			"53": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, ['char-middle', null, 'char-middle'], null],
				image: [null, ["Reina/Reina_casual_smiling", null, "Daena/Daena_casual_smiling"], null],
				class: [null, [null, null, 'fadeUp'], null],
                choicePath: 'reina~importants~0011-40', //reina%daena
			  	name: ["Tyler", null, "Daena"],
			  	text: [
                    "Don't worry about that. I'd never want to have multiple irons in the fire. I've got you, and I couldn't wish for anyone better in my life.",
                    null,
                    "Bye!"
                ],
				choiceNext: false,
			},
			"54": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, ['char-middle', null, 'char-middle'], null],
				image: [null, ["Reina/Reina_casual_seductive", null, "Daena/Daena_casual_smiling"], null],
				class: [null, ['fadeUp', null, 'fadeUpOut'], null],
                choicePath: 'reina~importants~0011-40', //reina%daena
			  	name: ["Reina", null, ""],
			  	text: [
                    "It's always nice to hear that from you. I wish I could give you a kiss right now.",
                    null,
                    "With that, Daena leaves the gym."
                ],
				choiceNext: false,
			},
			"55": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, ['char-middle', null, null], null],
				image: [null, ["Reina/Reina_casual_seductive", null, null], null],
				class: [null, [null, null, null], null],
                choicePath: 'reina~importants~0011-40', //reina%daena
			  	name: ["Tyler", null, ""],
                textClass: [null, null, 'italic'],
			  	text: [
                    "That would be nice for me too, but unfortunately, we're not alone right now.",
                    null,
                    "I can't say she's completely right, but the fact is, Reina and I aren't officially a couple. I'm just her lover, so what right does she have to dictate how I interact with other women?"
                ],
				choiceNext: false,
			},
			"56": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, ['char-middle', null, null], null],
				image: [null, ["Reina/Reina_casual_smiling", null, null], null],
				class: [null, ['fadeUp', null, null], null],
                choicePath: 'reina~importants~0011-40', //reina%daena
			  	name: ["Reina", null, ""],
                textClass: [null, null, 'italic'],
			  	text: [
                    "Sadly, yes, but maybe another time. Anyway, I'm glad you agreed with me. But now I've got to rush home—who knows what kind of chaos the girls have created while I've been away?",
                    null,
                    "She might not like it, but they asked me to say something. "
                ],
				choiceNext: false,
                stepSkip: [0, null, 4]
			},
			"57": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, ['char-middle', null, null], null],
				image: [null, ["Reina/Reina_casual_smiling", null, null], null],
				class: [null, [null, null, null], null],
                choicePath: 'reina~importants~0011-40', //reina%daena
			  	name: ["Tyler", null, null],
			  	text: [
                    "Of course, go ahead. I'm glad we got to spend a little time together today.",
                    null,
                    null
                ],
				choiceNext: false,
			},
			"58": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, ['char-middle', null, null], null],
				image: [null, ["Reina/Reina_casual_smiling", null, null], null],
				class: [null, ['fadeUp', null, null], null],
                choicePath: 'reina~importants~0011-40', //reina%daena
			  	name: ["Reina", null, null],
			  	text: [
                    "Same here. Bye.",
                    null,
                    null
                ],
				choiceNext: false,
			},
			"59": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, ['char-middle', null, null], null],
				image: [null, ["Reina/Reina_casual_smiling", null, null], null],
				class: [null, ['fadeUpOut', null, null], null],
                choicePath: 'reina~importants~0011-40', //reina%daena
			  	name: ["", null, null],
			  	text: [
                    "With that, Reina also left the gym.",
                    null,
                    null
                ],
				choiceNext: false,
			},
			"60": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, [null, null, null], null],
				image: [null, [null, null, null], null],
				class: [null, [null, null, null], null],
                choicePath: 'reina~importants~0011-40', //reina%daena
			  	name: ["", null, null],
                textClass: ['italic', null, null],
			  	text: [
                    "There was some truth in what Daena said, but I'm still committed to Reina. Sure, she overreacts sometimes, but she'll learn over time that she doesn't need to worry so much.",
                    null,
                    null
                ],
				choiceNext: false,
			},
			"61": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: 'italic',
			  	text: "There wasn't an answer that would've made everyone happy… or maybe I just couldn't think of one in the heat of the moment. But now it's too late. Words have weight, and I can't take back my decision.",
				choiceNext: false,
                choicePath: 'reina~importants~0011-40', //reina%daena
                backStepSkip: [0, 8, 4],
			},
			"62": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: 'italic',
			  	text: "I didn't need this drama today, but hopefully, both of them will calm down and not bring this tension into the gym in the future.",
				choiceNext: false,
			},
			"63": {
				bgMusic: {
					name: 'Girls_argument',
					command: 'FADE_OUT'
				},
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: 'italic',
			  	text: "Anyway, the next clients are already coming in. No more time to dwell on it, it's time to get back to work!",
				choiceNext: false,
                timeSkipNext: {
					content: "A few hours later...",
					nextSceneType: "STORY",
					nextSceneNumber: "0012",
				}
			}
		},
	},
];