export const scene_2 = [
	{
		sceneId: "0002",
		lengthNum: 41,
		story: {
			"1": {
				bgMusic: {
					name: 'Morning_normal',
					command: 'START'
				},
                background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "*yawn*",
				choiceNext: false,
            },
			"2": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "Is it Friday already? The sun rises so early in summer, but I could definitely sleep more.",
				choiceNext: false,
			},
			"3": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "At least there's time to rest, and I need to take advantage of it because the gym will be open on the weekend too, and unfortunately, I'm working both weekend days this week",
				choiceNext: false,
			},
			"4": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "So, I think I'll take it easy today and just stay in bed a little longer.",
				choiceNext: false,
			},
			"5": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I decided to lie down for a bit longer, hoping I could fall back asleep, but then...",
				choiceNext: false,
			},
			"6": {
				bgMusic: {
					name: 'Morning_normal',
					command: 'STOP'
				},
				otherSoundEffect: "door_noise",
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "Huh?",
				choiceNext: false,
			},
			"7": {
				otherSoundEffect: "footsteps",
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I hear something outside my bedroom. If only it were the neighbor making some noise, then I wouldn't be worried. But I'm certain I hear footsteps in the living room!",
				choiceNext: false,
			},
			"8": {
				bgMusic: {
					name: 'Huge_trouble',
					command: 'START'
				},
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "SOMEONE IS WALKING IN MY APARTMENT WITHOUT PERMISSION!",
				choiceNext: false,
			},
			"9": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "What should I do? Right now, I can barely figure out what planet I'm on, I'm not alert enough to protect what's mine, and the footsteps sound like they're getting closer!",
				choiceNext: false,
			},
			"10": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "Should I hide to at least keep myself safe, or maybe I could scare off the intruder by shouting?",
				choiceNext: true,
			},
			"11": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'reina~notImportants~0002-10',
			  	name: "",
                textClass: "italic",
			  	text: [
					"The best thing to do is hide and pretend I don't exist.",
					"I don't have a particularly deep or scary voice, but I'll try to sound intimidating."
				],
				choiceNext: false,
			},
			"12": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'reina~notImportants~0002-10',
			  	name: ["", "Tyler"],
			  	text: [
					"Without making too much noise, I pull the blanket off myself and try to quietly get out of bed and sneak into the wardrobe, just within arm's reach...",
					"Who's out there?"
				],
				choiceNext: false,
			},
			"13": {
				bgMusic: {
					name: 'Huge_trouble',
					command: 'FADE_OUT',
					insideOfScene: true
				},
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'reina~notImportants~0002-10',
			  	name: "",
			  	text: [
					"But I barely make it to the edge of my bed when I hear the doorknob turn, and the door to my bedroom begins to open! I have no choice but to defend myself and my belongings with force! But then...",
					"For a moment, the footsteps go silent, and I thought it was the best decision I could've made. But then another step approaches, and my bedroom door opens..."
				],
				choiceNext: false,
			},
			"14": {
				bgMusic: {
					name: 'Morning_normal',
					command: 'START'
				},
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_smiling", null],
				class: [null, "fadeUp", null],
				choicePath: 'reina~notImportants~0002-10',
			  	name: "???",
			  	text: [
					"Good morning, Tyler!",
					"Who else did you think it could be?"
				],
				choiceNext: false,
			},
			"15": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_smiling", null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Reina? — I couldn't have been more pleasantly surprised — How did you get here? And how did you get in? The door was locked!",
				choiceNext: false,
			},
			"16": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_normal", null],
				class: [null, "fadeUp", null],
			  	name: "Reina",
			  	text: "I was waiting for you on SocialSync last night, but I saw you didn't even check my messages. And that hadn't changed by this morning either.",
				choiceNext: false,
			},
			"17": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_normal", null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "I was worried something had happened to you, or maybe I did something to make you avoid me, so I decided to come over after my morning errands to be sure everything was okay.",
				choiceNext: false,
			},
			"18": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_normal", null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Oh, and no… your door wasn't locked at all. I didn't think you were the type to be so careless as to leave it open, so I got scared something might have happened. That's why, even though I was uninvited, I came in to check if everything was alright.",
				choiceNext: false,
			},
			"19": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_normal", null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Ah, I see… in any case, I'm really glad it's you. For a moment, I thought I was dealing with burglars.",
				choiceNext: false,
			},
			"20": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_embarrassed", null],
				class: [null, "fadeUp", null],
			  	name: "Reina",
			  	text: "Sorry if I gave you a scare. So… what's going on… between us?",
				choiceNext: false,
			},
			"21": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_embarrassed", null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Hm? What do you mean?",
				choiceNext: false,
			},
			"22": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_normal", null],
				class: [null, "fadeUp", null],
			  	name: "Reina",
			  	text: "Were you even paying attention to what I just said? You haven't replied to my messages since last night. What did I do to deserve this from you? Yes, I'm a married woman… yes, we've kissed, more than once… but I thought what happened between us meant something to you too!",
				choiceNext: false,
			},
			"23": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_normal", null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Oh… well… You know, I got home really late and was exhausted yesterday. The clients completely drained me mentally, so when I got home, the first and only thing I did was throw myself into bed. I've been sleeping ever since.",
				choiceNext: false,
			},
			"24": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_normal", null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "So, you didn't do anything wrong, it's just that my day was chaotic, and I crashed early.",
				choiceNext: false,
			},
			"25": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_normal", null],
				class: [null, "fadeUp", null],
			  	name: "Reina",
			  	text: "I see… sorry for assuming the worst… but please, in the future, at least have enough energy to message me saying you're tired and can't talk, and we'll speak tomorrow. Alright?",
				choiceNext: false,
			},
			"26": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_normal", null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Alright. I'm sorry.",
				choiceNext: false,
			},
			"27": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_smiling", null],
				class: [null, "fadeUp", null],
			  	name: "Reina",
			  	text: "So, have you rested up and are you ready to go?",
				choiceNext: false,
			},
			"28": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_smiling", null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Ready to go? Where?",
				choiceNext: false,
			},
			"29": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_sad", null],
				class: [null, "fadeUp", null],
			  	name: "Reina",
			  	text: "Oh my god, Tyler, are you still half-asleep?",
				choiceNext: false,
			},
			"30": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_sad", null],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "Today's your day off, and we planned our first… date, remember? We were going to take a walk in the park. I've been so excited since last night, I couldn't wait for today!",
				choiceNext: false,
			},
			"31": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_sad", null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Was that the plan? It seems like my brain still hasn't fully woken up. But okay, just give me a little time to get dressed.",
				choiceNext: false,
			},
			"32": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_normal", null],
				class: [null, "fadeUp", null],
			  	name: "Reina",
			  	text: "Alright, but hurry up! You know, if I could, I'd gladly spend the whole day with you, but as much as my husband works late, I still only have time until I have to pick up my daughters from school and daycare.",
				choiceNext: false,
			},
			"33": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_normal", null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Yes, yes, I'm hurrying!",
				choiceNext: false,
			},
			"34": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_normal", null],
				class: [null, "fadeUpOut", null],
			  	name: "",
			  	text: "While I'm getting dressed, Reina steps out of my room. My head is still foggy, but something vaguely reminds me that we did plan this date.",
				choiceNext: false,
			},
			"35": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I've really gotten myself into something tricky with her. There's more than a decade between us, she's married and has kids… I've never been in a situation like this, dating someone in secret.",
				choiceNext: false,
			},
			"36": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "We can't just go anywhere in broad daylight because what if one of her acquaintances or one of my clients sees us together? In Vensea, rumors spread fast, and in the worst case, I could lose my job for entering into any kind of romantic or physical relationship with a client, which is strictly against the rules...",
				choiceNext: false,
			},
			"37": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "But she has much more at stake as a full-time mother… Financially, for the sake of her family's stability, and she'd be labeled a \"cheating wife\" in this town, a reputation she'd never be able to shake. There's so much she could lose.",
				choiceNext: false,
			},
			"38": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "So, I have to respect her wish to meet only occasionally and for short periods, if we want to get closer. We must be careful not to be seen by anyone we know... and even then, it can only be for a few hours, while Polly and Molly, her daughters, are in school and daycare.",
				choiceNext: false,
			},
			"39": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "During that time, she can be free, since she can take care of the housework during the day. But afterwards, she has no choice but to return to her role as the perfect mom.",
				choiceNext: false,
			},
			"40": {
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Okay, Reina, I'm ready. Let's go.",
				choiceNext: false,
			},
			"41": {
 				bgMusic: {
					name: 'Morning_normal',
					command: 'FADE_OUT',
				},
				background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, "Reina/Reina_casual_grin", null],
				class: [null, "fadeUp", null],
			  	name: "Reina",
			  	text: "Great! I hope you'll like the place I'm taking you to!",
				choiceNext: false,
			},
		},
	},
];