export const scene_24 = [
	{
		sceneId: "0024",
		lengthNum: 48,
		story: {
			"1": {
				bgMusic: {
					name: 'FittnessRoom_normal_daily',
					command: 'START'
				},
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "The day has been pretty uneventful after Reina and Brianna, even though it's a long one for me since I'm working until late afternoon. And what better way to close the day than to have two more of my favorite clients in a group session together?",
				choiceNext: false,
            },
			"2": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Now, Hailey and Daena are paired up for a group workout. Hailey, performance-wise, clearly stands out from the crowd. This catches Daena's attention, and it motivates her to push beyond her limits, hoping to grab my focus.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Because of this, Daena makes a lot of mistakes or overexerts herself, but that's fine as long as she stays safe. The important thing is she's finally stepping out of her comfort zone to improve. By the end of the workout, she's absolutely spent.",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_reception_sunny",
				backGroundClass: 'fadeIn',
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Despite everything, Daena is almost the first to exit the women's locker room, panting heavily as she walks over to me at the front desk.",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_scared', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "Hah-hah... That was brutal! I can barely feel my body!",
				choiceNext: false,
			},
			"6": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_scared', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Yeah? Then how come you were one of the first to leave the locker room?",
				choiceNext: false,
			},
			"7": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Tyler",
			  	text: "I just changed, didn't shower. I'm heading straight home with my mom, by car, so I figured it's fine to skip the shower today.",
				choiceNext: false,
            },
			"8": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Ah, fair enough.",
				choiceNext: false,
			},
			"9": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Daena/Daena_casual_normal', 'Daena/Daena_casual_normal', 'Hailey/Hailey_casual_grin'],
				class: ['fadeLeft', 'fadeUpOut', 'fadeRight'],
			  	name: "Hailey",
			  	text: "Hellllooo, Tyler! Thanks for today's session, you really worked me good!",
				choiceNext: false,
			},
			"10": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_normal', null, 'Hailey/Hailey_casual_grin'],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "No problem, Hailey.",
				choiceNext: false,
			},
			"11": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_normal', null, 'Hailey/Hailey_casual_grin'],
				class: ['fadeLeft', null, null],
			  	name: "Daena",
			  	text: "Uhmm... Hailey?",
				choiceNext: false,
			},
			"12": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_normal', null, 'Hailey/Hailey_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: "Hailey",
			  	text: "Hm? Yeah?",
				choiceNext: false,
			},
			"13": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_normal', null, 'Hailey/Hailey_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Daena",
			  	text: "Where do you get all that energy? You were killing it out there like it was the easiest thing ever.",
				choiceNext: false,
			},
			"14": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_normal', null, 'Hailey/Hailey_casual_grin'],
				class: [null, null, 'fadeRight'],
			  	name: "Hailey",
			  	text: "Oh, thanks for the compliment, babe! Honestly, it's all Tyler's doing. He knows exactly what to do with me, when to correct me, and I'm super goal-oriented with my workouts. So, yeah... we make a pretty killer team!",
				choiceNext: false,
			},
			"15": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_normal', null, 'Hailey/Hailey_casual_grin'],
				class: ['fadeLeft', null, null],
				choicePath: 'daena~importants~0005-19',
			  	name: "Daena",
			  	text: [
					"Really? Tyler and I recently switched up my workout plan so I can see better results. Seeing you on that level might actually serve as a good example for where I should aim to be.",
					"Really? I was actually thinking of quitting recently because I wasn't seeing much change. But seeing how well you're doing, that might just be the example I need to keep going and figure out where I should be aiming."
				],
				choiceNext: false,
			},
			"16": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_normal', null, 'Hailey/Hailey_casual_grin'],
				class: [null, null, 'fadeRight'],
			  	name: "Hailey",
			  	text: "Oh! I didn't expect to become anyone's gym inspo so soon! See, Tyler? You did a fab job with me!",
				choiceNext: false,
			},
			"17": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_normal', null, 'Hailey/Hailey_casual_grin'],
				class: ['fadeLeft', null, null],
			  	name: "Daena",
			  	text: "But like, don't your piercings ever bother you during workouts?",
				choiceNext: false,
			},
			"18": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_normal', null, 'Hailey/Hailey_casual_smiling'],
				class: [null, null, 'fadeRight'],
			  	name: "Hailey",
			  	text: "Nah, girl, I've had these babies for so long I don't even notice ‘em anymore. It'd feel weird if I didn't have ‘em, honestly.",
				choiceNext: false,
			},
			"19": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_normal', null, 'Hailey/Hailey_casual_smiling'],
				class: ['fadeLeft', null, null],
			  	name: "Daena",
			  	text: "Really? That's kinda weird. I don't have anything like that, not even a belly piercing.",
				choiceNext: false,
			},
			"20": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_normal', null, 'Hailey/Hailey_casual_smiling'],
				class: [null, null, null],
			  	name: "",
				textClass: "italic",
			  	text: "At this point, I feel like this conversation is heading in a direction where I'm not really needed.",
				choiceNext: false,
			},
			"21": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_normal', null, 'Hailey/Hailey_casual_smiling'],
				class: [null, null, 'fadeRight'],
			  	name: "Hailey",
			  	text: "Well, not everyone can rock it, y'know? But I see you're still kinda young, so I'd say, wait till you stop growing first. Then you can do whatever you want with your body.",
				choiceNext: false,
			},
			"22": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_surprised', null, 'Hailey/Hailey_casual_smiling'],
				class: ['fadeLeft', null, null],
			  	name: "Daena",
			  	text: "Is that what you did? Waited till you were grown before getting your piercings?",
				choiceNext: false,
			},
			"23": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_surprised', null, 'Hailey/Hailey_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: "Hailey",
			  	text: "Nah, I didn't wait, sadly. And yeah, I kinda paid the price for it, but hey, live and learn, right? That's why I'm tellin' you to wait.",
				choiceNext: false,
			},
			"24": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_normal', null, 'Hailey/Hailey_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Daena",
			  	text: "And is your skin like, natural, or do you tan a lot? Or is it like... the tanning beds?",
				choiceNext: false,
			},
			"25": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_normal', null, 'Hailey/Hailey_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: "Hailey",
			  	text: "Both, babe. Tanning bed's my go-to.",
				choiceNext: false,
            },
			"26": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_surprised', null, 'Hailey/Hailey_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Daena",
			  	text: "Why do you like doing that?",
				choiceNext: false,
            },
			"27": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_surprised', null, 'Hailey/Hailey_casual_smiling'],
				class: [null, null, 'fadeRight'],
			  	name: "Hailey",
			  	text: "Girl, I just love me a good tan, y'know? Plus, it helps show off those bikini lines... dudes go crazy for that. Ain't that right, Tyler?",
				choiceNext: false,
			},
			"28": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_surprised', null, 'Hailey/Hailey_casual_smiling'],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Uh... wait, what?",
				choiceNext: false,
			},
			"29": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_surprised', null, 'Hailey/Hailey_casual_seductive'],
				class: [null, null, 'fadeRight'],
			  	name: "Hailey",
			  	text: "Ooooh, gotcha blushin' just picturin' me all tanned up with those bikini lines, huh?",
				choiceNext: false,
			},
			"30": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_surprised', null, 'Hailey/Hailey_casual_seductive'],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Hailey! Look, Daena might not be a kid anymore, but please don't start teasing me in front of other clients like that!",
				choiceNext: false,
			},
			"31": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_surprised', null, 'Hailey/Hailey_casual_seductive'],
				class: [null, null, 'fadeRight'],
			  	name: "Hailey",
			  	text: "What? So if it's just us, then it's cool?",
				choiceNext: false,
			},
			"32": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_surprised', null, 'Hailey/Hailey_casual_seductive'],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Hailey...",
				choiceNext: false,
			},
			"33": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_surprised', null, 'Hailey/Hailey_casual_seductive'],
				class: [null, null, 'fadeRight'],
			  	name: "Hailey",
			  	text: "Hehe!",
				choiceNext: false,
			},
			"34": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_normal', null, 'Hailey/Hailey_casual_seductive'],
				class: ['fadeLeft', null, null],
			  	name: "Daena",
			  	text: "Wow! I didn't know you two were that close. But Tyler, is it true? Are bikini lines really that attractive to guys?",
				choiceNext: false,
			},
			"35": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_normal', null, 'Hailey/Hailey_casual_seductive'],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Well, I'm sure some guys are into it, and others... not so much.",
				choiceNext: false,
			},
			"36": {
				bgMusic: {
					name: 'FittnessRoom_normal_daily',
					command: 'FADE_OUT',
					insideOfScene: true
				},
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_normal', null, 'Hailey/Hailey_casual_seductive'],
				class: ['fadeLeft', null, null],
			  	name: "Daena",
			  	text: "I'm not asking about \"some guys.\" I wanna know your opinion.",
				choiceNext: true,
			},
			"37": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_normal', null, 'Hailey/Hailey_casual_seductive'],
				class: [null, null, null],
                choicePath: 'hailey~importants~0024-36', //hailey%daena
			  	name: "Tyler",
			  	text: [
                    "I personally love when a woman really takes care of herself and makes sure she stands out, like, \"Hey, look at me!\"",
                    "Honestly, I don't have a type based solely on looks. As the saying goes, the outside attracts, but it's the inside that keeps me.",
                    "I prefer when someone is naturally beautiful, without anything artificial going on."
                ],
				choiceNext: false,
			},
			"38": {
				bgMusic: {
					name: 'Girls_argument',
					command: 'START',
				},
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: [['Daena/Daena_casual_normal', 'Daena/Daena_casual_normal', 'Daena/Daena_casual_smiling'], null, ['Hailey/Hailey_casual_smiling', 'Hailey/Hailey_casual_normal', 'Hailey/Hailey_casual_seductive']],
				class: [[null, null, 'fadeLeft'], null, ['fadeRight', 'fadeRight', null]],
                choicePath: 'hailey~importants~0024-36', //hailey%daena
			  	name: ["Hailey", "Hailey", "Daena"],
			  	text: [
                    "Hmm... I feel like that's kinda aimed at me.",
                    "Yeah, nice try, but that's not an answer. What part of the outside actually grabs your attention?",
                    "Oh, awesome! So I don't have to stress about it then!"
                ],
				choiceNext: false,
			},
			"39": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: [['Daena/Daena_casual_normal', 'Daena/Daena_casual_normal', 'Daena/Daena_casual_smiling'], null, ['Hailey/Hailey_casual_smiling', 'Hailey/Hailey_casual_normal', 'Hailey/Hailey_casual_seductive']],
				class: [null, null, null],
                choicePath: 'hailey~importants~0024-36', //hailey%daena
			  	name: 'Tyler',
			  	text: [
                    "Yeah, Hailey, that wasn't really in question.",
                    "Honestly, it's just a feeling. Sometimes I see someone, and boom, there's that instant spark.",
                    "No, Daena, there's really no need. You're great just the way you are."
                ],
				choiceNext: false,
			},
			"40": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: [['Daena/Daena_casual_sad', 'Daena/Daena_casual_sad', 'Daena/Daena_casual_smiling'], null, ['Hailey/Hailey_casual_smiling', 'Hailey/Hailey_casual_normal', 'Hailey/Hailey_casual_sad']],
				class: [['fadeLeft', 'fadeLeft', null], null, [null, null, 'fadeRight']],
                choicePath: 'hailey~importants~0024-36', //hailey%daena
			  	name: ["Daena", "Daena", "Hailey"],
			  	text: [
                    "But seriously, tell me, what's so much better about a non-natural female body?",
                    "Well, that didn't really get us anywhere.",
                    "So, all about natural, huh? Well... I'm afraid I'm way past that, no going back for me!"
                ],
				choiceNext: false,
			},
			"41": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: [['Daena/Daena_casual_sad', 'Daena/Daena_casual_sad', 'Daena/Daena_casual_smiling'], null, ['Hailey/Hailey_casual_smiling', 'Hailey/Hailey_casual_normal', 'Hailey/Hailey_casual_sad']],
				class: [null, null, null,],
                choicePath: 'hailey~importants~0024-36', //hailey%daena
			  	name: "Tyler",
			  	text: [
                    "It's just... well, it's more noticeable. In every way, really. And since guys are super visual creatures, it grabs our attention right away.",
                    "I'm sorry, but that's honestly all I've got on this.",
                    "That doesn't mean you're not beautiful, Hailey... but if I had to choose, I'd lean toward someone more natural."
                ],
				choiceNext: false,
			},
			"42": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: [['Daena/Daena_casual_sad', 'Daena/Daena_casual_sad', 'Daena/Daena_casual_smiling'], null, ['Hailey/Hailey_casual_smiling', 'Hailey/Hailey_casual_sad', 'Hailey/Hailey_casual_sad']],
				class: [['fadeLeft', null, null], null, [null, 'fadeRight', 'fadeRight']],
                choicePath: 'hailey~importants~0024-36', //hailey%daena
			  	name: ["Daena", "Hailey", "Hailey"],
			  	text: [
                    "And that right there is why I'll never fully get dudes.",
                    "It's like you're dodging the question on purpose.",
                    "I get it... but it still kinda bums me out."
                ],
				choiceNext: false,
			},
            "43": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: [['Daena/Daena_casual_sad', 'Daena/Daena_casual_sad', 'Daena/Daena_casual_smiling'], null, ['Hailey/Hailey_casual_smiling', 'Hailey/Hailey_casual_sad', 'Hailey/Hailey_casual_sad']],
				class: [null, null, null],
                choicePath: 'hailey~importants~0024-36', //hailey%daena
			  	name: "",
			  	text: "And just at that moment, Daena's mom, Angie, finally steps out of the women's locker room, giving me a way out of this conversation.",
				choiceNext: false,
			},
			"44": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: [['Daena/Daena_casual_sad', 'Daena/Daena_casual_sad', 'Daena/Daena_casual_smiling'], 'Angie/Angie_casual_normal', ['Hailey/Hailey_casual_smiling', 'Hailey/Hailey_casual_sad', 'Hailey/Hailey_casual_sad']],
				class: [null, 'fadeUp', null],
                choicePath: 'hailey~importants~0024-36', //hailey%daena
			  	name: 'Angie',
			  	text: "Alright, sweetie, I'm ready. Let's go.",
				choiceNext: false,
			},
			"45": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Daena/Daena_casual_normal', 'Angie/Angie_casual_normal', ['Hailey/Hailey_casual_smiling', 'Hailey/Hailey_casual_sad', 'Hailey/Hailey_casual_sad']],
				class: ['fadeLeft', null, null],
                choicePath: 'hailey~importants~0024-36', //hailey%daena
			  	name: 'Daena',
			  	text: "Okay, see you guys, and thanks again for the workout!",
				choiceNext: false,
			},
			"46": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Daena/Daena_casual_normal', 'Angie/Angie_casual_normal', 'Hailey/Hailey_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: 'Hailey',
			  	text: "As for me, I'm out too. Catch you next time, Tyler.",
				choiceNext: false,
			},
			"47": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Daena/Daena_casual_normal', 'Angie/Angie_casual_normal', 'Hailey/Hailey_casual_normal'],
				class: [null, null, null],
			  	name: 'Tyler',
			  	text: "Got it. See you all.",
				choiceNext: false,
			},
			"48": {
				bgMusic: {
					name: 'Girls_argument',
					command: 'FADE_OUT',
				},
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Daena/Daena_casual_normal', 'Angie/Angie_casual_normal', 'Hailey/Hailey_casual_normal'],
				class: ['fadeLeftOut', 'fadeUpOut', 'fadeRightOut'],
			  	name: null,
			  	text: "With that, they all left, and the gym suddenly fell quiet. All that's left is to clean up after the last clients, close up the gym, and head home.",
				choiceNext: false,
			},
		},
	},
];