export const scene_23 = [
    { sceneId: "0022" },
	{
		sceneId: "0023",
		lengthNum: 79,
		story: {
			"1": {
				bgMusic: {
					name: 'Morning_normal',
					command: 'START'
				},
                background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "It's Thursday. Not much of my day off yesterday was actually spent resting, and today I'm already back to work. Tomorrow is another day off, though, and I hope it'll be a more peaceful one.",
				choiceNext: false,
            },
			"2": {
                background: "backgrounds/BG_gym_inside_sunny",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "This Thursday starts off interestingly again, as two of my favorite clients are here at the same time: Reina and Brianna.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "They know each other by sight, and it's not uncommon for them to train together or to take over from one another in my sessions. Brianna has no issues with Reina, but unfortunately, the same can't be said in reverse.",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Reina really doesn't like her, though honestly, I can't quite figure out why... Maybe she sees Brianna as some sort of rival.",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "If only she knew how forward Brianna got last time... Reina would bring hell on Earth.",
				choiceNext: false,
			},
			"6": {
                background: "backgrounds/BG_gym_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "The workout went by without much incident, Reina leading the way, followed by Brianna, though she didn't push herself as hard today as she did when Hailey was around.",
				choiceNext: false,
			},
			"7": {
                background: "backgrounds/BG_reception_sunny",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Not long after the workout, they were the last two left in the locker room, but Reina was the first to come out.",
				choiceNext: false,
            },
			"8": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "Hey Tyler. Here's the key. And thanks for today's session.",
				choiceNext: false,
			},
			"9": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "No problem at all.",
				choiceNext: false,
			},
			"10": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "You look a little tired, by the way.",
				choiceNext: false,
			},
			"11": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Yeah, unfortunately, I didn't get much rest yesterday.",
				choiceNext: false,
			},
			"12": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Reina",
			  	text: "Why's that? I only spent the morning with you. What were you up to in the afternoon?",
				choiceNext: false,
			},
			"13": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Well... um...",
				choiceNext: false,
			},
			"14": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Reina/Reina_casual_normal', null],
				class: [null, 'fadeUpOut', null],
			  	name: "",
			  	text: "At that moment, Brianna steps out of the locker room, unintentionally rescuing me from the conversation.",
				choiceNext: false,
			},
			"15": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_normal', null, 'Brianna/Brianna_casual_smiling'],
				class: ['fadeLeft', null, 'fadeRight'],
			  	name: "Brianna",
			  	text: "Hey Tyler! Here's my key. Thanks a lot for today; you really worked me hard!",
				choiceNext: false,
			},
			"16": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_normal', null, 'Brianna/Brianna_casual_smiling'],
				class: ['fadeLeft', null, null],
			  	name: "Reina",
			  	text: "Yeah, that was pretty obvious. By the way, Brianna...",
				choiceNext: false,
			},
			"17": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_normal', null, 'Brianna/Brianna_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: "Brianna",
			  	text: "Yes?",
				choiceNext: false,
			},
			"18": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_normal', null, 'Brianna/Brianna_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Reina",
			  	text: "I heard a rumor that Hailey really had a go at you a few days ago.",
				choiceNext: false,
			},
			"19": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_normal', null, 'Brianna/Brianna_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: "Brianna",
			  	text: "Hailey? Hmm... You mean the tanned one with silver hair and all those piercings?",
				choiceNext: false,
			},
			"20": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_normal', null, 'Brianna/Brianna_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Reina",
			  	text: "Yes, that's her.",
				choiceNext: false,
			},
			"21": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_normal', null, 'Brianna/Brianna_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: "Brianna",
			  	text: "Oh, yeah. That day, I kind of snapped when she made some offhand comment about my age.",
				choiceNext: false,
			},
			"22": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_normal', null, 'Brianna/Brianna_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Reina",
			  	text: "What exactly did she say?",
				choiceNext: false,
			},
			"23": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_normal', null, 'Brianna/Brianna_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: "Brianna",
			  	text: "If I remember right, she said something like, \"You were moving pretty well for your age.\" It really got to me, because yes, I am the age I am, but I definitely don't feel that old... and I don't think I look it either.",
				choiceNext: false,
			},
			"24": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_normal', null, 'Brianna/Brianna_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Reina",
			  	text: "I don't know what she was thinking, acting like she could just tear down someone's self-esteem like that.",
				choiceNext: false,
			},
			"25": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_normal', null, 'Brianna/Brianna_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: "Brianna",
			  	text: "I don't think Hailey's a bad person, really. She just lacks the awareness that some things shouldn't be said in certain situations or to certain people. She just needs to learn to hold her tongue a bit.",
				choiceNext: false,
            },
			"26": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_normal', null, 'Brianna/Brianna_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Reina",
			  	text: "That doesn't change the fact that she needs a good washout of her mouth. You don't insult a woman older than you for her age, her relationship status, or her role as a mother. Especially when none of that even applies to her.",
				choiceNext: false,
            },
			"27": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_normal', null, 'Brianna/Brianna_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: "Brianna",
			  	text: "I agree. Raising three kids on my own and still managing to work is not easy... and on top of that, I have to look good, or else no one will ever notice me or see me as a woman.",
				choiceNext: false,
			},
			"28": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_normal', null, 'Brianna/Brianna_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Reina",
			  	text: "Well, I only have two daughters, though they're still little, so they require a lot of attention. But so far, I've been able to balance parenting with my personal life quite well. Luckily, there's someone who does see me as a woman and treats me that way...",
				choiceNext: false,
			},
			"29": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_normal', null, 'Brianna/Brianna_casual_normal'],
				class: [null, null, null],
			  	name: "",
                textClass: 'italic',
			  	text: "I’m guessing that someone might just be me… maybe?",
				choiceNext: false,
			},
			"30": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_normal', null, 'Brianna/Brianna_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: "Brianna",
			  	text: "You've got your husband for that, so congratulations on finding time for your personal life between work and raising kids. Without a man of my own, the only one I have left in my life to offer kind words is Tyler. And I do value his opinion.",
				choiceNext: false,
			},
			"31": {
                bgMusic: {
					name: 'Morning_normal',
					command: 'STOP'
				},
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_surprised', null, 'Brianna/Brianna_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Reina",
			  	text: "...!",
				choiceNext: false,
			},
			"32": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_surprised', null, 'Brianna/Brianna_casual_normal'],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "What did you just say?",
				choiceNext: false,
			},
			"33": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_surprised', null, 'Brianna/Brianna_casual_surprised'],
				class: [null, null, 'fadeRight'],
			  	name: "Brianna",
			  	text: "What? Did I say something wrong?",
				choiceNext: false,
			},
			"34": {
                bgMusic: {
					name: 'Girls_argument',
					command: 'START'
				},
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_normal', null, 'Brianna/Brianna_casual_normal'],
				class: [null, null, null],
			  	name: "Reina",
			  	text: "What exactly did you mean by that? What kind of relationship do you have with Tyler?",
				choiceNext: false,
			},
			"35": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_normal', null, 'Brianna/Brianna_casual_normal'],
				class: [null, null, null],
			  	name: "",
                textClass: 'italic',
			  	text: "Oh no... is this turning into another catfight?",
				choiceNext: false,
			},
			"36": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_normal', null, 'Brianna/Brianna_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: "Brianna",
			  	text: "All I meant is that I trust his words. At the office, a lot of guys try to flirt with me, but it's pretty obvious what they're after. Tyler is different though, he seems a lot more genuine than the rest.",
				choiceNext: false,
			},
			"37": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_angry', null, 'Brianna/Brianna_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Reina",
			  	text: "But at the office, there must be men your age, right? Tyler's almost 20 years younger than you... that seems like a pretty big gap to me.",
				choiceNext: false,
			},
			"38": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_angry', null, 'Brianna/Brianna_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: "Brianna",
			  	text: "Maybe so, but he's still the most decent guy around. Or don't you think so?",
				choiceNext: false,
			},
			"39": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_normal', null, 'Brianna/Brianna_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Reina",
			  	text: "Oh, I know all too well... he's definitely the most decent...",
				choiceNext: false,
			},
			"40": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_normal', null, 'Brianna/Brianna_casual_surprised'],
				class: [null, null, 'fadeRight'],
			  	name: "Brianna",
			  	text: "\"All too well\"? Is there something between you two that I should know about?",
				choiceNext: false,
			},
			"41": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_normal', null, 'Brianna/Brianna_casual_surprised'],
				class: ['fadeLeft', null, null],
			  	name: "Reina",
			  	text: "Tyler constantly praises me for how much I've learned and how hard I work in training. I'm pretty sure he'd still say I look younger than I am if he didn't already know my exact age. He's the one who keeps me feeling young and fit, and we're always in touch, consulting each other.",
				choiceNext: false,
			},
			"42": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_normal', null, 'Brianna/Brianna_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: "Brianna",
			  	text: "I might not be where you are yet, but I came here with zero experience in working out, and I already feel like I've surpassed most of the other clients. Soon, I'll catch up to you and Hailey too. So I owe a lot to him too, because he's the one keeping me fresh, fit, and youthful.",
				choiceNext: false,
			},
            "43": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_normal', null, 'Brianna/Brianna_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Reina",
			  	text: "Really? Well then, let's hear from him. Tyler, who do you think is fitter and more talented?",
				choiceNext: false,
			},
			"44": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_normal', null, 'Brianna/Brianna_casual_normal'],
				class: [null, null, null],
			  	name: "Reina",
                textClass: "italic",
			  	text: "Oh crap, why do they always put me on the spot like this, when I had nothing to do with the conversation in the first place?",
				choiceNext: true,
			},
			"45": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_normal', null, 'Brianna/Brianna_casual_normal'],
				class: [null, null, null],
                choicePath: 'reina~importants~0023-44', //reina%brianna
			  	name: "Tyler",
			  	text: [
                    "Reina's progress makes me really proud, and I always enjoy working with her.",
                    "Considering how far Brianna has come in such a short time, and how much potential I see in her, I think she could eventually become my most talented female client."
                ],
				choiceNext: false,
			},
			"46": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: [['Reina/Reina_casual_smiling', 'Reina/Reina_casual_scared'], null, 'Brianna/Brianna_casual_normal'],
				class: ['fadeLeft', null, null],
                choicePath: 'reina~importants~0023-44', //reina%brianna
			  	name: "Reina",
			  	text: [
                    "See? We're so in sync that it couldn't be better. He knows exactly what I need, and I know exactly how to perform my best for him. The harmony is perfect.",
                    "You can't be serious! All this time, you've been making me feel like I'm the best, your favorite! And now, I find out like this that you actually see more potential in Brianna?"
                ],
				choiceNext: false,
			},
			"47": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: [['Reina/Reina_casual_smiling', 'Reina/Reina_casual_scared'], null, ['Brianna/Brianna_casual_sad', 'Brianna/Brianna_casual_smiling']],
				class: [null, null, "fadeRight"],
                choicePath: 'reina~importants~0023-44', //reina%brianna
			  	name: "Brianna",
			  	text: [
                    "I get it. Well... maybe in time, I'll have better chances of becoming Tyler's little favorite. At least now I have a bit more motivation.",
                    "It's never enough just to claim the crown or the throne. You have to know how to keep it, too. Because, as you can see, challengers will always come along."
                ],
				choiceNext: false,
			},
			"48": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: [['Reina/Reina_casual_angry', 'Reina/Reina_casual_sad'], null, ['Brianna/Brianna_casual_sad', 'Brianna/Brianna_casual_smiling']],
				class: ['fadeLeft', null, null],
                choicePath: 'reina~importants~0023-44', //reina%brianna
			  	name: "Reina",
			  	text: [
                    "You'd better find another source of motivation because I'm not letting him go that easily to anyone.",
                    "But you, of all people!?"
                ],
				choiceNext: false,
			},
			"49": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: [['Reina/Reina_casual_angry', 'Reina/Reina_casual_sad'], null, 'Brianna/Brianna_casual_angry'],
				class: [null, null, "fadeRight"],
                choicePath: 'reina~importants~0023-44', //reina%brianna
			  	name: "Brianna",
			  	text: [
                    "You talk about him like he's your personal property!",
                    "Do you have some specific problem with me?"
                ],
				choiceNext: false,
			},
			"50": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Reina/Reina_casual_angry', null, 'Brianna/Brianna_casual_angry'],
				class: ['fadeLeft', null, null],
                choicePath: 'reina~importants~0023-44', //reina%brianna
			  	name: "Reina",
			  	text: [
                    "It's not that... I've just never felt so good in a gym, with a trainer, feeling so youthful and truly feminine as I have lately. I owe it all to him, and I don't want this to end anytime soon.",
                    "I just don't see what he could possibly see in you, that's all."
                ],
				choiceNext: false,
			},
			"51": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
                image: ['Reina/Reina_casual_angry', null, ['Brianna/Brianna_casual_sad', 'Brianna/Brianna_casual_normal']],
				class: [null, null, "fadeRight"],
                choicePath: 'reina~importants~0023-44', //reina%brianna
			  	name: "Brianna",
			  	text: [
                    "If you're this obsessed with him, there's nothing I can do about it.",
                    "That's why you're not the trainer, he is. It's up to him to see these things. I don't know what he sees in me either, but I'm glad he does, and that's enough for me."
                ],
				choiceNext: false,
			},
			"52": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
                image: ['Reina/Reina_casual_angry', null, 'Brianna/Brianna_casual_normal'],
                class: [null, null, ["fadeRight", null]],
                choicePath: 'reina~importants~0023-44', //reina%brianna
			  	name: "Brianna",
			  	text: "Anyway, I'm off. Work's calling. See you!",
				choiceNext: false,
			},
			"53": {
                bgMusic: {
					name: 'Girls_argument',
					command: 'FADE_OUT',
                    insideOfScene: true
				},
                background: "backgrounds/BG_reception_sunny",
				charContainer: ['char-left', null, 'char-right'],
                image: ['Reina/Reina_casual_angry', null, 'Brianna/Brianna_casual_normal'],
                class: ["fadeLeftOut", null, "fadeRightOut"],
                choicePath: 'reina~importants~0023-44', //reina%brianna
			  	name: "",
			  	text: "Brianna quickly leaves the gym, but Reina lingers for a little longer.",
				choiceNext: false,
			},
			"54": {
                bgMusic: {
					name: 'Date_with_Reina',
					command: 'START',
				},
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
                image: [null, 'Reina/Reina_casual_normal', null],
                class: [null, "fadeUp", null],
			  	name: "Reina",
			  	text: "Finally, she's gone, and we can talk just the two of us.",
				choiceNext: false,
			},
			"55": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
                image: [null, ['Reina/Reina_casual_smiling', 'Reina/Reina_casual_sad'], null],
                class: [null, "fadeUp", null],
                choicePath: 'reina~importants~0023-44', //reina%brianna
			  	name: "Reina",
			  	text: [
                    "Anyway, thanks for putting her in her place for me. I don't know how I'd survive if, despite all my efforts, someone were to take you away from me...",
                    "Though, I have to admit, it stung a bit to hear that it seems like she's now your new favorite. I'm not sure I even want to talk about it with you... but I guess it's too late now that I'm here…"
                ],
				choiceNext: false,
			},
			"56": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
                image: [null, 'Reina/Reina_casual_normal', null],
                class: [null, "fadeUp", null],
			  	name: "Reina",
			  	text: "So... tomorrow's Friday. That's your day off, right?",
				choiceNext: false,
			},
			"57": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
                image: [null, 'Reina/Reina_casual_normal', null],
                class: [null, null, null],
			  	name: "Tyler",
			  	text: "Yeah, that's right.",
				choiceNext: false,
			},
			"58": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
                image: [null, 'Reina/Reina_casual_smiling', null],
                class: [null, "fadeUp", null],
			  	name: "Reina",
			  	text: "Would you be up for continuing our date from Wednesday?",
				choiceNext: false,
            },
			"59": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
                image: [null, 'Reina/Reina_casual_smiling', null],
                class: [null, null, null],
			  	name: "Tyler",
			  	text: "You mean heading back to the mall and checking out the remaining stores?",
				choiceNext: false,
            },
			"60": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
                image: [null, 'Reina/Reina_casual_grin', null],
                class: [null, "fadeUp", null],
			  	name: "Reina",
			  	text: "No, no. I didn't mean it like that. I was thinking we could take our dating to the next level.",
				choiceNext: false,
			},
			"61": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
                image: [null, 'Reina/Reina_casual_grin', null],
                class: [null, null, null],
			  	name: "Tyler",
			  	text: "Ahhh… I see!",
				choiceNext: false,
			},
			"62": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
                image: [null, 'Reina/Reina_casual_grin', null],
                class: [null, "fadeUp", null],
			  	name: "Tyler",
			  	text: "Exactly! So... what are you in the mood for? What kind of date could you imagine for tomorrow?",
				choiceNext: true,
			},
			"63": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
                image: [null, 'Reina/Reina_casual_grin', null],
                class: [null, null, null],
                choicePath: 'reina~importants~0023-62',
			  	name: "Tyler",
			  	text: [
                    "Since I'm already burning with desire, what do you say we finally book a room and let what needs to happen, happen?",
                    "Hmm... I'm in the mood for something intimate, maybe not behind closed doors, but somewhere we can spend some private time together.",
                    "I'd love to take you on more walks. And if we find ourselves alone, I wouldn't hesitate to hold your hand in public or maybe we could stop somewhere to eat or drink."
                ],
				choiceNext: false,
			},
			"64": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
                image: [null, ['Reina/Reina_casual_sad', 'Reina/Reina_casual_seductive', 'Reina/Reina_casual_normal'], null],
                class: [null, "fadeUp", null],
                choicePath: 'reina~importants~0023-62',
			  	name: "Reina",
			  	text: [
                    "Tyler… Yes, I'm sure I'll feel like I'm on cloud nine when we finally get there, but I still need a bit more time to feel like the moment is right. I'm sorry, but you'll have to wait a little longer. Sometimes, though, I start to wonder if this is all you want from me.",
                    "Yeah, that doesn't sound bad at all. In fact, that's exactly what I had in mind. I already know where I want to take you!",
                    "I know I asked for us to take it slow, but there's no need to be this cautious. You could be a little bolder with me."
                ],
				choiceNext: false,
			},
			"65": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
                image: [null, ['Reina/Reina_casual_sad', 'Reina/Reina_casual_seductive', 'Reina/Reina_casual_normal'], null],
                class: [null, null, null],
                choicePath: 'reina~importants~0023-62',
			  	name: "Tyler",
			  	text: [
                    "That's not true at all!",
                    "Well then, I'm all ears.",
                    "Ahh... I'm really starting to struggle figuring you out—when to hold back and when I can be a bit more forward."
                ],
				choiceNext: false,
			},
			"66": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
                image: [null, ['Reina/Reina_casual_sad', 'Reina/Reina_casual_seductive', 'Reina/Reina_casual_sad'], null],
                class: [null, "fadeUp", null],
                choicePath: 'reina~importants~0023-62',
			  	name: "Reina",
			  	text: [
                    "Then please try to come up with something more restrained.",
                    "Just think back to what happened yesterday in the fitting room.",
                    "I like you and I'm attracted to you, but that doesn't mean I'll just throw myself at you. If you're serious about this relationship, try standing your ground and acting like a man!"
                ],
				choiceNext: false,
			},
			"67": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
                image: [null, ['Reina/Reina_casual_sad', 'Reina/Reina_casual_seductive', 'Reina/Reina_casual_sad'], null],
                class: [null, null, null],
                choicePath: 'reina~importants~0023-62',
			  	name: "Tyler",
			  	text: [
                    "I don't know then... something private, but not a bedroom?",
                    "Hmm... if not underwear shopping, then... something with swimsuits, maybe?",
                    "I don't know then... something private, but not a bedroom?"
                ],
				choiceNext: false,
			},
			"68": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
                image: [null, ['Reina/Reina_casual_smiling', 'Reina/Reina_casual_grin', 'Reina/Reina_casual_smiling'], null],
                class: [null, 'fadeUp', null],
                choicePath: 'reina~importants~0023-62',
			  	name: "Reina",
			  	text: [
                    "Now that's more like it. For example, how about a thermal bath?",
                    "Exactly! You got it! So, if it's swimsuits and bathing, how about the thermal bath?",
                    "Now that's more like it. For example, how about a thermal bath?"
                ],
				choiceNext: false,
			},
			"69": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
                image: [null, ['Reina/Reina_casual_smiling', 'Reina/Reina_casual_grin', 'Reina/Reina_casual_smiling'], null],
                class: [null, null, null],
                choicePath: 'reina~importants~0023-62',
			  	name: "Tyler",
			  	text: "The thermal bath? But there's always a crowd there, even if it's mostly older people!",
				choiceNext: false,
			},
			"70": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
                image: [null, 'Reina/Reina_casual_smiling', null],
                class: [null, "fadeUp", null],
			  	name: "Reina",
			  	text: "Don't worry about that. Sure, there might be others, but the place is huge, and there's plenty of space to slip away for some privacy, especially in the morning when it's less crowded.",
				choiceNext: false,
			},
			"71": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
                image: [null, 'Reina/Reina_casual_smiling', null],
                class: [null, null, null],
			  	name: "Tyler",
			  	text: "Okay... if you're so sure about it, then fine, I'm in.",
				choiceNext: false,
			},
			"72": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
                image: [null, 'Reina/Reina_casual_smiling', null],
                class: [null, "fadeUp", null],
			  	name: "Reina",
			  	text: "I'm glad we could settle this. Well, I'll get going now. I've got a few things to do before I need to pick up the girls. We'll discuss the rest tonight, alright?",
				choiceNext: false,
			},
			"73": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
                image: [null, 'Reina/Reina_casual_smiling', null],
                class: [null, null, null],
			  	name: "Tyler",
			  	text: "Alright.",
				choiceNext: false,
			},
			"74": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
                image: [null, 'Reina/Reina_casual_smiling', null],
                class: [null, "fadeUp", null],
			  	name: "Reina",
			  	text: "Kisses!",
				choiceNext: false,
			},
			"75": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, 'char-middle', null],
                image: [null, 'Reina/Reina_casual_smiling', null],
                class: [null, "fadeUpOut", null],
			  	name: "",
			  	text: "And with that, Reina left the gym.",
				choiceNext: false,
			},
			"76": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "So much for sleeping in and getting a proper rest tomorrow, but this plan sounds promising.",
				choiceNext: false,
			},
			"77": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "Reina, in a swimsuit? Well, it's not lingerie, that's for sure... but let's just ignore the fact that everyone can see a bikini, while lingerie is more private. They both cover about the same amount, and it wouldn't be bad to see her in so little clothing again.",
				choiceNext: false,
			},
			"78": {
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "Maybe this could finally be the moment when things start moving forward.",
				choiceNext: false,
			},
			"79": {
                bgMusic: {
					name: 'Date_with_Reina',
					command: 'FADE_OUT',
				},
                background: "backgrounds/BG_reception_sunny",
				charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "But there's still a long day ahead, so I'd better focus on the clients for now.",
				choiceNext: false,
			},
		},
	},
];