export const scene_7 = [
    { sceneId: "0006" }, //mobileScene: 0006
	{
		sceneId: "0007",
		lengthNum: 37,
		story: {
			"1": {
				bgMusic: {
					name: 'Morning_normal',
					command: 'START'
				},
                background: "backgrounds/BG_railway_station_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Thanks to Hailey's request, I couldn't sleep as much as I wanted today. The tennis courts open at 8 AM on Saturdays.",
				choiceNext: false,
            },
			"2": {
				background: "backgrounds/BG_railway_station_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "If I have an afternoon shift, I usually get to sleep in until around 10, but this is way too early for me, especially since I have to travel all the way to Vensea.",
				choiceNext: false,
			},
			"3": {
				background: "backgrounds/BG_shop_sunny",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "So, I left without breakfast, planning to stop by the store near the station and grab something to eat while I walk.",
				choiceNext: false,
			},
			"4": {
				background: "backgrounds/BG_shop_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "As I groggily wander through the aisles, I suddenly bump into a familiar face.",
				choiceNext: false,
			},
			"5": {
                specialSceneNow: true,
				specialSceneId: "0007-5",
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Brianna?",
				choiceNext: false,
			},
			"6": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Oh, good morning, Tyler!",
				choiceNext: false,
			},
			"7": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Another one of my clients. She's a bit clumsy sometimes and tends to be late for early morning sessions, but she's a real survivor.",
				choiceNext: false,
			},
			"8": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "What are you doing here this early in Vensea? I thought you had an afternoon shift today.",
				choiceNext: false,
			},
			"9": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Yeah, that's right. Just had a little something to take care of, so I had to come in early.",
				choiceNext: false,
			},
			"10": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "This early?",
				choiceNext: false,
			},
			"11": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Unfortunately, yes. And you're shopping? That's a pretty long list you've got there.",
				choiceNext: false,
			},
			"12": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Yeah. Finally got a Saturday off, and my kids won't be scattered all over the place. Some of them are bringing their friends over for lunch, so I'll need a lot of big portions of everything.",
				choiceNext: false,
			},
			"13": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "So much for a relaxing Saturday, huh?",
				choiceNext: false,
			},
			"14": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "It's fine, I'm used to never having a lazy day. But at least today, I only have to come here. Then it's just cooking… washing dishes… cleaning… you know, the usual. Not very exciting, I know.",
				choiceNext: false,
			},
			"15": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Well, someone's gotta clean the house, right?",
				choiceNext: false,
			},
			"16": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "As a single mom, who else can I count on?",
				choiceNext: false,
			},
			"17": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I mean, that's fair, but you could always ask your daughters for help.",
				choiceNext: false,
			},
			"18": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Teenagers— you know how they are.",
				choiceNext: false,
			},
			"19": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Okay, yeah, that's a good point.",
				choiceNext: false,
			},
			"20": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "How about I help you carry all this stuff then?",
				choiceNext: false,
			},
			"21": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Didn't you say you had things to do?",
				choiceNext: false,
			},
			"22": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Yeah, but I'm not on a strict schedule. Plus, I am your trainer, so obviously I can carry a lot more, and I wouldn't mind helping out.",
				choiceNext: false,
			},
			"23": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Thank you, Tyler. That's really sweet of you, but I've managed all this on my own so far, and I don't wanna burden you unnecessarily.",
				choiceNext: false,
			},
			"24": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				name: "Tyler",
				text: "Bria, I'm not offering because I think you can't handle it or because I pity you. I just wanna be polite and chivalrous.",
				choiceNext: false,
			},
			"25": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				name: "Brianna",
				text: "I know you are.",
				choiceNext: false,
			},
			"26": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				name: "Tyler",
				text: "Then, dear lady, I humbly request your noble permission to fulfill my knightly duty by your side on this fine morning.",
				choiceNext: false,
			},
			"27": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Hehe... okay, I see I can't really talk you out of it, so just this once, I'll allow it.",
				choiceNext: false,
			},
			"28": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				name: "Tyler",
				text: "Your kindness is overwhelming, my dear lady!",
				choiceNext: false,
			},
			"29": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				name: "Brianna",
				text: "Thanks so much for your help, Tyler, you will save me a lot of time.",
				choiceNext: false,
			},
			"30": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				name: "Tyler",
				text: "It's really no problem. Anytime you feel like you need help, don't hesitate or be stubborn about asking.",
				choiceNext: false,
			},
			"31": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				name: "Brianna",
				text: "You know that's not going to be easy for me.",
				choiceNext: false,
			},
			"32": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				name: "Tyler",
				text: "Yeah, which is why I'll keep reminding you.",				
				choiceNext: false,
			},
			"33": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				name: "Brianna",
				text: "Alright, then. But since it'll take some time, would you like a ride to where you were heading?",	
				choiceNext: true,
			},
			"34": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'brianna~notImportants~0007-33',
				name: "Tyler",
				text: [
					"Thanks, but like I said, I'm not in a hurry, and I still need to eat something. I don't wanna get crumbs all over your car.",
					"Thanks, that'd actually be nice."
				],	
				choiceNext: false,
			},
			"35": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'brianna~notImportants~0007-33',
				name: "Brianna",
				text: [
					"I wouldn't worry about that if I were you, but as you wish, I won't push it. I just want to return the favor for your kindness.",
					"Good. Let's finish here, and I'll take you wherever you need to go."
				],
				choiceNext: false,
			},
			"36": {
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'brianna~notImportants~0007-33',
				name: "Tyler",
				text: [
					"I'm sure you'll have plenty of chances to do that in the future.",
					"Alright, let's do it."
				],
				choiceNext: false,
                stepSkip: [0, 1]
			},
			"37": {
				bgMusic: {
					name: 'Morning_normal',
					command: 'FADE_OUT'
				},
				background: "special_scenes/0007-5",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'brianna~notImportants~0007-33',
				name: ["Brianna", null],
				text: [
					"We'll see.",
					null
				],
				choiceNext: false,
				backStepSkip: [0, 1],
			}
		},
	},
];