export const scene_31 = [
	{
		sceneId: "0031",
		lengthNum: 57,
		story: {
			"1": {
				bgMusic: {
					name: 'Morning_normal',
					command: 'START'
				},
                background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Saturday morning has finally arrived. I'd been looking forward to it, because my Friday night would turn out exactly as I'd imagined...",
				choiceNext: false,
            },
 			"2": {
                background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Lindsay kept promising that she'd changed, that she wasn't so temperamental anymore, and that she'd approach relationships with a more mature attitude. When everything's going well, it seems like she's holding to that promise, but the moment something doesn't go as she expects, all those promises go out the window.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "So, I have no regrets about how my night turned out—at least I didn't do anything I'd regret later.",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "This morning, however, has the potential to be even better, since I promised Daena I'd join her at the water park. I'll have to get an early start to make it to Brianna's by noon, but whatever, I can handle it.",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_spa_outside_sunny",
				backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I'm the first to arrive at the entrance of the water park, and I wait a bit for Daena, who looks delighted when she sees I'm already there.",
				choiceNext: false,
			},
			"6": {
                background: "backgrounds/BG_spa_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_smiling', null],
				class: [null, "fadeUp", null],
			  	name: "Daena",
			  	text: "Good morning, Tyler!",
				choiceNext: false,
			},
			"7": {
                background: "backgrounds/BG_spa_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Good morning, Daena.",
				choiceNext: false,
            },
			"8": {
                background: "backgrounds/BG_spa_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_smiling', null],
				class: [null, "fadeUp", null],
			  	name: "Daena",
			  	text: "How did you sleep? All rested up for our day of relaxation?",
				choiceNext: false,
			},
			"9": {
                background: "backgrounds/BG_spa_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Well, about last night... I'd rather not get into it. Let's just say it could have been worse. But I'm glad it's Saturday, and I get to be here with you.",
				choiceNext: false,
			},
			"10": {
                background: "backgrounds/BG_spa_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_embarrassed', null],
				class: [null, "fadeUp", null],
			  	name: "Daena",
			  	text: "Aww, that was so sweet, thank you!",
				choiceNext: false,
			},
			"11": {
                background: "backgrounds/BG_spa_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_smiling', null],
				class: [null, "fadeUp", null],
			  	name: "Daena",
			  	text: "Alright, you said your time is limited, so let's not waste any more—shall we head in?",
				choiceNext: false,
			},
			"12": {
                background: "backgrounds/BG_spa_outside_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_smiling', null],
				class: [null, 'fadeUpOut', null],
			  	name: "",
			  	text: "We made our way inside. At the ticket counter, Daena insisted on paying since she'd invited me, saying she'd use some money she got from her parents. But I was just as determined to be a gentleman. It took some convincing, but she finally let me pay.",
				choiceNext: false,
			},
			"13": {
                background: "backgrounds/BG_spa_changing_room",
				backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Inside, the changing rooms are separated by gender. As I change into my swim trunks, I find myself lost in thought.",
				choiceNext: false,
			},
			"14": {
				background: "backgrounds/BG_spa_changing_room",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
				textClass: "italic",
			  	text: "Not that I'm not curious about Daena, but why was going to the pool the first thing she thought of as a shared activity?",
				choiceNext: false,
			},
			"15": {
				background: "backgrounds/BG_spa_changing_room",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
				textClass: "italic",
			  	text: "Okay, she's been sending me some pretty clear signals lately, and I think it's safe to say I'm not misinterpreting them. But if she wants to impress me that much, she doesn't need to go this far just for me to see her in a bikini.",
				choiceNext: false,
			},
			"16": {
				background: "backgrounds/BG_spa_changing_room",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
				textClass: "italic",
			  	text: "From a guy's point of view, sure, but from a girl's perspective, a bikini isn't the same as underwear. So, that might explain why she'd want to show herself off in that kind of outfit, but I've never seen this much of her skin before, and that's a pretty big step on her part.",
				choiceNext: false,
			},
			"17": {
				background: "backgrounds/BG_spa_changing_room",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
				textClass: "italic",
			  	text: "But whatever; the view will definitely be worth it, and I came here to relax, not to play psychologist.",
				choiceNext: false,
			},
			"18": {
				background: "backgrounds/BG_spa_inside_sunny",
				backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
				textClass: "",
			  	text: "Once I'm done changing, I head out to the pool with only the essentials. There aren't too many people here this early in the morning; I figure there'll be a crowd by the time I have to leave. But with this few people, it shouldn't be hard to spot Daena, so I go looking for her.",
				choiceNext: false,
			},
			"19": {
				background: "backgrounds/BG_spa_inside_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "After a few minutes, I still haven't found her. Not at the women's locker room exit, not among the lounge chairs—she's done a great job hiding. I even start wondering if she turned around and went home. But then...",
				choiceNext: false,
			},
			"20": {
				bgMusic: {
					name: 'Date_with_Daena',
					command: 'START'
				},
                specialSceneNow: true,
				specialSceneId: '0031-20',
				background: "special_scenes/0031-20",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Tyler! Over here!",
				choiceNext: false,
			},
			"21": {
				background: "special_scenes/0031-20",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Oh, there you are, fina— Wow, Daena!",
				choiceNext: false,
			},
			"22": {
				background: "special_scenes/0031-20",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "What? Like what you see?",
				choiceNext: false,
			},
            "23": {
				background: "special_scenes/0031-20",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Uh, yeah... I mean no... I mean, not that I don't, but...",
				choiceNext: false,
			},
			"24": {
				background: "special_scenes/0031-20",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Haha! Finally, I get to make you blush if I try hard enough! But don't worry, I'd love an honest answer, ‘cause you can't lie with those reflexes of yours.",
				choiceNext: false,
			},
			"25": {
				background: "special_scenes/0031-20",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Okay... well, the bikini looks great on you.",
				choiceNext: false,
            },
			"26": {
				background: "special_scenes/0031-20",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Thanks! And...?",
				choiceNext: false,
            },
			"27": {
				background: "special_scenes/0031-20",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "And...?",
				choiceNext: false,
			},
			"28": {
				background: "special_scenes/0031-20",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "So, you're only impressed by my bikini?",
				choiceNext: false,
			},
			"29": {
				background: "special_scenes/0031-20",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "What else could I say?",
				choiceNext: false,
			},
			"30": {
				background: "special_scenes/0031-20",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "You know, Tyler, it's kinda hard to think of a hotter setup than this where you'd see this much of me—so you can give me a full body check, if you know what I mean.",
				choiceNext: false,
			},
			"31": {
				background: "special_scenes/0031-20",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Whoa, wait a sec! Are we really just here for me to... check out your progress?",
				choiceNext: false,
			},
			"32": {
				specialSceneId: '0031-32',
				background: "special_scenes/0031-32",
				backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Hmm... were you hoping it's, like, a date or something?",
				choiceNext: false,
			},
			"33": {
				background: "special_scenes/0031-32",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
				taxtClass: "italic",
			  	text: "I think I'm completely thrown off now.",
				choiceNext: false,
			},
			"34": {
				background: "special_scenes/0031-32",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Haha! I can totally read what's on your mind, so I'll quit messing with ya and just explain what's going on.",
				choiceNext: false,
			},
			"35": {
				background: "special_scenes/0031-32",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "The conversation I had with Hailey left a bit of an impression on me...",
				choiceNext: false,
			},
			"36": {
				background: "special_scenes/0031-32",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'daena~importants~0024-36',
			  	name: "Daena",
			  	text: [
					"It's a shame you're into girls like Hailey. I've thought a lot since then about whether I could look like her.",
					"Too bad you dodged the question about what kind of girls you like. If you're not going to answer now either, then I have to try something.",
					"I'm glad that you like natural girls more, so at least I don't have to change anything about myself to fit your type."
				],
				choiceNext: false,
			},
			"37": {
				background: "special_scenes/0031-32",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'daena~importants~0024-36',
			  	name: "Daena",
			  	text: [
					"I tried all sorts of outfits in front of my mirror, tried posing and acting like her, but I just couldn't feel comfortable in that role.",
					"I hope you won't run away from this and that I can count on your honesty.",
					"I'd like to take this conversation a bit further, get a deeper sense of what you like in girls, beyond just being \"natural.\""
				],
				choiceNext: false,
			},
			"38": {
				background: "special_scenes/0031-32",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'daena~importants~0024-36',
			  	name: "Tyler",
			  	text: [
					"I'm glad this is the conclusion you came to because you're great just as you are.",
					"I can't promise anything, Daena, but I've never lied to you.",
					"Um... okay, but I don't see why you're stressing over this so much. You could see it on my face that I like what I see."
				],
				choiceNext: false,
			},
			"39": {
				bgMusic: {
					name: 'Date_with_Daena',
					command: 'FADE_OUT',
					insideOfScene: true
				},
				background: "special_scenes/0031-32",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'daena~importants~0024-36',
			  	name: "Daena",
			  	text: [
					"And yet, it's still not enough for you to think more highly of me than Hailey. But whatever, I'd rather talk about something else with you now.",
					"That may be true, but I'll need you to take responsibility and answer my next question.",
					"There's something I definitely need to be sure about."
				],
				choiceNext: false,
			},
			"40": {
				background: "special_scenes/0031-32",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "And what's that?",
				choiceNext: false,
			},
			"41": {
				bgMusic: {
					name: 'Mysterious',
					command: 'START',
				},
				background: "special_scenes/0031-32",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Who do you prefer more? Teenage girls, women your age, or heaven forbid—older women?",
				choiceNext: false,
			},
			"42": {
				background: "special_scenes/0031-32",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Um... are you serious?",
				choiceNext: false,
			},
			"43": {
				background: "special_scenes/0031-32",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "I am.",
				choiceNext: false,
			},
            "44": {
				background: "special_scenes/0031-32",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Daena... the answer you'd want to hear most would obviously be teenage girls, and the other options would be out of the question. If I choose that, it's up to you whether you believe me or assume I'm saying it just to avoid hurting your feelings.",
				choiceNext: false,
			},
			"45": {
				background: "special_scenes/0031-32",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "So, I'd rather answer your question differently: Age can matter, but it's not the most important factor for me. A teenage girl can be mature and responsible, while a 40+ mom can be childish, playful, and immature.",
				choiceNext: false,
			},
			"46": {
				background: "special_scenes/0031-32",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "In short, I wouldn't choose someone solely based on age.",
				choiceNext: false,
            },
			"47": {
				background: "special_scenes/0031-32",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Hmm... I see your logic. So, let me rephrase my question a little: How exciting do you find a teenage girl's body? Is it as good or better than a woman's closer to 30?",
				choiceNext: false,
            },
			"48": {
				background: "special_scenes/0031-32",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
				textClass: "italic",
			  	text: "Oh boy, this is a serious question, and I need to think this one through...",
				choiceNext: true,
			},
			"49": {
				background: "special_scenes/0031-32",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'daena~importants~0031-48',
			  	name: "Tyler",
			  	text: [
					"Daena, it'd be great if you could drop this rivalry, especially with Hailey, because this isn't a competition. Neither you, nor her, nor I am some kind of big prize.",
					"Hmm... what I'm kinda missing in my life is my overly active teenage years. Back then, I didn't have much luck with girls, and that's missing—and I'm curious what a teenage girl can do with her qualities.",
					"No question, teenage girls are the best! They're still fresh, delicate, not as worn out or corrupted as girls my age or even older ones.",
					"It's possible to look good and sexy young, and it's tempting to think about what it'd be like to have a fling with them... but they're still so... young, inexperienced, and I don't want to be the one to be their first bad influence."
				],
				choiceNext: false,
			},
			"50": {
				specialSceneId: ['0031-50', '0031-32', '0031-52', '0031-52'],
				background: ["special_scenes/0031-50", "special_scenes/0031-32", "special_scenes/0031-52", "special_scenes/0031-52"],
				backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'daena~importants~0031-48',
			  	name: "Daena",
			  	text: [
					"Even if I overlook the end of it, I can't really agree. I'm not seeing this as a competition, but Hailey is the only obstacle I see right now that I need to overcome to get the guy I want!",
					"Really? Didn't think it didn't go so well with girls when you were a teen. Whatever changed in you, it worked out in your favor, because if anyone, I'd be happy to show you what an 18-year-old girl today can do.",
					"O-kaaay... I'm glad that you're into teens, but I didn't think you'd be so into them. Definitely didn't expect you'd look down on women like that just ten years older.",
					"That was a bit much, Tyler. Like, yeah, I might be inexperienced, but a lot of my friends are already in active relationships, so \"corrupting\" them isn't even a thing."
				],
				choiceNext: false,
			},
			"51": {
				background: ["special_scenes/0031-50", "special_scenes/0031-32", "special_scenes/0031-52", "special_scenes/0031-52"],
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'daena~importants~0031-48',
			  	name: "Tyler",
			  	text: [
					"You don't need to compete with her; just be yourself and ignore her.",
					"I thought you were still inexperienced.",
					"I could've put it this way too: fresh fruit is the sweetest to me.",
					"Yeah, and that's a problem. A lot of teens think they know everything and that they're gods or goddesses, but life will soon hit them with a reality check."
				],
				choiceNext: false,
			},
			"52": {
				bgMusic: {
					name: 'Mysterious',
					command: 'FADE_OUT',
					insideOfScene: true
				},
				specialSceneId: '0031-52',
				background: "special_scenes/0031-52",
				backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				choicePath: 'daena~importants~0031-48',
			  	name: "Daena",
			  	text: [
					"If that's all it takes to change your view on women to prefer naturalness, then okay, I'll go with it.",
					"Y-yeah, I guess you're right... maybe I'm not the best example for you, but I'm hoping it means something that with me... it'd be pretty emotional.",
					"Could be, but that wasn't the first thing that came to your mind. Plus, it wouldn't have changed the point.",
					"Thanks for the heads-up; I'll keep an eye out for these signs."
				],
				choiceNext: false,
			},
			"53": {
				bgMusic: {
					name: 'Date_with_Daena',
					command: 'START',
					insideOfScene: true
				},
				background: "special_scenes/0031-52",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Anyway, I more or less got the info I wanted, so now it's time to enjoy the fun part of the day.",
				choiceNext: false,
			},
			"54": {
				background: "special_scenes/0031-52",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "The fun part?",
				choiceNext: false,
			},
			"55": {
				background: "special_scenes/0031-32",
				backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "You didn't think I'd ask for a swim lesson or aquafitness session, did you?",
				choiceNext: false,
			},
			"56": {
				background: "special_scenes/0031-32",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "No, definitely not.",
				choiceNext: false,
			},
			"57": {
                bgMusic: {
					name: 'Date_with_Daena',
					command: 'FADE_OUT'
				},
				background: "special_scenes/0031-32",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Good! Then let's hit the slide until we're all worn out!",
				choiceNext: false,
				timeSkipNext: {
					content: "Later at noon...",
					nextSceneType: "STORY",
					nextSceneNumber: "0032",
				}
			},
		},
	},
];