export const daena_bad = [
	{
		sceneId: "",
		lengthNum: 44,
		story: {
			"1": {
				bgMusic: {
					name: 'Date_with_Daena',
					command: 'START'
				},
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I'm on my way to see Daena now; she wants to meet at her place. I've never been there before, so it's actually kind of exciting. It's been ages since I've had that experience of a teenage girl inviting me into her room.",
				choiceNext: false,
            },
 			"2": {
                background: "backgrounds/BG_Daena_house_sunny",
				backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "When I arrive at her family's house, I ring the doorbell, and after a short wait, Daena steps outside.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I notice a slight smile on her face, but she's not her usual high-energy self. She seems... subdued, which feels a bit strange for her.",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "She walks up to the gate, but instead of letting me in right away, she stops to chat with me first.",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "Hey, Tyler.",
				choiceNext: false,
			},
			"6": {
                background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Hey, Daena. Is something wrong?",
				choiceNext: false,
			},
			"7": {
                background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "Why do you ask?",
				choiceNext: false,
            },
			"8": {
                background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I don't know, you just seem... reserved. Like something's bothering you, and you're holding it in.",
				choiceNext: false,
			},
			"9": {
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "Oh... uh... didn't think it was that obvious.",
				choiceNext: false,
			},
			"10": {
                background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "So, there really is something, then.",
				choiceNext: false,
			},
			"11": {
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "Yeah... there is.",
				choiceNext: false,
			},
			"12": {
                background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "And does it have anything to do with what you messaged me about last night? You said you needed to talk about something important.",
				choiceNext: false,
			},
			"13": {
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "It's not just related to that—it's the whole thing.",
				choiceNext: false,
			},
			"14": {
                background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Alright, so... would you let me in and tell me what's going on?",
				choiceNext: false,
			},
			"15": {
				bgMusic: {
					name: 'Date_with_Daena',
					command: 'STOP'
				},
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "...",
				choiceNext: false,
			},
			"16": {
                background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Daena?",
				choiceNext: false,
			},
			"17": {
				bgMusic: {
					name: 'Bad_ending_with_main_girls',
					command: 'START'
				},
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_sad', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "No... I'm sorry, Tyler, but I don't think there's a reason to let you in.",
				choiceNext: false,
			},
			"18": {
                background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_sad', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "What? Why are you saying that?",
				choiceNext: false,
			},
			"19": {
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_sad', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "Believe me, it's really hard for me to talk about this. I struggled a lot with this decision, but I had to settle my own feelings.",
				choiceNext: false,
			},
			"20": {
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_sad', null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Believe me, it's really hard for me to talk about this. I struggled a lot with this decision, but I had to settle my own feelings.",
				choiceNext: false,
			},
			"21": {
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_sad', null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Tyler... I don't think it's a huge secret that I really like you. This past week, I feel like I've gotten to know you on a much deeper level. I got to see the person behind the trainer persona, and I'm so glad I'm one of the few who's had that chance.",
				choiceNext: false,
			},
			"22": {
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_sad', null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Up until yesterday, during our swim, I was working hard to understand that side of you and to get closer... but I feel like that didn't happen on your end.",
				choiceNext: false,
			},
            "23": {
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_sad', null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Sorry, but... I just don't feel enough of a spark between us to keep trying, you know? I wanted there to be something, 'cause you're a great guy and all, but... there's just something missing. Guess it only seemed like a perfect match in my head...",
				choiceNext: false,
			},
			"24": {
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_sad', null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "But the reality is, I don't think there's a future for us. I'm sorry.",
				choiceNext: false,
			},
			"25": {
                background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_sad', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Well, I... I'm kinda speechless. But, what was wrong? Was there something I could've done differently? I can work on it if that's what it'd take to bring us closer.",
				choiceNext: false,
            },
			"26": {
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_sad', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "I don't want that, Tyler. I've made up my mind, and it's final! I wouldn't want you to change just for me or try to be someone you're not. I wanted to fall for the real you... but it just didn't happen.",
				choiceNext: false,
            },
			"27": {
                background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_sad', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Ah... Well, that's tough to hear. And if you say it's final... I'm mature enough to know that if I push, it won't change your mind.",
				choiceNext: false,
			},
			"28": {
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "I'm glad you can take this rejection in stride.",
				choiceNext: false,
			},
			"29": {
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "So... this is goodbye, probably for good, 'cause... after this, I don't think it'd feel right to keep coming to you for training.",
				choiceNext: false,
			},
			"30": {
                background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Oh... so you really don't even want to see me around?",
				choiceNext: false,
			},
			"31": {
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "No, don't take it as hate... it's just... it'd be too weird. It'd make it easier for me to get over it if we don't meet anymore. I don't want to keep facing that feeling, like you're great and all, but deep down, there's just not enough there for this to make sense.",
				choiceNext: false,
			},
			"32": {
                background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I get it... I never thought I'd lose you like this, as both a woman in my life and a client.",
				choiceNext: false,
			},
			"33": {
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "Like I said, this wasn't an easy call for me either.",
				choiceNext: false,
			},
			"34": {
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, null, null],
			  	name: "Daena",
			  	text: "Alright, I've said everything, held nothing back, so now you know the full truth. Thanks for letting me get to know you and for everything you did for me... but this chapter's closed.",
				choiceNext: false,
			},
			"35": {
                background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "...",
				choiceNext: false,
			},
			"36": {
                background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I understand. Take care of yourself, and best of luck with everything ahead.",
				choiceNext: false,
			},
			"37": {
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "Thank you, you too.",
				choiceNext: false,
			},
			"38": {
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Daena",
			  	text: "Bye.",
				choiceNext: false,
			},
			"39": {
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Daena/Daena_casual_normal', null],
				class: [null, 'fadeUpOut', null],
			  	name: "",
			  	text: "With that, Daena turns around and heads back into the house without looking back once.",
				choiceNext: false,
			},
			"40": {
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "It stings, honestly, but I could see how set she was in her decision, and not even a miracle could change that.",
				choiceNext: false,
			},
			"41": {
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I hate this feeling, the sense of failure, but it's her choice who she wants to be with and who she doesn't, and I've got to respect that.",
				choiceNext: false,
			},
			"42": {
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "As I'm leaving, I catch a glimpse of her mom, Angie, watching from one of the first-floor windows. Her expression's hard to read with the glare, but it almost seems like sadness instead of disappointment.",
				choiceNext: false,
			},
			"43": {
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "But our eyes only meet for a split second before she steps away and pulls the curtain closed.",
				choiceNext: false,
			},
            "44": {
				bgMusic: {
					name: 'Bad_ending_with_main_girls',
					command: 'FADE_OUT',
				},
				background: "backgrounds/BG_Daena_house_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I've got no more reason to be here. Daena's out of my life.",
				choiceNext: false,
			},
		},
	},
];