export const harem_1 = [
    {
        sceneId: "",
        lengthNum: 121,
		endingSceneType: '',
        story: {
            "1": {
                otherSoundEffect: "knock-on-door",
                background: "backgrounds/BG_Tyler_livingroom_sunny",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "",
                text: "*knock-knock*",
                choiceNext: false,
            },
            "2": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "",
                text: "???",
                choiceNext: false,
            },
            "3": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "",
                textClass: "italic",
                text: "Who could that be? I wasn't expecting anyone at this time.",
                choiceNext: false,
            },
            "4": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "",
                text: "I open the door, and the one who's standing on the doorstep is...",
                choiceNext: false,
            },
            "5": {
                bgMusic: {
					name: 'Harem_ending_beginning',
					command: 'START'
				},
                background: "backgrounds/BG_Tyler_livingroom_sunny",
                charContainer: [null, 'char-middle', null],
                image: [null, 'Hailey/Hailey_casual_smiling', null],
                class: [null, 'fadeUp', null],
                name: "",
                text: "Hailey!",
                choiceNext: false,
            },
            "6": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
                charContainer: [null, 'char-middle', null],
                image: [null, 'Hailey/Hailey_casual_grin', null],
                class: [null, 'fadeUp', null],
                name: "Hailey",
                text: "Hey, Tyler! Surprise!",
                choiceNext: false,
            },
            "7": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
                charContainer: [null, 'char-middle', null],
                image: [null, 'Hailey/Hailey_casual_grin', null],
                class: [null, null, null],
                name: "Tyler",
                text: "Hey, Hailey. What brings you here? I thought we agreed to meet a little later.",
                choiceNext: false,
            },
            "8": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
                charContainer: [null, 'char-middle', null],
                image: [null, 'Hailey/Hailey_casual_smiling', null],
                class: [null, 'fadeUp', null],
                name: "Hailey",
                text: "I know, but I thought I'd surprise you instead. Hope I'm not catching you at a bad time. Mind if I come in?",
                choiceNext: false,
            },
            "9": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
                charContainer: [null, 'char-middle', null],
                image: [null, 'Hailey/Hailey_casual_smiling', null],
                class: [null, null, null],
                name: "Tyler",
                text: "Oh, of course. Come on in.",
                choiceNext: false,
            },
            "10": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
                charContainer: [null, 'char-middle', null],
                image: [null, 'Hailey/Hailey_casual_smiling', null],
                class: [null, 'fadeUp', null],
                name: "Hailey",
                text: "Thanks.",
                choiceNext: false,
            },
            "11": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
                charContainer: [null, 'char-middle', null],
                image: [null, 'Hailey/Hailey_casual_surprised', null],
                class: [null, 'fadeUp', null],
                name: "Hailey",
                text: "Oh my gosh, wow! It's like... so clean in here! Honestly, I was totally expecting some, like, messy bachelor pad vibes.",
                choiceNext: false,
            },
            "12": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
                charContainer: [null, 'char-middle', null],
                image: [null, 'Hailey/Hailey_casual_surprised', null],
                class: [null, 'fadeUp', null],
                name: "Tyler",
                text: "Well, glad I could surprise you in a good way. Want something to drink?",
                choiceNext: false,
            },
            "13": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
                charContainer: [null, 'char-middle', null],
                image: [null, 'Hailey/Hailey_casual_smiling', null],
                class: [null, 'fadeUp', null],
                name: "Hailey",
                text: "No thanks, I'm good.",
                choiceNext: false,
            },
            "14": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
                charContainer: [null, 'char-middle', null],
                image: [null, 'Hailey/Hailey_casual_smiling', null],
                class: [null, null, null],
                name: "Tyler",
                text: "Alright... have a seat and let's get into it. Whatever it is you wanted to talk about.",
                choiceNext: false,
            },
            "15": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "Alright.",
				choiceNext: false,
			},
			"16": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "So... it's about us.",
				choiceNext: false,
			},
			"17": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
			  	name: "Hailey",
			  	text: "I mean, over this last week, I feel like we've been getting closer and closer. Almost too close, really, cuz... as you know, I'm in a relationship.",
				choiceNext: false,
			},
			"18": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Exactly. Some of the things you've said or done have totally caught me off guard — especially since you're already in a relationship.",
				choiceNext: false,
			},
			"19": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "Totally get that. I mean, I've surprised myself too. But when I'm with you...",
				choiceNext: false,
			},
			"20": {
                bgMusic: {
					name: 'Harem_ending_beginning',
					command: 'STOP'
				},
                otherSoundEffect: "knock-on-door",
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
			  	name: "",
			  	text: "*knock-knock*",
				choiceNext: false,
			},
			"21": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "Hm?",
				choiceNext: false,
			},
			"22": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "Oh no, this isn't good. Who could it be at a time like this?",
				choiceNext: false,
			},
			"23": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "Tyler, are you expecting someone?",
				choiceNext: false,
			},
			"24": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I-I mean, yeah, I was expecting a guest... but not now!",
				choiceNext: false,
			},
			"25": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
			  	name: "",
			  	text: "*knock-knock*",
				choiceNext: false,
			},
            "26": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Hailey",
			  	text: "Aren't you gonna check who it is?",
				choiceNext: false,
			},
            "27": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Y-Yeah... I guess I have to.",
				choiceNext: false,
			},
            "28": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
			  	name: "",
                textClass: "italic",
			  	text: "Please, please let it not be Reina, because I have no idea how I'll get out of this one!",
				choiceNext: false,
			},
            "29": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
			  	name: "",
			  	text: "With shaky hands, I open the door, and standing there is none other than...",
				choiceNext: false,
			},
            "30": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Daena/Daena_casual_smiling', 'Hailey/Hailey_casual_normal', 'Hailey/Hailey_casual_normal'],
				class: ['fadeLeft', 'fadeUpOut', 'fadeRight'],
			  	name: "",
			  	text: "Daena!",
				choiceNext: false,
			},
            "31": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_smiling', null, 'Hailey/Hailey_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Daena",
			  	text: "Hi, Tyler! I know this isn't what we agreed on earlier, but I was hoping...",
				choiceNext: false,
			},
            "32": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_surprised', null, 'Hailey/Hailey_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Daena",
			  	text: "???",
				choiceNext: false,
			},
            "33": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_surprised', null, 'Hailey/Hailey_casual_surprised'],
				class: [null, null, 'fadeRight'],
			  	name: "Hailey",
			  	text: "Oh!",
				choiceNext: false,
			},
            "34": {
                bgMusic: {
					name: 'Harem_ending_argument',
					command: 'START'
				},
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_sad', null, 'Hailey/Hailey_casual_surprised'],
				class: ['fadeLeft', null, null],
			  	name: "Daena",
			  	text: "...Hoping I wasn't interrupting anything... but clearly, I am!",
				choiceNext: false,
			},
            "35": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_sad', null, 'Hailey/Hailey_casual_surprised'],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I-I mean... I wasn't...",
				choiceNext: false,
			},
            "36": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_sad', null, 'Hailey/Hailey_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: "Hailey",
			  	text: "Tyler! Why is she here?",
				choiceNext: false,
			},
            "37": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_normal', null, 'Hailey/Hailey_casual_normal'],
				class: ['fadeLeft', null, null],
			  	name: "Daena",
			  	text: "Why are you here?",
				choiceNext: false,
			},
            "38": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_normal', null, 'Hailey/Hailey_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: "Hailey",
			  	text: "We had a scheduled meeting, okay?",
				choiceNext: false,
			},
            "39": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_normal', null, 'Hailey/Hailey_casual_normal'],
                class: ['fadeLeft', null, null],
                name: "Daena",
			  	text: "Yeah? So did I!",
				choiceNext: false,
			},
            "40": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_normal', null, 'Hailey/Hailey_casual_normal'],
				class: [null, null, 'fadeRight'],
			  	name: "Hailey",
			  	text: "Oh, really? About what?",
				choiceNext: false,
			},
            "41": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_embarrassed', null, 'Hailey/Hailey_casual_normal'],
                class: ['fadeLeft', null, null],
                name: "Daena",
			  	text: "That... doesn't concern you. It was something personal I wanted to discuss with Tyler—just the two of us! But now that I've found you here in his apartment, it's clearly no longer relevant.",
				choiceNext: false,
			},
            "42": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_embarrassed', null, 'Hailey/Hailey_casual_seductive'],
				class: [null, null, 'fadeRight'],
			  	name: "Hailey",
			  	text: "Ohhh, don't tell me you were planning on confessing your feelings for him?",
				choiceNext: false,
			},
            "43": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_scared', null, 'Hailey/Hailey_casual_seductive'],
                class: ['fadeLeft', null, null],
                name: "Daena",
			  	text: "!!!",
				choiceNext: false,
			},
            "44": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_scared', null, 'Hailey/Hailey_casual_seductive'],
				class: [null, null, 'fadeRight'],
			  	name: "Hailey",
			  	text: "Haha! Looks like I hit the nail on the head.",
				choiceNext: false,
			},
            "45": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_embarrassed', null, 'Hailey/Hailey_casual_seductive'],
                class: ['fadeLeft', null, null],
                name: "Daena",
			  	text: "As I said, it's not relevant anymore.",
				choiceNext: false,
			},
            "46": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_embarrassed', null, 'Hailey/Hailey_casual_seductive'],
				class: [null, null, 'fadeRight'],
			  	name: "Hailey",
			  	text: "Why? It's not like I'm doing anything—yet. I'm just here as a guest... for now. We haven't fucked yet or anything.",
				choiceNext: false,
			},
            "47": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_scared', null, 'Hailey/Hailey_casual_seductive'],
                class: ['fadeLeft', null, null],
                name: "Daena",
			  	text: "What do you mean yet?",
				choiceNext: false,
			},
            "48": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_scared', null, 'Hailey/Hailey_casual_seductive'],
				class: [null, null, 'fadeRight'],
			  	name: "Hailey",
			  	text: "Hehe!",
				choiceNext: false,
			},
            "49": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_embarrassed', null, 'Hailey/Hailey_casual_seductive'],
                class: ['fadeLeft', null, null],
                name: "Daena",
			  	text: "Tyler! Explain why she's here?",
				choiceNext: false,
			},
            "50": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Daena/Daena_casual_embarrassed', 'Brianna/Brianna_casual_normal', 'Hailey/Hailey_casual_seductive'],
                class: [null, 'fadeUp', null],
                name: "Brianna",
			  	text: "That's exactly what we'd like to know!",
				choiceNext: false,
			},
            "51": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Daena/Daena_casual_embarrassed', 'Brianna/Brianna_casual_normal', 'Hailey/Hailey_casual_seductive'],
                class: [null, null, null],
                name: "",
			  	text: "I turn my head, and there, standing in the doorway, is Brianna... along with Reina.",
				choiceNext: false,
			},
            "52": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_normal', 'Hailey/Hailey_casual_seductive'],
                class: ['fadeLeft', null, null],
                name: "Reina",
			  	text: "And not just the two of them, but Brianna too? What is she doing here?",
				choiceNext: false,
			},
            "53": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_sad', 'Hailey/Hailey_casual_seductive'],
                class: [null, 'fadeUp', null],
                name: "Brianna",
			  	text: "I came to see Tyler... but clearly, so did everyone else. Honestly, this is a bit of a letdown.",
				choiceNext: false,
			},
            "54": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_sad', 'Hailey/Hailey_casual_surprised'],
                class: [null, null, 'fadeRight'],
                name: "Hailey",
			  	text: "Whoa, hold up—two more? Well, so much for me havin' sex today.",
				choiceNext: false,
			},
            "55": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_surprised', 'Hailey/Hailey_casual_surprised'],
                class: [null, 'fadeUp', null],
                name: "Brianna",
			  	text: "Excuse me?",
				choiceNext: false,
			},
            "56": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_surprised', 'Hailey/Hailey_casual_surprised'],
                class: ['fadeLeft', null, null],
                name: "Reina",
			  	text: "Tyler! Don't tell me you actually considered sleeping with this... Barbie doll today?!",
				choiceNext: false,
			},
            "57": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_surprised', 'Hailey/Hailey_casual_surprised'],
                class: [null, null, null],
                name: "Reina",
			  	text: "And right before our meeting! How humiliating!",
				choiceNext: false,
			},
            "58": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_surprised', 'Daena/Daena_casual_surprised'],
                class: [null, null, 'fadeRight'],
                name: "Daena",
			  	text: "Okay, I kinda get Hailey—y'know, you two are around the same age. But two moms too, Tyler? Really?",
				choiceNext: false,
			},
            "59": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_surprised', 'Daena/Daena_casual_surprised'],
                class: [null, null, null],
                name: "Daena",
			  	text: "Should I start worrying about my own mom next?",
				choiceNext: false,
			},
            "60": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_surprised', 'Daena/Daena_casual_surprised'],
                class: ['fadeLeft', null, null],
                name: "Reina",
			  	text: "And her—she's an even bigger issue! Tyler, for heaven's sake, she just turned 18! She might be legally an adult, but she's practically still a kid! Are you seriously into girls this young?!",
				choiceNext: false,
			},
            "61": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_surprised', 'Daena/Daena_casual_angry'],
                class: [null, null, 'fadeRight'],
                name: "Reina",
			  	text: "Who are you callin' a kid, huh? I'm not just legal on paper, I'm a full-on grown woman!",
				choiceNext: false,
			},
            "62": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_sad', 'Daena/Daena_casual_angry'],
                class: [null, 'fadeUp', null],
                name: "Brianna",
			  	text: "I'd have some doubts about that...",
				choiceNext: false,
			},
            "63": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_normal', 'Daena/Daena_casual_angry'],
                class: [null, 'fadeUp', null],
                name: "Brianna",
			  	text: "But you know what? Since we're all here—and hopefully, no one else is gonna show up—we're not getting anywhere by just throwing shade at each other.",
				choiceNext: false,
			},
            "64": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_normal', 'Daena/Daena_casual_angry'],
                class: [null, 'fadeUp', null],
                name: "Brianna",
			  	text: "Let's hear from Tyler, because he's been awfully quiet this whole time. Let him explain why the four of us are even here!",
				choiceNext: false,
			},
            "65": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_normal', 'Daena/Daena_casual_angry'],
                class: [null, null, null],
                name: "Tyler",
			  	text: "Well... alright...",
				choiceNext: false,
			},
            "66": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_sad', 'Brianna/Brianna_casual_normal', 'Daena/Daena_casual_angry'],
                class: ['fadeLeft', null, null],
                name: "Reina",
			  	text: "I... I have no questions and no desire to speak with this man. I was ready to set aside my marriage for him—all I had built with my husband over the years.",
				choiceNext: false,
			},
            "67": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_sad', 'Brianna/Brianna_casual_normal', 'Daena/Daena_casual_angry'],
                class: [null, null, null],
                name: "Reina",
			  	text: "It hurts so deeply that my sacrifice meant nothing to you, that while you were with me, you were stringing along others from the gym too!",
				choiceNext: false,
			},
            "68": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_sad', 'Brianna/Brianna_casual_normal', 'Daena/Daena_casual_angry'],
                class: [null, null, null],
                name: "Reina",
			  	text: "So this will be the last time I ever speak to you, Tyler, because from now on, it's over between us! I won't be looking for you, and don't you dare come looking for me—I want nothing to do with you.",
				choiceNext: false,
			},
            "69": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_sad', 'Brianna/Brianna_casual_normal', 'Hailey/Hailey_casual_smiling'],
                class: [null, null, 'fadeRight'],
                name: "Hailey",
			  	text: "Okay, bye! One less rival for me, then!",
				choiceNext: false,
			},
            "70": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_surprised', 'Brianna/Brianna_casual_normal', 'Hailey/Hailey_casual_smiling'],
                class: ['fadeLeft', null, null],
                name: "Reina",
			  	text: "What did you just say?",
				choiceNext: false,
			},
            "71": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_surprised', 'Brianna/Brianna_casual_normal', 'Hailey/Hailey_casual_smiling'],
                class: [null, null, 'fadeRight'],
                name: "Reina",
			  	text: "I said, \"One less rival.\" You're not the only one who's made sacrifices for him, y'know. I'm ready to ditch my boyfriend for Tyler too.",
				choiceNext: false,
			},
            "72": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_surprised', 'Daena/Daena_casual_normal', 'Hailey/Hailey_casual_smiling'],
                class: [null, 'fadeUp', null],
                name: "Daena",
			  	text: "Well, I've been seeing someone as well, but I've already decided Tyler's the one I really want!",
				choiceNext: false,
			},
            "73": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_surprised', 'Brianna/Brianna_casual_normal', 'Hailey/Hailey_casual_smiling'],
                class: [null, 'fadeUp', null],
                name: "Brianna",
			  	text: "I wasn't seeing anyone, but I made up my mind a long time ago that I wasn't gonna get into another relationship after all the heartbreak I've been through. But Tyler... he was the only one who made me reconsider.",
				choiceNext: false,
			},
            "74": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_surprised', 'Brianna/Brianna_casual_normal', 'Hailey/Hailey_casual_smiling'],
                class: [null, null, 'fadeRight'],
                name: "Hailey",
			  	text: "See? All of us made sacrifices for him! And if I've already set my sights on him, I'm not backing down just because everyone else is thirsting over my future man!",
				choiceNext: false,
			},
            "75": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_normal', 'Hailey/Hailey_casual_smiling'],
                class: ['fadeLeft', null, null],
                name: "Reina",
			  	text: "But this is pure deceit and betrayal! Are you seriously saying you can forgive him after knowing he's been sweet-talking all of us at the same time?!",
				choiceNext: false,
			},
            "76": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_normal', 'Hailey/Hailey_casual_smiling'],
                class: [null, null, 'fadeRight'],
                name: "Hailey",
			  	text: "I was kinda hoping things would be smoother after spilling my heart to him... but hey, I'm not scared of a little competition!",
				choiceNext: false,
			},
            "77": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_normal', 'Hailey/Hailey_casual_seductive'],
                class: [null, null, 'fadeRight'],
                name: "Hailey",
			  	text: "Honestly, none of you feel like serious threats to me, so I don't care who stays or goes. Tyler's gonna be mine no matter what!",
				choiceNext: false,
			},
            "78": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_angry', 'Hailey/Hailey_casual_seductive'],
                class: [null, 'fadeUp', null],
                name: "Brianna",
			  	text: "Oh, no way! Tyler might be the only one who's ever come close to thawing my frozen heart, so I'm not just handing him over to you!",
				choiceNext: false,
			},
            "79": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Daena/Daena_casual_angry', 'Hailey/Hailey_casual_seductive'],
                class: [null, 'fadeUp', null],
                name: "Daena",
			  	text: "I'm not backing down either, just ‘cause you're older than me! Youth has its own charm, and that's how I'm gonna win Tyler over!",
				choiceNext: false,
			},
            "80": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_sad', 'Daena/Daena_casual_angry', 'Hailey/Hailey_casual_seductive'],
                class: ['fadeLeft', null, null],
                name: "Reina",
			  	text: "...",
				choiceNext: false,
			},
            "81": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_sad', 'Daena/Daena_casual_angry', 'Hailey/Hailey_casual_smiling'],
                class: [null, null, 'fadeRight'],
                name: "Hailey",
			  	text: "So, what's it gonna be, Reina? Are you staying to fight for Tyler, or running back to your old life—the one you were apparently ready to toss aside for him?",
				choiceNext: false,
			},
            "82": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_sad', 'Daena/Daena_casual_angry', 'Hailey/Hailey_casual_smiling'],
                class: ['fadeLeft', null, null],
                name: "Reina",
			  	text: "I still don't like how we've ended up here. I thought what we had was special enough that no other girls would even cross your mind. And yet...",
				choiceNext: false,
			},
            "83": {
                bgMusic: {
					name: 'Harem_ending_argument',
					command: 'FADE_OUT',
                    insideOfScene: true
				},
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_sad', 'Daena/Daena_casual_angry', 'Hailey/Hailey_casual_smiling'],
                class: [null, null, null],
                name: "Reina",
			  	text: "You'll definitely have to take the responsibility for this in the future... But first, I need to make sure I don't lose you!",
				choiceNext: false,
			},
            "84": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_sad', 'Daena/Daena_casual_angry', 'Hailey/Hailey_casual_smiling'],
                class: [null, null, null],
                name: "Tyler",
			  	text: "Reina! Does that mean...?",
				choiceNext: false,
			},
            "85": {
                bgMusic: {
					name: 'Harem_ending_after_storm',
					command: 'START',
				},
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_normal', 'Daena/Daena_casual_angry', 'Hailey/Hailey_casual_smiling'],
                class: ['fadeLeft', null, null],
                name: "Reina",
			  	text: "Yes, I'm staying! Even though I can't explain why...",
				choiceNext: false,
			},
            "86": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_normal', 'Daena/Daena_casual_angry', 'Hailey/Hailey_casual_smiling'],
                class: [null, null, null],
                name: "Reina",
			  	text: "Out of the four of us, who are you most drawn to? Who's the one you want to stay, and who are the three you're saying goodbye to—for good?",
				choiceNext: false,
			},
            "87": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_normal', 'Brianna/Brianna_casual_normal', 'Hailey/Hailey_casual_smiling'],
                class: [null, 'fadeUp', null],
                name: "Brianna",
			  	text: "That's... a pretty brutal question.",
				choiceNext: false,
			},
            "88": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_normal', 'Brianna/Brianna_casual_normal', 'Hailey/Hailey_casual_smiling'],
                class: ['fadeLeft', null, null],
                name: "Reina",
			  	text: "But it's fair, and that's what matters! If he's been unfaithful to us, then he should face the consequences!",
				choiceNext: false,
			},
            "89": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Daena/Daena_casual_normal', 'Brianna/Brianna_casual_normal', 'Hailey/Hailey_casual_smiling'],
                class: ['fadeLeft', null, null],
                name: "Daena",
			  	text: "Wow, pot calling the kettle black much.",
				choiceNext: false,
			},
            "90": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Daena/Daena_casual_normal', 'Brianna/Brianna_casual_normal', 'Hailey/Hailey_casual_grin'],
                class: [null, null, 'fadeRight'],
                name: "Hailey",
			  	text: "Alright, fine. If you wanna play hardball, Reina, then let's do this.",
				choiceNext: false,
			},
            "91": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Daena/Daena_casual_normal', 'Brianna/Brianna_casual_normal', 'Hailey/Hailey_casual_grin'],
                class: [null, null, null],
                name: "Hailey",
			  	text: "But before you answer, Tyler, let me just... up my chances a little.",
				choiceNext: false,
			},
            "92": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Daena/Daena_casual_normal', 'Brianna/Brianna_casual_normal', 'Hailey/Hailey_casual_grin'],
                class: [null, null, null],
                name: "",
			  	text: "Hailey grabs the larger bag she brought with her.",
				choiceNext: false,
			},
            "93": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Daena/Daena_casual_normal', 'Brianna/Brianna_casual_normal', 'Hailey/Hailey_casual_grin'],
                class: [null, null, 'fadeRight'],
                name: "Hailey",
			  	text: "Can I just... run to the bathroom real quick?",
				choiceNext: false,
			},
            "94": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Daena/Daena_casual_normal', 'Brianna/Brianna_casual_normal', 'Hailey/Hailey_casual_grin'],
                class: [null, 'fadeUp', null],
                name: "Brianna",
			  	text: "What's in that bag?",
				choiceNext: false,
			},
            "95": {
                otherSoundEffect: "search-in-bag",
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Daena/Daena_casual_normal', 'Brianna/Brianna_casual_normal', 'Hailey/Hailey_casual_grin'],
                class: [null, null, null],
                name: "",
			  	text: "Brianna takes a quick peek inside Hailey's bag before she can move away.",
				choiceNext: false,
			},
            "96": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Daena/Daena_casual_normal', 'Brianna/Brianna_casual_scared', 'Hailey/Hailey_casual_grin'],
                class: [null, 'fadeUp', null],
                name: "Brianna",
			  	text: "Oh my God! What is this?",
				choiceNext: false,
			},
            "97": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Daena/Daena_casual_normal', 'Brianna/Brianna_casual_scared', 'Hailey/Hailey_casual_grin'],
                class: [null, null, null],
                name: "",
			  	text: "I can't see what's in Hailey's bag from here, but the others crowd around and take a look. They all seem completely shocked by whatever they find inside.",
				choiceNext: false,
			},
            "98": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Daena/Daena_casual_scared', 'Brianna/Brianna_casual_scared', 'Hailey/Hailey_casual_grin'],
                class: ['fadeLeft', null, null],
                name: "Daena",
			  	text: "Hailey, that would've been, like, so freaking unfair if you'd gone through with this!",
				choiceNext: false,
			},
            "99": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Daena/Daena_casual_scared', 'Brianna/Brianna_casual_scared', 'Hailey/Hailey_casual_seductive'],
                class: [null, null, 'fadeRight'],
                name: "Hailey",
			  	text: "Hehe! Well... like I said, if we're putting Tyler on the spot like this, I figured I'd give myself a little boost.",
				choiceNext: false,
			},
            "100": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Daena/Daena_casual_scared', 'Brianna/Brianna_casual_embarrassed', 'Hailey/Hailey_casual_seductive'],
                class: [null, 'fadeUp', null],
                name: "Brianna",
			  	text: "You really don't leave anything to chance, do you!",
				choiceNext: false,
			},
            "101": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_embarrassed', 'Hailey/Hailey_casual_seductive'],
                class: ['fadeLeft', null, null],
                name: "Reina",
			  	text: "This kind of explains why you thought you were better than any of us. The rest is probably just your overinflated ego.",
				choiceNext: false,
			},
            "102": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_embarrassed', 'Hailey/Hailey_casual_seductive'],
                class: [null, null, 'fadeRight'],
                name: "Hailey",
			  	text: "Nope! I've got plenty of confidence to crush you all without any help when it comes to Tyler!",
				choiceNext: false,
			},
            "103": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_angry', 'Hailey/Hailey_casual_seductive'],
                class: [null, 'fadeUp', null],
                name: "Brianna",
			  	text: "Oh yeah? Then how about you face us fair and square without that little \"helper\" of yours?",
				choiceNext: false,
			},
            "104": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_angry', 'Hailey/Hailey_casual_angry'],
                class: [null, null, 'fadeRight'],
                name: "Hailey",
			  	text: "No way! I didn't drag this thing all the way here for nothing!",
				choiceNext: false,
			},
            "105": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Daena/Daena_casual_angry', 'Hailey/Hailey_casual_angry'],
                class: [null, 'fadeUp', null],
                name: "Daena",
			  	text: "Coward!",
				choiceNext: false,
			},
            "106": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Daena/Daena_casual_angry', 'Hailey/Hailey_casual_angry'],
                class: ['fadeLeft', null, null],
                name: "Reina",
			  	text: "Fine. If this is how you wanna play it, Hailey, then let's level the playing field!",
				choiceNext: false,
			},
            "107": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Daena/Daena_casual_angry', 'Hailey/Hailey_casual_normal'],
                class: [null, null, 'fadeRight'],
                name: "Hailey",
			  	text: "What's that supposed to mean?",
				choiceNext: false,
			},
            "108": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Daena/Daena_casual_angry', 'Hailey/Hailey_casual_normal'],
                class: ['fadeLeft', null, null],
                name: "Reina",
			  	text: "Tyler! You've got a little time to think while the four of us head out and all get the same thing that Hailey's got in her bag!",
				choiceNext: false,
			},
            "109": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Daena/Daena_casual_angry', 'Hailey/Hailey_casual_angry'],
                class: [null, null, 'fadeRight'],
                name: "Hailey",
			  	text: "Why should I go? I already have one!",
				choiceNext: false,
			},
            "110": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_normal', 'Hailey/Hailey_casual_angry'],
                class: [null, 'fadeUp', null],
                name: "Brianna",
			  	text: "For the sake of fairness, Hailey! If you're really so confident about winning, what's a few extra hours compared to now?",
				choiceNext: false,
			},
            "111": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_normal', 'Hailey/Hailey_casual_sad'],
                class: [null, null, 'fadeRight'],
                name: "Hailey",
			  	text: "*sighs*",
				choiceNext: false,
			},
            "112": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_normal', 'Hailey/Hailey_casual_sad'],
                class: [null, null, null],
                name: "Hailey",
			  	text: "Ugh, fine! I'll go with you guys. I can handle this.",
				choiceNext: false,
			},
            "113": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_normal', 'Brianna/Brianna_casual_normal', 'Hailey/Hailey_casual_sad'],
                class: ['fadeLeft', null, null],
                name: "Reina",
			  	text: "Alright, Tyler! Stay here and don't go anywhere! We'll be back soon, and then there'll be no more time, no more running away. You'll have to make your final decision. Got it?",
				choiceNext: false,
			},
            "114": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_normal', 'Brianna/Brianna_casual_normal', 'Hailey/Hailey_casual_sad'],
                class: [null, null, null],
                name: "Tyler",
			  	text: "Uh... o-okay... got it.",
				choiceNext: false,
			},
            "115": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_normal', 'Brianna/Brianna_casual_normal', 'Hailey/Hailey_casual_sad'],
                class: ['fadeLeft', null, null],
                name: "Reina",
			  	text: "Good!",
				choiceNext: false,
			},
            "116": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_normal', 'Brianna/Brianna_casual_normal', 'Hailey/Hailey_casual_sad'],
                class: [null, 'fadeUp', null],
                name: "Brianna",
			  	text: "Alright, Hailey. Since you already have one, show us where you bought it.",
				choiceNext: false,
			},
            "117": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_normal', 'Brianna/Brianna_casual_normal', 'Hailey/Hailey_casual_sad'],
                class: [null, null, 'fadeRight'],
                name: "Hailey",
			  	text: "Ugh, fine... what a drag!",
				choiceNext: false,
			},
            "118": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_normal', 'Brianna/Brianna_casual_normal', 'Hailey/Hailey_casual_sad'],
                class: ['fadeLeftOut', 'fadeUpOut', 'fadeRightOut'],
                name: "",
			  	text: "And with that, the girls leave my apartment.",
				choiceNext: false,
			},
            "119": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
                class: [null, null, null],
                name: "",
			  	text: "I barely had a say in what just happened. I didn't even get a chance to explain myself. They seemed to work everything out among themselves.",
				choiceNext: false,
			},
            "120": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
                class: [null, null, null],
                name: "",
			  	text: "I still have no clue what was in Hailey's bag that caused such a stir or why they're all so determined to go get the same thing for the sake of \"fairness\".",
				choiceNext: false,
			},
            "121": {
                bgMusic: {
					name: 'Harem_ending_after_storm',
					command: 'FADE_OUT',
				},
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
                class: [null, null, null],
                name: "",
			  	text: "I'm completely in the dark about what's going to happen when they get back. All I know is I have a few hours to think things over before I'm forced to make the ultimate decision.",
				choiceNext: false,
                timeSkipNext: {
					content: "A few hours later...",
					nextSceneType: "STORY",
					nextSceneNumber: "",
                    isInEnding: true
				}
			},
        },
    },
];