export const harem_2 = [
    {
        sceneId: "",
        lengthNum: 64,
        story: {
            "1": {
                bgMusic: {
					name: 'Harem_ending_before_climax',
					command: 'START'
				},
                background: "backgrounds/BG_Tyler_bedroom_sunny",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "",
                text: "The few hours have passed. The girls are back, each carrying a shopping bag, but none of them have revealed what's inside.",
                choiceNext: false,
            },
            "2": {
                background: "backgrounds/BG_Tyler_bedroom_sunny",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "",
                text: "They sent me to my bedroom, claiming they needed the living room to prepare since the bathroom was way too cramped for all four of them.",
                choiceNext: false,
            },
            "3": {
                background: "backgrounds/BG_Tyler_bedroom_sunny",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "",
                text: "I've been lying on my bed ever since, just waiting for something to happen.",
                choiceNext: false,
            },
            "4": {
                background: "backgrounds/BG_Tyler_bedroom_sunny",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "",
                text: "I tried to spend the last few hours thinking things over—deciding who I'd pick if I had to—but it's no easy task. Honestly, I didn't even come to a conclusion. So, if they put me under pressure, I'll probably only make a decision at the last possible second.",
                choiceNext: false,
            },
            "5": {
                background: "backgrounds/BG_Tyler_bedroom_sunny",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "",
                text: "Choosing... between four amazing women? It's like living in a harem, where I get to pick freely, like some kind of king.",
                choiceNext: false,
            },
            "6": {
                background: "backgrounds/BG_Tyler_bedroom_sunny",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "",
                text: "But that's obviously not the case. They all know about each other, and whoever I choose, there are definitely going to be some serious consequences.",
                choiceNext: false,
            },
            "7": {
                otherSoundEffect: "knock-on-door",
                background: "backgrounds/BG_Tyler_bedroom_sunny",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "",
                text: "*Knock-knock*",
                choiceNext: false,
            },
            "8": {
                background: "backgrounds/BG_Tyler_bedroom_sunny",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Hailey",
                text: "Yo, Tyler! We're ready! And now... we're coming in!",
                choiceNext: false,
            },
            "9": {
                background: "backgrounds/BG_Tyler_bedroom_sunny",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Tyler",
                text: "Uh... okay!",
                choiceNext: false,
            },
            "10": {
                background: "backgrounds/BG_Tyler_bedroom_sunny",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "",
                text: "The moment of truth. Now I'll finally find out what the girls have been up to and why they thought Hailey had such an unfair advantage.",
                choiceNext: false,
            },
            "11": {
                bgMusic: {
					name: 'Harem_ending_before_climax',
					command: 'FADE_OUT',
                    insideOfScene: true
				},
                otherSoundEffect: "door_noise",
                background: "backgrounds/BG_Tyler_bedroom_sunny",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "",
                text: "The door to my room opens, and as they walk in...",
                choiceNext: false,
            },
            "12": {
                bgMusic: {
					name: 'Harem_ecchi',
					command: 'START',
				},
                specialSceneNow: true,
				specialSceneId: "harem_ending_1",
				background: "special_scenes/harem_ending_1",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "",
                text: "... I'm greeted by an absolutely jaw-dropping, sexy sight!",
                choiceNext: false,
            },
            "13": {
				background: "special_scenes/harem_ending_1",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Tyler",
                text: "Oh my... God!",
                choiceNext: false,
            },
            "14": {
				background: "special_scenes/harem_ending_1",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Hailey",
                text: "Well? Whaddaya think of our cute-as-heck matching fits?",
                choiceNext: false,
            },
            "15": {
				background: "special_scenes/harem_ending_1",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Tyler",
                text: "I... I... I... I don't even know what to say!",
                choiceNext: false,
			},
			"16": {
				background: "special_scenes/harem_ending_1",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Tyler",
                text: "Calling it \"cute-as-heck\" doesn't even cover it—yeah, it's adorable, but you all look drop-dead smoking hot in those outfits too!",
                choiceNext: false,
			},
			"17": {
                background: "special_scenes/harem_ending_1",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Brianna",
                text: "Hmm... then it was definitely the right move not to let Hailey prance around in this by herself.",
                choiceNext: false,
			},
			"18": {
                background: "special_scenes/harem_ending_1",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Daena",
                text: "Yeah, I never in my life thought I'd ever wear something like this, but now that I see the effect it's having on you? Oh, I'm totally buying more stuff like this.",
                choiceNext: false,
			},
			"19": {
                background: "special_scenes/harem_ending_1",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Hailey",
                text: "Pfft! Says the one who looks like she raided the teen aisle! This outfit's totally more in your age bracket, Dae.",
                choiceNext: false,
			},
			"20": {
                background: "special_scenes/harem_ending_1",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Hailey",
                text: "Oh, that's coming from the girl who already had hers stashed away in her bag from the start!",
                choiceNext: false,
			},
			"21": {
                background: "special_scenes/harem_ending_1",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Tyler",
                text: "Wait a second! Where's Reina?",
                choiceNext: false,
			},
			"22": {
                background: "special_scenes/harem_ending_1",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Hailey",
                text: "Aww... still thinking about her, even now? I was kinda hoping this would've made you forget all about her by now.",
                choiceNext: false,
			},
			"23": {
                background: "special_scenes/harem_ending_1",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Brianna",
                text: "She's still in the living room... just... kind of freaking out a little.",
                choiceNext: false,
			},
			"24": {
                background: "special_scenes/harem_ending_1",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Tyler",
                text: "Freaking out? What do you mean?",
                choiceNext: false,
			},
			"25": {
                background: "special_scenes/harem_ending_1",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Reina",
                text: "I mean, I don't think this whole thing is really my vibe!",
                choiceNext: false,
			},
            "26": {
                background: "special_scenes/harem_ending_1",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Hailey",
                text: "Well, guess that's one less rival for me!",
                choiceNext: false,
			},
            "27": {
                background: "special_scenes/harem_ending_1",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Tyler",
                text: "Reina! Please, I want to see you! Not because of the whole \"fairness\" thing or whatever, but because... because I know no matter what you wear, you always look absolutely stunning. And something in my gut is telling me... I need to see this!",
                choiceNext: false,
			},
            "28": {
                background: "special_scenes/harem_ending_1",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Reina",
                text: "...",
                choiceNext: false,
			},
            "29": {
                otherSoundEffect: "footsteps",
                background: "special_scenes/harem_ending_1",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "",
                text: "Eventually, she starts heading toward my room, looking shy as heck. But finally, she steps inside.",
                choiceNext: false,
			},
            "30": {
                specialSceneNow: true,
				specialSceneId: 'harem_ending_2',
                background: "special_scenes/harem_ending_2",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "",
                text: "And WOW. The sight is just... absolutely killer!",
                choiceNext: false,
			},
            "31": {
                background: "special_scenes/harem_ending_2",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "",
                text: "It's so much sexier than I ever imagined, even after seeing the others' outfits. I don't know... maybe it's the contrast—this kind of girly, cutesy teen outfit on a grown, confident woman. That contrast alone is off-the-charts alluring.",
                choiceNext: false,
			},
            "32": {
                background: "special_scenes/harem_ending_2",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Reina",
                text: "I... I don't look totally ridiculous, do I?",
                choiceNext: false,
			},
            "33": {
                background: "special_scenes/harem_ending_2",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Tyler",
                text: "Ridiculous? No way, Reina! I never in my life thought I'd see anything like this. In an instant, it's like you've checked off every dream I've ever had!",
                choiceNext: false,
			},
            "34": {
                background: "special_scenes/harem_ending_2",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Reina",
                text: "Really? Huh... that's new for me. I never would've guessed a silly outfit like this could get that reaction from you. But if you love it, then I'm keeping it—and I'll take the time to figure out more of your taste so I can keep you hooked!",
                choiceNext: false,
			},
            "35": {
                background: "special_scenes/harem_ending_2",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Tyler",
                text: "That... that sounds incredible.",
                choiceNext: false,
			},
            "36": {
                background: "special_scenes/harem_ending_2",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Hailey",
                text: "Ahem!",
                choiceNext: false,
			},
            "37": {
                background: "special_scenes/harem_ending_2",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Hailey",
                text: "Okay, Tyler, looks like I might've underestimated Reina. If I can't win you over visually, guess I'll just have to step up my game!",
                choiceNext: false,
			},
            "38": {
                background: "special_scenes/harem_ending_2",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "",
                text: "Hailey strides right up to me, then drops down onto her knees, sitting back on her heels.",
                choiceNext: false,
			},
            "39": {
                specialSceneNow: true,
				specialSceneId: 'harem_ending_3',
                background: "special_scenes/harem_ending_3",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Tyler",
                text: "Whoa, Hailey! What are you doing?",
                choiceNext: false,
			},
            "40": {
                background: "special_scenes/harem_ending_3",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Hailey",
                text: "Hehe! Just sit back, babe, and let me show you what VIP treatment feels like!",
                choiceNext: false,
			},
            "41": {
                background: "special_scenes/harem_ending_3",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Daena",
                text: "Oh, hell no! You're not pulling this sneaky little move while I'm standing here. No way I'm letting you snag the upper hand like that!",
                choiceNext: false,
			},
            "42": {
                background: "special_scenes/harem_ending_3",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Hailey",
                text: "Oh yeah? And what are you gonna do to stop me, huh, Dae?",
                choiceNext: false,
			},
            "43": {
                background: "special_scenes/harem_ending_3",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Daena",
                text: "Nothing. I'm not stopping you. If you're doing it, then I'm doing it too!",
                choiceNext: false,
			},
            "44": {
                background: "special_scenes/harem_ending_3",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Hailey",
                text: "What, both of us? You think you can keep up with me, rookie?",
                choiceNext: false,
			},
            "45": {
                background: "special_scenes/harem_ending_3",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Brianna",
                text: "If she can't, then I definitely will!",
                choiceNext: false,
			},
            "46": {
                background: "special_scenes/harem_ending_3",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Hailey",
                text: "Wait, now you're in this too?!",
                choiceNext: false,
			},
            "47": {
                background: "special_scenes/harem_ending_3",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Brianna",
                text: "Yup. I'm a little older, and a little wiser... So if you're stepping into the ring with me, you'd better bring your A-game, Hailey!",
                choiceNext: false,
			},
            "48": {
                background: "special_scenes/harem_ending_3",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "",
                textClass: "italic",
                text: "Oh, sweet mother of mercy! If these three team up on me all at once, I'm done for!",
                choiceNext: false,
			},
            "49": {
                background: "special_scenes/harem_ending_3",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "",
                textClass: "italic",
                text: "Maybe... maybe Reina will step in and save me from this chaos.",
                choiceNext: false,
			},
            "50": {
                background: "special_scenes/harem_ending_3",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Tyler",
                text: "Reina! I need backup here!",
                choiceNext: false,
			},
            "51": {
                background: "special_scenes/harem_ending_3",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "",
                text: "But instead of swooping in to rescue me and staking her claim...",
                choiceNext: false,
			},
            "52": {
                specialSceneNow: true,
				specialSceneId: 'harem_ending_4',
                background: "special_scenes/harem_ending_4",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "",
                text: "...she climbs right into bed with me.",
                choiceNext: false,
			},
            "53": {
                background: "special_scenes/harem_ending_4",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Tyler",
                text: "Reina?",
                choiceNext: false,
			},
            "54": {
                background: "special_scenes/harem_ending_4",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Reina",
                text: "If I'm going to win, I want to do it by proving I'm better than the rest, not just by beating them down. Victory tastes sweeter when everyone's giving their all!",
                choiceNext: false,
			},
            "55": {
                background: "special_scenes/harem_ending_4",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Tyler",
                text: "Oh. My. God. I'm doomed!",
                choiceNext: false,
			},
            "56": {
                background: "special_scenes/harem_ending_4",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Reina",
                text: "Hehe! You brought this on yourself, Casanova, stringing four of us along at the same time.",
                choiceNext: false,
			},
            "57": {
                background: "special_scenes/harem_ending_4",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Reina",
                text: "If you're gonna play the part of a player, you'd better have the stamina to match. Four women means four times the energy... because I swear, I won't stop until I'm so satisfied I don't even remember what planet I'm on!",
                choiceNext: false,
			},
            "58": {
                background: "special_scenes/harem_ending_4",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Reina",
                text: "Only... and only then will I forgive you. And maybe... just maybe... give you a shot at making things right!",
                choiceNext: false,
			},
            "59": {
                background: "special_scenes/harem_ending_4",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "Reina",
                text: "So pull it together, Tyler! I won't go easy on you. None of us will!",
                choiceNext: false,
			},
            "60": {
                background: "special_scenes/harem_ending_4",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "",
                text: "Never in my wildest dreams did I think I'd end up like this. Four gorgeous women. In my room. All at once!",
                choiceNext: false,
			},
            "61": {
                background: "special_scenes/harem_ending_4",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "",
                text: "It's the kind of scenario that sounds like pure fantasy. A harem situation come to life. At first, of course, it may seem tempting, but when it really happens and you start to feel the weight of it...",
                choiceNext: false,
			},
            "62": {
                background: "special_scenes/harem_ending_4",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "",
                text: "I can only pray I don't crumble under the pressure!",
                choiceNext: false,
			},
            "63": {
                background: "special_scenes/harem_ending_4",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "",
                text: "The girls start moving in sync. Everyone starts pampering me in their own way and in my chosen area. Excitement quickly reaches a high level in me, it's all too good to be true!",
                choiceNext: false,
			},
            "64": {
                bgMusic: {
					name: 'Harem_ecchi',
					command: 'FADE_OUT',
				},
                background: "special_scenes/harem_ending_4",
                charContainer: [null, null, null],
                image: [null, null, null],
                class: [null, null, null],
                name: "",
                text: "And then, in the next moment...",
                choiceNext: false,
			}
        },
    },
];