export const lindsay_bad_2 = [
	{ sceneId: "0000" },
	{ sceneId: "0001" },
	{ sceneId: "0002" },
	{ sceneId: "0003" },
	{ sceneId: "0004" },
	{ sceneId: "0005" },
	{ sceneId: "0006" },
	{ sceneId: "0007" },
	{ sceneId: "0008" },
	{ sceneId: "0009" },
	{ sceneId: "0010" },
	{ sceneId: "0011" },
	{ sceneId: "0012" },
	{ sceneId: "0013" },
	{ sceneId: "0014" },
	{ sceneId: "0015" },
	{ sceneId: "0016" },
	{ sceneId: "0017" },
	{ sceneId: "0018" },
	{ sceneId: "0019" },
	{ sceneId: "0020" },
	{ sceneId: "0021" },
	{ sceneId: "0022" },
	{ sceneId: "0023" },
	{ sceneId: "0024" },
	{ sceneId: "0025" },
	{ sceneId: "0026" },
	{ sceneId: "0027" },
	{ sceneId: "0028" },
	{ sceneId: "0029" },
	{ sceneId: "0030" },
	{
		sceneId: "0031",
		lengthNum: 59,
		story: {
			"1": {
				bgMusic: {
					name: 'Lindsay_bad_ending_start',
					command: 'START'
				},
                background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Morning has arrived. I'm not sure what I expected from Lindsay, but I'm relieved I didn't end up doing anything I'd regret.",
				choiceNext: false,
            },
			"2": {
                background: "backgrounds/BG_Tyler_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I spent the evening alone; no one messaged me that night, no one else wanted to meet up, so everything was quiet and peaceful.",
				choiceNext: false,
			},
			"3": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Shortly after I got out of bed, I checked my phone to see if anything happened while I was asleep, and sure enough, it had!",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I had several notifications that I'd been tagged in a post, with multiple reactions—none of them particularly positive.",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				name: "",
			  	text: "I immediately opened the post and, to my horror, saw that Lindsay had written something about me.",
				choiceNext: false,
			},
			"6": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				name: "Lindsay",
				textClass: "italic",
			  	text: "\"Dear community! I'd like to bring to everyone's attention that @Tyler Auburn is a deceitful man who doesn't care about the relationship status of other women!\"",
				choiceNext: false,
			},
			"7": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				name: "Lindsay",
				textClass: "italic",
			  	text: "\"He went out to dinner with me while knowing full well that I'm married, and I found out from him that there's someone from the gym where he works with whom he has a more intimate connection than with all the others.\"",
				choiceNext: false,
            },
			"8": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				name: "Lindsay",
				textClass: "italic",
			  	text: "\"Dear Lucky one, I hope you see this post, recognize yourself in it, and realize how @Tyler Auburn betrayed you, because this man respects neither monogamy, marriage, nor anything else.\"",
				choiceNext: false,
			},
			"9": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				name: "",
				textClass: "italic",
			  	text: "Alright... this is yet another clever attempt by Lindsay to make things difficult for me. She exaggerated in several respects, but it's true that this could easily smoke Reina out. So, I just hope Reina stays calm and doesn't give herself away, realizing that this post is mainly targeted at her.",
				choiceNext: false,
			},
			"10": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				name: "",
			  	text: "Though Lindsay has put me in quite an uncomfortable situation, I tried to keep my cool. There's no point in messaging her and demanding what she was thinking, as it would take her just one click to block me. In fact, I'd bet she's already done it.",
				choiceNext: false,
			},
			"11": {
				bgMusic: {
					name: 'Lindsay_bad_ending_start',
					command: 'STOP'
				},
				otherSoundEffect: "knock-on-door",
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				name: "",
			  	text: "Shortly after that, there's a knock on my door, and it's Hailey standing in the doorway.",
				choiceNext: false,
			},
			"12": {
				bgMusic: {
					name: 'Worst_ending',
					command: 'START'
				},
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				name: "",
			  	text: "Hailey? What are you doing here?",
				choiceNext: false,
			},
			"13": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, "fadeUp", null],
				name: "Hailey",
			  	text: "Tyler! What... what is all this? I really hoped this was just some kind of prank! Who is this Lindsay? Please, tell me it's not true!",
				choiceNext: false,
			},
			"14": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
				name: "Tyler",
			  	text: "I can explain.",
				choiceNext: false,
			},
			"15": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, "fadeUp", null],
				name: "Hailey",
			  	text: "Okay, I'm waiting for your explanation!",
				choiceNext: false,
			},
			"16": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Hailey/Hailey_casual_normal', null],
				class: [null, null, null],
				name: "Tyler",
			  	text: "Well... it's just that...",
				choiceNext: false,
			},
			"17": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_normal', 'Hailey/Hailey_casual_normal', 'Daena/Daena_casual_surprised'],
				class: ['fadeLeft', "fadeUpOut", 'fadeRight'],
				name: "Daena",
			  	text: "Tyler! Hailey? What are you doing here?",
				choiceNext: false,
			},
			"18": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_normal', null, 'Daena/Daena_casual_surprised'],
				class: ['fadeLeft', null, null],
				name: "Hailey",
			  	text: "What are YOU doing here? I'm here because of that post where Tyler...",
				choiceNext: false,
			},
			"19": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_surprised', null, 'Daena/Daena_casual_surprised'],
				class: ['fadeLeft', null, null],
				name: "Hailey",
			  	text: "No way! Don't tell me you're here for the same reason!",
				choiceNext: false,
			},
			"20": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_surprised', null, 'Daena/Daena_casual_normal'],
				class: [null, null, 'fadeRight'],
				name: "Daena",
			  	text: "Oh, I am.",
				choiceNext: false,
			},
			"21": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_surprised', null, 'Daena/Daena_casual_normal'],
				class: ['fadeLeft', null, null],
				name: "Hailey",
			  	text: "Tyler! So, which one of us was that message really meant for?",
				choiceNext: false,
			},
			"22": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_surprised', null, 'Daena/Daena_casual_sad'],
				class: [null, null, 'fadeRight'],
				name: "Daena",
			  	text: "And since we're both here because of it, how could you do this to me? I trusted you! I put my heart and soul into those workouts, and I tried to show you a kind of devotion I'd never show anyone else! And this is how you repay me—stringing others along, not just me?",
				choiceNext: false,
			},
            "23": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Hailey/Hailey_casual_sad', null, 'Daena/Daena_casual_sad'],
				class: ['fadeLeft', null, null],
				name: "Hailey",
			  	text: "I could say the same... I was ready to leave my boyfriend for you, let you get so close to me without shame, showed you sides of me no one else gets to see. And now I feel utterly humiliated that I let myself be fooled by the words of such a deceitful guy!",
				choiceNext: false,
			},
			"24": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_sad', 'Brianna/Brianna_casual_surprised', 'Daena/Daena_casual_sad'],
				class: [null, 'fadeUp', null],
				name: "Brianna",
			  	text: "Wait... what? Why are there so many of us here?",
				choiceNext: false,
			},
			"25": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_surprised', 'Brianna/Brianna_casual_surprised', 'Daena/Daena_casual_sad'],
				class: ['fadeLeft', null, null],
				name: "Hailey",
			  	text: "Brianna?",
				choiceNext: false,
            },
			"26": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_surprised', 'Brianna/Brianna_casual_surprised', 'Daena/Daena_casual_surprised'],
				class: [null, null, 'fadeRight'],
				name: "Daena",
			  	text: "Her too?",
				choiceNext: false,
            },
			"27": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_surprised', 'Brianna/Brianna_casual_normal', 'Daena/Daena_casual_surprised'],
				class: [null, 'fadeUp', null],
				name: "Brianna",
			  	text: "Uh-huh... two familiar faces from the gym... would someone be kind enough to explain why you're here?",
				choiceNext: false,
			},
			"28": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_normal', 'Brianna/Brianna_casual_normal', 'Daena/Daena_casual_surprised'],
				class: ['fadeLeft', null, null],
				name: "Hailey",
			  	text: "I think for the exact same reason as you.",
				choiceNext: false,
			},
			"29": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_normal', 'Brianna/Brianna_casual_sad', 'Daena/Daena_casual_surprised'],
				class: [null, 'fadeUp', null],
				name: "Brianna",
			  	text: "Really? Tyler... I can't even begin to express how deeply disappointed I am in you right now. After so long, finally someone makes my heart beat again, finally someone I'm willing to give another chance to, after so many heartbreaks... and here we are, the same old ending—a fresh heartbreak.",
				choiceNext: false,
			},
			"30": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_normal', 'Brianna/Brianna_casual_sad', 'Daena/Daena_casual_surprised'],
				class: [null, null, null],
				name: "Brianna",
			  	text: "My heart is breaking.",
				choiceNext: false,
			},
			"31": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_normal', 'Brianna/Brianna_casual_sad', 'Daena/Daena_casual_normal'],
				class: [null, null, 'fadeRight'],
				name: "Daena",
			  	text: "So... is this how it is? We're the three you led around by the nose?",
				choiceNext: false,
			},
			"32": {
				bgMusic: {
					name: 'Worst_ending',
					command: 'FADE_OUT',
					insideOfScene: true
				},
				otherSoundEffect: 'walking-up-the-stairs',
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_normal', 'Brianna/Brianna_casual_sad', 'Daena/Daena_casual_normal'],
				class: [null, null, null],
				name: "",
			  	text: "*Footsteps*",
				choiceNext: false,
			},
			"33": {
				otherSoundEffect: 'walking-up-the-stairs',
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Hailey/Hailey_casual_normal', 'Brianna/Brianna_casual_sad', 'Daena/Daena_casual_normal'],
				class: [null, null, null],
				name: "",
				textClass: "italic",
			  	text: "Oh no... Based on elimination, I think I know who's coming... this is really going to hurt.",
				choiceNext: false,
			},
			"34": {
				otherSoundEffect: 'walking-up-the-stairs',
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_surprised', 'Brianna/Brianna_casual_sad', 'Daena/Daena_casual_normal'],
				class: ["fadeLeft", null, null],
				name: "Reina",
			  	text: "!!!",
				choiceNext: false,
			},
			"35": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_surprised', 'Brianna/Brianna_casual_surprised', 'Daena/Daena_casual_normal'],
				class: [null, "fadeUp", null],
				name: "Brianna",
			  	text: "Reina?",
				choiceNext: false,
			},
			"36": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_surprised', 'Brianna/Brianna_casual_surprised', 'Daena/Daena_casual_surprised'],
				class: [null, null, "fadeRight"],
				name: "Daena",
			  	text: "Her too?",
				choiceNext: false,
			},
			"37": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_surprised', 'Brianna/Brianna_casual_surprised', 'Hailey/Hailey_casual_surprised'],
				class: [null, null, "fadeRight"],
				name: "Hailey",
			  	text: "Well, well!",
				choiceNext: false,
			},
			"38": {
				bgMusic: {
					name: 'Under_pressure',
					command: 'START'
				},
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_surprised', 'Hailey/Hailey_casual_surprised'],
				class: ['fadeLeft', null, null],
				name: "Reina",
			  	text: "Tyler...",
				choiceNext: false,
			},
			"39": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_surprised', 'Hailey/Hailey_casual_surprised'],
				class: [null, null, null],
				name: "Reina",
			  	text: "You... sneaky... lowlife!",
				choiceNext: false,
			},
			"40": {
                background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_surprised', 'Hailey/Hailey_casual_normal'],
				class: [null, null, 'fadeRight'],
				name: "Hailey",
			  	text: "Whoa, whoa, whoa! Hold on, let's keep it non-violent!",
				choiceNext: false,
			},
			"41": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_surprised', 'Hailey/Hailey_casual_normal'],
				class: [null, null, null],
				name: "Hailey",
			  	text: "Let's try to calmly ask Tyler why the four of us are even here.",
				choiceNext: false,
			},
			"42": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_surprised', 'Hailey/Hailey_casual_normal'],
				class: [null, null, null],
				name: "",
				textClass: "italic",
			  	text: "Reina is very quiet and seems heartbroken.",
				choiceNext: false,
			},
			"43": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_surprised', 'Hailey/Hailey_casual_normal'],
				class: ['fadeLeft', null, null],
				name: "Reina",
			  	text: "I... I have no questions and no desire to speak with this man. I was ready to set aside my marriage for him—all I had built with my husband over the years.",
				choiceNext: false,
			},
			"44": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_surprised', 'Hailey/Hailey_casual_normal'],
				class: [null, null, null],
				name: "Reina",
			  	text: "It hurts so deeply that my sacrifice meant nothing to you, that while you were with me, you were stringing along others from the gym too!",
				choiceNext: false,
			},
			"45": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_surprised', 'Hailey/Hailey_casual_normal'],
				class: [null, null, null],
				name: "Reina",
			  	text: "So this will be the last time I ever speak to you, Tyler, because from now on, it's over between us! I won't be looking for you, and don't you dare come looking for me—I want nothing to do with you.",
				choiceNext: false,
			},
			"46": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_surprised', 'Hailey/Hailey_casual_normal'],
				class: [null, null, null],
				name: "Reina",
			  	text: "Forget about me... forever!",
				choiceNext: false,
			},
			"47": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', 'char-middle', 'char-right'],
				image: ['Reina/Reina_casual_angry', 'Brianna/Brianna_casual_surprised', 'Hailey/Hailey_casual_normal'],
				class: ["fadeLeftOut", null, null],
				name: "",
			  	text: "With that, Reina leaves my apartment, not even giving me a chance to say anything. Though honestly, what could I even say?",
				choiceNext: false,
			},
			"48": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', 'char-right'],
				image: [null, 'Brianna/Brianna_casual_sad', 'Hailey/Hailey_casual_normal'],
				class: [null, 'fadeUp', null],
				name: "Brianna",
			  	text: "...",
				choiceNext: false,
			},
			"49": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', 'char-right'],
				image: [null, 'Brianna/Brianna_casual_sad', 'Hailey/Hailey_casual_normal'],
				class: [null, null, null],
				name: "Brianna",
			  	text: "She's right, actually. We could yell at Tyler, slap him, or even trash his apartment... but that won't solve anything. What's done is done, and now I don't want anything from him either.",
				choiceNext: false,
			},
			"50": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', 'char-right'],
				image: [null, 'Brianna/Brianna_casual_sad', 'Hailey/Hailey_casual_normal'],
				class: [null, null, null],
				name: "Brianna",
			  	text: "I'll survive somehow. But the fact is, he doesn't deserve my attention, my energy, my patience... or my love.",
				choiceNext: false,
			},
			"51": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, 'char-middle', 'char-right'],
				image: [null, 'Brianna/Brianna_casual_sad', 'Hailey/Hailey_casual_normal'],
				class: [null, "fadeUpOut", null],
				name: "",
			  	text: "Brianna leaves too, and it really seems like the others feel the same way.",
				choiceNext: false,
			},
			"52": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, 'char-right'],
				image: [null, null, 'Hailey/Hailey_casual_sad'],
				class: [null, null, 'fadeRight'],
				name: "Hailey",
			  	text: "It was fun while it lasted... too bad I believed you when you said I could be \"the one.\"",
				choiceNext: false,
			},
			"53": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_sad', null, 'Hailey/Hailey_casual_sad'],
				class: ['fadeLeft', null, null],
				name: "Daena",
			  	text: "This was a hard lesson on growing up and understanding men. But somehow, I'll recover from this blow, too.",
				choiceNext: false,
			},
			"54": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: ['char-left', null, 'char-right'],
				image: ['Daena/Daena_casual_sad', null, 'Hailey/Hailey_casual_sad'],
				class: ['fadeLeftOut', null, 'fadeRightOut'],
				name: "",
			  	text: "With that, everyone left the apartment, and I was left alone.",
				choiceNext: false,
			},
			"55": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				name: "",
				textClass: "italic",
			  	text: "I don't even know if I should feel sorry for not getting a chance to explain myself, because, honestly, what could I have said?",
				choiceNext: false,
			},
			"56": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				name: "",
			  	text: "I had a chance to be happy with one of them, but with one bad decision, everything crumbled before my eyes in an instant.",
				choiceNext: false,
			},
			"57": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				name: "",
			  	text: "I wish I could go back in time, do things differently, and avoid living through this terrible situation.",
				choiceNext: false,
			},
			"58": {
				background: "backgrounds/BG_Tyler_livingroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				name: "",
			  	text: "But that's not how it works. Or... could it be?",
				choiceNext: false,
			},
			"59": {
				bgMusic: {
					name: 'Under_pressure',
					command: 'FADE_OUT',
				},
				background: "backgrounds/BG_dark",
				backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
				name: "",
			  	text: "Suddenly, everything around me goes dark, and in the next moment...",
				choiceNext: false,
			},
		},
	},
];