export const brianna_bad = [
	{
		sceneId: "",
		lengthNum: 38,
		endingSceneType: '',
		story: {
			"1": {
				bgMusic: {
					name: 'Date_with_Brianna',
					command: 'START'
				},
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "It's time to see Brianna. Yesterday she mentioned wanting to get out a bit, just the two of us.",
				choiceNext: false,
            },
 			"2": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I don't think this is a bad sign. Going for a walk together... If she wanted to brush me off, she could have done it somewhere close by, or even worse, over the phone. But if she just wants to walk and chat, I'm taking that as a good sign and staying positive.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_Brianna_house_sunny",
				backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "When I arrive at her house, I message her to let her know I'm here, and she comes out. We start off on a little walk around the area.",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_outskirt_park_sunny",
				backGroundClass: "fadeIn",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "So, how are you, Tyler?",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Honestly, I have to admit, I'm a little nervous.",
				choiceNext: false,
			},
			"6": {
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "Why's that?",
				choiceNext: false,
			},
			"7": {
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Because, in my experience, whenever a woman asks me to meet up for a \"talk\", it's usually something serious. Sadly, it doesn't usually mean good news... but I'm hoping that's not the case today.",
				choiceNext: false,
            },
			"8": {
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "Have most of your relationships ended with the other person breaking up with you?",
				choiceNext: false,
			},
			"9": {
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I wouldn't even say I've had that many relationships. But yeah, the ones I've had mostly ended that way. I've always tried to hold on until the very end, doing my best. I just never wanted to break anyone's heart by saying goodbye myself.",
				choiceNext: false,
			},
			"10": {
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "And why do you think you haven't had many relationships? And the ones you had—why do you think they always ended like that?",
				choiceNext: false,
			},
			"11": {
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "If I knew the answer to that, I probably would've had more relationships. Or if not more, at least longer ones. In the best case, I'd be in a relationship now.",
				choiceNext: false,
			},
			"12": {
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "Yeah, that's fair. Honestly, if I had all the answers to questions like that myself, I probably wouldn't have raised my daughters on my own. I've got things to learn too.",
				choiceNext: false,
			},
			"13": {
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "So, does this walk... I mean, was your idea for today to help each other learn and grow together?",
				choiceNext: false,
			},
			"14": {
				bgMusic: {
					name: 'Date_with_Brianna',
					command: 'STOP'
				},
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "Yes. That's what I'd like, it'd be the best outcome...",
				choiceNext: false,
			},
			"15": {
				bgMusic: {
					name: 'Bad_ending_with_main_girls',
					command: 'START'
				},
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_sad', null],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "But I don't think it's worth the energy.",
				choiceNext: false,
			},
			"16": {
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_sad', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Wait... did I hear you right?",
				choiceNext: false,
			},
			"17": {
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_sad', null],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "Yes... yes, I'm really sorry, believe me.",
				choiceNext: false,
			},
			"18": {
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_sad', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "But... why? You're the one who brought up the idea of giving this a chance after all the letdowns. So, what changed so suddenly?",
				choiceNext: false,
			},
			"19": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_sad', null],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "It's a bit surprising to me too, why I said what I did, and did what I did... and now why I feel the way I do about us.",
				choiceNext: false,
			},
			"20": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_sad', null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "The best explanation I have is that... I think I just wanted to be in love, more than I actually wanted to be in love with you.",
				choiceNext: false,
			},
			"21": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_sad', null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "You definitely sparked something in me because no one else has even managed that much. But unfortunately, all you really awakened in me was a desire to be loved. But... you didn't quite break through into my heart. It's more like the feeling itself that I'm missing.",
				choiceNext: false,
			},
			"22": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_sad', null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "I'm sorry.",
				choiceNext: false,
			},
            "23": {
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_sad', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "This is... well, this is really awkward... and kind of frustrating... and honestly, a bit infuriating.",
				choiceNext: false,
			},
			"24": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_sad', null],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "I know, I totally understand, and you have every reason to be mad at me.",
				choiceNext: false,
			},
			"25": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_sad', null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "I feel like I might have strung you along a bit. But please believe me, I didn't want to play with your feelings. At the same time, I didn't want to say yes now and then turn around in a few years and tell you that something's missing.",
				choiceNext: false,
            },
			"26": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_sad', null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "It's better we go our separate ways than waste each other's time in a relationship without real feelings.",
				choiceNext: false,
            },
			"27": {
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_sad', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Yeah, I get it, that's logical, but... I just can't believe this is happening to me!",
				choiceNext: false,
			},
			"28": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_sad', null],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "I really am so sorry. Even if I know it doesn't help.",
				choiceNext: false,
			},
			"29": {
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_sad', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Unfortunately, it doesn't.",
				choiceNext: false,
			},
			"30": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_sad', null],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "True.",
				choiceNext: false,
			},
			"31": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "And I also know that thanking you for everything you've done doesn't make this any easier. But after this... I just don't feel it's good for either of us to keep going with the sessions, so... I guess this is where our paths split for good.",
				choiceNext: false,
			},
			"32": {
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I... I don't know what to say. Sorry.",
				choiceNext: false,
			},
			"33": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "I understand.",
				choiceNext: false,
			},
			"34": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "And... I think... this is as far as our walk goes. I don't want to drag this out and make you suffer any more from my presence.",
				choiceNext: false,
			},
			"35": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "But really, thank you for everything. Please take care of yourself, and I hope that, unlike me, you find the true love.",
				choiceNext: false,
			},
			"36": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Wishing you all the best.",
				choiceNext: false,
			},
			"37": {
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, 'fadeUpOut', null],
			  	name: "",
			  	text: "She lightly brushes my shoulder before heading back home alone, while I stay here for a while to process what just happened.",
				choiceNext: false,
			},
			"38": {
				bgMusic: {
					name: 'Bad_ending_with_main_girls',
					command: 'FADE_OUT',
				},
				background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Brianna is a painful loss in my life. She had her own kind of charm, but it seems she's a true ice queen—a heart that even I couldn't melt. And that's a real shame.",
				choiceNext: false,
			},
		},
	},
];

