export const brianna_good_3 = [
    {
        sceneId: "",
        lengthNum: 29,
        story: {
			"1": {
                background: "backgrounds/BG_night_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "We were both pretty tired when we got back to our room, so we quickly went through the usual routine of eating and freshening up, then curled up together in bed and slowly drifted off to sleep.",
				choiceNext: false,
            },
 			"2": {
                background: "backgrounds/BG_Brianna_bedroom_sunny",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "As the morning sun rises, its light and the soft chirping of birds gently start to pull me out of my dreams.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_Brianna_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I'm trying to resist, as it feels so good to just lie here in bed. Turning over, I reach out for Brianna, half-asleep, but her side of the bed is empty.",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_Brianna_bedroom_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "The unusual feeling of her absence stirs me awake even more, and just as I'm about to open my eyes, I suddenly feel something settle over my hips.",
				choiceNext: false,
			},
			"5": {
                bgMusic: {
					name: 'Brianna_ecchi',
					command: 'START',
				},
                specialSceneNow: true,
				specialSceneId: "brianna_ending_3",
				background: "special_scenes/brianna_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I open my eyes and look up to see Brianna sitting on me. She looks fresh and vibrant, like she's been up for a while. And this lingerie set she's wearing... it's incredibly sexy!",
				choiceNext: false,
			},
			"6": {
				background: "special_scenes/brianna_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Good morning, Tyler!",
				choiceNext: false,
			},
			"7": {
				background: "special_scenes/brianna_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Brianna? Good morning... you really surprised me with this.",
				choiceNext: false,
            },
			"8": {
				background: "special_scenes/brianna_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Hehe! Glad I managed to do something you didn't expect!",
				choiceNext: false,
			},
			"9": {
				background: "special_scenes/brianna_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "You definitely weren't wearing that outfit last night...",
				choiceNext: false,
			},
			"10": {
				background: "special_scenes/brianna_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "I woke up a bit earlier than you. Originally, I planned to wear this last night, but since we were both exhausted, I thought I'd surprise you with it this morning.",
				choiceNext: false,
			},
			"11": {
				background: "special_scenes/brianna_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Well, you succeeded.",
				choiceNext: false,
			},
			"12": {
				background: "special_scenes/brianna_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Do you like it?",
				choiceNext: false,
			},
			"13": {
				background: "special_scenes/brianna_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "That's putting it lightly.",
				choiceNext: false,
			},
			"14": {
				background: "special_scenes/brianna_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Hehe, good answer!",
				choiceNext: false,
			},
			"15": {
				background: "special_scenes/brianna_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Have you ever... been with a mom before?",
				choiceNext: false,
			},
			"16": {
				background: "special_scenes/brianna_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Not yet.",
				choiceNext: false,
			},
			"17": {
				background: "special_scenes/brianna_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Did you ever imagine you would?",
				choiceNext: false,
			},
			"18": {
				background: "special_scenes/brianna_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Honestly, with my limited relationship experience, I never really thought it would happen.",
				choiceNext: false,
			},
			"19": {
                background: "special_scenes/brianna_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Well then, Tyler... consider yourself incredibly lucky because you're about to have an experience so intense, you'll be leaving this bed with a sprained hip, at the very least...",
				choiceNext: false,
			},
			"20": {
				background: "special_scenes/brianna_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "...Maybe around midday tomorrow... no sooner! Hehe!",
				choiceNext: false,
			},
			"21": {
				background: "special_scenes/brianna_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "You're so mischievous, Brianna!",
				choiceNext: false,
			},
			"22": {
				background: "special_scenes/brianna_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Hehe! I never said there wasn't a bit of a bad girl in me, just waiting for someone to bring her out.",
				choiceNext: false,
			},
            "23": {
				background: "special_scenes/brianna_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Alright then! Show me what you've got, because I won't be holding back either.",
				choiceNext: false,
			},
			"24": {
				background: "special_scenes/brianna_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "You asked for it!",
				choiceNext: false,
			},
			"25": {
				background: "special_scenes/brianna_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "And then it happened, something I could only dream about in my wildest fantasies. For the first time in my life, I could experience what it feels like to do it with a milf.",
				choiceNext: false,
            },
			"26": {
				background: "special_scenes/brianna_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "It was such a beautiful and at the same time erotic moment that I could only imagine in my wildest dreams.",
				choiceNext: false,
            },
			"27": {
				background: "special_scenes/brianna_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I had always wanted this, but never imagined it would come true.",
				choiceNext: false,
			},
			"28": {
				background: "special_scenes/brianna_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "But this moment has come, I'm here, and as more and more clothes come off and things get more and more intense, I can say for sure: I would happily relive this moment over and over!",
				choiceNext: false,
			},
			"29": {
                bgMusic: {
					name: 'Brianna_ecchi',
					command: 'FADE_OUT',
				},
                background: "special_scenes/brianna_ending_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "However...",
				choiceNext: false,
			},
		},
    },
];