export const brianna_good_1 = [
    {
        sceneId: "",
        lengthNum: 38,
		endingSceneType: '',
        story: {
			"1": {
				bgMusic: {
					name: 'Date_with_Brianna',
					command: 'START'
				},
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "It's time to see Brianna. Yesterday she mentioned wanting to get out a bit, just the two of us.",
				choiceNext: false,
            },
 			"2": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I don't think this is a bad sign. Going for a walk together... If she wanted to brush me off, she could have done it somewhere close by, or even worse, over the phone. But if she just wants to walk and chat, I'm taking that as a good sign and staying positive.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_Brianna_house_sunny",
				backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "When I arrive at her house, I message her to let her know I'm here, and she comes out. We start off on a little walk around the area.",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_outskirt_park_sunny",
				backGroundClass: "fadeIn",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "So, how are you, Tyler?",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Honestly, I have to admit, I'm a little nervous.",
				choiceNext: false,
			},
			"6": {
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "Why's that?",
				choiceNext: false,
			},
			"7": {
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Because, in my experience, whenever a woman asks me to meet up for a \"talk\", it's usually something serious. Sadly, it doesn't usually mean good news... but I'm hoping that's not the case today.",
				choiceNext: false,
            },
			"8": {
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "Have most of your relationships ended with the other person breaking up with you?",
				choiceNext: false,
			},
			"9": {
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I wouldn't even say I've had that many relationships. But yeah, the ones I've had mostly ended that way. I've always tried to hold on until the very end, doing my best. I just never wanted to break anyone's heart by saying goodbye myself.",
				choiceNext: false,
			},
			"10": {
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "And why do you think you haven't had many relationships? And the ones you had—why do you think they always ended like that?",
				choiceNext: false,
			},
			"11": {
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "If I knew the answer to that, I probably would've had more relationships. Or if not more, at least longer ones. In the best case, I'd be in a relationship now.",
				choiceNext: false,
			},
			"12": {
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "Yeah, that's fair. Honestly, if I had all the answers to questions like that myself, I probably wouldn't have raised my daughters on my own. I've got things to learn too.",
				choiceNext: false,
			},
			"13": {
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "So, does this walk... I mean, was your idea for today to help each other learn and grow together?",
				choiceNext: false,
			},
			"14": {
				bgMusic: {
					name: 'Date_with_Brianna',
					command: 'STOP'
				},
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_normal', null],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "Yes. That's what I'd like, it'd be the best outcome...",
				choiceNext: false,
			},
			"15": {
				bgMusic: {
					name: 'Yes_at_last',
					command: 'START'
				},
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "And I feel ready for it, because you've managed to open up my heart that's been closed for so long.",
				choiceNext: false,
			},
			"16": {
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_smiling', null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "I can't guarantee I'll be perfect in everything for you, nor that we won't have any disagreements along the way. But I can promise you that, just like you, I'll do my best to keep this relationship strong for as long as possible.",
				choiceNext: false,
			},
			"17": {
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_smiling', null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Raising my daughters alone, I figured things out, but a helping hand would have been nice sometimes. Now, I can say that I've lived most of my life already, so if I'm giving love another chance, I can't afford to play games or let anyone play games with me—because I simply don't have time to waste.",
				choiceNext: false,
			},
			"18": {
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_smiling', null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "So, Tyler, this is important: If we're doing this, let's take it very seriously!",
				choiceNext: false,
			},
			"19": {
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_smiling', null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "You don't have to remind me; my intentions with you were serious from the very beginning.",
				choiceNext: false,
			},
			"20": {
                bgMusic: {
					name: 'Yes_at_last',
					command: 'FADE_OUT',
                    insideOfScene: true
				},
                background: "backgrounds/BG_outskirt_park_sunny",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_smiling', null],
				class: [null, 'fadeUp', null],
			  	name: "Brianna",
			  	text: "Then let me give you a hug!",
				choiceNext: false,
			},
			"21": {
                bgMusic: {
					name: 'A_happy_outcome',
					command: 'START',
				},
                specialSceneNow: true,
				specialSceneId: "brianna_ending_1_1",
				background: "special_scenes/brianna_ending_1_1",
				charContainer: [null, 'char-middle', null],
				image: [null, 'Brianna/Brianna_casual_smiling', null],
				class: [null, 'fadeUpOut', null],
			  	name: "",
			  	text: "Without waiting for my reaction, Brianna wraps me in a tight, warm hug—stronger than I even realized she could be, even after all our training sessions.",
				choiceNext: false,
			},
			"22": {
				background: "special_scenes/brianna_ending_1_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "I'm so happy to have you in my life!",
				choiceNext: false,
			},
            "23": {
				background: "special_scenes/brianna_ending_1_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "And I'm glad you decided to give this relationship a chance.",
				choiceNext: false,
			},
			"24": {
				background: "special_scenes/brianna_ending_1_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Well, yes... I'm sorry for being such a tough case. You know, all the disappointments and everything... I know it couldn't have been easy, waiting until you could finally melt my frozen heart.",
				choiceNext: false,
			},
			"25": {
				background: "special_scenes/brianna_ending_1_1",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "They say good things are worth the wait. I knew I needed to be patient with you, because if I could just open up your heart and get to know the real Brianna, then I'd be looking at the happiest time of my life.",
				choiceNext: false,
            },
			"26": {
                specialSceneId: "brianna_ending_1_2",
				background: "special_scenes/brianna_ending_1_2",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Oh, Tyler! Since when did you learn to be so poetic about such tough topics?",
				choiceNext: false,
            },
			"27": {
				background: "special_scenes/brianna_ending_1_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "I don't know; it just came out naturally.",
				choiceNext: false,
			},
			"28": {
				background: "special_scenes/brianna_ending_1_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Maybe you should consider becoming a poet... though I'm not sure if that's a reliable career these days.",
				choiceNext: false,
			},
			"29": {
				background: "special_scenes/brianna_ending_1_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Same goes for being a coach—it's not exactly a path to riches, unless I'm some celebrity coach in the big leagues. But around here, with all the limitations, it feels nearly impossible.",
				choiceNext: false,
			},
			"30": {
                background: "special_scenes/brianna_ending_1_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Don't worry, Tyler. Now that we're together, I'll support you if you need it.",
				choiceNext: false,
			},
			"31": {
				background: "special_scenes/brianna_ending_1_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "No, Brianna. You spent most of your life pushing forward alone. If I ever change careers, I want to be the one who takes some of the weight off your shoulders, so that you can finally relax, sit back, and truly enjoy the rest of your life.",
				choiceNext: false,
			},
			"32": {
                background: "special_scenes/brianna_ending_1_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "But I...",
				choiceNext: false,
			},
			"33": {
				background: "special_scenes/brianna_ending_1_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "No \"buts\". I wasn't there for you while you raised your daughters alone, when you needed help the most. So please, let me make things easier for you now, to bring happiness to this new chapter of your life with me. You deserve that.",
				choiceNext: false,
			},
			"34": {
                background: "special_scenes/brianna_ending_1_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Oh, Tyler...",
				choiceNext: false,
			},
			"35": {
                specialSceneId: 'brianna_ending_1_3',
                background: "special_scenes/brianna_ending_1_3",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "At this moment, Brianna can't hold back, and she shyly leans in to kiss me gently.",
				choiceNext: false,
			},
			"36": {
                background: "special_scenes/brianna_ending_1_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "The world fades around me, every sound falls away except my heartbeat and the sound of Brianna's quickened breaths.",
				choiceNext: false,
			},
			"37": {
                background: "special_scenes/brianna_ending_1_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "These new scents, so close to me, the taste of her kiss—it's so euphoric, it makes my head spin.",
				choiceNext: false,
			},
			"38": {
				bgMusic: {
					name: 'A_happy_outcome',
					command: 'FADE_OUT',
				},
                background: "special_scenes/brianna_ending_1_3",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "I completely lose track of time, having no idea how long we stand there, kissing like teenagers. But I don't mind; this kiss feels like the reward for all my efforts up to now.",
				choiceNext: false,
                timeSkipNext: {
					content: "Some weeks later...",
					nextSceneType: "STORY",
					nextSceneNumber: "",
                    isInEnding: true
				}
			},
		},
    },
];