export const brianna_good_2 = [
    {
        sceneId: "",
        lengthNum: 30,
		endingSceneType: '',
        story: {
			"1": {
				bgMusic: {
					name: 'Brianna_good_ending',
					command: 'START'
				},
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "The weeks pass, and my relationship with Brianna grows closer and closer. We're much more relaxed and laid-back together than high-energetic, and that's exactly what we both seem to need.",
				choiceNext: false,
            },
 			"2": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "For my part, I'm working on becoming a bit more mature and more thoughtful about what I say to her; when making decisions, I aim to be more forward-thinking and selfless, which is necessary if I'm serious about being with someone as mature as Brianna.",
				choiceNext: false,
			},
			"3": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "But the reverse is also true—she's learning to loosen up a little, to let go of some of her seriousness. She's realizing she can allow herself to be a bit selfish and playful, since, after all, she's with a younger guy.",
				choiceNext: false,
			},
			"4": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Finding our balance takes time, but day by day, we're getting closer to that golden middle ground.",
				choiceNext: false,
			},
			"5": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "We didn't wait too long to announce our relationship at my job. Although it wasn't easy, we explained to my boss that, even though the rules prohibit this kind of relationship, it was actually Brianna, as the client, who initiated it.",
				choiceNext: false,
			},
			"6": {
                background: "backgrounds/BG_sunny_sky",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "The situation was precarious, but he accepted our story. I was able to keep my job for now, as long as we remain discreet around other clients.",
				choiceNext: false,
			},
			"7": {
                background: "backgrounds/BG_harbor_sunny",
                backGroundClass: "fadeIn",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Before summer ends, we decide to take a short vacation—just the two of us, without her daughters. Luckily, her daughters are old enough to handle a few days on their own, and if they need anything, their grandmother is nearby.",
				choiceNext: false,
            },
			"8": {
                background: "backgrounds/BG_harbor_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "So, we set off for a small island—not a beach destination but a place people visit to enjoy nature, often as an escape from the big city.",
				choiceNext: false,
			},
			"9": {
                background: "backgrounds/BG_harbor_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "It's a calm environment with low-key activities, which suits us perfectly.",
				choiceNext: false,
			},
			"10": {
                background: "backgrounds/BG_harbor_sunny",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "Although we're tired from the journey, we decide to head out at sunset rather than resting in bed. We stroll along the seaside path and down to the docks, soaking up the view of the ocean as it glows in the sunset.",
				choiceNext: false,
			},
			"11": {
                specialSceneNow: true,
				specialSceneId: "brianna_ending_2",
				background: "special_scenes/brianna_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "",
			  	text: "The most beautiful sight, though, is Brianna herself, framed against this stunning scene. Despite her exhaustion, she looks so happy, so refreshed—like she's finally feeling truly free.",
				choiceNext: false,
			},
			"12": {
				background: "special_scenes/brianna_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Tyler. Thank you for bringing me here.",
				choiceNext: false,
			},
			"13": {
				background: "special_scenes/brianna_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Oh, it's not just my doing. We chose this place together.",
				choiceNext: false,
			},
			"14": {
				background: "special_scenes/brianna_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Yes, but if it weren't for you, I never would have thought of taking a few days off, trusting the girls to be fine at home, and coming here to relax.",
				choiceNext: false,
			},
			"15": {
				background: "special_scenes/brianna_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Yeah, it took a bit of reprogramming to remind you that, yes, you deserve relaxation and some self-care. You don't have to be in “robot mode” all the time.",
				choiceNext: false,
			},
			"16": {
				background: "special_scenes/brianna_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "I know, I know. If it weren't for you, I might never have realized that flaw in myself. So... just for that, I'm incredibly grateful, and I'm so happy to have you in my life.",
				choiceNext: false,
			},
			"17": {
				background: "special_scenes/brianna_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "It's been a long time since I felt this good. It's such... a relief to be out here in nature, feeling like, right now, there are no responsibilities or weights pressing on my shoulders.",
				choiceNext: false,
			},
			"18": {
                background: "special_scenes/brianna_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "It's either the first time, or the first time in a long while, that I can do exactly what I want... not what I have to do or what's expected of me.",
				choiceNext: false,
			},
			"19": {
                background: "special_scenes/brianna_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "And I owe all this to you. You've already done so much for me, and for that, I'm so grateful and will love you forever.",
				choiceNext: false,
			},
			"20": {
                background: "special_scenes/brianna_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "...",
				choiceNext: false,
			},
			"21": {
                background: "special_scenes/brianna_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Wow! Did I really just say that?",
				choiceNext: false,
			},
			"22": {
                background: "special_scenes/brianna_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "So, I didn't hear that wrong, did I?",
				choiceNext: false,
			},
            "23": {
                background: "special_scenes/brianna_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Oops! Haha! But... honestly, it's such a relief to finally say it.",
				choiceNext: false,
			},
			"24": {
                background: "special_scenes/brianna_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Since that's how it happened, and you said it first, let me tell you that I feel the same way. I love you very much, too. I was just waiting for the right romantic moment to tell you first.",
				choiceNext: false,
			},
			"25": {
                background: "special_scenes/brianna_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Sorry! Haha! Hope you're not upset.",
				choiceNext: false,
            },
			"26": {
                background: "special_scenes/brianna_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Not at all.",
				choiceNext: false,
            },
			"27": {
                background: "special_scenes/brianna_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Good.",
				choiceNext: false,
			},
			"28": {
                background: "special_scenes/brianna_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Brianna",
			  	text: "Well, I think... we should keep walking a bit longer.",
				choiceNext: false,
			},
			"29": {
                background: "special_scenes/brianna_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "Alright.",
				choiceNext: false,
			},
			"30": {
                bgMusic: {
					name: 'Brianna_good_ending',
					command: 'FADE_OUT',
				},
                background: "special_scenes/brianna_ending_2",
				charContainer: [null, null, null],
				image: [null, null, null],
				class: [null, null, null],
			  	name: "Tyler",
			  	text: "So, we continue walking a bit more. There's no rush, and our time together doesn't end with the sunset. We even get a taste of the island's nightlife before deciding to head back to our place.",
				choiceNext: false,
			},
		},
    },
];